# Teste de hiperparâmetros do FAGTB

Este notebook testa um produto cartesiano de hiperparâmetros do FAGTB usando o mesmo wrapper `modelo_fagtb` do fluxo principal.

A ideia é usar uma amostra menor do dataset, por exemplo 5.000 linhas do HMDA, para encontrar uma região razoável de hiperparâmetros antes de rodar o fluxo principal completo.

In [1]:
# ============================================================
# CONFIGURAÇÕES GERAIS
# ============================================================

from pathlib import Path

# Raiz do projeto
PROJECT_ROOT = Path.cwd()

# Dataset que será usado para escolher hiperparâmetros
CAMINHO_DATASET = Path("datasets/tratado/hmda.csv")

# Nome do dataset dentro do configs_datasets.json
# Deve bater com uma chave do JSON, por exemplo: "hmda" ou "compas"
NOME_DATASET = "hmda"

# Arquivo de configuração dos datasets
CAMINHO_CONFIGS = Path("configs_datasets.json")

# Pasta de saída dos resultados
PASTA_SAIDA = Path("resultados/testes_hiperparametros_fagtb")
PASTA_SAIDA.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------------------
# Amostragem do dataset
# ------------------------------------------------------------

# Opção 1: usar número fixo de linhas.
# Para HMDA, recomendo começar com 5000.
N_LINHAS_AMOSTRA = 5000

# Opção 2: usar uma fração do dataset.
# Só será usada se N_LINHAS_AMOSTRA = None.
FRACAO_DATASET = None

# Amostragem estratificada pelo target
AMOSTRAGEM_ESTRATIFICADA = True

# ------------------------------------------------------------
# Split interno para validação dos hiperparâmetros
# ------------------------------------------------------------

TEST_SIZE_VALIDACAO = 0.30
RANDOM_STATE = 42

# ------------------------------------------------------------
# Uso do atributo sensível como feature
# ------------------------------------------------------------

# True  -> cenário aware: mantém o atributo sensível no X
# False -> cenário unaware: remove o atributo sensível do X antes do treino
USAR_ATRIBUTO_SENSIVEL_NO_MODELO = True

# ------------------------------------------------------------
# Controle de execução
# ------------------------------------------------------------

# Use True para testar só a primeira configuração sensível do JSON.
# Ajuda a estimar tempo antes de rodar tudo.
TESTAR_APENAS_PRIMEIRA_CONFIG_SENSIVEL = False

# Quantos primeiros testes usar para estimar tempo total durante a execução.
N_TESTES_PARA_ESTIMAR_TEMPO = 3

# Salvar os modelos de cada combinação geralmente pesa muito.
# Recomendo False para busca de hiperparâmetros.
SALVAR_MODELOS = False

# ------------------------------------------------------------
# Critério de escolha
# ------------------------------------------------------------

# O score abaixo tenta escolher modelos que aumentem balanced accuracy,
# sem ignorar completamente justiça. Ajuste a penalidade se quiser.
PENALIDADE_EQUALIZED_ODDS = 0.05
PENALIDADE_EQUAL_OPPORTUNITY = 0.03

# ------------------------------------------------------------
# Grade de hiperparâmetros
# ------------------------------------------------------------

GRADE_HIPERPARAMETROS = {
    "lambda_fagtb": [ 0.0001, 0.0005, 0.001, 0.005, 0.01],
    "n_estimators": [100, 200],
    "learning_rate": [0.03, 0.05, 0.10],
    "max_depth": [3, 5],
    "max_features": [None],
    "min_samples_split": [2],
    "min_impurity": [0],
    "regression": [False],
}

In [2]:
# ============================================================
# IMPORTS
# ============================================================

import sys
import gc
import json
import time
import itertools
import importlib
import numpy as np
import pandas as pd
import joblib

from tqdm import tqdm
from sklearn.model_selection import train_test_split, ParameterGrid
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

sys.path.append(str(PROJECT_ROOT))

import func_aux
importlib.reload(func_aux)
from func_aux import *

print("Imports concluídos.")

Arquivo exportado: func_aux.py
Arquivo exportado: func_aux.py
Imports concluídos.

In [3]:
# ============================================================
# FUNÇÕES AUXILIARES
# ============================================================

def formatar_numero(n):
    return f"{int(n):,}".replace(",", ".")


def preparar_para_fagtb(X, y, sensitive):
    """
    Converte dados para arrays compactos.
    Isso reduz bastante problemas de memória no HMDA.
    """
    if hasattr(X, "to_numpy"):
        X_np = X.to_numpy(dtype=np.float32, copy=True)
    else:
        X_np = np.asarray(X, dtype=np.float32)

    y_np = np.asarray(y, dtype=np.int32).ravel()
    sensitive_np = np.asarray(sensitive, dtype=np.int32).ravel()

    return X_np, y_np, sensitive_np


def taxa_positiva(y_pred, sensitive, grupo):
    mask = sensitive == grupo
    if mask.sum() == 0:
        return np.nan
    return np.mean(y_pred[mask] == 1)


def tpr_por_grupo(y_true, y_pred, sensitive, grupo):
    mask = (sensitive == grupo) & (y_true == 1)
    if mask.sum() == 0:
        return np.nan
    return np.mean(y_pred[mask] == 1)


def fpr_por_grupo(y_true, y_pred, sensitive, grupo):
    mask = (sensitive == grupo) & (y_true == 0)
    if mask.sum() == 0:
        return np.nan
    return np.mean(y_pred[mask] == 1)


def avaliar_modelo_fairness(
    y_true,
    y_pred,
    sensitive,
    grupo_privilegiado,
    grupo_desprivilegiado
):
    y_true = np.asarray(y_true).astype(int).ravel()
    y_pred = np.asarray(y_pred).astype(int).ravel()
    sensitive = np.asarray(sensitive).astype(int).ravel()

    acc = accuracy_score(y_true, y_pred)
    bal_acc = balanced_accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, zero_division=0)
    recall = recall_score(y_true, y_pred, zero_division=0)
    f1 = f1_score(y_true, y_pred, zero_division=0)

    tpr_priv = tpr_por_grupo(y_true, y_pred, sensitive, grupo_privilegiado)
    tpr_despriv = tpr_por_grupo(y_true, y_pred, sensitive, grupo_desprivilegiado)
    fpr_priv = fpr_por_grupo(y_true, y_pred, sensitive, grupo_privilegiado)
    fpr_despriv = fpr_por_grupo(y_true, y_pred, sensitive, grupo_desprivilegiado)

    taxa_pos_priv = taxa_positiva(y_pred, sensitive, grupo_privilegiado)
    taxa_pos_despriv = taxa_positiva(y_pred, sensitive, grupo_desprivilegiado)

    equal_opportunity = abs(tpr_despriv - tpr_priv)
    equalized_odds = max(
        abs(tpr_despriv - tpr_priv),
        abs(fpr_despriv - fpr_priv)
    )
    demographic_parity = abs(taxa_pos_despriv - taxa_pos_priv)

    if pd.isna(taxa_pos_priv) or pd.isna(taxa_pos_despriv) or taxa_pos_priv == 0:
        p_rule = np.nan
    else:
        p_rule = 100 * min(
            taxa_pos_despriv / taxa_pos_priv,
            taxa_pos_priv / taxa_pos_despriv if taxa_pos_despriv != 0 else np.nan
        )

    return {
        "accuracy": acc,
        "balanced_accuracy": bal_acc,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "equal_opportunity": equal_opportunity,
        "equalized_odds": equalized_odds,
        "demographic_parity": demographic_parity,
        "p_rule": p_rule,
        "tpr_privilegiado": tpr_priv,
        "tpr_desprivilegiado": tpr_despriv,
        "fpr_privilegiado": fpr_priv,
        "fpr_desprivilegiado": fpr_despriv,
        "taxa_positiva_privilegiado": taxa_pos_priv,
        "taxa_positiva_desprivilegiado": taxa_pos_despriv,
    }


def calcular_score(linha):
    return (
        linha["balanced_accuracy"]
        - PENALIDADE_EQUALIZED_ODDS * linha["equalized_odds"]
        - PENALIDADE_EQUAL_OPPORTUNITY * linha["equal_opportunity"]
    )


def resumo_melhor_valor_por_hiperparametro(df_resultados, colunas_parametros):
    """
    Para cada hiperparâmetro, calcula o melhor valor médio considerando o score.
    Isso não substitui a melhor combinação global, mas ajuda a interpretar tendências.
    """
    linhas = []

    for parametro in colunas_parametros:
        df_param = (
            df_resultados
            .groupby(parametro, dropna=False)
            .agg(
                score_medio=("score", "mean"),
                score_max=("score", "max"),
                balanced_accuracy_media=("balanced_accuracy", "mean"),
                balanced_accuracy_max=("balanced_accuracy", "max"),
                accuracy_media=("accuracy", "mean"),
                equalized_odds_media=("equalized_odds", "mean"),
                tempo_min_medio=("tempo_min", "mean"),
                n_testes=("score", "count")
            )
            .reset_index()
            .sort_values(
                by=["score_medio", "balanced_accuracy_media"],
                ascending=[False, False]
            )
        )

        melhor = df_param.iloc[0].to_dict()
        melhor["hiperparametro"] = parametro
        melhor["melhor_valor"] = melhor[parametro]
        linhas.append(melhor)

    return pd.DataFrame(linhas)

In [4]:
# ============================================================
# CARREGA DATASET E CONFIGURAÇÕES
# ============================================================

with open(CAMINHO_CONFIGS, "r", encoding="utf-8") as f:
    configs = json.load(f)

config_dataset = configs[NOME_DATASET]
configs_sensiveis = config_dataset["configs_sensiveis"]
target_col = config_dataset["target"]

if TESTAR_APENAS_PRIMEIRA_CONFIG_SENSIVEL:
    configs_sensiveis = configs_sensiveis[:1]

print(f"Dataset: {NOME_DATASET}")
print(f"Arquivo: {CAMINHO_DATASET}")
print(f"Target: {target_col}")
print(f"Configurações sensíveis: {[c['nome'] for c in configs_sensiveis]}")

# Carrega dataset completo
# Observação: se der problema de memória nesta leitura, gere antes um hmda_5pct.csv e use esse caminho.
df_original = pd.read_csv(CAMINHO_DATASET)

n_original = len(df_original)
print(f"\nLinhas no dataset original: {formatar_numero(n_original)}")

# ------------------------------------------------------------
# Amostragem
# ------------------------------------------------------------

if N_LINHAS_AMOSTRA is not None:
    n_amostra = min(N_LINHAS_AMOSTRA, n_original)
    train_size = n_amostra
elif FRACAO_DATASET is not None:
    n_amostra = int(n_original * FRACAO_DATASET)
    train_size = FRACAO_DATASET
else:
    n_amostra = n_original
    train_size = None

if n_amostra < n_original:
    if AMOSTRAGEM_ESTRATIFICADA:
        df_amostra, _ = train_test_split(
            df_original,
            train_size=n_amostra if N_LINHAS_AMOSTRA is not None else train_size,
            random_state=RANDOM_STATE,
            stratify=df_original[target_col]
        )
    else:
        df_amostra = df_original.sample(
            n=n_amostra,
            random_state=RANDOM_STATE
        )

    df_amostra = df_amostra.reset_index(drop=True)
else:
    df_amostra = df_original.reset_index(drop=True)

# Libera dataset completo para economizar memória
del df_original
gc.collect()

print(f"Linhas usadas para busca de hiperparâmetros: {formatar_numero(len(df_amostra))}")
print(f"Percentual usado: {100 * len(df_amostra) / n_original:.4f}%")

print("\nDistribuição do target na amostra:")
print(df_amostra[target_col].value_counts(normalize=True))

Dataset: hmda
Arquivo: datasets\tratado\hmda.csv
Target: Favorable Outcome (Credit Approved)
Configurações sensíveis: ['african_american_0', 'caucasian_1']

Linhas no dataset original: 34.717
Linhas usadas para busca de hiperparâmetros: 5.000
Percentual usado: 14.4022%

Distribuição do target na amostra:
Favorable Outcome (Credit Approved)
1    0.7812
0    0.2188
Name: proportion, dtype: float64

In [5]:
# ============================================================
# SPLIT TREINO / VALIDAÇÃO
# ============================================================

X = df_amostra.drop(columns=[target_col]).reset_index(drop=True)
y = df_amostra[target_col].astype(int).reset_index(drop=True)

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=TEST_SIZE_VALIDACAO,
    random_state=RANDOM_STATE,
    stratify=y
)

X_train = X_train.reset_index(drop=True)
X_val = X_val.reset_index(drop=True)
y_train = y_train.reset_index(drop=True)
y_val = y_val.reset_index(drop=True)

print("X_train:", X_train.shape)
print("X_val:", X_val.shape)
print("y_train:", y_train.shape)
print("y_val:", y_val.shape)

print("\nDistribuição y_train:")
print(y_train.value_counts(normalize=True))

print("\nDistribuição y_val:")
print(y_val.value_counts(normalize=True))

# Libera a amostra original após split
del df_amostra, X, y
gc.collect()

X_train: (3500, 50)
X_val: (1500, 50)
y_train: (3500,)
y_val: (1500,)

Distribuição y_train:
Favorable Outcome (Credit Approved)
1    0.781143
0    0.218857
Name: proportion, dtype: float64

Distribuição y_val:
Favorable Outcome (Credit Approved)
1    0.781333
0    0.218667
Name: proportion, dtype: float64

0

In [6]:
# ============================================================
# PRODUTO CARTESIANO DE HIPERPARÂMETROS
# ============================================================

grade = list(ParameterGrid(GRADE_HIPERPARAMETROS))

print(f"Combinações por configuração sensível: {len(grade)}")
print(f"Configurações sensíveis: {len(configs_sensiveis)}")
print(f"Total de treinos FAGTB: {len(grade) * len(configs_sensiveis)}")

pd.DataFrame(grade).head()

Combinações por configuração sensível: 60
Configurações sensíveis: 2
Total de treinos FAGTB: 120

,lambda_fagtb,learning_rate,max_depth,max_features,min_impurity,min_samples_split,n_estimators,regression
0,0.0001,0.03,3,None,0,2,100,False
1,0.0001,0.03,3,None,0,2,200,False
2,0.0001,0.03,5,None,0,2,100,False
3,0.0001,0.03,5,None,0,2,200,False
4,0.0001,0.05,3,None,0,2,100,False

In [7]:
# ============================================================
# BUSCA DE HIPERPARÂMETROS
# ============================================================

resultados = []
colunas_parametros = list(GRADE_HIPERPARAMETROS.keys())

total_treinos = len(grade) * len(configs_sensiveis)
contador_treinos = 0
tempos_primeiros_testes = []

for config in configs_sensiveis:

    nome_config = config["nome"]
    atributo_sensivel = config["atributo_sensivel"]
    grupo_privilegiado = config["grupo_privilegiado"]
    grupo_desprivilegiado = config["grupo_desprivilegiado"]

    print("\n" + "=" * 100, flush=True)
    print(f"Configuração sensível: {nome_config}", flush=True)
    print(f"Atributo sensível: {atributo_sensivel}", flush=True)
    print("=" * 100, flush=True)

    s_train = X_train[atributo_sensivel].astype(int).reset_index(drop=True)
    s_val = X_val[atributo_sensivel].astype(int).reset_index(drop=True)

    if USAR_ATRIBUTO_SENSIVEL_NO_MODELO:
        X_train_model = X_train.copy()
        X_val_model = X_val.copy()
        cenario = "aware"
    else:
        X_train_model = X_train.drop(columns=[atributo_sensivel]).copy()
        X_val_model = X_val.drop(columns=[atributo_sensivel]).copy()
        cenario = "unaware"

    X_train_np, y_train_np, s_train_np = preparar_para_fagtb(
        X_train_model,
        y_train,
        s_train
    )

    X_val_np, y_val_np, s_val_np = preparar_para_fagtb(
        X_val_model,
        y_val,
        s_val
    )

    for params in tqdm(grade, desc=f"FAGTB {nome_config}", unit="modelo"):

        contador_treinos += 1

        lambda_fagtb = params["lambda_fagtb"]

        print("\n" + "-" * 100, flush=True)
        print(
            f"Treino {contador_treinos}/{total_treinos} | "
            f"config={nome_config} | "
            f"lambda={lambda_fagtb} | "
            f"n_estimators={params['n_estimators']} | "
            f"learning_rate={params['learning_rate']} | "
            f"max_depth={params['max_depth']}",
            flush=True
        )
        print("-" * 100, flush=True)

        inicio = time.time()

        try:
            modelo = modelo_fagtb(
                X_train=X_train_np,
                y_train=y_train_np,
                sensitive_train=s_train_np,
                X_test=X_val_np,
                y_test=y_val_np,
                sensitive_test=s_val_np,
                lambda_fagtb=lambda_fagtb,
                n_estimators=params["n_estimators"],
                learning_rate=params["learning_rate"],
                max_depth=params["max_depth"],
                max_features=params["max_features"],
                min_samples_split=params["min_samples_split"],
                min_impurity=params["min_impurity"],
                regression=params["regression"]
            )

            y_pred_val = modelo.predict(X_val_np)

            metricas = avaliar_modelo_fairness(
                y_true=y_val_np,
                y_pred=y_pred_val,
                sensitive=s_val_np,
                grupo_privilegiado=grupo_privilegiado,
                grupo_desprivilegiado=grupo_desprivilegiado
            )

            status = "ok"
            erro = None

            if SALVAR_MODELOS:
                nome_modelo = (
                    f"modelo_{NOME_DATASET}_{nome_config}_"
                    f"lambda_{lambda_fagtb}_"
                    f"nest_{params['n_estimators']}_"
                    f"lr_{params['learning_rate']}_"
                    f"depth_{params['max_depth']}.joblib"
                )
                joblib.dump(modelo, PASTA_SAIDA / nome_modelo)

        except MemoryError as e:
            metricas = {}
            status = "MemoryError"
            erro = str(e)
            print("MemoryError nesta combinação. Pulando.", flush=True)

        except Exception as e:
            metricas = {}
            status = "erro"
            erro = repr(e)
            print(f"Erro nesta combinação: {erro}", flush=True)

        fim = time.time()
        tempo_seg = fim - inicio
        tempo_min = tempo_seg / 60

        linha = {
            "dataset": NOME_DATASET,
            "config_sensivel": nome_config,
            "atributo_sensivel": atributo_sensivel,
            "cenario": cenario,
            **params,
            "status": status,
            "erro": erro,
            "tempo_seg": tempo_seg,
            "tempo_min": tempo_min,
            **metricas
        }
        print(f"Tempo de execução: {tempo_min:.2f} min", flush=True)
        print(f"Resultado parcial: {linha}", flush=True)

        if status == "ok":
            linha["score"] = calcular_score(linha)
        else:
            linha["score"] = np.nan

        resultados.append(linha)

        df_resultados = pd.DataFrame(resultados)
        df_resultados.to_csv(PASTA_SAIDA / "resultados_hiperparametros_fagtb.csv", index=False)

        if status == "ok":
            print(
                f"Resultado | "
                f"acc={linha['accuracy']:.4f} | "
                f"bal_acc={linha['balanced_accuracy']:.4f} | "
                f"f1={linha['f1']:.4f} | "
                f"EOdds={linha['equalized_odds']:.4f} | "
                f"EOp={linha['equal_opportunity']:.4f} | "
                f"p-rule={linha['p_rule']:.2f} | "
                f"score={linha['score']:.4f} | "
                f"tempo={tempo_min:.2f} min",
                flush=True
            )

        if len(tempos_primeiros_testes) < N_TESTES_PARA_ESTIMAR_TEMPO and status == "ok":
            tempos_primeiros_testes.append(tempo_min)

            media_tempo = np.mean(tempos_primeiros_testes)
            estimativa_total_min = media_tempo * total_treinos
            estimativa_restante_min = media_tempo * (total_treinos - contador_treinos)

            print(
                f"Estimativa parcial | "
                f"média={media_tempo:.2f} min/modelo | "
                f"total≈{estimativa_total_min/60:.2f} h | "
                f"restante≈{estimativa_restante_min/60:.2f} h",
                flush=True
            )

        if 'modelo' in locals():
            del modelo
        gc.collect()

    del X_train_np, X_val_np, y_train_np, y_val_np, s_train_np, s_val_np
    gc.collect()

print("\nBusca concluída.")

====================================================================================================
Configuração sensível: african_american_0
Atributo sensível: Applicant_African-American
====================================================================================================

FAGTB african_american_0:   0%|          | 0/60 [00:00<?, ?modelo/s]

----------------------------------------------------------------------------------------------------
Treino 1/120 | config=african_american_0 | lambda=0.0001 | n_estimators=100 | learning_rate=0.03 | max_depth=3
----------------------------------------------------------------------------------------------------
WARNING:tensorflow:From c:\Users\Davi Araujo\OneDrive\Documents\GitHub\tcc\fagtb_core.py:85: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From c:\Users\Davi Araujo\OneDrive\Documents\GitHub\tcc\fagtb_core.py:94: The name tf.train.GradientDescentOptimizer is deprecated. Please use tf.compat.v1.train.GradientDescentOptimizer instead.

0 945.2967211235476 1830.1451554416485 1830.239685113761 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1700.8075461358974 1787.1979139244243 1787.367994679038 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 582.6756612492989 1747.0721399612758 1747.1304075274006 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 381.40400250799985 1707.7994375287203 1707.837577928971 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2707.676071085536 1668.9083184157719 1669.1790860228805 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1507.5044326867999 1631.8166650258404 1631.967415469109 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 830.3274798082775 1596.8057233307788 1596.8887560787598 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 37.12409554385478 1563.8244638903232 1563.8281762998777 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2869.7326174586005 1533.069331522869 1533.356304784615 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 1618.6010564592152 1503.4224488349732 1503.5843089406194 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 982.0936415552005 1475.42123460186 1475.5194439660156 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -594.4604984641696 1449.5669058679518 1449.5074598181054 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 2962.287886422361 1424.8083626194846 1425.1045914081267 Accuracy: 0.7811  test :  0.782  Prule Train :  1.0  Prule test :  0.9991166077738517
65 2196.2085826515636 1401.1018167781945 1401.3214376364597 Accuracy: 0.7834  test :  0.782  Prule Train :  0.9982498640341629  Prule test :  0.9991166077738517
70 1070.2396406736425 1378.7404430734682 1378.8474670375358 Accuracy: 0.8654  test :  0.8413  Prule Train :  0.9503137527262979  Prule test :  0.9616392368787358
75 -1273.6538805328078 1357.2204334862804 1357.093068098227 Accuracy: 0.868  test :  0.8427  Prule Train :  0.9503981481662503  Prule test :  0.9596463549563579
80 3321.8065963423264 1336.5729738863918 1336.905154546026 Accuracy: 0.8726  test :  0.8433  Prule Train :  0.951493591523171  Prule test :  0.9623674693844005
85 1993.8620701017148 1317.059169486095 1317.2585556931049 Accuracy: 0.8763  test :  0.8427  Prule Train :  0.951431862864811  Prule test :  0.9632779400271483
90 1480.2782809199648 1298.4116581572816 1298.5596859853738 Accuracy: 0.8803  test :  0.842  Prule Train :  0.9517604939275026  Prule test :  0.9603677347702686
95 -1899.6455016751836 1281.0121500013854 1280.822185451218 Accuracy: 0.8829  test :  0.8433  Prule Train :  0.9449828536609207  Prule test :  0.9563568926437255
Resultado | acc=0.8420 | bal_acc=0.6541 | f1=0.9072 | EOdds=0.0629 | EOp=0.0132 | p-rule=95.43 | score=0.6506 | tempo=0.21 min
Estimativa parcial | média=0.21 min/modelo | total≈0.42 h | restante≈0.42 h

FAGTB african_american_0:   2%|▏         | 1/60 [00:12<12:36, 12.83s/modelo]

----------------------------------------------------------------------------------------------------
Treino 2/120 | config=african_american_0 | lambda=0.0001 | n_estimators=200 | learning_rate=0.03 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1830.1451554416485 1830.239685113761 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1700.8075461358974 1787.1979139244243 1787.367994679038 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 582.6756612492989 1747.0721399612758 1747.1304075274006 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 381.40400250799985 1707.7994375287203 1707.837577928971 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2707.676071085536 1668.9083184157719 1669.1790860228805 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1507.5044326867999 1631.8166650258404 1631.967415469109 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 830.3274798082775 1596.8057233307788 1596.8887560787598 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 37.12409554385478 1563.8244638903232 1563.8281762998777 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2869.7326174586005 1533.069331522869 1533.356304784615 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 1618.6010564592152 1503.4224488349732 1503.5843089406194 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 982.0936415552005 1475.42123460186 1475.5194439660156 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -594.4604984641696 1449.5669058679518 1449.5074598181054 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 2962.287886422361 1424.8083626194846 1425.1045914081267 Accuracy: 0.7811  test :  0.782  Prule Train :  1.0  Prule test :  0.9991166077738517
65 2196.2085826515636 1401.1018167781945 1401.3214376364597 Accuracy: 0.7834  test :  0.782  Prule Train :  0.9982498640341629  Prule test :  0.9991166077738517
70 1070.2396406736425 1378.7404430734682 1378.8474670375358 Accuracy: 0.8654  test :  0.8413  Prule Train :  0.9503137527262979  Prule test :  0.9616392368787358
75 -1273.6538805328078 1357.2204334862804 1357.093068098227 Accuracy: 0.868  test :  0.8427  Prule Train :  0.9503981481662503  Prule test :  0.9596463549563579
80 3321.8065963423264 1336.5729738863918 1336.905154546026 Accuracy: 0.8726  test :  0.8433  Prule Train :  0.951493591523171  Prule test :  0.9623674693844005
85 1993.8620701017148 1317.059169486095 1317.2585556931049 Accuracy: 0.8763  test :  0.8427  Prule Train :  0.951431862864811  Prule test :  0.9632779400271483
90 1480.2782809199648 1298.4116581572816 1298.5596859853738 Accuracy: 0.8803  test :  0.842  Prule Train :  0.9517604939275026  Prule test :  0.9603677347702686
95 -1899.6455016751836 1281.0121500013854 1280.822185451218 Accuracy: 0.8829  test :  0.8433  Prule Train :  0.9449828536609207  Prule test :  0.9563568926437255
100 3419.259226780483 1264.6576610883008 1264.9995870109788 Accuracy: 0.8837  test :  0.8413  Prule Train :  0.9461504601522646  Prule test :  0.9514272749773122
105 2650.561814986279 1248.830091943185 1249.0951481246836 Accuracy: 0.8851  test :  0.84  Prule Train :  0.9481028960997516  Prule test :  0.9532360720780294
110 1719.325741892286 1232.9591585143046 1233.131091088494 Accuracy: 0.8857  test :  0.84  Prule Train :  0.9471640640330545  Prule test :  0.951216232987217
115 -2483.831448156128 1217.2223558893932 1216.9739727445776 Accuracy: 0.8863  test :  0.84  Prule Train :  0.9445034908194786  Prule test :  0.951216232987217
120 3665.96918833918 1201.6843012852237 1202.0508982040578 Accuracy: 0.8871  test :  0.84  Prule Train :  0.9422319481377514  Prule test :  0.951216232987217
125 2322.7992747779836 1187.5160567895573 1187.7483367170353 Accuracy: 0.888  test :  0.8393  Prule Train :  0.9399585281480227  Prule test :  0.9521221532091098
130 1996.259528707602 1173.6617279862007 1173.8613539390713 Accuracy: 0.8889  test :  0.84  Prule Train :  0.9428483411754367  Prule test :  0.953029800638289
135 -2130.6711521676066 1160.0787957299374 1159.8657286147204 Accuracy: 0.8903  test :  0.8407  Prule Train :  0.9430761352065566  Prule test :  0.9521221532091098
140 1769.3701496639137 1146.9556776815616 1147.132614696528 Accuracy: 0.8911  test :  0.8407  Prule Train :  0.9407945789278034  Prule test :  0.9521221532091098
145 -2800.828635324388 1133.9682913489066 1133.6882084853742 Accuracy: 0.892  test :  0.8413  Prule Train :  0.9402381800055182  Prule test :  0.953029800638289
150 3716.8946498864443 1121.4192554526558 1121.7909449176445 Accuracy: 0.8934  test :  0.842  Prule Train :  0.9370037030113717  Prule test :  0.9539391802190508
155 2209.4258209030404 1109.1487549555814 1109.3696975376715 Accuracy: 0.8934  test :  0.8413  Prule Train :  0.9370037030113717  Prule test :  0.95485029691458
160 2877.9175816538514 1097.0861049586974 1097.3738967168629 Accuracy: 0.8949  test :  0.842  Prule Train :  0.9372226213011782  Prule test :  0.9557631557070413
165 -1176.1519440038023 1085.257466988839 1085.1398517944385 Accuracy: 0.8966  test :  0.8427  Prule Train :  0.9291777919337859  Prule test :  0.9528223459971735
170 1969.0458838007703 1073.753005459736 1073.9499100481162 Accuracy: 0.8983  test :  0.844  Prule Train :  0.929771592933798  Prule test :  0.95667776159767
175 -2958.438421017753 1062.6092097021037 1062.3133658600018 Accuracy: 0.8994  test :  0.844  Prule Train :  0.9313250960130524  Prule test :  0.954647676161919
180 2959.7218110621125 1051.813446916866 1052.1094190979725 Accuracy: 0.9003  test :  0.8433  Prule Train :  0.9307568251227453  Prule test :  0.9573988222027316
185 3550.811197081422 1041.2830622250221 1041.6381433447305 Accuracy: 0.9023  test :  0.842  Prule Train :  0.9300068778258591  Prule test :  0.959241745825836
190 2403.5112484934216 1031.1009674594509 1031.3413185843003 Accuracy: 0.9031  test :  0.8407  Prule Train :  0.929435833630476  Prule test :  0.9590502769850596
195 1941.3427327409959 1021.0298582329482 1021.2239925062224 Accuracy: 0.9043  test :  0.84  Prule Train :  0.929253782135619  Prule test :  0.959976895610166
Resultado | acc=0.8393 | bal_acc=0.6634 | f1=0.9047 | EOdds=0.0345 | EOp=0.0168 | p-rule=95.70 | score=0.6611 | tempo=0.12 min
Estimativa parcial | média=0.16 min/modelo | total≈0.33 h | restante≈0.32 h

FAGTB african_american_0:   3%|▎         | 2/60 [00:19<09:10,  9.49s/modelo]

----------------------------------------------------------------------------------------------------
Treino 3/120 | config=african_american_0 | lambda=0.0001 | n_estimators=100 | learning_rate=0.03 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1830.1451554416485 1830.239685113761 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1700.8075461358974 1787.1979139244243 1787.367994679038 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 582.6756612492989 1747.0721399612758 1747.1304075274006 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 381.40400250799985 1707.7994375287203 1707.837577928971 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2707.676071085536 1668.9083184157719 1669.1790860228805 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1507.5044326867999 1631.8166650258404 1631.967415469109 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 830.3274798082775 1596.8057233307788 1596.8887560787598 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 37.12409554385478 1563.8244638903232 1563.8281762998777 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2869.7326174586005 1533.069331522869 1533.356304784615 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 1618.6010564592152 1503.4224488349732 1503.5843089406194 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 982.0936415552005 1475.42123460186 1475.5194439660156 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -594.4604984641696 1449.5669058679518 1449.5074598181054 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 2962.287886422361 1424.8083626194846 1425.1045914081267 Accuracy: 0.7811  test :  0.782  Prule Train :  1.0  Prule test :  0.9991166077738517
65 2196.2085826515636 1401.1018167781945 1401.3214376364597 Accuracy: 0.7834  test :  0.782  Prule Train :  0.9982498640341629  Prule test :  0.9991166077738517
70 1070.2396406736425 1378.7404430734682 1378.8474670375358 Accuracy: 0.8654  test :  0.8413  Prule Train :  0.9503137527262979  Prule test :  0.9616392368787358
75 -1273.6538805328078 1357.2204334862804 1357.093068098227 Accuracy: 0.868  test :  0.8427  Prule Train :  0.9503981481662503  Prule test :  0.9596463549563579
80 3321.8065963423264 1336.5729738863918 1336.905154546026 Accuracy: 0.8726  test :  0.8433  Prule Train :  0.951493591523171  Prule test :  0.9623674693844005
85 1993.8620701017148 1317.059169486095 1317.2585556931049 Accuracy: 0.8763  test :  0.8427  Prule Train :  0.951431862864811  Prule test :  0.9632779400271483
90 1480.2782809199648 1298.4116581572816 1298.5596859853738 Accuracy: 0.8803  test :  0.842  Prule Train :  0.9517604939275026  Prule test :  0.9603677347702686
95 -1899.6455016751836 1281.0121500013854 1280.822185451218 Accuracy: 0.8829  test :  0.8433  Prule Train :  0.9449828536609207  Prule test :  0.9563568926437255
Resultado | acc=0.8420 | bal_acc=0.6541 | f1=0.9072 | EOdds=0.0629 | EOp=0.0132 | p-rule=95.43 | score=0.6506 | tempo=0.06 min
Estimativa parcial | média=0.13 min/modelo | total≈0.26 h | restante≈0.25 h

FAGTB african_american_0:   5%|▌         | 3/60 [00:23<06:30,  6.84s/modelo]

----------------------------------------------------------------------------------------------------
Treino 4/120 | config=african_american_0 | lambda=0.0001 | n_estimators=200 | learning_rate=0.03 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1830.1451554416485 1830.239685113761 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1700.8075461358974 1787.1979139244243 1787.367994679038 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 582.6756612492989 1747.0721399612758 1747.1304075274006 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 381.40400250799985 1707.7994375287203 1707.837577928971 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2707.676071085536 1668.9083184157719 1669.1790860228805 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1507.5044326867999 1631.8166650258404 1631.967415469109 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 830.3274798082775 1596.8057233307788 1596.8887560787598 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 37.12409554385478 1563.8244638903232 1563.8281762998777 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2869.7326174586005 1533.069331522869 1533.356304784615 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 1618.6010564592152 1503.4224488349732 1503.5843089406194 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 982.0936415552005 1475.42123460186 1475.5194439660156 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -594.4604984641696 1449.5669058679518 1449.5074598181054 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 2962.287886422361 1424.8083626194846 1425.1045914081267 Accuracy: 0.7811  test :  0.782  Prule Train :  1.0  Prule test :  0.9991166077738517
65 2196.2085826515636 1401.1018167781945 1401.3214376364597 Accuracy: 0.7834  test :  0.782  Prule Train :  0.9982498640341629  Prule test :  0.9991166077738517
70 1070.2396406736425 1378.7404430734682 1378.8474670375358 Accuracy: 0.8654  test :  0.8413  Prule Train :  0.9503137527262979  Prule test :  0.9616392368787358
75 -1273.6538805328078 1357.2204334862804 1357.093068098227 Accuracy: 0.868  test :  0.8427  Prule Train :  0.9503981481662503  Prule test :  0.9596463549563579
80 3321.8065963423264 1336.5729738863918 1336.905154546026 Accuracy: 0.8726  test :  0.8433  Prule Train :  0.951493591523171  Prule test :  0.9623674693844005
85 1993.8620701017148 1317.059169486095 1317.2585556931049 Accuracy: 0.8763  test :  0.8427  Prule Train :  0.951431862864811  Prule test :  0.9632779400271483
90 1480.2782809199648 1298.4116581572816 1298.5596859853738 Accuracy: 0.8803  test :  0.842  Prule Train :  0.9517604939275026  Prule test :  0.9603677347702686
95 -1899.6455016751836 1281.0121500013854 1280.822185451218 Accuracy: 0.8829  test :  0.8433  Prule Train :  0.9449828536609207  Prule test :  0.9563568926437255
100 3419.259226780483 1264.6576610883008 1264.9995870109788 Accuracy: 0.8837  test :  0.8413  Prule Train :  0.9461504601522646  Prule test :  0.9514272749773122
105 2650.561814986279 1248.830091943185 1249.0951481246836 Accuracy: 0.8851  test :  0.84  Prule Train :  0.9481028960997516  Prule test :  0.9532360720780294
110 1719.325741892286 1232.9591585143046 1233.131091088494 Accuracy: 0.8857  test :  0.84  Prule Train :  0.9471640640330545  Prule test :  0.951216232987217
115 -2483.831448156128 1217.2223558893932 1216.9739727445776 Accuracy: 0.8863  test :  0.84  Prule Train :  0.9445034908194786  Prule test :  0.951216232987217
120 3665.96918833918 1201.6843012852237 1202.0508982040578 Accuracy: 0.8871  test :  0.84  Prule Train :  0.9422319481377514  Prule test :  0.951216232987217
125 2322.7992747779836 1187.5160567895573 1187.7483367170353 Accuracy: 0.888  test :  0.8393  Prule Train :  0.9399585281480227  Prule test :  0.9521221532091098
130 1996.259528707602 1173.6617279862007 1173.8613539390713 Accuracy: 0.8889  test :  0.84  Prule Train :  0.9428483411754367  Prule test :  0.953029800638289
135 -2130.6711521676066 1160.0787957299374 1159.8657286147204 Accuracy: 0.8903  test :  0.8407  Prule Train :  0.9430761352065566  Prule test :  0.9521221532091098
140 1769.3701496639137 1146.9556776815616 1147.132614696528 Accuracy: 0.8911  test :  0.8407  Prule Train :  0.9407945789278034  Prule test :  0.9521221532091098
145 -2800.828635324388 1133.9682913489066 1133.6882084853742 Accuracy: 0.892  test :  0.8413  Prule Train :  0.9402381800055182  Prule test :  0.953029800638289
150 3716.8946498864443 1121.4192554526558 1121.7909449176445 Accuracy: 0.8934  test :  0.842  Prule Train :  0.9370037030113717  Prule test :  0.9539391802190508
155 2209.4258209030404 1109.1487549555814 1109.3696975376715 Accuracy: 0.8934  test :  0.8413  Prule Train :  0.9370037030113717  Prule test :  0.95485029691458
160 2877.9175816538514 1097.0861049586974 1097.3738967168629 Accuracy: 0.8949  test :  0.842  Prule Train :  0.9372226213011782  Prule test :  0.9557631557070413
165 -1176.1519440038023 1085.257466988839 1085.1398517944385 Accuracy: 0.8966  test :  0.8427  Prule Train :  0.9291777919337859  Prule test :  0.9528223459971735
170 1969.0458838007703 1073.753005459736 1073.9499100481162 Accuracy: 0.8983  test :  0.844  Prule Train :  0.929771592933798  Prule test :  0.95667776159767
175 -2958.438421017753 1062.6092097021037 1062.3133658600018 Accuracy: 0.8994  test :  0.844  Prule Train :  0.9313250960130524  Prule test :  0.954647676161919
180 2959.7218110621125 1051.813446916866 1052.1094190979725 Accuracy: 0.9003  test :  0.8433  Prule Train :  0.9307568251227453  Prule test :  0.9573988222027316
185 3550.811197081422 1041.2830622250221 1041.6381433447305 Accuracy: 0.9023  test :  0.842  Prule Train :  0.9300068778258591  Prule test :  0.959241745825836
190 2403.5112484934216 1031.1009674594509 1031.3413185843003 Accuracy: 0.9031  test :  0.8407  Prule Train :  0.929435833630476  Prule test :  0.9590502769850596
195 1941.3427327409959 1021.0298582329482 1021.2239925062224 Accuracy: 0.9043  test :  0.84  Prule Train :  0.929253782135619  Prule test :  0.959976895610166
Resultado | acc=0.8393 | bal_acc=0.6634 | f1=0.9047 | EOdds=0.0345 | EOp=0.0168 | p-rule=95.70 | score=0.6611 | tempo=0.12 min

FAGTB african_american_0:   7%|▋         | 4/60 [00:30<06:29,  6.96s/modelo]

----------------------------------------------------------------------------------------------------
Treino 5/120 | config=african_american_0 | lambda=0.0001 | n_estimators=100 | learning_rate=0.05 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1824.1998321701997 1824.294361842312 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1709.8424127807186 1754.5810627507503 1754.7520469920282 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 585.1841749587791 1689.6760707892759 1689.734589206772 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 323.5790453634411 1626.927207638042 1626.9595655425787 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2758.0019295173506 1569.8029464897104 1570.0787466826623 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1520.5870299876722 1518.7769907781112 1518.9290494811098 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 879.0857891664725 1471.594394995191 1471.6823035741077 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -307.0583296628472 1429.178701114983 1429.1479952820166 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2883.3593610198322 1389.9610916368736 1390.2494275729755 Accuracy: 0.8506  test :  0.8313  Prule Train :  0.9622183680497439  Prule test :  0.9616338630313785
45 2020.313581824657 1354.197984606701 1354.4000159648838 Accuracy: 0.8689  test :  0.8427  Prule Train :  0.9515548193404894  Prule test :  0.9596463549563579
50 1210.3222811347987 1320.6408451466993 1320.7618773748127 Accuracy: 0.876  test :  0.8427  Prule Train :  0.9510428882683822  Prule test :  0.9632779400271483
55 -953.506824924537 1289.159186495436 1289.0638358129436 Accuracy: 0.8829  test :  0.8427  Prule Train :  0.9466976425561068  Prule test :  0.9554512516469038
60 2784.1643081073184 1261.7069397975688 1261.9853562283795 Accuracy: 0.884  test :  0.8407  Prule Train :  0.9465403037699622  Prule test :  0.9523308146496554
65 2252.4220033103356 1235.45015946808 1235.675401668411 Accuracy: 0.8857  test :  0.84  Prule Train :  0.9471640640330545  Prule test :  0.9532360720780294
70 1570.5255009361706 1207.4162643735697 1207.5733169236635 Accuracy: 0.8869  test :  0.84  Prule Train :  0.9418429176059026  Prule test :  0.951216232987217
75 -1324.101055995286 1183.818496867334 1183.6860867617345 Accuracy: 0.8886  test :  0.84  Prule Train :  0.9407359959132403  Prule test :  0.951216232987217
80 3336.21097545896 1161.2729051913766 1161.6065262889224 Accuracy: 0.8903  test :  0.8407  Prule Train :  0.9396254058802542  Prule test :  0.9521221532091098
85 2559.0061286339187 1139.08736544475 1139.3432660576136 Accuracy: 0.892  test :  0.842  Prule Train :  0.9402381800055182  Prule test :  0.9539391802190508
90 1789.760739345022 1118.2652697784256 1118.44424585236 Accuracy: 0.8934  test :  0.842  Prule Train :  0.9387322806774779  Prule test :  0.9539391802190508
95 -2869.8458261170435 1097.8741179998708 1097.587133417259 Accuracy: 0.8954  test :  0.842  Prule Train :  0.9362714424750584  Prule test :  0.9539391802190508
Resultado | acc=0.8420 | bal_acc=0.6596 | f1=0.9068 | EOdds=0.0413 | EOp=0.0220 | p-rule=95.19 | score=0.6569 | tempo=0.06 min

FAGTB african_american_0:   8%|▊         | 5/60 [00:34<05:18,  5.79s/modelo]

----------------------------------------------------------------------------------------------------
Treino 6/120 | config=african_american_0 | lambda=0.0001 | n_estimators=200 | learning_rate=0.05 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1824.1998321701997 1824.294361842312 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1709.8424127807186 1754.5810627507503 1754.7520469920282 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 585.1841749587791 1689.6760707892759 1689.734589206772 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 323.5790453634411 1626.927207638042 1626.9595655425787 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2758.0019295173506 1569.8029464897104 1570.0787466826623 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1520.5870299876722 1518.7769907781112 1518.9290494811098 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 879.0857891664725 1471.594394995191 1471.6823035741077 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -307.0583296628472 1429.178701114983 1429.1479952820166 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2883.3593610198322 1389.9610916368736 1390.2494275729755 Accuracy: 0.8506  test :  0.8313  Prule Train :  0.9622183680497439  Prule test :  0.9616338630313785
45 2020.313581824657 1354.197984606701 1354.4000159648838 Accuracy: 0.8689  test :  0.8427  Prule Train :  0.9515548193404894  Prule test :  0.9596463549563579
50 1210.3222811347987 1320.6408451466993 1320.7618773748127 Accuracy: 0.876  test :  0.8427  Prule Train :  0.9510428882683822  Prule test :  0.9632779400271483
55 -953.506824924537 1289.159186495436 1289.0638358129436 Accuracy: 0.8829  test :  0.8427  Prule Train :  0.9466976425561068  Prule test :  0.9554512516469038
60 2784.1643081073184 1261.7069397975688 1261.9853562283795 Accuracy: 0.884  test :  0.8407  Prule Train :  0.9465403037699622  Prule test :  0.9523308146496554
65 2252.4220033103356 1235.45015946808 1235.675401668411 Accuracy: 0.8857  test :  0.84  Prule Train :  0.9471640640330545  Prule test :  0.9532360720780294
70 1570.5255009361706 1207.4162643735697 1207.5733169236635 Accuracy: 0.8869  test :  0.84  Prule Train :  0.9418429176059026  Prule test :  0.951216232987217
75 -1324.101055995286 1183.818496867334 1183.6860867617345 Accuracy: 0.8886  test :  0.84  Prule Train :  0.9407359959132403  Prule test :  0.951216232987217
80 3336.21097545896 1161.2729051913766 1161.6065262889224 Accuracy: 0.8903  test :  0.8407  Prule Train :  0.9396254058802542  Prule test :  0.9521221532091098
85 2559.0061286339187 1139.08736544475 1139.3432660576136 Accuracy: 0.892  test :  0.842  Prule Train :  0.9402381800055182  Prule test :  0.9539391802190508
90 1789.760739345022 1118.2652697784256 1118.44424585236 Accuracy: 0.8934  test :  0.842  Prule Train :  0.9387322806774779  Prule test :  0.9539391802190508
95 -2869.8458261170435 1097.8741179998708 1097.587133417259 Accuracy: 0.8954  test :  0.842  Prule Train :  0.9362714424750584  Prule test :  0.9539391802190508
100 3340.8694671229823 1078.5964767915539 1078.9305637382658 Accuracy: 0.898  test :  0.8433  Prule Train :  0.9328478048304248  Prule test :  0.953734137715831
105 2848.4169276600264 1060.38864903429 1060.6734907270559 Accuracy: 0.9006  test :  0.8427  Prule Train :  0.9276750594944946  Prule test :  0.9544438875663033
110 -1065.583793858362 1042.6602836321256 1042.5537252527397 Accuracy: 0.9023  test :  0.8407  Prule Train :  0.9300068778258591  Prule test :  0.9572023959118706
115 1930.0291344532648 1025.8256366937871 1026.0186396072327 Accuracy: 0.904  test :  0.8393  Prule Train :  0.9306064077282472  Prule test :  0.9590502769850596
120 -246.60943134113 1009.5208735458716 1009.4962126027375 Accuracy: 0.9063  test :  0.8393  Prule Train :  0.9319926353882293  Prule test :  0.9570048309178745
125 2409.6129302334866 994.5824509286194 994.8234122216428 Accuracy: 0.9069  test :  0.8393  Prule Train :  0.9327781327631878  Prule test :  0.9549554284753173
130 -223.00579550654624 980.530151097749 980.5078505181984 Accuracy: 0.9083  test :  0.8407  Prule Train :  0.9312399159171999  Prule test :  0.9547505587652342
135 2132.8834023432537 967.3187131258787 967.532001466113 Accuracy: 0.9103  test :  0.8413  Prule Train :  0.9304840136999926  Prule test :  0.9517669632690929
140 554.9336528773792 953.1605167442914 953.2160101095792 Accuracy: 0.9129  test :  0.84  Prule Train :  0.9322752389642944  Prule test :  0.9536168504668949
145 -1446.0963915803084 938.4031677514427 938.2585581122846 Accuracy: 0.9134  test :  0.84  Prule Train :  0.933066980143882  Prule test :  0.9536168504668949
150 1765.768373784785 923.6966361440439 923.8732129814223 Accuracy: 0.9143  test :  0.84  Prule Train :  0.9342571165981471  Prule test :  0.9536168504668949
155 1381.714919455233 910.0025345575542 910.1407060494998 Accuracy: 0.9163  test :  0.8407  Prule Train :  0.9335018448724162  Prule test :  0.9526910088644998
160 -1183.3773509818134 896.6843374402663 896.5659997051681 Accuracy: 0.9166  test :  0.8413  Prule Train :  0.9338997569972552  Prule test :  0.9536168504668949
165 2186.8383557280868 883.91092009365 884.1296039292228 Accuracy: 0.9171  test :  0.8413  Prule Train :  0.9346965997933281  Prule test :  0.9536168504668949
170 -1663.0021481966255 871.8884496733504 871.7221494585306 Accuracy: 0.918  test :  0.842  Prule Train :  0.9323452503594878  Prule test :  0.9545444933175434
175 3012.8515264155376 860.3108224179571 860.6121075705985 Accuracy: 0.9206  test :  0.842  Prule Train :  0.9359404119932648  Prule test :  0.9545444933175434
180 1477.4557207642047 849.5999121875759 849.7476577596524 Accuracy: 0.9223  test :  0.8427  Prule Train :  0.934781550759227  Prule test :  0.9554739426781255
185 -1893.936874021123 839.5803258472113 839.3909321598092 Accuracy: 0.9229  test :  0.8433  Prule Train :  0.9320159248694069  Prule test :  0.96033934252386
190 2343.0730855505744 831.2397712202926 831.4740785288476 Accuracy: 0.924  test :  0.8433  Prule Train :  0.9318328967701234  Prule test :  0.96033934252386
195 -1706.9030341216903 821.7859651745621 821.6152748711501 Accuracy: 0.9249  test :  0.8433  Prule Train :  0.9312486867193276  Prule test :  0.96033934252386
Resultado | acc=0.8433 | bal_acc=0.6758 | f1=0.9066 | EOdds=0.0182 | EOp=0.0182 | p-rule=96.03 | score=0.6743 | tempo=0.12 min

FAGTB african_american_0:  10%|█         | 6/60 [00:41<05:41,  6.32s/modelo]

----------------------------------------------------------------------------------------------------
Treino 7/120 | config=african_american_0 | lambda=0.0001 | n_estimators=100 | learning_rate=0.05 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1824.1998321701997 1824.294361842312 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1709.8424127807186 1754.5810627507503 1754.7520469920282 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 585.1841749587791 1689.6760707892759 1689.734589206772 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 323.5790453634411 1626.927207638042 1626.9595655425787 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2758.0019295173506 1569.8029464897104 1570.0787466826623 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1520.5870299876722 1518.7769907781112 1518.9290494811098 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 879.0857891664725 1471.594394995191 1471.6823035741077 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -307.0583296628472 1429.178701114983 1429.1479952820166 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2883.3593610198322 1389.9610916368736 1390.2494275729755 Accuracy: 0.8506  test :  0.8313  Prule Train :  0.9622183680497439  Prule test :  0.9616338630313785
45 2020.313581824657 1354.197984606701 1354.4000159648838 Accuracy: 0.8689  test :  0.8427  Prule Train :  0.9515548193404894  Prule test :  0.9596463549563579
50 1210.3222811347987 1320.6408451466993 1320.7618773748127 Accuracy: 0.876  test :  0.8427  Prule Train :  0.9510428882683822  Prule test :  0.9632779400271483
55 -953.506824924537 1289.159186495436 1289.0638358129436 Accuracy: 0.8829  test :  0.8427  Prule Train :  0.9466976425561068  Prule test :  0.9554512516469038
60 2784.1643081073184 1261.7069397975688 1261.9853562283795 Accuracy: 0.884  test :  0.8407  Prule Train :  0.9465403037699622  Prule test :  0.9523308146496554
65 2252.4220033103356 1235.45015946808 1235.675401668411 Accuracy: 0.8857  test :  0.84  Prule Train :  0.9471640640330545  Prule test :  0.9532360720780294
70 1570.5255009361706 1207.4162643735697 1207.5733169236635 Accuracy: 0.8869  test :  0.84  Prule Train :  0.9418429176059026  Prule test :  0.951216232987217
75 -1324.101055995286 1183.818496867334 1183.6860867617345 Accuracy: 0.8886  test :  0.84  Prule Train :  0.9407359959132403  Prule test :  0.951216232987217
80 3336.21097545896 1161.2729051913766 1161.6065262889224 Accuracy: 0.8903  test :  0.8407  Prule Train :  0.9396254058802542  Prule test :  0.9521221532091098
85 2559.0061286339187 1139.08736544475 1139.3432660576136 Accuracy: 0.892  test :  0.842  Prule Train :  0.9402381800055182  Prule test :  0.9539391802190508
90 1789.760739345022 1118.2652697784256 1118.44424585236 Accuracy: 0.8934  test :  0.842  Prule Train :  0.9387322806774779  Prule test :  0.9539391802190508
95 -2869.8458261170435 1097.8741179998708 1097.587133417259 Accuracy: 0.8954  test :  0.842  Prule Train :  0.9362714424750584  Prule test :  0.9539391802190508
Resultado | acc=0.8420 | bal_acc=0.6596 | f1=0.9068 | EOdds=0.0413 | EOp=0.0220 | p-rule=95.19 | score=0.6569 | tempo=0.06 min

FAGTB african_american_0:  12%|█▏        | 7/60 [00:45<04:52,  5.52s/modelo]

----------------------------------------------------------------------------------------------------
Treino 8/120 | config=african_american_0 | lambda=0.0001 | n_estimators=200 | learning_rate=0.05 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1824.1998321701997 1824.294361842312 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1709.8424127807186 1754.5810627507503 1754.7520469920282 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 585.1841749587791 1689.6760707892759 1689.734589206772 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 323.5790453634411 1626.927207638042 1626.9595655425787 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2758.0019295173506 1569.8029464897104 1570.0787466826623 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1520.5870299876722 1518.7769907781112 1518.9290494811098 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 879.0857891664725 1471.594394995191 1471.6823035741077 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -307.0583296628472 1429.178701114983 1429.1479952820166 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2883.3593610198322 1389.9610916368736 1390.2494275729755 Accuracy: 0.8506  test :  0.8313  Prule Train :  0.9622183680497439  Prule test :  0.9616338630313785
45 2020.313581824657 1354.197984606701 1354.4000159648838 Accuracy: 0.8689  test :  0.8427  Prule Train :  0.9515548193404894  Prule test :  0.9596463549563579
50 1210.3222811347987 1320.6408451466993 1320.7618773748127 Accuracy: 0.876  test :  0.8427  Prule Train :  0.9510428882683822  Prule test :  0.9632779400271483
55 -953.506824924537 1289.159186495436 1289.0638358129436 Accuracy: 0.8829  test :  0.8427  Prule Train :  0.9466976425561068  Prule test :  0.9554512516469038
60 2784.1643081073184 1261.7069397975688 1261.9853562283795 Accuracy: 0.884  test :  0.8407  Prule Train :  0.9465403037699622  Prule test :  0.9523308146496554
65 2252.4220033103356 1235.45015946808 1235.675401668411 Accuracy: 0.8857  test :  0.84  Prule Train :  0.9471640640330545  Prule test :  0.9532360720780294
70 1570.5255009361706 1207.4162643735697 1207.5733169236635 Accuracy: 0.8869  test :  0.84  Prule Train :  0.9418429176059026  Prule test :  0.951216232987217
75 -1324.101055995286 1183.818496867334 1183.6860867617345 Accuracy: 0.8886  test :  0.84  Prule Train :  0.9407359959132403  Prule test :  0.951216232987217
80 3336.21097545896 1161.2729051913766 1161.6065262889224 Accuracy: 0.8903  test :  0.8407  Prule Train :  0.9396254058802542  Prule test :  0.9521221532091098
85 2559.0061286339187 1139.08736544475 1139.3432660576136 Accuracy: 0.892  test :  0.842  Prule Train :  0.9402381800055182  Prule test :  0.9539391802190508
90 1789.760739345022 1118.2652697784256 1118.44424585236 Accuracy: 0.8934  test :  0.842  Prule Train :  0.9387322806774779  Prule test :  0.9539391802190508
95 -2869.8458261170435 1097.8741179998708 1097.587133417259 Accuracy: 0.8954  test :  0.842  Prule Train :  0.9362714424750584  Prule test :  0.9539391802190508
100 3340.8694671229823 1078.5964767915539 1078.9305637382658 Accuracy: 0.898  test :  0.8433  Prule Train :  0.9328478048304248  Prule test :  0.953734137715831
105 2848.4169276600264 1060.38864903429 1060.6734907270559 Accuracy: 0.9006  test :  0.8427  Prule Train :  0.9276750594944946  Prule test :  0.9544438875663033
110 -1065.583793858362 1042.6602836321256 1042.5537252527397 Accuracy: 0.9023  test :  0.8407  Prule Train :  0.9300068778258591  Prule test :  0.9572023959118706
115 1930.0291344532648 1025.8256366937871 1026.0186396072327 Accuracy: 0.904  test :  0.8393  Prule Train :  0.9306064077282472  Prule test :  0.9590502769850596
120 -246.60943134113 1009.5208735458716 1009.4962126027375 Accuracy: 0.9063  test :  0.8393  Prule Train :  0.9319926353882293  Prule test :  0.9570048309178745
125 2409.6129302334866 994.5824509286194 994.8234122216428 Accuracy: 0.9069  test :  0.8393  Prule Train :  0.9327781327631878  Prule test :  0.9549554284753173
130 -223.00579550654624 980.530151097749 980.5078505181984 Accuracy: 0.9083  test :  0.8407  Prule Train :  0.9312399159171999  Prule test :  0.9547505587652342
135 2132.8834023432537 967.3187131258787 967.532001466113 Accuracy: 0.9103  test :  0.8413  Prule Train :  0.9304840136999926  Prule test :  0.9517669632690929
140 554.9336528773792 953.1605167442914 953.2160101095792 Accuracy: 0.9129  test :  0.84  Prule Train :  0.9322752389642944  Prule test :  0.9536168504668949
145 -1446.0963915803084 938.4031677514427 938.2585581122846 Accuracy: 0.9134  test :  0.84  Prule Train :  0.933066980143882  Prule test :  0.9536168504668949
150 1765.768373784785 923.6966361440439 923.8732129814223 Accuracy: 0.9143  test :  0.84  Prule Train :  0.9342571165981471  Prule test :  0.9536168504668949
155 1381.714919455233 910.0025345575542 910.1407060494998 Accuracy: 0.9163  test :  0.8407  Prule Train :  0.9335018448724162  Prule test :  0.9526910088644998
160 -1183.3773509818134 896.6843374402663 896.5659997051681 Accuracy: 0.9166  test :  0.8413  Prule Train :  0.9338997569972552  Prule test :  0.9536168504668949
165 2186.8383557280868 883.91092009365 884.1296039292228 Accuracy: 0.9171  test :  0.8413  Prule Train :  0.9346965997933281  Prule test :  0.9536168504668949
170 -1663.0021481966255 871.8884496733504 871.7221494585306 Accuracy: 0.918  test :  0.842  Prule Train :  0.9323452503594878  Prule test :  0.9545444933175434
175 3012.8515264155376 860.3108224179571 860.6121075705985 Accuracy: 0.9206  test :  0.842  Prule Train :  0.9359404119932648  Prule test :  0.9545444933175434
180 1477.4557207642047 849.5999121875759 849.7476577596524 Accuracy: 0.9223  test :  0.8427  Prule Train :  0.934781550759227  Prule test :  0.9554739426781255
185 -1893.936874021123 839.5803258472113 839.3909321598092 Accuracy: 0.9229  test :  0.8433  Prule Train :  0.9320159248694069  Prule test :  0.96033934252386
190 2343.0730855505744 831.2397712202926 831.4740785288476 Accuracy: 0.924  test :  0.8433  Prule Train :  0.9318328967701234  Prule test :  0.96033934252386
195 -1706.9030341216903 821.7859651745621 821.6152748711501 Accuracy: 0.9249  test :  0.8433  Prule Train :  0.9312486867193276  Prule test :  0.96033934252386
Resultado | acc=0.8433 | bal_acc=0.6758 | f1=0.9066 | EOdds=0.0182 | EOp=0.0182 | p-rule=96.03 | score=0.6743 | tempo=0.12 min

FAGTB african_american_0:  13%|█▎        | 8/60 [00:53<05:16,  6.08s/modelo]

----------------------------------------------------------------------------------------------------
Treino 9/120 | config=african_american_0 | lambda=0.0001 | n_estimators=100 | learning_rate=0.1 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1809.4278781434023 1809.5224078155147 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1729.4466186748587 1675.0911821930333 1675.264126854901 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 586.8036623775893 1557.4546836843983 1557.513364050636 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 189.7267946762315 1461.6167441367334 1461.635716816201 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2802.4480477556162 1381.1861446555267 1381.4663894603023 Accuracy: 0.8654  test :  0.8413  Prule Train :  0.9503137527262979  Prule test :  0.9616392368787358
25 1536.166611273548 1312.921277456292 1313.0748941174193 Accuracy: 0.8774  test :  0.8427  Prule Train :  0.9529909482607387  Prule test :  0.9632779400271483
30 980.4653053468504 1255.638677281498 1255.7367238120323 Accuracy: 0.8849  test :  0.8407  Prule Train :  0.9442742823274597  Prule test :  0.9541430521656393
35 -769.4566953603245 1203.220511391502 1203.1435657219658 Accuracy: 0.8871  test :  0.8393  Prule Train :  0.9405126309991145  Prule test :  0.9521221532091098
40 2815.891798231318 1157.6599794932142 1157.9415686730374 Accuracy: 0.8906  test :  0.8407  Prule Train :  0.9400148072088412  Prule test :  0.9521221532091098
45 2193.5162504168597 1115.0541192938913 1115.273470918933 Accuracy: 0.8949  test :  0.8413  Prule Train :  0.9354925144863105  Prule test :  0.9528223459971735
50 336.4833847121911 1076.0625753149354 1076.0962236534067 Accuracy: 0.8986  test :  0.8427  Prule Train :  0.9301594826263027  Prule test :  0.954647676161919
55 -1259.5560059922072 1038.7891126471743 1038.6631570465752 Accuracy: 0.9037  test :  0.8433  Prule Train :  0.926733985276899  Prule test :  0.9553616220735787
60 -846.523595710052 1006.7940094268924 1006.7093570673214 Accuracy: 0.908  test :  0.8393  Prule Train :  0.9290963939975224  Prule test :  0.9531118851771027
65 2664.1571092225513 978.6284736954958 978.8948894064181 Accuracy: 0.9111  test :  0.8387  Prule Train :  0.9316658308215421  Prule test :  0.954032766225583
70 2256.551466947468 948.4104476052206 948.6361027519154 Accuracy: 0.914  test :  0.8393  Prule Train :  0.9338600672498266  Prule test :  0.9568061172901922
75 313.14554529766025 917.9631501267622 917.994464681292 Accuracy: 0.9151  test :  0.84  Prule Train :  0.9336811847137026  Prule test :  0.9595956394980353
80 -1542.6176290354551 891.1518274349772 890.9975656720736 Accuracy: 0.9189  test :  0.8387  Prule Train :  0.935317176465977  Prule test :  0.9614643749206215
85 -1102.2507381134412 865.9039240427157 865.7936989689044 Accuracy: 0.9209  test :  0.8407  Prule Train :  0.9381247323130019  Prule test :  0.9624014747012459
90 2234.425463559492 844.9233598887245 845.1468024350804 Accuracy: 0.922  test :  0.8407  Prule Train :  0.9325982243170489  Prule test :  0.9624014747012459
95 2832.017833351667 825.2593317479252 825.5425335312605 Accuracy: 0.9237  test :  0.84  Prule Train :  0.9332174924562602  Prule test :  0.9594033392660396
Resultado | acc=0.8393 | bal_acc=0.6699 | f1=0.9043 | EOdds=0.0233 | EOp=0.0149 | p-rule=96.03 | score=0.6683 | tempo=0.06 min

FAGTB african_american_0:  15%|█▌        | 9/60 [00:56<04:32,  5.34s/modelo]

----------------------------------------------------------------------------------------------------
Treino 10/120 | config=african_american_0 | lambda=0.0001 | n_estimators=200 | learning_rate=0.1 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1809.4278781434023 1809.5224078155147 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1729.4466186748587 1675.0911821930333 1675.264126854901 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 586.8036623775893 1557.4546836843983 1557.513364050636 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 189.7267946762315 1461.6167441367334 1461.635716816201 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2802.4480477556162 1381.1861446555267 1381.4663894603023 Accuracy: 0.8654  test :  0.8413  Prule Train :  0.9503137527262979  Prule test :  0.9616392368787358
25 1536.166611273548 1312.921277456292 1313.0748941174193 Accuracy: 0.8774  test :  0.8427  Prule Train :  0.9529909482607387  Prule test :  0.9632779400271483
30 980.4653053468504 1255.638677281498 1255.7367238120323 Accuracy: 0.8849  test :  0.8407  Prule Train :  0.9442742823274597  Prule test :  0.9541430521656393
35 -769.4566953603245 1203.220511391502 1203.1435657219658 Accuracy: 0.8871  test :  0.8393  Prule Train :  0.9405126309991145  Prule test :  0.9521221532091098
40 2815.891798231318 1157.6599794932142 1157.9415686730374 Accuracy: 0.8906  test :  0.8407  Prule Train :  0.9400148072088412  Prule test :  0.9521221532091098
45 2193.5162504168597 1115.0541192938913 1115.273470918933 Accuracy: 0.8949  test :  0.8413  Prule Train :  0.9354925144863105  Prule test :  0.9528223459971735
50 336.4833847121911 1076.0625753149354 1076.0962236534067 Accuracy: 0.8986  test :  0.8427  Prule Train :  0.9301594826263027  Prule test :  0.954647676161919
55 -1259.5560059922072 1038.7891126471743 1038.6631570465752 Accuracy: 0.9037  test :  0.8433  Prule Train :  0.926733985276899  Prule test :  0.9553616220735787
60 -846.523595710052 1006.7940094268924 1006.7093570673214 Accuracy: 0.908  test :  0.8393  Prule Train :  0.9290963939975224  Prule test :  0.9531118851771027
65 2664.1571092225513 978.6284736954958 978.8948894064181 Accuracy: 0.9111  test :  0.8387  Prule Train :  0.9316658308215421  Prule test :  0.954032766225583
70 2256.551466947468 948.4104476052206 948.6361027519154 Accuracy: 0.914  test :  0.8393  Prule Train :  0.9338600672498266  Prule test :  0.9568061172901922
75 313.14554529766025 917.9631501267622 917.994464681292 Accuracy: 0.9151  test :  0.84  Prule Train :  0.9336811847137026  Prule test :  0.9595956394980353
80 -1542.6176290354551 891.1518274349772 890.9975656720736 Accuracy: 0.9189  test :  0.8387  Prule Train :  0.935317176465977  Prule test :  0.9614643749206215
85 -1102.2507381134412 865.9039240427157 865.7936989689044 Accuracy: 0.9209  test :  0.8407  Prule Train :  0.9381247323130019  Prule test :  0.9624014747012459
90 2234.425463559492 844.9233598887245 845.1468024350804 Accuracy: 0.922  test :  0.8407  Prule Train :  0.9325982243170489  Prule test :  0.9624014747012459
95 2832.017833351667 825.2593317479252 825.5425335312605 Accuracy: 0.9237  test :  0.84  Prule Train :  0.9332174924562602  Prule test :  0.9594033392660396
100 1202.751825464044 805.781732009425 805.9020071919714 Accuracy: 0.9277  test :  0.8393  Prule Train :  0.9334763568483575  Prule test :  0.96033934252386
105 -1511.524181926044 786.7951967033645 786.6440442851718 Accuracy: 0.9297  test :  0.84  Prule Train :  0.9345061854108898  Prule test :  0.9513361611876988
110 -390.54597297462357 770.5161580903332 770.4771034930357 Accuracy: 0.9329  test :  0.8393  Prule Train :  0.9299477072443372  Prule test :  0.9522652004076086
115 1279.671566667099 753.5575884512432 753.6855556079098 Accuracy: 0.9369  test :  0.8413  Prule Train :  0.9301934823401794  Prule test :  0.9552691915760869
120 2606.641069471258 739.1529079980347 739.4135721049818 Accuracy: 0.9377  test :  0.8427  Prule Train :  0.9295991710363993  Prule test :  0.9531960559309788
125 1692.5380500854867 724.1072498788769 724.2765036838855 Accuracy: 0.9389  test :  0.8427  Prule Train :  0.929409854319384  Prule test :  0.9511188632689528
130 1352.7806403863046 710.491521167049 710.6267992310875 Accuracy: 0.9406  test :  0.8433  Prule Train :  0.9227721800938119  Prule test :  0.9481089934484812
135 2638.822110996158 696.3880227814251 696.6519049925247 Accuracy: 0.942  test :  0.8433  Prule Train :  0.9211629017299766  Prule test :  0.9499680306905371
140 1194.6364262621455 682.159967355612 682.2794309982382 Accuracy: 0.9429  test :  0.8453  Prule Train :  0.9223744268089726  Prule test :  0.9467209610533964
145 -1560.3691022222465 668.4945931570177 668.3385562467954 Accuracy: 0.9451  test :  0.8427  Prule Train :  0.918334761047301  Prule test :  0.940920716112532
150 2378.5893911678695 656.3428754970755 656.5807344361922 Accuracy: 0.9471  test :  0.8413  Prule Train :  0.9156983671006523  Prule test :  0.9388253616077143
155 1866.5127953297629 645.2912965919779 645.4779478715109 Accuracy: 0.9486  test :  0.842  Prule Train :  0.9177171024778584  Prule test :  0.9397475869138122
160 777.8711389699306 634.5641502348408 634.6419373487379 Accuracy: 0.95  test :  0.842  Prule Train :  0.9160876291816785  Prule test :  0.9397475869138122
165 -1483.999918776205 624.2392754137873 624.0908754219097 Accuracy: 0.9514  test :  0.8407  Prule Train :  0.9144538336751639  Prule test :  0.9436962934461972
170 2365.567261596755 614.1376679273004 614.3742246534601 Accuracy: 0.9534  test :  0.842  Prule Train :  0.9099631496797957  Prule test :  0.9376469582317984
175 1742.7560732197794 602.6157415906418 602.7900171979638 Accuracy: 0.9543  test :  0.842  Prule Train :  0.9093419587793612  Prule test :  0.939494538445063
180 917.3696608273212 592.9857190516939 593.0774560177765 Accuracy: 0.9557  test :  0.842  Prule Train :  0.9113609240519619  Prule test :  0.9413494141379458
185 -1363.49344319032 584.8430330652135 584.7066837208945 Accuracy: 0.9569  test :  0.8427  Prule Train :  0.9129825627068587  Prule test :  0.9404210616585198
190 2251.5923338349694 576.2999290615362 576.5250882949197 Accuracy: 0.9586  test :  0.8427  Prule Train :  0.9135812959444394  Prule test :  0.9404210616585198
195 1673.1645147447525 568.6058338186091 568.7731502700835 Accuracy: 0.9594  test :  0.842  Prule Train :  0.9148048423229364  Prule test :  0.9434546779864506
Resultado | acc=0.8420 | bal_acc=0.6848 | f1=0.9051 | EOdds=0.0305 | EOp=0.0299 | p-rule=94.35 | score=0.6824 | tempo=0.12 min

FAGTB african_american_0:  17%|█▋        | 10/60 [01:03<04:55,  5.92s/modelo]

----------------------------------------------------------------------------------------------------
Treino 11/120 | config=african_american_0 | lambda=0.0001 | n_estimators=100 | learning_rate=0.1 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1809.4278781434023 1809.5224078155147 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1729.4466186748587 1675.0911821930333 1675.264126854901 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 586.8036623775893 1557.4546836843983 1557.513364050636 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 189.7267946762315 1461.6167441367334 1461.635716816201 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2802.4480477556162 1381.1861446555267 1381.4663894603023 Accuracy: 0.8654  test :  0.8413  Prule Train :  0.9503137527262979  Prule test :  0.9616392368787358
25 1536.166611273548 1312.921277456292 1313.0748941174193 Accuracy: 0.8774  test :  0.8427  Prule Train :  0.9529909482607387  Prule test :  0.9632779400271483
30 980.4653053468504 1255.638677281498 1255.7367238120323 Accuracy: 0.8849  test :  0.8407  Prule Train :  0.9442742823274597  Prule test :  0.9541430521656393
35 -769.4566953603245 1203.220511391502 1203.1435657219658 Accuracy: 0.8871  test :  0.8393  Prule Train :  0.9405126309991145  Prule test :  0.9521221532091098
40 2815.891798231318 1157.6599794932142 1157.9415686730374 Accuracy: 0.8906  test :  0.8407  Prule Train :  0.9400148072088412  Prule test :  0.9521221532091098
45 2193.5162504168597 1115.0541192938913 1115.273470918933 Accuracy: 0.8949  test :  0.8413  Prule Train :  0.9354925144863105  Prule test :  0.9528223459971735
50 336.4833847121911 1076.0625753149354 1076.0962236534067 Accuracy: 0.8986  test :  0.8427  Prule Train :  0.9301594826263027  Prule test :  0.954647676161919
55 -1259.5560059922072 1038.7891126471743 1038.6631570465752 Accuracy: 0.9037  test :  0.8433  Prule Train :  0.926733985276899  Prule test :  0.9553616220735787
60 -846.523595710052 1006.7940094268924 1006.7093570673214 Accuracy: 0.908  test :  0.8393  Prule Train :  0.9290963939975224  Prule test :  0.9531118851771027
65 2664.1571092225513 978.6284736954958 978.8948894064181 Accuracy: 0.9111  test :  0.8387  Prule Train :  0.9316658308215421  Prule test :  0.954032766225583
70 2256.551466947468 948.4104476052206 948.6361027519154 Accuracy: 0.914  test :  0.8393  Prule Train :  0.9338600672498266  Prule test :  0.9568061172901922
75 313.14554529766025 917.9631501267622 917.994464681292 Accuracy: 0.9151  test :  0.84  Prule Train :  0.9336811847137026  Prule test :  0.9595956394980353
80 -1542.6176290354551 891.1518274349772 890.9975656720736 Accuracy: 0.9189  test :  0.8387  Prule Train :  0.935317176465977  Prule test :  0.9614643749206215
85 -1102.2507381134412 865.9039240427157 865.7936989689044 Accuracy: 0.9209  test :  0.8407  Prule Train :  0.9381247323130019  Prule test :  0.9624014747012459
90 2234.425463559492 844.9233598887245 845.1468024350804 Accuracy: 0.922  test :  0.8407  Prule Train :  0.9325982243170489  Prule test :  0.9624014747012459
95 2832.017833351667 825.2593317479252 825.5425335312605 Accuracy: 0.9237  test :  0.84  Prule Train :  0.9332174924562602  Prule test :  0.9594033392660396
Resultado | acc=0.8393 | bal_acc=0.6699 | f1=0.9043 | EOdds=0.0233 | EOp=0.0149 | p-rule=96.03 | score=0.6683 | tempo=0.06 min

FAGTB african_american_0:  18%|█▊        | 11/60 [01:07<04:16,  5.23s/modelo]

----------------------------------------------------------------------------------------------------
Treino 12/120 | config=african_american_0 | lambda=0.0001 | n_estimators=200 | learning_rate=0.1 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1809.4278781434023 1809.5224078155147 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1729.4466186748587 1675.0911821930333 1675.264126854901 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 586.8036623775893 1557.4546836843983 1557.513364050636 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 189.7267946762315 1461.6167441367334 1461.635716816201 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2802.4480477556162 1381.1861446555267 1381.4663894603023 Accuracy: 0.8654  test :  0.8413  Prule Train :  0.9503137527262979  Prule test :  0.9616392368787358
25 1536.166611273548 1312.921277456292 1313.0748941174193 Accuracy: 0.8774  test :  0.8427  Prule Train :  0.9529909482607387  Prule test :  0.9632779400271483
30 980.4653053468504 1255.638677281498 1255.7367238120323 Accuracy: 0.8849  test :  0.8407  Prule Train :  0.9442742823274597  Prule test :  0.9541430521656393
35 -769.4566953603245 1203.220511391502 1203.1435657219658 Accuracy: 0.8871  test :  0.8393  Prule Train :  0.9405126309991145  Prule test :  0.9521221532091098
40 2815.891798231318 1157.6599794932142 1157.9415686730374 Accuracy: 0.8906  test :  0.8407  Prule Train :  0.9400148072088412  Prule test :  0.9521221532091098
45 2193.5162504168597 1115.0541192938913 1115.273470918933 Accuracy: 0.8949  test :  0.8413  Prule Train :  0.9354925144863105  Prule test :  0.9528223459971735
50 336.4833847121911 1076.0625753149354 1076.0962236534067 Accuracy: 0.8986  test :  0.8427  Prule Train :  0.9301594826263027  Prule test :  0.954647676161919
55 -1259.5560059922072 1038.7891126471743 1038.6631570465752 Accuracy: 0.9037  test :  0.8433  Prule Train :  0.926733985276899  Prule test :  0.9553616220735787
60 -846.523595710052 1006.7940094268924 1006.7093570673214 Accuracy: 0.908  test :  0.8393  Prule Train :  0.9290963939975224  Prule test :  0.9531118851771027
65 2664.1571092225513 978.6284736954958 978.8948894064181 Accuracy: 0.9111  test :  0.8387  Prule Train :  0.9316658308215421  Prule test :  0.954032766225583
70 2256.551466947468 948.4104476052206 948.6361027519154 Accuracy: 0.914  test :  0.8393  Prule Train :  0.9338600672498266  Prule test :  0.9568061172901922
75 313.14554529766025 917.9631501267622 917.994464681292 Accuracy: 0.9151  test :  0.84  Prule Train :  0.9336811847137026  Prule test :  0.9595956394980353
80 -1542.6176290354551 891.1518274349772 890.9975656720736 Accuracy: 0.9189  test :  0.8387  Prule Train :  0.935317176465977  Prule test :  0.9614643749206215
85 -1102.2507381134412 865.9039240427157 865.7936989689044 Accuracy: 0.9209  test :  0.8407  Prule Train :  0.9381247323130019  Prule test :  0.9624014747012459
90 2234.425463559492 844.9233598887245 845.1468024350804 Accuracy: 0.922  test :  0.8407  Prule Train :  0.9325982243170489  Prule test :  0.9624014747012459
95 2832.017833351667 825.2593317479252 825.5425335312605 Accuracy: 0.9237  test :  0.84  Prule Train :  0.9332174924562602  Prule test :  0.9594033392660396
100 1202.751825464044 805.781732009425 805.9020071919714 Accuracy: 0.9277  test :  0.8393  Prule Train :  0.9334763568483575  Prule test :  0.96033934252386
105 -1511.524181926044 786.7951967033645 786.6440442851718 Accuracy: 0.9297  test :  0.84  Prule Train :  0.9345061854108898  Prule test :  0.9513361611876988
110 -390.54597297462357 770.5161580903332 770.4771034930357 Accuracy: 0.9329  test :  0.8393  Prule Train :  0.9299477072443372  Prule test :  0.9522652004076086
115 1279.671566667099 753.5575884512432 753.6855556079098 Accuracy: 0.9369  test :  0.8413  Prule Train :  0.9301934823401794  Prule test :  0.9552691915760869
120 2606.641069471258 739.1529079980347 739.4135721049818 Accuracy: 0.9377  test :  0.8427  Prule Train :  0.9295991710363993  Prule test :  0.9531960559309788
125 1692.5380500854867 724.1072498788769 724.2765036838855 Accuracy: 0.9389  test :  0.8427  Prule Train :  0.929409854319384  Prule test :  0.9511188632689528
130 1352.7806403863046 710.491521167049 710.6267992310875 Accuracy: 0.9406  test :  0.8433  Prule Train :  0.9227721800938119  Prule test :  0.9481089934484812
135 2638.822110996158 696.3880227814251 696.6519049925247 Accuracy: 0.942  test :  0.8433  Prule Train :  0.9211629017299766  Prule test :  0.9499680306905371
140 1194.6364262621455 682.159967355612 682.2794309982382 Accuracy: 0.9429  test :  0.8453  Prule Train :  0.9223744268089726  Prule test :  0.9467209610533964
145 -1560.3691022222465 668.4945931570177 668.3385562467954 Accuracy: 0.9451  test :  0.8427  Prule Train :  0.918334761047301  Prule test :  0.940920716112532
150 2378.5893911678695 656.3428754970755 656.5807344361922 Accuracy: 0.9471  test :  0.8413  Prule Train :  0.9156983671006523  Prule test :  0.9388253616077143
155 1866.5127953297629 645.2912965919779 645.4779478715109 Accuracy: 0.9486  test :  0.842  Prule Train :  0.9177171024778584  Prule test :  0.9397475869138122
160 777.8711389699306 634.5641502348408 634.6419373487379 Accuracy: 0.95  test :  0.842  Prule Train :  0.9160876291816785  Prule test :  0.9397475869138122
165 -1483.999918776205 624.2392754137873 624.0908754219097 Accuracy: 0.9514  test :  0.8407  Prule Train :  0.9144538336751639  Prule test :  0.9436962934461972
170 2365.567261596755 614.1376679273004 614.3742246534601 Accuracy: 0.9534  test :  0.842  Prule Train :  0.9099631496797957  Prule test :  0.9376469582317984
175 1742.7560732197794 602.6157415906418 602.7900171979638 Accuracy: 0.9543  test :  0.842  Prule Train :  0.9093419587793612  Prule test :  0.939494538445063
180 917.3696608273212 592.9857190516939 593.0774560177765 Accuracy: 0.9557  test :  0.842  Prule Train :  0.9113609240519619  Prule test :  0.9413494141379458
185 -1363.49344319032 584.8430330652135 584.7066837208945 Accuracy: 0.9569  test :  0.8427  Prule Train :  0.9129825627068587  Prule test :  0.9404210616585198
190 2251.5923338349694 576.2999290615362 576.5250882949197 Accuracy: 0.9586  test :  0.8427  Prule Train :  0.9135812959444394  Prule test :  0.9404210616585198
195 1673.1645147447525 568.6058338186091 568.7731502700835 Accuracy: 0.9594  test :  0.842  Prule Train :  0.9148048423229364  Prule test :  0.9434546779864506
Resultado | acc=0.8420 | bal_acc=0.6848 | f1=0.9051 | EOdds=0.0305 | EOp=0.0299 | p-rule=94.35 | score=0.6824 | tempo=0.12 min

FAGTB african_american_0:  20%|██        | 12/60 [01:14<04:38,  5.80s/modelo]

----------------------------------------------------------------------------------------------------
Treino 13/120 | config=african_american_0 | lambda=0.0005 | n_estimators=100 | learning_rate=0.03 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1830.219953143357 1830.692601503919 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1700.5092305485573 1787.2311180190854 1788.0813726343595 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 583.4443379476976 1747.1979915416568 1747.4897137106304 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 381.1186490351347 1707.953178473267 1708.1437377977845 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2707.648959094704 1668.9846611997996 1670.3384856793468 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1507.7182942996692 1631.9447356267478 1632.6985947738976 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 829.9823286374685 1597.0571591028968 1597.4721502672155 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 41.28864000857054 1563.8631741360332 1563.8838184560375 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2869.096617048219 1533.3048465684644 1534.7393948769886 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 1619.3726104564298 1503.887103073002 1504.6967893782303 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 982.6302184169266 1476.0511702458607 1476.5424853550692 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -592.3979194873451 1449.9008703057093 1449.604671345966 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 2964.493473975853 1425.2008586048971 1426.683105341885 Accuracy: 0.7811  test :  0.782  Prule Train :  1.0  Prule test :  0.9991166077738517
65 2191.6301147347863 1401.4953608528353 1402.591175910203 Accuracy: 0.7834  test :  0.782  Prule Train :  0.9982498640341629  Prule test :  0.9991166077738517
70 1088.2805837928213 1378.569709196214 1379.1138494881106 Accuracy: 0.8654  test :  0.8407  Prule Train :  0.9503137527262979  Prule test :  0.9607345903717943
75 -1274.1456193131648 1357.4319972494848 1356.7949244398283 Accuracy: 0.8686  test :  0.8427  Prule Train :  0.9494773715089849  Prule test :  0.9596463549563579
80 3312.9245154378596 1337.1854039683512 1338.8418662260704 Accuracy: 0.8723  test :  0.844  Prule Train :  0.9511061755657104  Prule test :  0.9614587182329515
85 2021.9924025404919 1317.4233241912311 1318.4343203925014 Accuracy: 0.8763  test :  0.8427  Prule Train :  0.951431862864811  Prule test :  0.9632779400271483
90 1487.475380189845 1298.425004069905 1299.16874176 Accuracy: 0.8811  test :  0.842  Prule Train :  0.9477893096691126  Prule test :  0.9583642127799737
95 -1910.4553272957673 1281.061528103913 1280.106300440265 Accuracy: 0.8829  test :  0.842  Prule Train :  0.9449828536609207  Prule test :  0.950525448176386
Resultado | acc=0.8413 | bal_acc=0.6537 | f1=0.9067 | EOdds=0.0629 | EOp=0.0168 | p-rule=95.14 | score=0.6500 | tempo=0.06 min

FAGTB african_american_0:  22%|██▏       | 13/60 [01:18<04:02,  5.16s/modelo]

----------------------------------------------------------------------------------------------------
Treino 14/120 | config=african_american_0 | lambda=0.0005 | n_estimators=200 | learning_rate=0.03 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1830.219953143357 1830.692601503919 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1700.5092305485573 1787.2311180190854 1788.0813726343595 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 583.4443379476976 1747.1979915416568 1747.4897137106304 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 381.1186490351347 1707.953178473267 1708.1437377977845 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2707.648959094704 1668.9846611997996 1670.3384856793468 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1507.7182942996692 1631.9447356267478 1632.6985947738976 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 829.9823286374685 1597.0571591028968 1597.4721502672155 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 41.28864000857054 1563.8631741360332 1563.8838184560375 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2869.096617048219 1533.3048465684644 1534.7393948769886 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 1619.3726104564298 1503.887103073002 1504.6967893782303 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 982.6302184169266 1476.0511702458607 1476.5424853550692 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -592.3979194873451 1449.9008703057093 1449.604671345966 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 2964.493473975853 1425.2008586048971 1426.683105341885 Accuracy: 0.7811  test :  0.782  Prule Train :  1.0  Prule test :  0.9991166077738517
65 2191.6301147347863 1401.4953608528353 1402.591175910203 Accuracy: 0.7834  test :  0.782  Prule Train :  0.9982498640341629  Prule test :  0.9991166077738517
70 1088.2805837928213 1378.569709196214 1379.1138494881106 Accuracy: 0.8654  test :  0.8407  Prule Train :  0.9503137527262979  Prule test :  0.9607345903717943
75 -1274.1456193131648 1357.4319972494848 1356.7949244398283 Accuracy: 0.8686  test :  0.8427  Prule Train :  0.9494773715089849  Prule test :  0.9596463549563579
80 3312.9245154378596 1337.1854039683512 1338.8418662260704 Accuracy: 0.8723  test :  0.844  Prule Train :  0.9511061755657104  Prule test :  0.9614587182329515
85 2021.9924025404919 1317.4233241912311 1318.4343203925014 Accuracy: 0.8763  test :  0.8427  Prule Train :  0.951431862864811  Prule test :  0.9632779400271483
90 1487.475380189845 1298.425004069905 1299.16874176 Accuracy: 0.8811  test :  0.842  Prule Train :  0.9477893096691126  Prule test :  0.9583642127799737
95 -1910.4553272957673 1281.061528103913 1280.106300440265 Accuracy: 0.8829  test :  0.842  Prule Train :  0.9449828536609207  Prule test :  0.950525448176386
100 3409.896335728826 1265.0923856804502 1266.7973338483146 Accuracy: 0.8834  test :  0.8413  Prule Train :  0.9457609375256066  Prule test :  0.9514272749773122
105 2675.8390742285483 1249.2508784895522 1250.5887980266666 Accuracy: 0.8849  test :  0.84  Prule Train :  0.9477117645419547  Prule test :  0.9532360720780294
110 1580.218988001547 1233.726012702354 1234.5161221963544 Accuracy: 0.8854  test :  0.8407  Prule Train :  0.9450533865207992  Prule test :  0.9541430521656393
115 -2640.948239989064 1217.4031443506688 1216.0826702306742 Accuracy: 0.886  test :  0.84  Prule Train :  0.9458337774262665  Prule test :  0.951216232987217
120 3699.5588976747044 1202.2321794957718 1204.0819589446091 Accuracy: 0.8871  test :  0.8393  Prule Train :  0.9422319481377514  Prule test :  0.9521221532091098
125 2619.583989263145 1188.3861038045825 1189.6958957992138 Accuracy: 0.888  test :  0.8393  Prule Train :  0.9399585281480227  Prule test :  0.9521221532091098
130 2119.0152555266886 1174.7860119295226 1175.845519557286 Accuracy: 0.8891  test :  0.8393  Prule Train :  0.9415147508767445  Prule test :  0.9521221532091098
135 -3089.7619288840315 1161.1381762762708 1159.5932953118286 Accuracy: 0.8903  test :  0.8413  Prule Train :  0.9413500555145354  Prule test :  0.95485029691458
140 3220.073201733926 1147.617772991987 1149.227809592854 Accuracy: 0.8906  test :  0.8413  Prule Train :  0.9417403333153292  Prule test :  0.95485029691458
145 2687.3608386475007 1134.874502399287 1136.2181828186108 Accuracy: 0.8909  test :  0.8413  Prule Train :  0.9404045314241019  Prule test :  0.95485029691458
150 2121.6278529017122 1122.4118713852324 1123.4726853116833 Accuracy: 0.8926  test :  0.8413  Prule Train :  0.9358373083603202  Prule test :  0.95485029691458
155 974.8427140713607 1110.1648538408444 1110.6522751978803 Accuracy: 0.8931  test :  0.842  Prule Train :  0.9348883183838652  Prule test :  0.9557631557070413
160 -2528.035255656406 1097.9870531691731 1096.7230355413446 Accuracy: 0.8943  test :  0.842  Prule Train :  0.9364432261899089  Prule test :  0.9557631557070413
165 -2849.5520091225176 1086.1468440339881 1084.7220680294272 Accuracy: 0.896  test :  0.8427  Prule Train :  0.9335887162788549  Prule test :  0.95667776159767
170 3656.7190380210704 1074.9018205047296 1076.7301800237399 Accuracy: 0.8977  test :  0.8433  Prule Train :  0.9324587940694449  Prule test :  0.9594321121588918
175 2207.3617339721004 1063.9217001791567 1065.0253810461427 Accuracy: 0.8989  test :  0.8427  Prule Train :  0.9305476960998529  Prule test :  0.9603537568391597
180 2759.383443338413 1053.0940615455293 1054.4737532671984 Accuracy: 0.8997  test :  0.8433  Prule Train :  0.9299792504985825  Prule test :  0.9573988222027316
185 -1766.4796012432337 1042.1727081494364 1041.2894683488148 Accuracy: 0.9017  test :  0.8413  Prule Train :  0.9292283036292699  Prule test :  0.9583193979933111
190 2681.7874898252658 1031.780927114614 1033.1218208595267 Accuracy: 0.9026  test :  0.8413  Prule Train :  0.9303966543882338  Prule test :  0.9562811231535339
195 -1767.5742339563967 1021.8717759488745 1020.9879888318962 Accuracy: 0.904  test :  0.8413  Prule Train :  0.9306064077282472  Prule test :  0.9581254454739843
Resultado | acc=0.8407 | bal_acc=0.6642 | f1=0.9056 | EOdds=0.0345 | EOp=0.0190 | p-rule=95.52 | score=0.6619 | tempo=0.12 min

FAGTB african_american_0:  23%|██▎       | 14/60 [01:25<04:24,  5.76s/modelo]

----------------------------------------------------------------------------------------------------
Treino 15/120 | config=african_american_0 | lambda=0.0005 | n_estimators=100 | learning_rate=0.03 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1830.219953143357 1830.692601503919 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1700.5092305485573 1787.2311180190854 1788.0813726343595 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 583.4443379476976 1747.1979915416568 1747.4897137106304 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 381.1186490351347 1707.953178473267 1708.1437377977845 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2707.648959094704 1668.9846611997996 1670.3384856793468 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1507.7182942996692 1631.9447356267478 1632.6985947738976 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 829.9823286374685 1597.0571591028968 1597.4721502672155 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 41.28864000857054 1563.8631741360332 1563.8838184560375 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2869.096617048219 1533.3048465684644 1534.7393948769886 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 1619.3726104564298 1503.887103073002 1504.6967893782303 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 982.6302184169266 1476.0511702458607 1476.5424853550692 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -592.3979194873451 1449.9008703057093 1449.604671345966 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 2964.493473975853 1425.2008586048971 1426.683105341885 Accuracy: 0.7811  test :  0.782  Prule Train :  1.0  Prule test :  0.9991166077738517
65 2191.6301147347863 1401.4953608528353 1402.591175910203 Accuracy: 0.7834  test :  0.782  Prule Train :  0.9982498640341629  Prule test :  0.9991166077738517
70 1088.2805837928213 1378.569709196214 1379.1138494881106 Accuracy: 0.8654  test :  0.8407  Prule Train :  0.9503137527262979  Prule test :  0.9607345903717943
75 -1274.1456193131648 1357.4319972494848 1356.7949244398283 Accuracy: 0.8686  test :  0.8427  Prule Train :  0.9494773715089849  Prule test :  0.9596463549563579
80 3312.9245154378596 1337.1854039683512 1338.8418662260704 Accuracy: 0.8723  test :  0.844  Prule Train :  0.9511061755657104  Prule test :  0.9614587182329515
85 2021.9924025404919 1317.4233241912311 1318.4343203925014 Accuracy: 0.8763  test :  0.8427  Prule Train :  0.951431862864811  Prule test :  0.9632779400271483
90 1487.475380189845 1298.425004069905 1299.16874176 Accuracy: 0.8811  test :  0.842  Prule Train :  0.9477893096691126  Prule test :  0.9583642127799737
95 -1910.4553272957673 1281.061528103913 1280.106300440265 Accuracy: 0.8829  test :  0.842  Prule Train :  0.9449828536609207  Prule test :  0.950525448176386
Resultado | acc=0.8413 | bal_acc=0.6537 | f1=0.9067 | EOdds=0.0629 | EOp=0.0168 | p-rule=95.14 | score=0.6500 | tempo=0.06 min

FAGTB african_american_0:  25%|██▌       | 15/60 [01:29<03:51,  5.15s/modelo]

----------------------------------------------------------------------------------------------------
Treino 16/120 | config=african_american_0 | lambda=0.0005 | n_estimators=200 | learning_rate=0.03 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1830.219953143357 1830.692601503919 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1700.5092305485573 1787.2311180190854 1788.0813726343595 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 583.4443379476976 1747.1979915416568 1747.4897137106304 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 381.1186490351347 1707.953178473267 1708.1437377977845 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2707.648959094704 1668.9846611997996 1670.3384856793468 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1507.7182942996692 1631.9447356267478 1632.6985947738976 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 829.9823286374685 1597.0571591028968 1597.4721502672155 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 41.28864000857054 1563.8631741360332 1563.8838184560375 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2869.096617048219 1533.3048465684644 1534.7393948769886 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 1619.3726104564298 1503.887103073002 1504.6967893782303 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 982.6302184169266 1476.0511702458607 1476.5424853550692 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -592.3979194873451 1449.9008703057093 1449.604671345966 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 2964.493473975853 1425.2008586048971 1426.683105341885 Accuracy: 0.7811  test :  0.782  Prule Train :  1.0  Prule test :  0.9991166077738517
65 2191.6301147347863 1401.4953608528353 1402.591175910203 Accuracy: 0.7834  test :  0.782  Prule Train :  0.9982498640341629  Prule test :  0.9991166077738517
70 1088.2805837928213 1378.569709196214 1379.1138494881106 Accuracy: 0.8654  test :  0.8407  Prule Train :  0.9503137527262979  Prule test :  0.9607345903717943
75 -1274.1456193131648 1357.4319972494848 1356.7949244398283 Accuracy: 0.8686  test :  0.8427  Prule Train :  0.9494773715089849  Prule test :  0.9596463549563579
80 3312.9245154378596 1337.1854039683512 1338.8418662260704 Accuracy: 0.8723  test :  0.844  Prule Train :  0.9511061755657104  Prule test :  0.9614587182329515
85 2021.9924025404919 1317.4233241912311 1318.4343203925014 Accuracy: 0.8763  test :  0.8427  Prule Train :  0.951431862864811  Prule test :  0.9632779400271483
90 1487.475380189845 1298.425004069905 1299.16874176 Accuracy: 0.8811  test :  0.842  Prule Train :  0.9477893096691126  Prule test :  0.9583642127799737
95 -1910.4553272957673 1281.061528103913 1280.106300440265 Accuracy: 0.8829  test :  0.842  Prule Train :  0.9449828536609207  Prule test :  0.950525448176386
100 3409.896335728826 1265.0923856804502 1266.7973338483146 Accuracy: 0.8834  test :  0.8413  Prule Train :  0.9457609375256066  Prule test :  0.9514272749773122
105 2675.8390742285483 1249.2508784895522 1250.5887980266666 Accuracy: 0.8849  test :  0.84  Prule Train :  0.9477117645419547  Prule test :  0.9532360720780294
110 1580.218988001547 1233.726012702354 1234.5161221963544 Accuracy: 0.8854  test :  0.8407  Prule Train :  0.9450533865207992  Prule test :  0.9541430521656393
115 -2640.948239989064 1217.4031443506688 1216.0826702306742 Accuracy: 0.886  test :  0.84  Prule Train :  0.9458337774262665  Prule test :  0.951216232987217
120 3699.5588976747044 1202.2321794957718 1204.0819589446091 Accuracy: 0.8871  test :  0.8393  Prule Train :  0.9422319481377514  Prule test :  0.9521221532091098
125 2619.583989263145 1188.3861038045825 1189.6958957992138 Accuracy: 0.888  test :  0.8393  Prule Train :  0.9399585281480227  Prule test :  0.9521221532091098
130 2119.0152555266886 1174.7860119295226 1175.845519557286 Accuracy: 0.8891  test :  0.8393  Prule Train :  0.9415147508767445  Prule test :  0.9521221532091098
135 -3089.7619288840315 1161.1381762762708 1159.5932953118286 Accuracy: 0.8903  test :  0.8413  Prule Train :  0.9413500555145354  Prule test :  0.95485029691458
140 3220.073201733926 1147.617772991987 1149.227809592854 Accuracy: 0.8906  test :  0.8413  Prule Train :  0.9417403333153292  Prule test :  0.95485029691458
145 2687.3608386475007 1134.874502399287 1136.2181828186108 Accuracy: 0.8909  test :  0.8413  Prule Train :  0.9404045314241019  Prule test :  0.95485029691458
150 2121.6278529017122 1122.4118713852324 1123.4726853116833 Accuracy: 0.8926  test :  0.8413  Prule Train :  0.9358373083603202  Prule test :  0.95485029691458
155 974.8427140713607 1110.1648538408444 1110.6522751978803 Accuracy: 0.8931  test :  0.842  Prule Train :  0.9348883183838652  Prule test :  0.9557631557070413
160 -2528.035255656406 1097.9870531691731 1096.7230355413446 Accuracy: 0.8943  test :  0.842  Prule Train :  0.9364432261899089  Prule test :  0.9557631557070413
165 -2849.5520091225176 1086.1468440339881 1084.7220680294272 Accuracy: 0.896  test :  0.8427  Prule Train :  0.9335887162788549  Prule test :  0.95667776159767
170 3656.7190380210704 1074.9018205047296 1076.7301800237399 Accuracy: 0.8977  test :  0.8433  Prule Train :  0.9324587940694449  Prule test :  0.9594321121588918
175 2207.3617339721004 1063.9217001791567 1065.0253810461427 Accuracy: 0.8989  test :  0.8427  Prule Train :  0.9305476960998529  Prule test :  0.9603537568391597
180 2759.383443338413 1053.0940615455293 1054.4737532671984 Accuracy: 0.8997  test :  0.8433  Prule Train :  0.9299792504985825  Prule test :  0.9573988222027316
185 -1766.4796012432337 1042.1727081494364 1041.2894683488148 Accuracy: 0.9017  test :  0.8413  Prule Train :  0.9292283036292699  Prule test :  0.9583193979933111
190 2681.7874898252658 1031.780927114614 1033.1218208595267 Accuracy: 0.9026  test :  0.8413  Prule Train :  0.9303966543882338  Prule test :  0.9562811231535339
195 -1767.5742339563967 1021.8717759488745 1020.9879888318962 Accuracy: 0.904  test :  0.8413  Prule Train :  0.9306064077282472  Prule test :  0.9581254454739843
Resultado | acc=0.8407 | bal_acc=0.6642 | f1=0.9056 | EOdds=0.0345 | EOp=0.0190 | p-rule=95.52 | score=0.6619 | tempo=0.12 min

FAGTB african_american_0:  27%|██▋       | 16/60 [01:36<04:11,  5.72s/modelo]

----------------------------------------------------------------------------------------------------
Treino 17/120 | config=african_american_0 | lambda=0.0005 | n_estimators=100 | learning_rate=0.05 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1824.3242767593665 1824.7969251199281 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1708.1623713644944 1754.8444739561673 1755.6985551418497 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 587.2939484889861 1690.4530099380042 1690.7466569122485 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 318.60439106359723 1627.4395800152097 1627.5988822107415 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2758.2881149783816 1571.0154679450459 1572.3946120025353 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1521.124564510984 1519.5614047484678 1520.3219670307235 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 879.0631201500062 1472.522729379346 1472.9622609394212 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -303.3723210595614 1430.0788260090733 1429.9271398485437 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2884.672363695834 1391.0420593060687 1392.4843954879166 Accuracy: 0.8506  test :  0.8313  Prule Train :  0.9622183680497439  Prule test :  0.9616338630313785
45 2010.392508349827 1354.495440143264 1355.500636397439 Accuracy: 0.8691  test :  0.8427  Prule Train :  0.9502477385446921  Prule test :  0.9596463549563579
50 1222.7032129647846 1320.6779717987529 1321.2893234052353 Accuracy: 0.876  test :  0.8427  Prule Train :  0.9527496355280587  Prule test :  0.9632779400271483
55 -810.1627352176904 1290.1258810531872 1289.7207996855782 Accuracy: 0.8826  test :  0.8433  Prule Train :  0.9463082153070091  Prule test :  0.9583642127799737
60 2644.5262542140545 1262.016165979833 1263.33842910694 Accuracy: 0.884  test :  0.8407  Prule Train :  0.9465403037699622  Prule test :  0.950525448176386
65 2208.7495135340505 1235.8101366203023 1236.9145113770694 Accuracy: 0.8857  test :  0.84  Prule Train :  0.9471640640330545  Prule test :  0.9532360720780294
70 1555.6866236498724 1209.7851352730086 1210.5629785848332 Accuracy: 0.8866  test :  0.84  Prule Train :  0.944893620307632  Prule test :  0.951216232987217
75 -1145.2862454431056 1185.6554692144573 1185.0828260917356 Accuracy: 0.8874  test :  0.84  Prule Train :  0.9426213001824364  Prule test :  0.951216232987217
80 3301.4597901236857 1163.457633445584 1165.1083633406456 Accuracy: 0.8891  test :  0.8407  Prule Train :  0.9415147508767445  Prule test :  0.9521221532091098
85 2455.1714128558524 1140.9871158566505 1142.2147015630785 Accuracy: 0.8911  test :  0.842  Prule Train :  0.9390687295328743  Prule test :  0.9539391802190508
90 1835.4749841689895 1119.9013524640495 1120.8190899561341 Accuracy: 0.8923  test :  0.8427  Prule Train :  0.9354491551838955  Prule test :  0.95485029691458
95 -2276.598153900526 1100.128657656382 1098.9903585794318 Accuracy: 0.8943  test :  0.8427  Prule Train :  0.9364432261899089  Prule test :  0.95667776159767
Resultado | acc=0.8427 | bal_acc=0.6633 | f1=0.9070 | EOdds=0.0284 | EOp=0.0198 | p-rule=95.65 | score=0.6613 | tempo=0.06 min

FAGTB african_american_0:  28%|██▊       | 17/60 [01:39<03:39,  5.09s/modelo]

----------------------------------------------------------------------------------------------------
Treino 18/120 | config=african_american_0 | lambda=0.0005 | n_estimators=200 | learning_rate=0.05 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1824.3242767593665 1824.7969251199281 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1708.1623713644944 1754.8444739561673 1755.6985551418497 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 587.2939484889861 1690.4530099380042 1690.7466569122485 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 318.60439106359723 1627.4395800152097 1627.5988822107415 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2758.2881149783816 1571.0154679450459 1572.3946120025353 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1521.124564510984 1519.5614047484678 1520.3219670307235 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 879.0631201500062 1472.522729379346 1472.9622609394212 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -303.3723210595614 1430.0788260090733 1429.9271398485437 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2884.672363695834 1391.0420593060687 1392.4843954879166 Accuracy: 0.8506  test :  0.8313  Prule Train :  0.9622183680497439  Prule test :  0.9616338630313785
45 2010.392508349827 1354.495440143264 1355.500636397439 Accuracy: 0.8691  test :  0.8427  Prule Train :  0.9502477385446921  Prule test :  0.9596463549563579
50 1222.7032129647846 1320.6779717987529 1321.2893234052353 Accuracy: 0.876  test :  0.8427  Prule Train :  0.9527496355280587  Prule test :  0.9632779400271483
55 -810.1627352176904 1290.1258810531872 1289.7207996855782 Accuracy: 0.8826  test :  0.8433  Prule Train :  0.9463082153070091  Prule test :  0.9583642127799737
60 2644.5262542140545 1262.016165979833 1263.33842910694 Accuracy: 0.884  test :  0.8407  Prule Train :  0.9465403037699622  Prule test :  0.950525448176386
65 2208.7495135340505 1235.8101366203023 1236.9145113770694 Accuracy: 0.8857  test :  0.84  Prule Train :  0.9471640640330545  Prule test :  0.9532360720780294
70 1555.6866236498724 1209.7851352730086 1210.5629785848332 Accuracy: 0.8866  test :  0.84  Prule Train :  0.944893620307632  Prule test :  0.951216232987217
75 -1145.2862454431056 1185.6554692144573 1185.0828260917356 Accuracy: 0.8874  test :  0.84  Prule Train :  0.9426213001824364  Prule test :  0.951216232987217
80 3301.4597901236857 1163.457633445584 1165.1083633406456 Accuracy: 0.8891  test :  0.8407  Prule Train :  0.9415147508767445  Prule test :  0.9521221532091098
85 2455.1714128558524 1140.9871158566505 1142.2147015630785 Accuracy: 0.8911  test :  0.842  Prule Train :  0.9390687295328743  Prule test :  0.9539391802190508
90 1835.4749841689895 1119.9013524640495 1120.8190899561341 Accuracy: 0.8923  test :  0.8427  Prule Train :  0.9354491551838955  Prule test :  0.95485029691458
95 -2276.598153900526 1100.128657656382 1098.9903585794318 Accuracy: 0.8943  test :  0.8427  Prule Train :  0.9364432261899089  Prule test :  0.95667776159767
100 2781.5718194210413 1081.1055383989526 1082.4963243086631 Accuracy: 0.896  test :  0.844  Prule Train :  0.9353194713300499  Prule test :  0.9603537568391597
105 3377.7477049442623 1063.1813470829586 1064.8702209354308 Accuracy: 0.8986  test :  0.8447  Prule Train :  0.9301594826263027  Prule test :  0.9573988222027316
110 2037.9328089538453 1044.9721930984729 1045.9911595029498 Accuracy: 0.9011  test :  0.844  Prule Train :  0.9301876031514503  Prule test :  0.9583193979933111
115 868.8151540769011 1027.8017630400218 1028.23617061706 Accuracy: 0.9029  test :  0.8393  Prule Train :  0.9307867578072644  Prule test :  0.9570048309178745
120 -1954.7104374448477 1010.7178611859537 1009.7405059672312 Accuracy: 0.9051  test :  0.8393  Prule Train :  0.9321717675393967  Prule test :  0.9570048309178745
125 -2155.4947302030364 995.6011790322173 994.5234316671157 Accuracy: 0.9063  test :  0.8387  Prule Train :  0.9302443412817358  Prule test :  0.954032766225583
130 2904.9399472390423 981.3822584968971 982.8347284705166 Accuracy: 0.9066  test :  0.8413  Prule Train :  0.9306360231096439  Prule test :  0.9558798770992045
135 2518.7737641948056 967.7790496721943 969.0384365542917 Accuracy: 0.91  test :  0.8387  Prule Train :  0.9300907406595446  Prule test :  0.9556775010552976
140 -2142.4096192613024 952.973808716755 951.9026039071243 Accuracy: 0.9114  test :  0.8387  Prule Train :  0.9320604372725465  Prule test :  0.9556775010552976
145 3151.6584111560137 939.6905103810611 941.266339586639 Accuracy: 0.9131  test :  0.8387  Prule Train :  0.9326709415275222  Prule test :  0.9556775010552976
150 2080.008502237871 926.1520314193267 927.1920356704456 Accuracy: 0.9146  test :  0.8387  Prule Train :  0.9346545037170745  Prule test :  0.9556775010552976
155 1682.292350780495 912.6742190970051 913.5153652723955 Accuracy: 0.9163  test :  0.84  Prule Train :  0.9335018448724162  Prule test :  0.9536168504668949
160 2530.0218743610985 899.8048030387381 901.0698139759186 Accuracy: 0.9174  test :  0.8407  Prule Train :  0.9333220459701026  Prule test :  0.9506274559513246
165 3080.916819268088 886.9240872038121 888.464545613446 Accuracy: 0.9183  test :  0.8413  Prule Train :  0.9327433482460631  Prule test :  0.9515521908306546
170 1450.6168042652473 874.6106874420376 875.3359958441702 Accuracy: 0.9191  test :  0.8413  Prule Train :  0.9339396843062334  Prule test :  0.9515521908306546
175 -2178.4640187725995 863.1399467058184 862.0507146964321 Accuracy: 0.9203  test :  0.8433  Prule Train :  0.9355395809817044  Prule test :  0.9564052038308332
180 2889.675497564973 852.7083132584296 854.1531510072122 Accuracy: 0.9209  test :  0.8427  Prule Train :  0.9363415866233518  Prule test :  0.9573382820784729
185 2334.673705907133 840.9672946734119 842.1346315263654 Accuracy: 0.9226  test :  0.8427  Prule Train :  0.9333987378143168  Prule test :  0.9573382820784729
190 692.159857494285 831.9750139421574 832.3210938709046 Accuracy: 0.924  test :  0.8433  Prule Train :  0.9336187037599818  Prule test :  0.9564052038308332
195 -1995.781922369284 822.111753892674 821.1138629314894 Accuracy: 0.9263  test :  0.8433  Prule Train :  0.9332556881993261  Prule test :  0.9564052038308332
Resultado | acc=0.8433 | bal_acc=0.6758 | f1=0.9066 | EOdds=0.0251 | EOp=0.0182 | p-rule=95.64 | score=0.6740 | tempo=0.12 min

FAGTB african_american_0:  30%|███       | 18/60 [01:47<03:59,  5.70s/modelo]

----------------------------------------------------------------------------------------------------
Treino 19/120 | config=african_american_0 | lambda=0.0005 | n_estimators=100 | learning_rate=0.05 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1824.3242767593665 1824.7969251199281 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1708.1623713644944 1754.8444739561673 1755.6985551418497 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 587.2939484889861 1690.4530099380042 1690.7466569122485 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 318.60439106359723 1627.4395800152097 1627.5988822107415 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2758.2881149783816 1571.0154679450459 1572.3946120025353 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1521.124564510984 1519.5614047484678 1520.3219670307235 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 879.0631201500062 1472.522729379346 1472.9622609394212 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -303.3723210595614 1430.0788260090733 1429.9271398485437 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2884.672363695834 1391.0420593060687 1392.4843954879166 Accuracy: 0.8506  test :  0.8313  Prule Train :  0.9622183680497439  Prule test :  0.9616338630313785
45 2010.392508349827 1354.495440143264 1355.500636397439 Accuracy: 0.8691  test :  0.8427  Prule Train :  0.9502477385446921  Prule test :  0.9596463549563579
50 1222.7032129647846 1320.6779717987529 1321.2893234052353 Accuracy: 0.876  test :  0.8427  Prule Train :  0.9527496355280587  Prule test :  0.9632779400271483
55 -810.1627352176904 1290.1258810531872 1289.7207996855782 Accuracy: 0.8826  test :  0.8433  Prule Train :  0.9463082153070091  Prule test :  0.9583642127799737
60 2644.5262542140545 1262.016165979833 1263.33842910694 Accuracy: 0.884  test :  0.8407  Prule Train :  0.9465403037699622  Prule test :  0.950525448176386
65 2208.7495135340505 1235.8101366203023 1236.9145113770694 Accuracy: 0.8857  test :  0.84  Prule Train :  0.9471640640330545  Prule test :  0.9532360720780294
70 1555.6866236498724 1209.7851352730086 1210.5629785848332 Accuracy: 0.8866  test :  0.84  Prule Train :  0.944893620307632  Prule test :  0.951216232987217
75 -1145.2862454431056 1185.6554692144573 1185.0828260917356 Accuracy: 0.8874  test :  0.84  Prule Train :  0.9426213001824364  Prule test :  0.951216232987217
80 3301.4597901236857 1163.457633445584 1165.1083633406456 Accuracy: 0.8891  test :  0.8407  Prule Train :  0.9415147508767445  Prule test :  0.9521221532091098
85 2455.1714128558524 1140.9871158566505 1142.2147015630785 Accuracy: 0.8911  test :  0.842  Prule Train :  0.9390687295328743  Prule test :  0.9539391802190508
90 1835.4749841689895 1119.9013524640495 1120.8190899561341 Accuracy: 0.8923  test :  0.8427  Prule Train :  0.9354491551838955  Prule test :  0.95485029691458
95 -2276.598153900526 1100.128657656382 1098.9903585794318 Accuracy: 0.8943  test :  0.8427  Prule Train :  0.9364432261899089  Prule test :  0.95667776159767
Resultado | acc=0.8427 | bal_acc=0.6633 | f1=0.9070 | EOdds=0.0284 | EOp=0.0198 | p-rule=95.65 | score=0.6613 | tempo=0.06 min

FAGTB african_american_0:  32%|███▏      | 19/60 [01:50<03:29,  5.10s/modelo]

----------------------------------------------------------------------------------------------------
Treino 20/120 | config=african_american_0 | lambda=0.0005 | n_estimators=200 | learning_rate=0.05 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1824.3242767593665 1824.7969251199281 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1708.1623713644944 1754.8444739561673 1755.6985551418497 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 587.2939484889861 1690.4530099380042 1690.7466569122485 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 318.60439106359723 1627.4395800152097 1627.5988822107415 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2758.2881149783816 1571.0154679450459 1572.3946120025353 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1521.124564510984 1519.5614047484678 1520.3219670307235 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 879.0631201500062 1472.522729379346 1472.9622609394212 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -303.3723210595614 1430.0788260090733 1429.9271398485437 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2884.672363695834 1391.0420593060687 1392.4843954879166 Accuracy: 0.8506  test :  0.8313  Prule Train :  0.9622183680497439  Prule test :  0.9616338630313785
45 2010.392508349827 1354.495440143264 1355.500636397439 Accuracy: 0.8691  test :  0.8427  Prule Train :  0.9502477385446921  Prule test :  0.9596463549563579
50 1222.7032129647846 1320.6779717987529 1321.2893234052353 Accuracy: 0.876  test :  0.8427  Prule Train :  0.9527496355280587  Prule test :  0.9632779400271483
55 -810.1627352176904 1290.1258810531872 1289.7207996855782 Accuracy: 0.8826  test :  0.8433  Prule Train :  0.9463082153070091  Prule test :  0.9583642127799737
60 2644.5262542140545 1262.016165979833 1263.33842910694 Accuracy: 0.884  test :  0.8407  Prule Train :  0.9465403037699622  Prule test :  0.950525448176386
65 2208.7495135340505 1235.8101366203023 1236.9145113770694 Accuracy: 0.8857  test :  0.84  Prule Train :  0.9471640640330545  Prule test :  0.9532360720780294
70 1555.6866236498724 1209.7851352730086 1210.5629785848332 Accuracy: 0.8866  test :  0.84  Prule Train :  0.944893620307632  Prule test :  0.951216232987217
75 -1145.2862454431056 1185.6554692144573 1185.0828260917356 Accuracy: 0.8874  test :  0.84  Prule Train :  0.9426213001824364  Prule test :  0.951216232987217
80 3301.4597901236857 1163.457633445584 1165.1083633406456 Accuracy: 0.8891  test :  0.8407  Prule Train :  0.9415147508767445  Prule test :  0.9521221532091098
85 2455.1714128558524 1140.9871158566505 1142.2147015630785 Accuracy: 0.8911  test :  0.842  Prule Train :  0.9390687295328743  Prule test :  0.9539391802190508
90 1835.4749841689895 1119.9013524640495 1120.8190899561341 Accuracy: 0.8923  test :  0.8427  Prule Train :  0.9354491551838955  Prule test :  0.95485029691458
95 -2276.598153900526 1100.128657656382 1098.9903585794318 Accuracy: 0.8943  test :  0.8427  Prule Train :  0.9364432261899089  Prule test :  0.95667776159767
100 2781.5718194210413 1081.1055383989526 1082.4963243086631 Accuracy: 0.896  test :  0.844  Prule Train :  0.9353194713300499  Prule test :  0.9603537568391597
105 3377.7477049442623 1063.1813470829586 1064.8702209354308 Accuracy: 0.8986  test :  0.8447  Prule Train :  0.9301594826263027  Prule test :  0.9573988222027316
110 2037.9328089538453 1044.9721930984729 1045.9911595029498 Accuracy: 0.9011  test :  0.844  Prule Train :  0.9301876031514503  Prule test :  0.9583193979933111
115 868.8151540769011 1027.8017630400218 1028.23617061706 Accuracy: 0.9029  test :  0.8393  Prule Train :  0.9307867578072644  Prule test :  0.9570048309178745
120 -1954.7104374448477 1010.7178611859537 1009.7405059672312 Accuracy: 0.9051  test :  0.8393  Prule Train :  0.9321717675393967  Prule test :  0.9570048309178745
125 -2155.4947302030364 995.6011790322173 994.5234316671157 Accuracy: 0.9063  test :  0.8387  Prule Train :  0.9302443412817358  Prule test :  0.954032766225583
130 2904.9399472390423 981.3822584968971 982.8347284705166 Accuracy: 0.9066  test :  0.8413  Prule Train :  0.9306360231096439  Prule test :  0.9558798770992045
135 2518.7737641948056 967.7790496721943 969.0384365542917 Accuracy: 0.91  test :  0.8387  Prule Train :  0.9300907406595446  Prule test :  0.9556775010552976
140 -2142.4096192613024 952.973808716755 951.9026039071243 Accuracy: 0.9114  test :  0.8387  Prule Train :  0.9320604372725465  Prule test :  0.9556775010552976
145 3151.6584111560137 939.6905103810611 941.266339586639 Accuracy: 0.9131  test :  0.8387  Prule Train :  0.9326709415275222  Prule test :  0.9556775010552976
150 2080.008502237871 926.1520314193267 927.1920356704456 Accuracy: 0.9146  test :  0.8387  Prule Train :  0.9346545037170745  Prule test :  0.9556775010552976
155 1682.292350780495 912.6742190970051 913.5153652723955 Accuracy: 0.9163  test :  0.84  Prule Train :  0.9335018448724162  Prule test :  0.9536168504668949
160 2530.0218743610985 899.8048030387381 901.0698139759186 Accuracy: 0.9174  test :  0.8407  Prule Train :  0.9333220459701026  Prule test :  0.9506274559513246
165 3080.916819268088 886.9240872038121 888.464545613446 Accuracy: 0.9183  test :  0.8413  Prule Train :  0.9327433482460631  Prule test :  0.9515521908306546
170 1450.6168042652473 874.6106874420376 875.3359958441702 Accuracy: 0.9191  test :  0.8413  Prule Train :  0.9339396843062334  Prule test :  0.9515521908306546
175 -2178.4640187725995 863.1399467058184 862.0507146964321 Accuracy: 0.9203  test :  0.8433  Prule Train :  0.9355395809817044  Prule test :  0.9564052038308332
180 2889.675497564973 852.7083132584296 854.1531510072122 Accuracy: 0.9209  test :  0.8427  Prule Train :  0.9363415866233518  Prule test :  0.9573382820784729
185 2334.673705907133 840.9672946734119 842.1346315263654 Accuracy: 0.9226  test :  0.8427  Prule Train :  0.9333987378143168  Prule test :  0.9573382820784729
190 692.159857494285 831.9750139421574 832.3210938709046 Accuracy: 0.924  test :  0.8433  Prule Train :  0.9336187037599818  Prule test :  0.9564052038308332
195 -1995.781922369284 822.111753892674 821.1138629314894 Accuracy: 0.9263  test :  0.8433  Prule Train :  0.9332556881993261  Prule test :  0.9564052038308332
Resultado | acc=0.8433 | bal_acc=0.6758 | f1=0.9066 | EOdds=0.0251 | EOp=0.0182 | p-rule=95.64 | score=0.6740 | tempo=0.11 min

FAGTB african_american_0:  33%|███▎      | 20/60 [01:57<03:46,  5.67s/modelo]

----------------------------------------------------------------------------------------------------
Treino 21/120 | config=african_american_0 | lambda=0.0005 | n_estimators=100 | learning_rate=0.1 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1809.675663132863 1810.1483114934247 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1728.1714591635136 1675.1153868316605 1675.9794725612423 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 589.8709055478573 1557.3927629659524 1557.6876984187263 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 181.0132936104402 1460.9848770640817 1461.075383710887 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2805.168919611787 1380.424963489602 1381.827547949408 Accuracy: 0.8654  test :  0.8413  Prule Train :  0.9520001989325901  Prule test :  0.9616392368787358
25 1507.9218128215703 1311.0646042591559 1311.8185651655667 Accuracy: 0.8797  test :  0.8427  Prule Train :  0.9458463221544158  Prule test :  0.957457529513389
30 958.7967962042034 1253.8103978012196 1254.2897961993217 Accuracy: 0.8846  test :  0.8407  Prule Train :  0.945602375551549  Prule test :  0.9541430521656393
35 -757.7486401471292 1202.227258630318 1201.848384310244 Accuracy: 0.8866  test :  0.84  Prule Train :  0.9431732042126905  Prule test :  0.951216232987217
40 2830.7644047744557 1156.9707359962335 1158.3861181986208 Accuracy: 0.8906  test :  0.8407  Prule Train :  0.9400148072088412  Prule test :  0.9521221532091098
45 2132.1885383207127 1114.8285818994664 1115.8946761686268 Accuracy: 0.8934  test :  0.84  Prule Train :  0.9370037030113717  Prule test :  0.9491925465838509
50 1083.2028636910682 1075.7923166949472 1076.3339181267927 Accuracy: 0.8977  test :  0.84  Prule Train :  0.9324587940694449  Prule test :  0.9489742950874133
55 -1601.2734936505083 1039.2061019029995 1038.4054651561742 Accuracy: 0.9026  test :  0.842  Prule Train :  0.9303966543882338  Prule test :  0.9496644295302014
60 3089.782589456112 1001.9280492343214 1003.4729405290494 Accuracy: 0.9071  test :  0.8407  Prule Train :  0.9279227985524731  Prule test :  0.955159112825458
65 1968.501670285226 974.6190094487981 975.6032602839407 Accuracy: 0.91  test :  0.8413  Prule Train :  0.9300907406595446  Prule test :  0.954032766225583
70 1605.5863665986467 945.5234783757373 946.3262715590366 Accuracy: 0.9146  test :  0.842  Prule Train :  0.9311214746772465  Prule test :  0.9549554284753173
75 2051.236546476302 915.8478813354627 916.8734996087007 Accuracy: 0.9163  test :  0.8407  Prule Train :  0.9317320595204088  Prule test :  0.9490055504162812
80 1612.2966065147248 888.4067264215321 889.2128747247896 Accuracy: 0.9206  test :  0.8413  Prule Train :  0.9288268199083479  Prule test :  0.9538254128749578
85 2942.3869527528514 863.2433597778718 864.7145532542482 Accuracy: 0.9229  test :  0.8427  Prule Train :  0.930233869920239  Prule test :  0.9556775010552976
90 2298.5701336895804 839.2530232194395 840.4023082862843 Accuracy: 0.9249  test :  0.8413  Prule Train :  0.9330357791669868  Prule test :  0.9536168504668949
95 961.0865879678556 819.9847236861563 820.4652669801401 Accuracy: 0.9271  test :  0.844  Prule Train :  0.9326709415275221  Prule test :  0.9494835104356292
Resultado | acc=0.8433 | bal_acc=0.6769 | f1=0.9066 | EOdds=0.0503 | EOp=0.0219 | p-rule=94.65 | score=0.6737 | tempo=0.06 min

FAGTB african_american_0:  35%|███▌      | 21/60 [02:01<03:17,  5.07s/modelo]

----------------------------------------------------------------------------------------------------
Treino 22/120 | config=african_american_0 | lambda=0.0005 | n_estimators=200 | learning_rate=0.1 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1809.675663132863 1810.1483114934247 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1728.1714591635136 1675.1153868316605 1675.9794725612423 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 589.8709055478573 1557.3927629659524 1557.6876984187263 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 181.0132936104402 1460.9848770640817 1461.075383710887 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2805.168919611787 1380.424963489602 1381.827547949408 Accuracy: 0.8654  test :  0.8413  Prule Train :  0.9520001989325901  Prule test :  0.9616392368787358
25 1507.9218128215703 1311.0646042591559 1311.8185651655667 Accuracy: 0.8797  test :  0.8427  Prule Train :  0.9458463221544158  Prule test :  0.957457529513389
30 958.7967962042034 1253.8103978012196 1254.2897961993217 Accuracy: 0.8846  test :  0.8407  Prule Train :  0.945602375551549  Prule test :  0.9541430521656393
35 -757.7486401471292 1202.227258630318 1201.848384310244 Accuracy: 0.8866  test :  0.84  Prule Train :  0.9431732042126905  Prule test :  0.951216232987217
40 2830.7644047744557 1156.9707359962335 1158.3861181986208 Accuracy: 0.8906  test :  0.8407  Prule Train :  0.9400148072088412  Prule test :  0.9521221532091098
45 2132.1885383207127 1114.8285818994664 1115.8946761686268 Accuracy: 0.8934  test :  0.84  Prule Train :  0.9370037030113717  Prule test :  0.9491925465838509
50 1083.2028636910682 1075.7923166949472 1076.3339181267927 Accuracy: 0.8977  test :  0.84  Prule Train :  0.9324587940694449  Prule test :  0.9489742950874133
55 -1601.2734936505083 1039.2061019029995 1038.4054651561742 Accuracy: 0.9026  test :  0.842  Prule Train :  0.9303966543882338  Prule test :  0.9496644295302014
60 3089.782589456112 1001.9280492343214 1003.4729405290494 Accuracy: 0.9071  test :  0.8407  Prule Train :  0.9279227985524731  Prule test :  0.955159112825458
65 1968.501670285226 974.6190094487981 975.6032602839407 Accuracy: 0.91  test :  0.8413  Prule Train :  0.9300907406595446  Prule test :  0.954032766225583
70 1605.5863665986467 945.5234783757373 946.3262715590366 Accuracy: 0.9146  test :  0.842  Prule Train :  0.9311214746772465  Prule test :  0.9549554284753173
75 2051.236546476302 915.8478813354627 916.8734996087007 Accuracy: 0.9163  test :  0.8407  Prule Train :  0.9317320595204088  Prule test :  0.9490055504162812
80 1612.2966065147248 888.4067264215321 889.2128747247896 Accuracy: 0.9206  test :  0.8413  Prule Train :  0.9288268199083479  Prule test :  0.9538254128749578
85 2942.3869527528514 863.2433597778718 864.7145532542482 Accuracy: 0.9229  test :  0.8427  Prule Train :  0.930233869920239  Prule test :  0.9556775010552976
90 2298.5701336895804 839.2530232194395 840.4023082862843 Accuracy: 0.9249  test :  0.8413  Prule Train :  0.9330357791669868  Prule test :  0.9536168504668949
95 961.0865879678556 819.9847236861563 820.4652669801401 Accuracy: 0.9271  test :  0.844  Prule Train :  0.9326709415275221  Prule test :  0.9494835104356292
100 -2078.4027028317737 801.4788682335422 800.4396668821264 Accuracy: 0.9303  test :  0.8433  Prule Train :  0.9335155193319684  Prule test :  0.9444126620900076
105 2879.5262924462627 783.351831029179 784.7915941754022 Accuracy: 0.9326  test :  0.8447  Prule Train :  0.9331495552819079  Prule test :  0.9423329798515376
110 1945.8011362960892 764.6737845097173 765.6466850778653 Accuracy: 0.9351  test :  0.8427  Prule Train :  0.9349984625937227  Prule test :  0.9411683454460451
115 1379.786765029061 747.8943501160256 748.58424349854 Accuracy: 0.9374  test :  0.844  Prule Train :  0.9346341473697302  Prule test :  0.9430119661031384
120 -1657.402653858695 731.9997617937827 731.1710604668533 Accuracy: 0.9397  test :  0.844  Prule Train :  0.928813557533294  Prule test :  0.9411683454460451
125 2411.778347596527 717.1963467218794 718.4022358956777 Accuracy: 0.942  test :  0.844  Prule Train :  0.9229776704830955  Prule test :  0.9430119661031384
130 2006.2093299202775 703.7297257679395 704.7328304328998 Accuracy: 0.9434  test :  0.8433  Prule Train :  0.9195493902796954  Prule test :  0.9399991483200614
135 216.37291221115188 689.4885740436539 689.5967604997595 Accuracy: 0.9449  test :  0.8427  Prule Train :  0.9179316290187465  Prule test :  0.9430119661031384
140 -1512.7744371580206 674.0791005127192 673.3227132941402 Accuracy: 0.9486  test :  0.842  Prule Train :  0.9158926550278282  Prule test :  0.9439364876385337
145 2519.343701053169 662.1390353556377 663.3987072061643 Accuracy: 0.9497  test :  0.8427  Prule Train :  0.9138581940603712  Prule test :  0.9388253616077143
150 1785.490963862072 649.3238622922594 650.2166077741904 Accuracy: 0.9514  test :  0.8427  Prule Train :  0.9144538336751639  Prule test :  0.9427692833347571
155 1091.9168494904402 635.720702526589 636.2666609513342 Accuracy: 0.9543  test :  0.8427  Prule Train :  0.9111732070596891  Prule test :  0.9425251659884344
160 -1472.991840227257 623.9067869236371 623.1702910035235 Accuracy: 0.956  test :  0.8427  Prule Train :  0.9044332524693819  Prule test :  0.9425251659884344
165 2349.0623635611164 613.1996995940694 614.37423077585 Accuracy: 0.9563  test :  0.8413  Prule Train :  0.9048345094580551  Prule test :  0.9425251659884344
170 1748.9308469214368 601.7818645676136 602.6563299910742 Accuracy: 0.9574  test :  0.8407  Prule Train :  0.904609076035902  Prule test :  0.9434546779864506
175 921.4826519034423 592.743432027394 593.2041733533456 Accuracy: 0.9586  test :  0.8413  Prule Train :  0.9062194170702338  Prule test :  0.9443860251512942
180 -1376.3126423358212 583.4303554406821 582.7421991195142 Accuracy: 0.9597  test :  0.8427  Prule Train :  0.9041564017075878  Prule test :  0.9462542467638585
185 2251.9068533716686 574.5135656630699 575.6395190897558 Accuracy: 0.9606  test :  0.8433  Prule Train :  0.9035261558947366  Prule test :  0.9453192129231826
190 1669.6223028152071 566.9351604831824 567.7699716345899 Accuracy: 0.9614  test :  0.8433  Prule Train :  0.9047362355678098  Prule test :  0.9453192129231826
195 886.5118341396094 559.4751739554824 559.9184298725522 Accuracy: 0.9629  test :  0.8427  Prule Train :  0.9049137806396481  Prule test :  0.9462542467638585
Resultado | acc=0.8427 | bal_acc=0.6874 | f1=0.9054 | EOdds=0.0366 | EOp=0.0240 | p-rule=94.63 | score=0.6849 | tempo=0.11 min

FAGTB african_american_0:  37%|███▋      | 22/60 [02:08<03:34,  5.65s/modelo]

----------------------------------------------------------------------------------------------------
Treino 23/120 | config=african_american_0 | lambda=0.0005 | n_estimators=100 | learning_rate=0.1 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1809.675663132863 1810.1483114934247 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1728.1714591635136 1675.1153868316605 1675.9794725612423 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 589.8709055478573 1557.3927629659524 1557.6876984187263 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 181.0132936104402 1460.9848770640817 1461.075383710887 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2805.168919611787 1380.424963489602 1381.827547949408 Accuracy: 0.8654  test :  0.8413  Prule Train :  0.9520001989325901  Prule test :  0.9616392368787358
25 1507.9218128215703 1311.0646042591559 1311.8185651655667 Accuracy: 0.8797  test :  0.8427  Prule Train :  0.9458463221544158  Prule test :  0.957457529513389
30 958.7967962042034 1253.8103978012196 1254.2897961993217 Accuracy: 0.8846  test :  0.8407  Prule Train :  0.945602375551549  Prule test :  0.9541430521656393
35 -757.7486401471292 1202.227258630318 1201.848384310244 Accuracy: 0.8866  test :  0.84  Prule Train :  0.9431732042126905  Prule test :  0.951216232987217
40 2830.7644047744557 1156.9707359962335 1158.3861181986208 Accuracy: 0.8906  test :  0.8407  Prule Train :  0.9400148072088412  Prule test :  0.9521221532091098
45 2132.1885383207127 1114.8285818994664 1115.8946761686268 Accuracy: 0.8934  test :  0.84  Prule Train :  0.9370037030113717  Prule test :  0.9491925465838509
50 1083.2028636910682 1075.7923166949472 1076.3339181267927 Accuracy: 0.8977  test :  0.84  Prule Train :  0.9324587940694449  Prule test :  0.9489742950874133
55 -1601.2734936505083 1039.2061019029995 1038.4054651561742 Accuracy: 0.9026  test :  0.842  Prule Train :  0.9303966543882338  Prule test :  0.9496644295302014
60 3089.782589456112 1001.9280492343214 1003.4729405290494 Accuracy: 0.9071  test :  0.8407  Prule Train :  0.9279227985524731  Prule test :  0.955159112825458
65 1968.501670285226 974.6190094487981 975.6032602839407 Accuracy: 0.91  test :  0.8413  Prule Train :  0.9300907406595446  Prule test :  0.954032766225583
70 1605.5863665986467 945.5234783757373 946.3262715590366 Accuracy: 0.9146  test :  0.842  Prule Train :  0.9311214746772465  Prule test :  0.9549554284753173
75 2051.236546476302 915.8478813354627 916.8734996087007 Accuracy: 0.9163  test :  0.8407  Prule Train :  0.9317320595204088  Prule test :  0.9490055504162812
80 1612.2966065147248 888.4067264215321 889.2128747247896 Accuracy: 0.9206  test :  0.8413  Prule Train :  0.9288268199083479  Prule test :  0.9538254128749578
85 2942.3869527528514 863.2433597778718 864.7145532542482 Accuracy: 0.9229  test :  0.8427  Prule Train :  0.930233869920239  Prule test :  0.9556775010552976
90 2298.5701336895804 839.2530232194395 840.4023082862843 Accuracy: 0.9249  test :  0.8413  Prule Train :  0.9330357791669868  Prule test :  0.9536168504668949
95 961.0865879678556 819.9847236861563 820.4652669801401 Accuracy: 0.9271  test :  0.844  Prule Train :  0.9326709415275221  Prule test :  0.9494835104356292
Resultado | acc=0.8433 | bal_acc=0.6769 | f1=0.9066 | EOdds=0.0503 | EOp=0.0219 | p-rule=94.65 | score=0.6737 | tempo=0.06 min

FAGTB african_american_0:  38%|███▊      | 23/60 [02:12<03:07,  5.06s/modelo]

----------------------------------------------------------------------------------------------------
Treino 24/120 | config=african_american_0 | lambda=0.0005 | n_estimators=200 | learning_rate=0.1 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1809.675663132863 1810.1483114934247 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1728.1714591635136 1675.1153868316605 1675.9794725612423 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 589.8709055478573 1557.3927629659524 1557.6876984187263 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 181.0132936104402 1460.9848770640817 1461.075383710887 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2805.168919611787 1380.424963489602 1381.827547949408 Accuracy: 0.8654  test :  0.8413  Prule Train :  0.9520001989325901  Prule test :  0.9616392368787358
25 1507.9218128215703 1311.0646042591559 1311.8185651655667 Accuracy: 0.8797  test :  0.8427  Prule Train :  0.9458463221544158  Prule test :  0.957457529513389
30 958.7967962042034 1253.8103978012196 1254.2897961993217 Accuracy: 0.8846  test :  0.8407  Prule Train :  0.945602375551549  Prule test :  0.9541430521656393
35 -757.7486401471292 1202.227258630318 1201.848384310244 Accuracy: 0.8866  test :  0.84  Prule Train :  0.9431732042126905  Prule test :  0.951216232987217
40 2830.7644047744557 1156.9707359962335 1158.3861181986208 Accuracy: 0.8906  test :  0.8407  Prule Train :  0.9400148072088412  Prule test :  0.9521221532091098
45 2132.1885383207127 1114.8285818994664 1115.8946761686268 Accuracy: 0.8934  test :  0.84  Prule Train :  0.9370037030113717  Prule test :  0.9491925465838509
50 1083.2028636910682 1075.7923166949472 1076.3339181267927 Accuracy: 0.8977  test :  0.84  Prule Train :  0.9324587940694449  Prule test :  0.9489742950874133
55 -1601.2734936505083 1039.2061019029995 1038.4054651561742 Accuracy: 0.9026  test :  0.842  Prule Train :  0.9303966543882338  Prule test :  0.9496644295302014
60 3089.782589456112 1001.9280492343214 1003.4729405290494 Accuracy: 0.9071  test :  0.8407  Prule Train :  0.9279227985524731  Prule test :  0.955159112825458
65 1968.501670285226 974.6190094487981 975.6032602839407 Accuracy: 0.91  test :  0.8413  Prule Train :  0.9300907406595446  Prule test :  0.954032766225583
70 1605.5863665986467 945.5234783757373 946.3262715590366 Accuracy: 0.9146  test :  0.842  Prule Train :  0.9311214746772465  Prule test :  0.9549554284753173
75 2051.236546476302 915.8478813354627 916.8734996087007 Accuracy: 0.9163  test :  0.8407  Prule Train :  0.9317320595204088  Prule test :  0.9490055504162812
80 1612.2966065147248 888.4067264215321 889.2128747247896 Accuracy: 0.9206  test :  0.8413  Prule Train :  0.9288268199083479  Prule test :  0.9538254128749578
85 2942.3869527528514 863.2433597778718 864.7145532542482 Accuracy: 0.9229  test :  0.8427  Prule Train :  0.930233869920239  Prule test :  0.9556775010552976
90 2298.5701336895804 839.2530232194395 840.4023082862843 Accuracy: 0.9249  test :  0.8413  Prule Train :  0.9330357791669868  Prule test :  0.9536168504668949
95 961.0865879678556 819.9847236861563 820.4652669801401 Accuracy: 0.9271  test :  0.844  Prule Train :  0.9326709415275221  Prule test :  0.9494835104356292
100 -2078.4027028317737 801.4788682335422 800.4396668821264 Accuracy: 0.9303  test :  0.8433  Prule Train :  0.9335155193319684  Prule test :  0.9444126620900076
105 2879.5262924462627 783.351831029179 784.7915941754022 Accuracy: 0.9326  test :  0.8447  Prule Train :  0.9331495552819079  Prule test :  0.9423329798515376
110 1945.8011362960892 764.6737845097173 765.6466850778653 Accuracy: 0.9351  test :  0.8427  Prule Train :  0.9349984625937227  Prule test :  0.9411683454460451
115 1379.786765029061 747.8943501160256 748.58424349854 Accuracy: 0.9374  test :  0.844  Prule Train :  0.9346341473697302  Prule test :  0.9430119661031384
120 -1657.402653858695 731.9997617937827 731.1710604668533 Accuracy: 0.9397  test :  0.844  Prule Train :  0.928813557533294  Prule test :  0.9411683454460451
125 2411.778347596527 717.1963467218794 718.4022358956777 Accuracy: 0.942  test :  0.844  Prule Train :  0.9229776704830955  Prule test :  0.9430119661031384
130 2006.2093299202775 703.7297257679395 704.7328304328998 Accuracy: 0.9434  test :  0.8433  Prule Train :  0.9195493902796954  Prule test :  0.9399991483200614
135 216.37291221115188 689.4885740436539 689.5967604997595 Accuracy: 0.9449  test :  0.8427  Prule Train :  0.9179316290187465  Prule test :  0.9430119661031384
140 -1512.7744371580206 674.0791005127192 673.3227132941402 Accuracy: 0.9486  test :  0.842  Prule Train :  0.9158926550278282  Prule test :  0.9439364876385337
145 2519.343701053169 662.1390353556377 663.3987072061643 Accuracy: 0.9497  test :  0.8427  Prule Train :  0.9138581940603712  Prule test :  0.9388253616077143
150 1785.490963862072 649.3238622922594 650.2166077741904 Accuracy: 0.9514  test :  0.8427  Prule Train :  0.9144538336751639  Prule test :  0.9427692833347571
155 1091.9168494904402 635.720702526589 636.2666609513342 Accuracy: 0.9543  test :  0.8427  Prule Train :  0.9111732070596891  Prule test :  0.9425251659884344
160 -1472.991840227257 623.9067869236371 623.1702910035235 Accuracy: 0.956  test :  0.8427  Prule Train :  0.9044332524693819  Prule test :  0.9425251659884344
165 2349.0623635611164 613.1996995940694 614.37423077585 Accuracy: 0.9563  test :  0.8413  Prule Train :  0.9048345094580551  Prule test :  0.9425251659884344
170 1748.9308469214368 601.7818645676136 602.6563299910742 Accuracy: 0.9574  test :  0.8407  Prule Train :  0.904609076035902  Prule test :  0.9434546779864506
175 921.4826519034423 592.743432027394 593.2041733533456 Accuracy: 0.9586  test :  0.8413  Prule Train :  0.9062194170702338  Prule test :  0.9443860251512942
180 -1376.3126423358212 583.4303554406821 582.7421991195142 Accuracy: 0.9597  test :  0.8427  Prule Train :  0.9041564017075878  Prule test :  0.9462542467638585
185 2251.9068533716686 574.5135656630699 575.6395190897558 Accuracy: 0.9606  test :  0.8433  Prule Train :  0.9035261558947366  Prule test :  0.9453192129231826
190 1669.6223028152071 566.9351604831824 567.7699716345899 Accuracy: 0.9614  test :  0.8433  Prule Train :  0.9047362355678098  Prule test :  0.9453192129231826
195 886.5118341396094 559.4751739554824 559.9184298725522 Accuracy: 0.9629  test :  0.8427  Prule Train :  0.9049137806396481  Prule test :  0.9462542467638585
Resultado | acc=0.8427 | bal_acc=0.6874 | f1=0.9054 | EOdds=0.0366 | EOp=0.0240 | p-rule=94.63 | score=0.6849 | tempo=0.12 min

FAGTB african_american_0:  40%|████      | 24/60 [02:19<03:23,  5.65s/modelo]

----------------------------------------------------------------------------------------------------
Treino 25/120 | config=african_american_0 | lambda=0.001 | n_estimators=100 | learning_rate=0.03 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1830.3513996590912 1831.2966963802146 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1700.5937235994406 1787.3709096406747 1789.0715033642741 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 583.242402981062 1747.3092398481936 1747.8924822511744 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 381.3967339132713 1708.6471899734333 1709.0285867073467 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2706.45778140876 1670.6223223242039 1673.3287801056129 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1507.8682062908238 1633.5815812945793 1635.0894495008702 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 829.8480824487012 1598.409952603532 1599.2398006859805 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 46.426288448565174 1565.5027838165988 1565.5492101050477 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2868.505032656724 1534.7051343230328 1537.5736393556897 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 1621.3783707061727 1505.1402919465124 1506.7616703172184 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 983.8504907291433 1477.5351276642523 1478.5189781549816 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -589.1573548068243 1451.225629100671 1450.6364717458646 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 2970.0549775162144 1426.3016095654639 1429.27166454298 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 2183.254497065641 1402.7166344938264 1404.8998889908917 Accuracy: 0.7834  test :  0.782  Prule Train :  0.9982498640341629  Prule test :  0.9991166077738517
70 1124.6370609683936 1379.9116390477311 1381.0362761087 Accuracy: 0.8651  test :  0.8407  Prule Train :  0.9516155523875669  Prule test :  0.9607345903717943
75 -1263.8792038123179 1358.4174910880683 1357.153611884256 Accuracy: 0.8674  test :  0.842  Prule Train :  0.947940378596789  Prule test :  0.9625455886571324
80 3232.6947135611586 1337.7560494558352 1340.9887441693963 Accuracy: 0.8723  test :  0.8433  Prule Train :  0.952805996476996  Prule test :  0.9605516817063166
85 2385.8557439676715 1318.3238654602196 1320.7097212041872 Accuracy: 0.8769  test :  0.8427  Prule Train :  0.9522107673780037  Prule test :  0.9632779400271483
90 1586.5143186816338 1299.8886372784364 1301.4751515971184 Accuracy: 0.88  test :  0.8427  Prule Train :  0.9479446589644073  Prule test :  0.9612771739130435
95 -2036.4572972847814 1282.7600547899274 1280.7235974926427 Accuracy: 0.8829  test :  0.8427  Prule Train :  0.9449828536609207  Prule test :  0.9554512516469038
Resultado | acc=0.8420 | bal_acc=0.6530 | f1=0.9072 | EOdds=0.0672 | EOp=0.0143 | p-rule=95.25 | score=0.6492 | tempo=0.06 min

FAGTB african_american_0:  42%|████▏     | 25/60 [02:22<02:57,  5.06s/modelo]

----------------------------------------------------------------------------------------------------
Treino 26/120 | config=african_american_0 | lambda=0.001 | n_estimators=200 | learning_rate=0.03 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1830.3513996590912 1831.2966963802146 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1700.5937235994406 1787.3709096406747 1789.0715033642741 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 583.242402981062 1747.3092398481936 1747.8924822511744 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 381.3967339132713 1708.6471899734333 1709.0285867073467 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2706.45778140876 1670.6223223242039 1673.3287801056129 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1507.8682062908238 1633.5815812945793 1635.0894495008702 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 829.8480824487012 1598.409952603532 1599.2398006859805 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 46.426288448565174 1565.5027838165988 1565.5492101050477 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2868.505032656724 1534.7051343230328 1537.5736393556897 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 1621.3783707061727 1505.1402919465124 1506.7616703172184 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 983.8504907291433 1477.5351276642523 1478.5189781549816 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -589.1573548068243 1451.225629100671 1450.6364717458646 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 2970.0549775162144 1426.3016095654639 1429.27166454298 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 2183.254497065641 1402.7166344938264 1404.8998889908917 Accuracy: 0.7834  test :  0.782  Prule Train :  0.9982498640341629  Prule test :  0.9991166077738517
70 1124.6370609683936 1379.9116390477311 1381.0362761087 Accuracy: 0.8651  test :  0.8407  Prule Train :  0.9516155523875669  Prule test :  0.9607345903717943
75 -1263.8792038123179 1358.4174910880683 1357.153611884256 Accuracy: 0.8674  test :  0.842  Prule Train :  0.947940378596789  Prule test :  0.9625455886571324
80 3232.6947135611586 1337.7560494558352 1340.9887441693963 Accuracy: 0.8723  test :  0.8433  Prule Train :  0.952805996476996  Prule test :  0.9605516817063166
85 2385.8557439676715 1318.3238654602196 1320.7097212041872 Accuracy: 0.8769  test :  0.8427  Prule Train :  0.9522107673780037  Prule test :  0.9632779400271483
90 1586.5143186816338 1299.8886372784364 1301.4751515971184 Accuracy: 0.88  test :  0.8427  Prule Train :  0.9479446589644073  Prule test :  0.9612771739130435
95 -2036.4572972847814 1282.7600547899274 1280.7235974926427 Accuracy: 0.8829  test :  0.8427  Prule Train :  0.9449828536609207  Prule test :  0.9554512516469038
100 3134.2122904224375 1266.0283110741755 1269.162523364598 Accuracy: 0.8837  test :  0.842  Prule Train :  0.9461504601522646  Prule test :  0.9525382905138341
105 2633.720152003443 1250.2201222581425 1252.853842410146 Accuracy: 0.8846  test :  0.84  Prule Train :  0.9473209555668859  Prule test :  0.9514272749773122
110 1875.0868999672368 1234.4108569852417 1236.285943885209 Accuracy: 0.8854  test :  0.84  Prule Train :  0.9467731585175642  Prule test :  0.9532360720780294
115 -2815.428708437332 1218.7715652570014 1215.9561365485638 Accuracy: 0.8854  test :  0.8393  Prule Train :  0.9467731585175642  Prule test :  0.9503120350471151
120 3181.821114503166 1203.534682282952 1206.716503397455 Accuracy: 0.8869  test :  0.8387  Prule Train :  0.9435627842226916  Prule test :  0.951216232987217
125 2774.959797663698 1189.9017137748635 1192.676673572527 Accuracy: 0.8877  test :  0.8387  Prule Train :  0.9412899141652296  Prule test :  0.951216232987217
130 2026.6117314610465 1176.0820646959373 1178.1086764273984 Accuracy: 0.8889  test :  0.8387  Prule Train :  0.9428483411754367  Prule test :  0.951216232987217
135 -3329.454821104793 1162.699062290825 1159.3696074697204 Accuracy: 0.8897  test :  0.84  Prule Train :  0.9422947962378686  Prule test :  0.953029800638289
140 3236.6278074895827 1149.3425987075238 1152.5792265150135 Accuracy: 0.8911  test :  0.84  Prule Train :  0.9407945789278034  Prule test :  0.953029800638289
145 2696.0906296852436 1136.5750904000736 1139.2711810297587 Accuracy: 0.8917  test :  0.8407  Prule Train :  0.9398480396818644  Prule test :  0.9539391802190508
150 1983.0653061372718 1123.9774431721396 1125.960508478277 Accuracy: 0.8923  test :  0.8413  Prule Train :  0.9389007146001049  Prule test :  0.95485029691458
155 -3113.272351247579 1111.7571247164444 1108.6438523651968 Accuracy: 0.8937  test :  0.8413  Prule Train :  0.935665126292784  Prule test :  0.95485029691458
160 3061.7926676227016 1099.9608154605874 1103.0226081282099 Accuracy: 0.8937  test :  0.8413  Prule Train :  0.935665126292784  Prule test :  0.95485029691458
165 3688.6889095101646 1088.1951858867396 1091.88387479625 Accuracy: 0.8954  test :  0.842  Prule Train :  0.9310844666695088  Prule test :  0.9557631557070413
170 2266.963180211091 1076.573190859181 1078.840154039392 Accuracy: 0.8969  test :  0.8433  Prule Train :  0.9312937060302076  Prule test :  0.9575941196068632
175 2491.452499103915 1065.5756293458599 1068.0670818449637 Accuracy: 0.8983  test :  0.844  Prule Train :  0.933237140308234  Prule test :  0.9585122347742715
180 1949.5334735931824 1055.0570753715615 1057.006608845155 Accuracy: 0.8994  test :  0.8433  Prule Train :  0.9313250960130524  Prule test :  0.9573988222027316
185 1907.7239095669224 1044.1379964282662 1046.0457203378332 Accuracy: 0.9011  test :  0.842  Prule Train :  0.9284510319407466  Prule test :  0.9553616220735787
190 3186.616708867612 1033.248551299459 1036.4351680083266 Accuracy: 0.9023  test :  0.8433  Prule Train :  0.9300068778258591  Prule test :  0.9553616220735787
195 2717.6138055626216 1023.0564989822625 1025.774112787825 Accuracy: 0.9034  test :  0.842  Prule Train :  0.9315679468612362  Prule test :  0.9572023959118706
Resultado | acc=0.8420 | bal_acc=0.6662 | f1=0.9064 | EOdds=0.0449 | EOp=0.0153 | p-rule=95.52 | score=0.6635 | tempo=0.12 min

FAGTB african_american_0:  43%|████▎     | 26/60 [02:29<03:12,  5.66s/modelo]

----------------------------------------------------------------------------------------------------
Treino 27/120 | config=african_american_0 | lambda=0.001 | n_estimators=100 | learning_rate=0.03 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1830.3513996590912 1831.2966963802146 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1700.5937235994406 1787.3709096406747 1789.0715033642741 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 583.242402981062 1747.3092398481936 1747.8924822511744 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 381.3967339132713 1708.6471899734333 1709.0285867073467 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2706.45778140876 1670.6223223242039 1673.3287801056129 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1507.8682062908238 1633.5815812945793 1635.0894495008702 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 829.8480824487012 1598.409952603532 1599.2398006859805 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 46.426288448565174 1565.5027838165988 1565.5492101050477 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2868.505032656724 1534.7051343230328 1537.5736393556897 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 1621.3783707061727 1505.1402919465124 1506.7616703172184 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 983.8504907291433 1477.5351276642523 1478.5189781549816 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -589.1573548068243 1451.225629100671 1450.6364717458646 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 2970.0549775162144 1426.3016095654639 1429.27166454298 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 2183.254497065641 1402.7166344938264 1404.8998889908917 Accuracy: 0.7834  test :  0.782  Prule Train :  0.9982498640341629  Prule test :  0.9991166077738517
70 1124.6370609683936 1379.9116390477311 1381.0362761087 Accuracy: 0.8651  test :  0.8407  Prule Train :  0.9516155523875669  Prule test :  0.9607345903717943
75 -1263.8792038123179 1358.4174910880683 1357.153611884256 Accuracy: 0.8674  test :  0.842  Prule Train :  0.947940378596789  Prule test :  0.9625455886571324
80 3232.6947135611586 1337.7560494558352 1340.9887441693963 Accuracy: 0.8723  test :  0.8433  Prule Train :  0.952805996476996  Prule test :  0.9605516817063166
85 2385.8557439676715 1318.3238654602196 1320.7097212041872 Accuracy: 0.8769  test :  0.8427  Prule Train :  0.9522107673780037  Prule test :  0.9632779400271483
90 1586.5143186816338 1299.8886372784364 1301.4751515971184 Accuracy: 0.88  test :  0.8427  Prule Train :  0.9479446589644073  Prule test :  0.9612771739130435
95 -2036.4572972847814 1282.7600547899274 1280.7235974926427 Accuracy: 0.8829  test :  0.8427  Prule Train :  0.9449828536609207  Prule test :  0.9554512516469038
Resultado | acc=0.8420 | bal_acc=0.6530 | f1=0.9072 | EOdds=0.0672 | EOp=0.0143 | p-rule=95.25 | score=0.6492 | tempo=0.06 min

FAGTB african_american_0:  45%|████▌     | 27/60 [02:33<02:47,  5.06s/modelo]

----------------------------------------------------------------------------------------------------
Treino 28/120 | config=african_american_0 | lambda=0.001 | n_estimators=200 | learning_rate=0.03 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1830.3513996590912 1831.2966963802146 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1700.5937235994406 1787.3709096406747 1789.0715033642741 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 583.242402981062 1747.3092398481936 1747.8924822511744 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 381.3967339132713 1708.6471899734333 1709.0285867073467 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2706.45778140876 1670.6223223242039 1673.3287801056129 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1507.8682062908238 1633.5815812945793 1635.0894495008702 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 829.8480824487012 1598.409952603532 1599.2398006859805 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 46.426288448565174 1565.5027838165988 1565.5492101050477 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2868.505032656724 1534.7051343230328 1537.5736393556897 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 1621.3783707061727 1505.1402919465124 1506.7616703172184 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 983.8504907291433 1477.5351276642523 1478.5189781549816 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -589.1573548068243 1451.225629100671 1450.6364717458646 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 2970.0549775162144 1426.3016095654639 1429.27166454298 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 2183.254497065641 1402.7166344938264 1404.8998889908917 Accuracy: 0.7834  test :  0.782  Prule Train :  0.9982498640341629  Prule test :  0.9991166077738517
70 1124.6370609683936 1379.9116390477311 1381.0362761087 Accuracy: 0.8651  test :  0.8407  Prule Train :  0.9516155523875669  Prule test :  0.9607345903717943
75 -1263.8792038123179 1358.4174910880683 1357.153611884256 Accuracy: 0.8674  test :  0.842  Prule Train :  0.947940378596789  Prule test :  0.9625455886571324
80 3232.6947135611586 1337.7560494558352 1340.9887441693963 Accuracy: 0.8723  test :  0.8433  Prule Train :  0.952805996476996  Prule test :  0.9605516817063166
85 2385.8557439676715 1318.3238654602196 1320.7097212041872 Accuracy: 0.8769  test :  0.8427  Prule Train :  0.9522107673780037  Prule test :  0.9632779400271483
90 1586.5143186816338 1299.8886372784364 1301.4751515971184 Accuracy: 0.88  test :  0.8427  Prule Train :  0.9479446589644073  Prule test :  0.9612771739130435
95 -2036.4572972847814 1282.7600547899274 1280.7235974926427 Accuracy: 0.8829  test :  0.8427  Prule Train :  0.9449828536609207  Prule test :  0.9554512516469038
100 3134.2122904224375 1266.0283110741755 1269.162523364598 Accuracy: 0.8837  test :  0.842  Prule Train :  0.9461504601522646  Prule test :  0.9525382905138341
105 2633.720152003443 1250.2201222581425 1252.853842410146 Accuracy: 0.8846  test :  0.84  Prule Train :  0.9473209555668859  Prule test :  0.9514272749773122
110 1875.0868999672368 1234.4108569852417 1236.285943885209 Accuracy: 0.8854  test :  0.84  Prule Train :  0.9467731585175642  Prule test :  0.9532360720780294
115 -2815.428708437332 1218.7715652570014 1215.9561365485638 Accuracy: 0.8854  test :  0.8393  Prule Train :  0.9467731585175642  Prule test :  0.9503120350471151
120 3181.821114503166 1203.534682282952 1206.716503397455 Accuracy: 0.8869  test :  0.8387  Prule Train :  0.9435627842226916  Prule test :  0.951216232987217
125 2774.959797663698 1189.9017137748635 1192.676673572527 Accuracy: 0.8877  test :  0.8387  Prule Train :  0.9412899141652296  Prule test :  0.951216232987217
130 2026.6117314610465 1176.0820646959373 1178.1086764273984 Accuracy: 0.8889  test :  0.8387  Prule Train :  0.9428483411754367  Prule test :  0.951216232987217
135 -3329.454821104793 1162.699062290825 1159.3696074697204 Accuracy: 0.8897  test :  0.84  Prule Train :  0.9422947962378686  Prule test :  0.953029800638289
140 3236.6278074895827 1149.3425987075238 1152.5792265150135 Accuracy: 0.8911  test :  0.84  Prule Train :  0.9407945789278034  Prule test :  0.953029800638289
145 2696.0906296852436 1136.5750904000736 1139.2711810297587 Accuracy: 0.8917  test :  0.8407  Prule Train :  0.9398480396818644  Prule test :  0.9539391802190508
150 1983.0653061372718 1123.9774431721396 1125.960508478277 Accuracy: 0.8923  test :  0.8413  Prule Train :  0.9389007146001049  Prule test :  0.95485029691458
155 -3113.272351247579 1111.7571247164444 1108.6438523651968 Accuracy: 0.8937  test :  0.8413  Prule Train :  0.935665126292784  Prule test :  0.95485029691458
160 3061.7926676227016 1099.9608154605874 1103.0226081282099 Accuracy: 0.8937  test :  0.8413  Prule Train :  0.935665126292784  Prule test :  0.95485029691458
165 3688.6889095101646 1088.1951858867396 1091.88387479625 Accuracy: 0.8954  test :  0.842  Prule Train :  0.9310844666695088  Prule test :  0.9557631557070413
170 2266.963180211091 1076.573190859181 1078.840154039392 Accuracy: 0.8969  test :  0.8433  Prule Train :  0.9312937060302076  Prule test :  0.9575941196068632
175 2491.452499103915 1065.5756293458599 1068.0670818449637 Accuracy: 0.8983  test :  0.844  Prule Train :  0.933237140308234  Prule test :  0.9585122347742715
180 1949.5334735931824 1055.0570753715615 1057.006608845155 Accuracy: 0.8994  test :  0.8433  Prule Train :  0.9313250960130524  Prule test :  0.9573988222027316
185 1907.7239095669224 1044.1379964282662 1046.0457203378332 Accuracy: 0.9011  test :  0.842  Prule Train :  0.9284510319407466  Prule test :  0.9553616220735787
190 3186.616708867612 1033.248551299459 1036.4351680083266 Accuracy: 0.9023  test :  0.8433  Prule Train :  0.9300068778258591  Prule test :  0.9553616220735787
195 2717.6138055626216 1023.0564989822625 1025.774112787825 Accuracy: 0.9034  test :  0.842  Prule Train :  0.9315679468612362  Prule test :  0.9572023959118706
Resultado | acc=0.8420 | bal_acc=0.6662 | f1=0.9064 | EOdds=0.0449 | EOp=0.0153 | p-rule=95.52 | score=0.6635 | tempo=0.12 min

FAGTB african_american_0:  47%|████▋     | 28/60 [02:40<03:01,  5.67s/modelo]

----------------------------------------------------------------------------------------------------
Treino 29/120 | config=african_american_0 | lambda=0.001 | n_estimators=100 | learning_rate=0.05 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1824.5429729818252 1825.4882697029486 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1708.3462447909803 1754.9196570205158 1756.6280032653071 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 586.378111478308 1690.8267797112849 1691.4131578227632 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 321.2976862368243 1628.0771724115198 1628.3984700977567 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2757.9778716864926 1572.0214767288926 1574.7794546005794 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1520.3227374666865 1520.185222280358 1521.7055450178248 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 878.3138222531143 1473.1722171175406 1474.0505309397938 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -302.1433709441847 1430.8462699519591 1430.5441265810152 Accuracy: 0.7811  test :  0.782  Prule Train :  1.0  Prule test :  0.9991166077738517
40 2882.6091499204867 1391.5938178945053 1394.4764270444261 Accuracy: 0.8514  test :  0.832  Prule Train :  0.9617006037139333  Prule test :  0.962526744984054
45 2010.3917795900002 1354.917145507039 1356.9275372866293 Accuracy: 0.8689  test :  0.8427  Prule Train :  0.9498623988291428  Prule test :  0.9596463549563579
50 1215.4147990307142 1321.5671550795837 1322.7825698786146 Accuracy: 0.8763  test :  0.8427  Prule Train :  0.9531394676211555  Prule test :  0.9632779400271483
55 -849.4136996171292 1290.860676959309 1290.011263259692 Accuracy: 0.8826  test :  0.8427  Prule Train :  0.9445942916322774  Prule test :  0.9554512516469038
60 2646.5012174089825 1263.691088382255 1266.3375895996642 Accuracy: 0.884  test :  0.84  Prule Train :  0.9465403037699622  Prule test :  0.9552520748172922
65 2199.8613945334037 1237.9784306321044 1240.1782920266378 Accuracy: 0.8857  test :  0.8407  Prule Train :  0.9471640640330545  Prule test :  0.9561601091089436
70 1554.536526097645 1211.9657375070458 1213.5202740331433 Accuracy: 0.8869  test :  0.84  Prule Train :  0.9435627842226916  Prule test :  0.951216232987217
75 -1140.4107460351029 1188.2827202337876 1187.1423094877523 Accuracy: 0.8877  test :  0.8393  Prule Train :  0.9412899141652296  Prule test :  0.9521221532091098
80 3256.459236212905 1165.7833105586906 1169.0397697949036 Accuracy: 0.8897  test :  0.8407  Prule Train :  0.9440205521259242  Prule test :  0.9521221532091098
85 2508.7725209589817 1143.6603153930237 1146.1690879139828 Accuracy: 0.8914  test :  0.8427  Prule Train :  0.9394582229918264  Prule test :  0.95485029691458
90 1649.0666825134902 1122.8315395449363 1124.4806062274497 Accuracy: 0.8929  test :  0.842  Prule Train :  0.9379526027034933  Prule test :  0.9557631557070413
95 -2423.24898018649 1103.4853784942393 1101.062129514053 Accuracy: 0.8937  test :  0.8427  Prule Train :  0.9373931476094646  Prule test :  0.95485029691458
Resultado | acc=0.8433 | bal_acc=0.6615 | f1=0.9076 | EOdds=0.0370 | EOp=0.0183 | p-rule=95.58 | score=0.6591 | tempo=0.06 min

FAGTB african_american_0:  48%|████▊     | 29/60 [02:44<02:37,  5.07s/modelo]

----------------------------------------------------------------------------------------------------
Treino 30/120 | config=african_american_0 | lambda=0.001 | n_estimators=200 | learning_rate=0.05 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1824.5429729818252 1825.4882697029486 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1708.3462447909803 1754.9196570205158 1756.6280032653071 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 586.378111478308 1690.8267797112849 1691.4131578227632 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 321.2976862368243 1628.0771724115198 1628.3984700977567 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2757.9778716864926 1572.0214767288926 1574.7794546005794 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1520.3227374666865 1520.185222280358 1521.7055450178248 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 878.3138222531143 1473.1722171175406 1474.0505309397938 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -302.1433709441847 1430.8462699519591 1430.5441265810152 Accuracy: 0.7811  test :  0.782  Prule Train :  1.0  Prule test :  0.9991166077738517
40 2882.6091499204867 1391.5938178945053 1394.4764270444261 Accuracy: 0.8514  test :  0.832  Prule Train :  0.9617006037139333  Prule test :  0.962526744984054
45 2010.3917795900002 1354.917145507039 1356.9275372866293 Accuracy: 0.8689  test :  0.8427  Prule Train :  0.9498623988291428  Prule test :  0.9596463549563579
50 1215.4147990307142 1321.5671550795837 1322.7825698786146 Accuracy: 0.8763  test :  0.8427  Prule Train :  0.9531394676211555  Prule test :  0.9632779400271483
55 -849.4136996171292 1290.860676959309 1290.011263259692 Accuracy: 0.8826  test :  0.8427  Prule Train :  0.9445942916322774  Prule test :  0.9554512516469038
60 2646.5012174089825 1263.691088382255 1266.3375895996642 Accuracy: 0.884  test :  0.84  Prule Train :  0.9465403037699622  Prule test :  0.9552520748172922
65 2199.8613945334037 1237.9784306321044 1240.1782920266378 Accuracy: 0.8857  test :  0.8407  Prule Train :  0.9471640640330545  Prule test :  0.9561601091089436
70 1554.536526097645 1211.9657375070458 1213.5202740331433 Accuracy: 0.8869  test :  0.84  Prule Train :  0.9435627842226916  Prule test :  0.951216232987217
75 -1140.4107460351029 1188.2827202337876 1187.1423094877523 Accuracy: 0.8877  test :  0.8393  Prule Train :  0.9412899141652296  Prule test :  0.9521221532091098
80 3256.459236212905 1165.7833105586906 1169.0397697949036 Accuracy: 0.8897  test :  0.8407  Prule Train :  0.9440205521259242  Prule test :  0.9521221532091098
85 2508.7725209589817 1143.6603153930237 1146.1690879139828 Accuracy: 0.8914  test :  0.8427  Prule Train :  0.9394582229918264  Prule test :  0.95485029691458
90 1649.0666825134902 1122.8315395449363 1124.4806062274497 Accuracy: 0.8929  test :  0.842  Prule Train :  0.9379526027034933  Prule test :  0.9557631557070413
95 -2423.24898018649 1103.4853784942393 1101.062129514053 Accuracy: 0.8937  test :  0.8427  Prule Train :  0.9373931476094646  Prule test :  0.95485029691458
100 3491.3233960075922 1083.3769995180032 1086.8683229140106 Accuracy: 0.8957  test :  0.8433  Prule Train :  0.933200206617482  Prule test :  0.9557631557070413
105 1987.040065786152 1064.755108494639 1066.742148560425 Accuracy: 0.8986  test :  0.8433  Prule Train :  0.9318924182040433  Prule test :  0.9575941196068632
110 2218.1498939476032 1046.302960529712 1048.5211104236596 Accuracy: 0.9006  test :  0.8447  Prule Train :  0.9294098543193838  Prule test :  0.9594321121588918
115 1826.6323611459406 1029.2133501578187 1031.0399825189647 Accuracy: 0.9023  test :  0.8433  Prule Train :  0.9282682006736538  Prule test :  0.9572023959118706
120 2278.685677205687 1011.8974017975986 1014.1760874748043 Accuracy: 0.904  test :  0.8413  Prule Train :  0.9288638309051802  Prule test :  0.959976895610166
125 1809.059300733613 996.5375150550906 998.3465743558241 Accuracy: 0.9063  test :  0.8433  Prule Train :  0.9284975181841664  Prule test :  0.9549554284753173
130 2656.495001776616 981.3820425540387 984.0385375558152 Accuracy: 0.9083  test :  0.842  Prule Train :  0.9277380659361224  Prule test :  0.9568061172901922
135 2808.2693381599242 967.3311941508205 970.1394634889805 Accuracy: 0.9097  test :  0.842  Prule Train :  0.9296977999157086  Prule test :  0.9547505587652342
140 2464.4261464446304 954.3314104740228 956.7958366204675 Accuracy: 0.9117  test :  0.8413  Prule Train :  0.9306957807026014  Prule test :  0.9556775010552976
145 -1657.340538392986 940.1520430528747 938.4947025144816 Accuracy: 0.9143  test :  0.8407  Prule Train :  0.9324907709635365  Prule test :  0.9566062449824649
150 2464.2871857522514 926.6841412403738 929.1484284261261 Accuracy: 0.9151  test :  0.8407  Prule Train :  0.93545029299227  Prule test :  0.9566062449824649
155 -1549.0170861126176 913.0982259755948 911.5492088894822 Accuracy: 0.9171  test :  0.8407  Prule Train :  0.9382462588551845  Prule test :  0.9566062449824649
160 2396.2216121838883 900.8229371439174 903.2191587561013 Accuracy: 0.9186  test :  0.8407  Prule Train :  0.934917468270906  Prule test :  0.9566062449824649
165 -2013.462708660731 886.7652953682909 884.7518326596302 Accuracy: 0.92  test :  0.8407  Prule Train :  0.9369194328710578  Prule test :  0.9566062449824649
170 3051.8553230010466 874.6578328248365 877.7096881478376 Accuracy: 0.9217  test :  0.8407  Prule Train :  0.9321984822577618  Prule test :  0.9566062449824649
175 1642.6713950967787 863.4757315356368 865.1184029307335 Accuracy: 0.9229  test :  0.84  Prule Train :  0.9320159248694069  Prule test :  0.9575367958044325
180 2997.869722172409 852.922814528454 855.9206842506264 Accuracy: 0.9229  test :  0.8413  Prule Train :  0.9337995101362637  Prule test :  0.9575367958044325
185 1423.9698828803791 842.8697875064253 844.2937573893056 Accuracy: 0.924  test :  0.8413  Prule Train :  0.9318328967701234  Prule test :  0.9575367958044325
190 -2021.902783668586 833.4905236971638 831.4686209134952 Accuracy: 0.9246  test :  0.842  Prule Train :  0.932634473455517  Prule test :  0.9584691587993734
195 2630.5141678333566 823.8225700537146 826.4530842215479 Accuracy: 0.9254  test :  0.8433  Prule Train :  0.9320504505477558  Prule test :  0.9584691587993734
Resultado | acc=0.8440 | bal_acc=0.6762 | f1=0.9071 | EOdds=0.0251 | EOp=0.0145 | p-rule=95.94 | score=0.6745 | tempo=0.12 min

FAGTB african_american_0:  50%|█████     | 30/60 [02:51<02:50,  5.67s/modelo]

----------------------------------------------------------------------------------------------------
Treino 31/120 | config=african_american_0 | lambda=0.001 | n_estimators=100 | learning_rate=0.05 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1824.5429729818252 1825.4882697029486 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1708.3462447909803 1754.9196570205158 1756.6280032653071 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 586.378111478308 1690.8267797112849 1691.4131578227632 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 321.2976862368243 1628.0771724115198 1628.3984700977567 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2757.9778716864926 1572.0214767288926 1574.7794546005794 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1520.3227374666865 1520.185222280358 1521.7055450178248 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 878.3138222531143 1473.1722171175406 1474.0505309397938 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -302.1433709441847 1430.8462699519591 1430.5441265810152 Accuracy: 0.7811  test :  0.782  Prule Train :  1.0  Prule test :  0.9991166077738517
40 2882.6091499204867 1391.5938178945053 1394.4764270444261 Accuracy: 0.8514  test :  0.832  Prule Train :  0.9617006037139333  Prule test :  0.962526744984054
45 2010.3917795900002 1354.917145507039 1356.9275372866293 Accuracy: 0.8689  test :  0.8427  Prule Train :  0.9498623988291428  Prule test :  0.9596463549563579
50 1215.4147990307142 1321.5671550795837 1322.7825698786146 Accuracy: 0.8763  test :  0.8427  Prule Train :  0.9531394676211555  Prule test :  0.9632779400271483
55 -849.4136996171292 1290.860676959309 1290.011263259692 Accuracy: 0.8826  test :  0.8427  Prule Train :  0.9445942916322774  Prule test :  0.9554512516469038
60 2646.5012174089825 1263.691088382255 1266.3375895996642 Accuracy: 0.884  test :  0.84  Prule Train :  0.9465403037699622  Prule test :  0.9552520748172922
65 2199.8613945334037 1237.9784306321044 1240.1782920266378 Accuracy: 0.8857  test :  0.8407  Prule Train :  0.9471640640330545  Prule test :  0.9561601091089436
70 1554.536526097645 1211.9657375070458 1213.5202740331433 Accuracy: 0.8869  test :  0.84  Prule Train :  0.9435627842226916  Prule test :  0.951216232987217
75 -1140.4107460351029 1188.2827202337876 1187.1423094877523 Accuracy: 0.8877  test :  0.8393  Prule Train :  0.9412899141652296  Prule test :  0.9521221532091098
80 3256.459236212905 1165.7833105586906 1169.0397697949036 Accuracy: 0.8897  test :  0.8407  Prule Train :  0.9440205521259242  Prule test :  0.9521221532091098
85 2508.7725209589817 1143.6603153930237 1146.1690879139828 Accuracy: 0.8914  test :  0.8427  Prule Train :  0.9394582229918264  Prule test :  0.95485029691458
90 1649.0666825134902 1122.8315395449363 1124.4806062274497 Accuracy: 0.8929  test :  0.842  Prule Train :  0.9379526027034933  Prule test :  0.9557631557070413
95 -2423.24898018649 1103.4853784942393 1101.062129514053 Accuracy: 0.8937  test :  0.8427  Prule Train :  0.9373931476094646  Prule test :  0.95485029691458
Resultado | acc=0.8433 | bal_acc=0.6615 | f1=0.9076 | EOdds=0.0370 | EOp=0.0183 | p-rule=95.58 | score=0.6591 | tempo=0.06 min

FAGTB african_american_0:  52%|█████▏    | 31/60 [02:55<02:27,  5.08s/modelo]

----------------------------------------------------------------------------------------------------
Treino 32/120 | config=african_american_0 | lambda=0.001 | n_estimators=200 | learning_rate=0.05 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1824.5429729818252 1825.4882697029486 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1708.3462447909803 1754.9196570205158 1756.6280032653071 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 586.378111478308 1690.8267797112849 1691.4131578227632 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 321.2976862368243 1628.0771724115198 1628.3984700977567 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2757.9778716864926 1572.0214767288926 1574.7794546005794 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1520.3227374666865 1520.185222280358 1521.7055450178248 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 878.3138222531143 1473.1722171175406 1474.0505309397938 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -302.1433709441847 1430.8462699519591 1430.5441265810152 Accuracy: 0.7811  test :  0.782  Prule Train :  1.0  Prule test :  0.9991166077738517
40 2882.6091499204867 1391.5938178945053 1394.4764270444261 Accuracy: 0.8514  test :  0.832  Prule Train :  0.9617006037139333  Prule test :  0.962526744984054
45 2010.3917795900002 1354.917145507039 1356.9275372866293 Accuracy: 0.8689  test :  0.8427  Prule Train :  0.9498623988291428  Prule test :  0.9596463549563579
50 1215.4147990307142 1321.5671550795837 1322.7825698786146 Accuracy: 0.8763  test :  0.8427  Prule Train :  0.9531394676211555  Prule test :  0.9632779400271483
55 -849.4136996171292 1290.860676959309 1290.011263259692 Accuracy: 0.8826  test :  0.8427  Prule Train :  0.9445942916322774  Prule test :  0.9554512516469038
60 2646.5012174089825 1263.691088382255 1266.3375895996642 Accuracy: 0.884  test :  0.84  Prule Train :  0.9465403037699622  Prule test :  0.9552520748172922
65 2199.8613945334037 1237.9784306321044 1240.1782920266378 Accuracy: 0.8857  test :  0.8407  Prule Train :  0.9471640640330545  Prule test :  0.9561601091089436
70 1554.536526097645 1211.9657375070458 1213.5202740331433 Accuracy: 0.8869  test :  0.84  Prule Train :  0.9435627842226916  Prule test :  0.951216232987217
75 -1140.4107460351029 1188.2827202337876 1187.1423094877523 Accuracy: 0.8877  test :  0.8393  Prule Train :  0.9412899141652296  Prule test :  0.9521221532091098
80 3256.459236212905 1165.7833105586906 1169.0397697949036 Accuracy: 0.8897  test :  0.8407  Prule Train :  0.9440205521259242  Prule test :  0.9521221532091098
85 2508.7725209589817 1143.6603153930237 1146.1690879139828 Accuracy: 0.8914  test :  0.8427  Prule Train :  0.9394582229918264  Prule test :  0.95485029691458
90 1649.0666825134902 1122.8315395449363 1124.4806062274497 Accuracy: 0.8929  test :  0.842  Prule Train :  0.9379526027034933  Prule test :  0.9557631557070413
95 -2423.24898018649 1103.4853784942393 1101.062129514053 Accuracy: 0.8937  test :  0.8427  Prule Train :  0.9373931476094646  Prule test :  0.95485029691458
100 3491.3233960075922 1083.3769995180032 1086.8683229140106 Accuracy: 0.8957  test :  0.8433  Prule Train :  0.933200206617482  Prule test :  0.9557631557070413
105 1987.040065786152 1064.755108494639 1066.742148560425 Accuracy: 0.8986  test :  0.8433  Prule Train :  0.9318924182040433  Prule test :  0.9575941196068632
110 2218.1498939476032 1046.302960529712 1048.5211104236596 Accuracy: 0.9006  test :  0.8447  Prule Train :  0.9294098543193838  Prule test :  0.9594321121588918
115 1826.6323611459406 1029.2133501578187 1031.0399825189647 Accuracy: 0.9023  test :  0.8433  Prule Train :  0.9282682006736538  Prule test :  0.9572023959118706
120 2278.685677205687 1011.8974017975986 1014.1760874748043 Accuracy: 0.904  test :  0.8413  Prule Train :  0.9288638309051802  Prule test :  0.959976895610166
125 1809.059300733613 996.5375150550906 998.3465743558241 Accuracy: 0.9063  test :  0.8433  Prule Train :  0.9284975181841664  Prule test :  0.9549554284753173
130 2656.495001776616 981.3820425540387 984.0385375558152 Accuracy: 0.9083  test :  0.842  Prule Train :  0.9277380659361224  Prule test :  0.9568061172901922
135 2808.2693381599242 967.3311941508205 970.1394634889805 Accuracy: 0.9097  test :  0.842  Prule Train :  0.9296977999157086  Prule test :  0.9547505587652342
140 2464.4261464446304 954.3314104740228 956.7958366204675 Accuracy: 0.9117  test :  0.8413  Prule Train :  0.9306957807026014  Prule test :  0.9556775010552976
145 -1657.340538392986 940.1520430528747 938.4947025144816 Accuracy: 0.9143  test :  0.8407  Prule Train :  0.9324907709635365  Prule test :  0.9566062449824649
150 2464.2871857522514 926.6841412403738 929.1484284261261 Accuracy: 0.9151  test :  0.8407  Prule Train :  0.93545029299227  Prule test :  0.9566062449824649
155 -1549.0170861126176 913.0982259755948 911.5492088894822 Accuracy: 0.9171  test :  0.8407  Prule Train :  0.9382462588551845  Prule test :  0.9566062449824649
160 2396.2216121838883 900.8229371439174 903.2191587561013 Accuracy: 0.9186  test :  0.8407  Prule Train :  0.934917468270906  Prule test :  0.9566062449824649
165 -2013.462708660731 886.7652953682909 884.7518326596302 Accuracy: 0.92  test :  0.8407  Prule Train :  0.9369194328710578  Prule test :  0.9566062449824649
170 3051.8553230010466 874.6578328248365 877.7096881478376 Accuracy: 0.9217  test :  0.8407  Prule Train :  0.9321984822577618  Prule test :  0.9566062449824649
175 1642.6713950967787 863.4757315356368 865.1184029307335 Accuracy: 0.9229  test :  0.84  Prule Train :  0.9320159248694069  Prule test :  0.9575367958044325
180 2997.869722172409 852.922814528454 855.9206842506264 Accuracy: 0.9229  test :  0.8413  Prule Train :  0.9337995101362637  Prule test :  0.9575367958044325
185 1423.9698828803791 842.8697875064253 844.2937573893056 Accuracy: 0.924  test :  0.8413  Prule Train :  0.9318328967701234  Prule test :  0.9575367958044325
190 -2021.902783668586 833.4905236971638 831.4686209134952 Accuracy: 0.9246  test :  0.842  Prule Train :  0.932634473455517  Prule test :  0.9584691587993734
195 2630.5141678333566 823.8225700537146 826.4530842215479 Accuracy: 0.9254  test :  0.8433  Prule Train :  0.9320504505477558  Prule test :  0.9584691587993734
Resultado | acc=0.8440 | bal_acc=0.6762 | f1=0.9071 | EOdds=0.0251 | EOp=0.0145 | p-rule=95.94 | score=0.6745 | tempo=0.12 min

FAGTB african_american_0:  53%|█████▎    | 32/60 [03:02<02:38,  5.67s/modelo]

----------------------------------------------------------------------------------------------------
Treino 33/120 | config=african_american_0 | lambda=0.001 | n_estimators=100 | learning_rate=0.1 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1810.1111339096487 1811.0564306307724 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1728.234179510548 1675.6652178333607 1677.393452012871 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 589.8912916061739 1557.819757730254 1558.4096490218603 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 181.16001169654135 1461.5578428328495 1461.7390028445457 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2807.228910106345 1380.9656017735151 1383.7728306836214 Accuracy: 0.8651  test :  0.8407  Prule Train :  0.9533025247861231  Prule test :  0.9607345903717943
25 1507.150375563201 1313.013997988195 1314.5211483637581 Accuracy: 0.876  test :  0.8433  Prule Train :  0.9527496355280587  Prule test :  0.958554009114423
30 957.1806607906407 1254.5221615762061 1255.479342236997 Accuracy: 0.8846  test :  0.842  Prule Train :  0.945602375551549  Prule test :  0.9561601091089436
35 -756.1425515029583 1202.0795514245065 1201.3234088730035 Accuracy: 0.8871  test :  0.8413  Prule Train :  0.9405126309991145  Prule test :  0.9550517598343685
40 2825.7815270623987 1158.7945239521198 1161.620305479182 Accuracy: 0.8903  test :  0.8413  Prule Train :  0.9396254058802542  Prule test :  0.9587039654169093
45 2135.210159427889 1116.590138406629 1118.7253485660567 Accuracy: 0.8937  test :  0.8427  Prule Train :  0.935665126292784  Prule test :  0.9605405630518075
50 1025.9900024009419 1077.2295854100855 1078.2555754124865 Accuracy: 0.8974  test :  0.842  Prule Train :  0.9286098624969793  Prule test :  0.9573988222027316
55 -1616.9996431503841 1040.997699192454 1039.3806995493037 Accuracy: 0.9014  test :  0.8413  Prule Train :  0.9271034977869868  Prule test :  0.9562811231535339
60 3144.58508432369 1005.3008775597967 1008.4454626441203 Accuracy: 0.9054  test :  0.842  Prule Train :  0.9273271431612451  Prule test :  0.9572023959118706
65 1674.1231356044486 972.694068896815 974.3681920324195 Accuracy: 0.9103  test :  0.8407  Prule Train :  0.9287289679792232  Prule test :  0.9490055504162812
70 -1270.5894859570012 944.9785344587378 943.7079449727808 Accuracy: 0.9134  test :  0.8393  Prule Train :  0.9277806937039526  Prule test :  0.9508447084597236
75 2436.77411468594 916.314090149797 918.750864264483 Accuracy: 0.9154  test :  0.84  Prule Train :  0.9305431202696386  Prule test :  0.9536168504668949
80 1617.878416148764 887.8396278676005 889.4575062837491 Accuracy: 0.9203  test :  0.8407  Prule Train :  0.9284297156672585  Prule test :  0.9586639932460954
85 1325.444481161665 861.1087641019332 862.4342085830948 Accuracy: 0.9223  test :  0.842  Prule Train :  0.9294364126807018  Prule test :  0.9485598883437657
90 -1141.1721536010843 834.6614415439262 833.5202693903251 Accuracy: 0.9249  test :  0.8427  Prule Train :  0.9330357791669868  Prule test :  0.9494835104356292
95 2093.75423800061 813.4440971941609 815.5378514321615 Accuracy: 0.928  test :  0.8427  Prule Train :  0.928501026736788  Prule test :  0.9534070683956267
Resultado | acc=0.8420 | bal_acc=0.6749 | f1=0.9058 | EOdds=0.0546 | EOp=0.0112 | p-rule=95.43 | score=0.6719 | tempo=0.06 min

FAGTB african_american_0:  55%|█████▌    | 33/60 [03:05<02:17,  5.08s/modelo]

----------------------------------------------------------------------------------------------------
Treino 34/120 | config=african_american_0 | lambda=0.001 | n_estimators=200 | learning_rate=0.1 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1810.1111339096487 1811.0564306307724 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1728.234179510548 1675.6652178333607 1677.393452012871 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 589.8912916061739 1557.819757730254 1558.4096490218603 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 181.16001169654135 1461.5578428328495 1461.7390028445457 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2807.228910106345 1380.9656017735151 1383.7728306836214 Accuracy: 0.8651  test :  0.8407  Prule Train :  0.9533025247861231  Prule test :  0.9607345903717943
25 1507.150375563201 1313.013997988195 1314.5211483637581 Accuracy: 0.876  test :  0.8433  Prule Train :  0.9527496355280587  Prule test :  0.958554009114423
30 957.1806607906407 1254.5221615762061 1255.479342236997 Accuracy: 0.8846  test :  0.842  Prule Train :  0.945602375551549  Prule test :  0.9561601091089436
35 -756.1425515029583 1202.0795514245065 1201.3234088730035 Accuracy: 0.8871  test :  0.8413  Prule Train :  0.9405126309991145  Prule test :  0.9550517598343685
40 2825.7815270623987 1158.7945239521198 1161.620305479182 Accuracy: 0.8903  test :  0.8413  Prule Train :  0.9396254058802542  Prule test :  0.9587039654169093
45 2135.210159427889 1116.590138406629 1118.7253485660567 Accuracy: 0.8937  test :  0.8427  Prule Train :  0.935665126292784  Prule test :  0.9605405630518075
50 1025.9900024009419 1077.2295854100855 1078.2555754124865 Accuracy: 0.8974  test :  0.842  Prule Train :  0.9286098624969793  Prule test :  0.9573988222027316
55 -1616.9996431503841 1040.997699192454 1039.3806995493037 Accuracy: 0.9014  test :  0.8413  Prule Train :  0.9271034977869868  Prule test :  0.9562811231535339
60 3144.58508432369 1005.3008775597967 1008.4454626441203 Accuracy: 0.9054  test :  0.842  Prule Train :  0.9273271431612451  Prule test :  0.9572023959118706
65 1674.1231356044486 972.694068896815 974.3681920324195 Accuracy: 0.9103  test :  0.8407  Prule Train :  0.9287289679792232  Prule test :  0.9490055504162812
70 -1270.5894859570012 944.9785344587378 943.7079449727808 Accuracy: 0.9134  test :  0.8393  Prule Train :  0.9277806937039526  Prule test :  0.9508447084597236
75 2436.77411468594 916.314090149797 918.750864264483 Accuracy: 0.9154  test :  0.84  Prule Train :  0.9305431202696386  Prule test :  0.9536168504668949
80 1617.878416148764 887.8396278676005 889.4575062837491 Accuracy: 0.9203  test :  0.8407  Prule Train :  0.9284297156672585  Prule test :  0.9586639932460954
85 1325.444481161665 861.1087641019332 862.4342085830948 Accuracy: 0.9223  test :  0.842  Prule Train :  0.9294364126807018  Prule test :  0.9485598883437657
90 -1141.1721536010843 834.6614415439262 833.5202693903251 Accuracy: 0.9249  test :  0.8427  Prule Train :  0.9330357791669868  Prule test :  0.9494835104356292
95 2093.75423800061 813.4440971941609 815.5378514321615 Accuracy: 0.928  test :  0.8427  Prule Train :  0.928501026736788  Prule test :  0.9534070683956267
100 -501.01430761398666 797.4843647760479 796.9833504684339 Accuracy: 0.9294  test :  0.842  Prule Train :  0.9269207220961526  Prule test :  0.9543372216330859
105 1340.898474626757 782.8477454412982 784.188643915925 Accuracy: 0.9326  test :  0.844  Prule Train :  0.927743956344021  Prule test :  0.9531960559309788
110 1632.4839536378618 768.4401488611898 770.0726328148276 Accuracy: 0.9337  test :  0.842  Prule Train :  0.9275534559998575  Prule test :  0.9501891283097454
115 1323.8533657380121 754.6536590561107 755.9775124218486 Accuracy: 0.9357  test :  0.8433  Prule Train :  0.9267674938400309  Prule test :  0.9520504194523699
120 2609.6405662538345 739.743932661791 742.3535732280448 Accuracy: 0.9366  test :  0.8433  Prule Train :  0.9243656040579495  Prule test :  0.9520504194523699
125 1923.5306704059622 724.7100631698722 726.6335938402782 Accuracy: 0.9377  test :  0.8433  Prule Train :  0.9205583318972945  Prule test :  0.9499680306905371
130 1334.7179501921523 710.1477271153328 711.482445065525 Accuracy: 0.9394  test :  0.8433  Prule Train :  0.9193534126147064  Prule test :  0.9499680306905371
135 -1485.4336324621509 696.9024243985807 695.4169907661185 Accuracy: 0.9426  test :  0.8427  Prule Train :  0.9183415758441268  Prule test :  0.9469522591645354
140 2396.2764065911674 684.9325968850646 687.3288732916558 Accuracy: 0.9443  test :  0.842  Prule Train :  0.9153118354857799  Prule test :  0.9439364876385337
145 1951.356608049941 671.3795260307324 673.3308826387824 Accuracy: 0.9469  test :  0.844  Prule Train :  0.913477113959623  Prule test :  0.9448628237402397
150 187.08184246062197 656.3381797562713 656.525261598732 Accuracy: 0.9494  test :  0.8433  Prule Train :  0.9134552583487043  Prule test :  0.9478815548065026
155 -1433.787161295961 642.9301113597403 641.4963241984443 Accuracy: 0.9497  test :  0.842  Prule Train :  0.9120346436389862  Prule test :  0.9457909797557016
160 2336.825451253323 631.4326070676785 633.7694325189319 Accuracy: 0.9511  test :  0.8427  Prule Train :  0.9122228876376238  Prule test :  0.9485864210751765
165 1811.4079869442107 620.1951093932568 622.006517380201 Accuracy: 0.9534  test :  0.8427  Prule Train :  0.9136245739698449  Prule test :  0.9485864210751765
170 797.791987595519 608.9575192642544 609.75531125185 Accuracy: 0.9557  test :  0.842  Prule Train :  0.913197136884344  Prule test :  0.9476527730229373
175 -1425.7791788111972 597.0861909882614 595.6604118094501 Accuracy: 0.9566  test :  0.842  Prule Train :  0.9125766122565665  Prule test :  0.9476527730229373
180 2289.346453263226 589.0915043528172 591.3808508060804 Accuracy: 0.9589  test :  0.8413  Prule Train :  0.910302557254945  Prule test :  0.9485864210751765
185 1700.702194576683 581.3442982140862 583.0450004086629 Accuracy: 0.9594  test :  0.8413  Prule Train :  0.9111146023550831  Prule test :  0.9485864210751765
190 889.5238140746475 572.3729174070326 573.2624412211073 Accuracy: 0.9606  test :  0.842  Prule Train :  0.9090513527485783  Prule test :  0.9476527730229373
195 -1314.405190561841 563.6412908393658 562.3268856488039 Accuracy: 0.9614  test :  0.8413  Prule Train :  0.9102704649784602  Prule test :  0.9485864210751765
Resultado | acc=0.8413 | bal_acc=0.6822 | f1=0.9048 | EOdds=0.0392 | EOp=0.0215 | p-rule=94.86 | score=0.6796 | tempo=0.12 min

FAGTB african_american_0:  57%|█████▋    | 34/60 [03:12<02:27,  5.66s/modelo]

----------------------------------------------------------------------------------------------------
Treino 35/120 | config=african_american_0 | lambda=0.001 | n_estimators=100 | learning_rate=0.1 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1810.1111339096487 1811.0564306307724 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1728.234179510548 1675.6652178333607 1677.393452012871 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 589.8912916061739 1557.819757730254 1558.4096490218603 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 181.16001169654135 1461.5578428328495 1461.7390028445457 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2807.228910106345 1380.9656017735151 1383.7728306836214 Accuracy: 0.8651  test :  0.8407  Prule Train :  0.9533025247861231  Prule test :  0.9607345903717943
25 1507.150375563201 1313.013997988195 1314.5211483637581 Accuracy: 0.876  test :  0.8433  Prule Train :  0.9527496355280587  Prule test :  0.958554009114423
30 957.1806607906407 1254.5221615762061 1255.479342236997 Accuracy: 0.8846  test :  0.842  Prule Train :  0.945602375551549  Prule test :  0.9561601091089436
35 -756.1425515029583 1202.0795514245065 1201.3234088730035 Accuracy: 0.8871  test :  0.8413  Prule Train :  0.9405126309991145  Prule test :  0.9550517598343685
40 2825.7815270623987 1158.7945239521198 1161.620305479182 Accuracy: 0.8903  test :  0.8413  Prule Train :  0.9396254058802542  Prule test :  0.9587039654169093
45 2135.210159427889 1116.590138406629 1118.7253485660567 Accuracy: 0.8937  test :  0.8427  Prule Train :  0.935665126292784  Prule test :  0.9605405630518075
50 1025.9900024009419 1077.2295854100855 1078.2555754124865 Accuracy: 0.8974  test :  0.842  Prule Train :  0.9286098624969793  Prule test :  0.9573988222027316
55 -1616.9996431503841 1040.997699192454 1039.3806995493037 Accuracy: 0.9014  test :  0.8413  Prule Train :  0.9271034977869868  Prule test :  0.9562811231535339
60 3144.58508432369 1005.3008775597967 1008.4454626441203 Accuracy: 0.9054  test :  0.842  Prule Train :  0.9273271431612451  Prule test :  0.9572023959118706
65 1674.1231356044486 972.694068896815 974.3681920324195 Accuracy: 0.9103  test :  0.8407  Prule Train :  0.9287289679792232  Prule test :  0.9490055504162812
70 -1270.5894859570012 944.9785344587378 943.7079449727808 Accuracy: 0.9134  test :  0.8393  Prule Train :  0.9277806937039526  Prule test :  0.9508447084597236
75 2436.77411468594 916.314090149797 918.750864264483 Accuracy: 0.9154  test :  0.84  Prule Train :  0.9305431202696386  Prule test :  0.9536168504668949
80 1617.878416148764 887.8396278676005 889.4575062837491 Accuracy: 0.9203  test :  0.8407  Prule Train :  0.9284297156672585  Prule test :  0.9586639932460954
85 1325.444481161665 861.1087641019332 862.4342085830948 Accuracy: 0.9223  test :  0.842  Prule Train :  0.9294364126807018  Prule test :  0.9485598883437657
90 -1141.1721536010843 834.6614415439262 833.5202693903251 Accuracy: 0.9249  test :  0.8427  Prule Train :  0.9330357791669868  Prule test :  0.9494835104356292
95 2093.75423800061 813.4440971941609 815.5378514321615 Accuracy: 0.928  test :  0.8427  Prule Train :  0.928501026736788  Prule test :  0.9534070683956267
Resultado | acc=0.8420 | bal_acc=0.6749 | f1=0.9058 | EOdds=0.0546 | EOp=0.0112 | p-rule=95.43 | score=0.6719 | tempo=0.06 min

FAGTB african_american_0:  58%|█████▊    | 35/60 [03:16<02:06,  5.07s/modelo]

----------------------------------------------------------------------------------------------------
Treino 36/120 | config=african_american_0 | lambda=0.001 | n_estimators=200 | learning_rate=0.1 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1810.1111339096487 1811.0564306307724 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1728.234179510548 1675.6652178333607 1677.393452012871 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 589.8912916061739 1557.819757730254 1558.4096490218603 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 181.16001169654135 1461.5578428328495 1461.7390028445457 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2807.228910106345 1380.9656017735151 1383.7728306836214 Accuracy: 0.8651  test :  0.8407  Prule Train :  0.9533025247861231  Prule test :  0.9607345903717943
25 1507.150375563201 1313.013997988195 1314.5211483637581 Accuracy: 0.876  test :  0.8433  Prule Train :  0.9527496355280587  Prule test :  0.958554009114423
30 957.1806607906407 1254.5221615762061 1255.479342236997 Accuracy: 0.8846  test :  0.842  Prule Train :  0.945602375551549  Prule test :  0.9561601091089436
35 -756.1425515029583 1202.0795514245065 1201.3234088730035 Accuracy: 0.8871  test :  0.8413  Prule Train :  0.9405126309991145  Prule test :  0.9550517598343685
40 2825.7815270623987 1158.7945239521198 1161.620305479182 Accuracy: 0.8903  test :  0.8413  Prule Train :  0.9396254058802542  Prule test :  0.9587039654169093
45 2135.210159427889 1116.590138406629 1118.7253485660567 Accuracy: 0.8937  test :  0.8427  Prule Train :  0.935665126292784  Prule test :  0.9605405630518075
50 1025.9900024009419 1077.2295854100855 1078.2555754124865 Accuracy: 0.8974  test :  0.842  Prule Train :  0.9286098624969793  Prule test :  0.9573988222027316
55 -1616.9996431503841 1040.997699192454 1039.3806995493037 Accuracy: 0.9014  test :  0.8413  Prule Train :  0.9271034977869868  Prule test :  0.9562811231535339
60 3144.58508432369 1005.3008775597967 1008.4454626441203 Accuracy: 0.9054  test :  0.842  Prule Train :  0.9273271431612451  Prule test :  0.9572023959118706
65 1674.1231356044486 972.694068896815 974.3681920324195 Accuracy: 0.9103  test :  0.8407  Prule Train :  0.9287289679792232  Prule test :  0.9490055504162812
70 -1270.5894859570012 944.9785344587378 943.7079449727808 Accuracy: 0.9134  test :  0.8393  Prule Train :  0.9277806937039526  Prule test :  0.9508447084597236
75 2436.77411468594 916.314090149797 918.750864264483 Accuracy: 0.9154  test :  0.84  Prule Train :  0.9305431202696386  Prule test :  0.9536168504668949
80 1617.878416148764 887.8396278676005 889.4575062837491 Accuracy: 0.9203  test :  0.8407  Prule Train :  0.9284297156672585  Prule test :  0.9586639932460954
85 1325.444481161665 861.1087641019332 862.4342085830948 Accuracy: 0.9223  test :  0.842  Prule Train :  0.9294364126807018  Prule test :  0.9485598883437657
90 -1141.1721536010843 834.6614415439262 833.5202693903251 Accuracy: 0.9249  test :  0.8427  Prule Train :  0.9330357791669868  Prule test :  0.9494835104356292
95 2093.75423800061 813.4440971941609 815.5378514321615 Accuracy: 0.928  test :  0.8427  Prule Train :  0.928501026736788  Prule test :  0.9534070683956267
100 -501.01430761398666 797.4843647760479 796.9833504684339 Accuracy: 0.9294  test :  0.842  Prule Train :  0.9269207220961526  Prule test :  0.9543372216330859
105 1340.898474626757 782.8477454412982 784.188643915925 Accuracy: 0.9326  test :  0.844  Prule Train :  0.927743956344021  Prule test :  0.9531960559309788
110 1632.4839536378618 768.4401488611898 770.0726328148276 Accuracy: 0.9337  test :  0.842  Prule Train :  0.9275534559998575  Prule test :  0.9501891283097454
115 1323.8533657380121 754.6536590561107 755.9775124218486 Accuracy: 0.9357  test :  0.8433  Prule Train :  0.9267674938400309  Prule test :  0.9520504194523699
120 2609.6405662538345 739.743932661791 742.3535732280448 Accuracy: 0.9366  test :  0.8433  Prule Train :  0.9243656040579495  Prule test :  0.9520504194523699
125 1923.5306704059622 724.7100631698722 726.6335938402782 Accuracy: 0.9377  test :  0.8433  Prule Train :  0.9205583318972945  Prule test :  0.9499680306905371
130 1334.7179501921523 710.1477271153328 711.482445065525 Accuracy: 0.9394  test :  0.8433  Prule Train :  0.9193534126147064  Prule test :  0.9499680306905371
135 -1485.4336324621509 696.9024243985807 695.4169907661185 Accuracy: 0.9426  test :  0.8427  Prule Train :  0.9183415758441268  Prule test :  0.9469522591645354
140 2396.2764065911674 684.9325968850646 687.3288732916558 Accuracy: 0.9443  test :  0.842  Prule Train :  0.9153118354857799  Prule test :  0.9439364876385337
145 1951.356608049941 671.3795260307324 673.3308826387824 Accuracy: 0.9469  test :  0.844  Prule Train :  0.913477113959623  Prule test :  0.9448628237402397
150 187.08184246062197 656.3381797562713 656.525261598732 Accuracy: 0.9494  test :  0.8433  Prule Train :  0.9134552583487043  Prule test :  0.9478815548065026
155 -1433.787161295961 642.9301113597403 641.4963241984443 Accuracy: 0.9497  test :  0.842  Prule Train :  0.9120346436389862  Prule test :  0.9457909797557016
160 2336.825451253323 631.4326070676785 633.7694325189319 Accuracy: 0.9511  test :  0.8427  Prule Train :  0.9122228876376238  Prule test :  0.9485864210751765
165 1811.4079869442107 620.1951093932568 622.006517380201 Accuracy: 0.9534  test :  0.8427  Prule Train :  0.9136245739698449  Prule test :  0.9485864210751765
170 797.791987595519 608.9575192642544 609.75531125185 Accuracy: 0.9557  test :  0.842  Prule Train :  0.913197136884344  Prule test :  0.9476527730229373
175 -1425.7791788111972 597.0861909882614 595.6604118094501 Accuracy: 0.9566  test :  0.842  Prule Train :  0.9125766122565665  Prule test :  0.9476527730229373
180 2289.346453263226 589.0915043528172 591.3808508060804 Accuracy: 0.9589  test :  0.8413  Prule Train :  0.910302557254945  Prule test :  0.9485864210751765
185 1700.702194576683 581.3442982140862 583.0450004086629 Accuracy: 0.9594  test :  0.8413  Prule Train :  0.9111146023550831  Prule test :  0.9485864210751765
190 889.5238140746475 572.3729174070326 573.2624412211073 Accuracy: 0.9606  test :  0.842  Prule Train :  0.9090513527485783  Prule test :  0.9476527730229373
195 -1314.405190561841 563.6412908393658 562.3268856488039 Accuracy: 0.9614  test :  0.8413  Prule Train :  0.9102704649784602  Prule test :  0.9485864210751765
Resultado | acc=0.8413 | bal_acc=0.6822 | f1=0.9048 | EOdds=0.0392 | EOp=0.0215 | p-rule=94.86 | score=0.6796 | tempo=0.12 min

FAGTB african_american_0:  60%|██████    | 36/60 [03:23<02:15,  5.65s/modelo]

----------------------------------------------------------------------------------------------------
Treino 37/120 | config=african_american_0 | lambda=0.005 | n_estimators=100 | learning_rate=0.03 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1830.3577651691924 1835.0842487748102 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1699.3096128774632 1787.7736313246703 1796.2701793890576 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 582.9445166473379 1747.579794766762 1750.4945173499987 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 386.56132344221226 1709.3381534277996 1711.2709600450112 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2697.523954248808 1672.140593155174 1685.6282129264182 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1503.781042472459 1636.96959202282 1644.4884972351824 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 822.3079137470122 1602.4034488468924 1606.5149884156272 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 95.25516635078156 1569.9068482468003 1570.3831240785544 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2839.413811478659 1539.3987658475305 1553.5958349049238 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 1634.7383358339252 1510.2132914703432 1518.3869831495124 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 986.9350697997918 1482.1161784940214 1487.0508538430201 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -478.55326439754356 1455.468870285456 1453.076103963468 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 3027.0609540199757 1430.6009090285247 1445.7362137986245 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 1788.0738309782332 1407.1034538882473 1416.0438230431384 Accuracy: 0.7837  test :  0.7827  Prule Train :  0.9997913004427056  Prule test :  0.9982332155477032
70 1181.964685944219 1384.4473945434083 1390.3572179731295 Accuracy: 0.8646  test :  0.84  Prule Train :  0.9525324904365382  Prule test :  0.9598316443282119
75 -1134.8842408217786 1362.9973983856432 1357.3229771815343 Accuracy: 0.868  test :  0.84  Prule Train :  0.9487082525365191  Prule test :  0.9598316443282119
80 3113.9679776741937 1342.716834261976 1358.286674150347 Accuracy: 0.872  test :  0.842  Prule Train :  0.9524180461526975  Prule test :  0.9587427331531974
85 2393.385371041655 1322.8557486194568 1334.822675474665 Accuracy: 0.8757  test :  0.8427  Prule Train :  0.9557760913213522  Prule test :  0.9596463549563579
90 1158.9253503038842 1303.8198155504772 1309.6144423019969 Accuracy: 0.8789  test :  0.8413  Prule Train :  0.9480996262532382  Prule test :  0.9556492999958944
95 -1842.861203980016 1285.6029698664615 1276.3886638465615 Accuracy: 0.8811  test :  0.8413  Prule Train :  0.9443658749636039  Prule test :  0.9554512516469038
Resultado | acc=0.8413 | bal_acc=0.6515 | f1=0.9069 | EOdds=0.0715 | EOp=0.0095 | p-rule=95.55 | score=0.6476 | tempo=0.06 min

FAGTB african_american_0:  62%|██████▏   | 37/60 [03:27<01:56,  5.05s/modelo]

----------------------------------------------------------------------------------------------------
Treino 38/120 | config=african_american_0 | lambda=0.005 | n_estimators=200 | learning_rate=0.03 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1830.3577651691924 1835.0842487748102 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1699.3096128774632 1787.7736313246703 1796.2701793890576 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 582.9445166473379 1747.579794766762 1750.4945173499987 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 386.56132344221226 1709.3381534277996 1711.2709600450112 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2697.523954248808 1672.140593155174 1685.6282129264182 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1503.781042472459 1636.96959202282 1644.4884972351824 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 822.3079137470122 1602.4034488468924 1606.5149884156272 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 95.25516635078156 1569.9068482468003 1570.3831240785544 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2839.413811478659 1539.3987658475305 1553.5958349049238 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 1634.7383358339252 1510.2132914703432 1518.3869831495124 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 986.9350697997918 1482.1161784940214 1487.0508538430201 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -478.55326439754356 1455.468870285456 1453.076103963468 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 3027.0609540199757 1430.6009090285247 1445.7362137986245 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 1788.0738309782332 1407.1034538882473 1416.0438230431384 Accuracy: 0.7837  test :  0.7827  Prule Train :  0.9997913004427056  Prule test :  0.9982332155477032
70 1181.964685944219 1384.4473945434083 1390.3572179731295 Accuracy: 0.8646  test :  0.84  Prule Train :  0.9525324904365382  Prule test :  0.9598316443282119
75 -1134.8842408217786 1362.9973983856432 1357.3229771815343 Accuracy: 0.868  test :  0.84  Prule Train :  0.9487082525365191  Prule test :  0.9598316443282119
80 3113.9679776741937 1342.716834261976 1358.286674150347 Accuracy: 0.872  test :  0.842  Prule Train :  0.9524180461526975  Prule test :  0.9587427331531974
85 2393.385371041655 1322.8557486194568 1334.822675474665 Accuracy: 0.8757  test :  0.8427  Prule Train :  0.9557760913213522  Prule test :  0.9596463549563579
90 1158.9253503038842 1303.8198155504772 1309.6144423019969 Accuracy: 0.8789  test :  0.8413  Prule Train :  0.9480996262532382  Prule test :  0.9556492999958944
95 -1842.861203980016 1285.6029698664615 1276.3886638465615 Accuracy: 0.8811  test :  0.8413  Prule Train :  0.9443658749636039  Prule test :  0.9554512516469038
100 3174.0591467413906 1268.9020491327549 1284.772344866462 Accuracy: 0.8823  test :  0.8413  Prule Train :  0.9459191083105836  Prule test :  0.9554512516469038
105 2611.205517439375 1253.0489473964908 1266.1049749836875 Accuracy: 0.8831  test :  0.8413  Prule Train :  0.9470873904534126  Prule test :  0.9552520748172922
110 1593.8810676746284 1237.5221696065164 1245.4915749448896 Accuracy: 0.8849  test :  0.8413  Prule Train :  0.9442742823274597  Prule test :  0.9552520748172922
115 -2439.6821709554015 1222.2714681909165 1210.0730573361393 Accuracy: 0.8854  test :  0.8407  Prule Train :  0.9450533865207992  Prule test :  0.9523308146496554
120 3596.3049778015516 1208.831168096939 1226.8126929859468 Accuracy: 0.886  test :  0.8407  Prule Train :  0.9441136833531888  Prule test :  0.9523308146496554
125 2517.837642754627 1195.8348218493293 1208.4240100631025 Accuracy: 0.8871  test :  0.84  Prule Train :  0.9422319481377514  Prule test :  0.9494095544820182
130 2005.1351996981564 1183.2711786169668 1193.2968546154575 Accuracy: 0.8871  test :  0.8393  Prule Train :  0.9422319481377514  Prule test :  0.9503120350471151
135 -2824.0913932999315 1170.3453578859067 1156.224900919407 Accuracy: 0.8874  test :  0.84  Prule Train :  0.9426213001824364  Prule test :  0.951216232987217
140 3198.2214717690595 1158.1002155463389 1174.0913229051841 Accuracy: 0.8883  test :  0.8393  Prule Train :  0.9420684831595761  Prule test :  0.9521221532091098
145 2850.9946308008302 1145.6263645583215 1159.8813377123256 Accuracy: 0.8897  test :  0.84  Prule Train :  0.9405704695472356  Prule test :  0.951216232987217
150 668.4905014497209 1132.8679681689428 1136.2104206761915 Accuracy: 0.8909  test :  0.8413  Prule Train :  0.9386795589031468  Prule test :  0.953029800638289
155 -2588.6334004058863 1120.3333607617715 1107.3901937597418 Accuracy: 0.8923  test :  0.842  Prule Train :  0.937174218800835  Prule test :  0.9557631557070413
160 -2526.4903473971826 1108.2351970718178 1095.602745334832 Accuracy: 0.8946  test :  0.8427  Prule Train :  0.9351035363098089  Prule test :  0.95667776159767
165 3128.849635145664 1096.6523077528382 1112.2965559285667 Accuracy: 0.8951  test :  0.8427  Prule Train :  0.9358818164066127  Prule test :  0.95667776159767
170 2716.1046645922006 1085.8713868348175 1099.4519101577785 Accuracy: 0.8957  test :  0.8427  Prule Train :  0.9349300793769566  Prule test :  0.9585122347742715
175 -726.5265625500225 1074.6711983955568 1071.0385655828065 Accuracy: 0.896  test :  0.84  Prule Train :  0.9335887162788549  Prule test :  0.9544438875663033
180 1820.0093686419584 1064.4104379313367 1073.5104847745465 Accuracy: 0.8966  test :  0.84  Prule Train :  0.9326356277968216  Prule test :  0.9524038461538463
185 269.9093190278232 1054.4869121469626 1055.8364587421017 Accuracy: 0.8971  test :  0.84  Prule Train :  0.931681745074387  Prule test :  0.9524038461538463
190 -2089.8505331056026 1043.9201401371388 1033.470887471611 Accuracy: 0.8986  test :  0.842  Prule Train :  0.9318924182040433  Prule test :  0.955159112825458
195 3276.229973171471 1034.3777885724116 1050.758938438269 Accuracy: 0.9006  test :  0.842  Prule Train :  0.931146100248267  Prule test :  0.955159112825458
Resultado | acc=0.8420 | bal_acc=0.6662 | f1=0.9064 | EOdds=0.0302 | EOp=0.0201 | p-rule=95.52 | score=0.6641 | tempo=0.12 min

FAGTB african_american_0:  63%|██████▎   | 38/60 [03:34<02:04,  5.67s/modelo]

----------------------------------------------------------------------------------------------------
Treino 39/120 | config=african_american_0 | lambda=0.005 | n_estimators=100 | learning_rate=0.03 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1830.3577651691924 1835.0842487748102 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1699.3096128774632 1787.7736313246703 1796.2701793890576 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 582.9445166473379 1747.579794766762 1750.4945173499987 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 386.56132344221226 1709.3381534277996 1711.2709600450112 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2697.523954248808 1672.140593155174 1685.6282129264182 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1503.781042472459 1636.96959202282 1644.4884972351824 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 822.3079137470122 1602.4034488468924 1606.5149884156272 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 95.25516635078156 1569.9068482468003 1570.3831240785544 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2839.413811478659 1539.3987658475305 1553.5958349049238 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 1634.7383358339252 1510.2132914703432 1518.3869831495124 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 986.9350697997918 1482.1161784940214 1487.0508538430201 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -478.55326439754356 1455.468870285456 1453.076103963468 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 3027.0609540199757 1430.6009090285247 1445.7362137986245 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 1788.0738309782332 1407.1034538882473 1416.0438230431384 Accuracy: 0.7837  test :  0.7827  Prule Train :  0.9997913004427056  Prule test :  0.9982332155477032
70 1181.964685944219 1384.4473945434083 1390.3572179731295 Accuracy: 0.8646  test :  0.84  Prule Train :  0.9525324904365382  Prule test :  0.9598316443282119
75 -1134.8842408217786 1362.9973983856432 1357.3229771815343 Accuracy: 0.868  test :  0.84  Prule Train :  0.9487082525365191  Prule test :  0.9598316443282119
80 3113.9679776741937 1342.716834261976 1358.286674150347 Accuracy: 0.872  test :  0.842  Prule Train :  0.9524180461526975  Prule test :  0.9587427331531974
85 2393.385371041655 1322.8557486194568 1334.822675474665 Accuracy: 0.8757  test :  0.8427  Prule Train :  0.9557760913213522  Prule test :  0.9596463549563579
90 1158.9253503038842 1303.8198155504772 1309.6144423019969 Accuracy: 0.8789  test :  0.8413  Prule Train :  0.9480996262532382  Prule test :  0.9556492999958944
95 -1842.861203980016 1285.6029698664615 1276.3886638465615 Accuracy: 0.8811  test :  0.8413  Prule Train :  0.9443658749636039  Prule test :  0.9554512516469038
Resultado | acc=0.8413 | bal_acc=0.6515 | f1=0.9069 | EOdds=0.0715 | EOp=0.0095 | p-rule=95.55 | score=0.6476 | tempo=0.06 min

FAGTB african_american_0:  65%|██████▌   | 39/60 [03:37<01:46,  5.06s/modelo]

----------------------------------------------------------------------------------------------------
Treino 40/120 | config=african_american_0 | lambda=0.005 | n_estimators=200 | learning_rate=0.03 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1830.3577651691924 1835.0842487748102 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1699.3096128774632 1787.7736313246703 1796.2701793890576 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 582.9445166473379 1747.579794766762 1750.4945173499987 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 386.56132344221226 1709.3381534277996 1711.2709600450112 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2697.523954248808 1672.140593155174 1685.6282129264182 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1503.781042472459 1636.96959202282 1644.4884972351824 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 822.3079137470122 1602.4034488468924 1606.5149884156272 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 95.25516635078156 1569.9068482468003 1570.3831240785544 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2839.413811478659 1539.3987658475305 1553.5958349049238 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 1634.7383358339252 1510.2132914703432 1518.3869831495124 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 986.9350697997918 1482.1161784940214 1487.0508538430201 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -478.55326439754356 1455.468870285456 1453.076103963468 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 3027.0609540199757 1430.6009090285247 1445.7362137986245 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 1788.0738309782332 1407.1034538882473 1416.0438230431384 Accuracy: 0.7837  test :  0.7827  Prule Train :  0.9997913004427056  Prule test :  0.9982332155477032
70 1181.964685944219 1384.4473945434083 1390.3572179731295 Accuracy: 0.8646  test :  0.84  Prule Train :  0.9525324904365382  Prule test :  0.9598316443282119
75 -1134.8842408217786 1362.9973983856432 1357.3229771815343 Accuracy: 0.868  test :  0.84  Prule Train :  0.9487082525365191  Prule test :  0.9598316443282119
80 3113.9679776741937 1342.716834261976 1358.286674150347 Accuracy: 0.872  test :  0.842  Prule Train :  0.9524180461526975  Prule test :  0.9587427331531974
85 2393.385371041655 1322.8557486194568 1334.822675474665 Accuracy: 0.8757  test :  0.8427  Prule Train :  0.9557760913213522  Prule test :  0.9596463549563579
90 1158.9253503038842 1303.8198155504772 1309.6144423019969 Accuracy: 0.8789  test :  0.8413  Prule Train :  0.9480996262532382  Prule test :  0.9556492999958944
95 -1842.861203980016 1285.6029698664615 1276.3886638465615 Accuracy: 0.8811  test :  0.8413  Prule Train :  0.9443658749636039  Prule test :  0.9554512516469038
100 3174.0591467413906 1268.9020491327549 1284.772344866462 Accuracy: 0.8823  test :  0.8413  Prule Train :  0.9459191083105836  Prule test :  0.9554512516469038
105 2611.205517439375 1253.0489473964908 1266.1049749836875 Accuracy: 0.8831  test :  0.8413  Prule Train :  0.9470873904534126  Prule test :  0.9552520748172922
110 1593.8810676746284 1237.5221696065164 1245.4915749448896 Accuracy: 0.8849  test :  0.8413  Prule Train :  0.9442742823274597  Prule test :  0.9552520748172922
115 -2439.6821709554015 1222.2714681909165 1210.0730573361393 Accuracy: 0.8854  test :  0.8407  Prule Train :  0.9450533865207992  Prule test :  0.9523308146496554
120 3596.3049778015516 1208.831168096939 1226.8126929859468 Accuracy: 0.886  test :  0.8407  Prule Train :  0.9441136833531888  Prule test :  0.9523308146496554
125 2517.837642754627 1195.8348218493293 1208.4240100631025 Accuracy: 0.8871  test :  0.84  Prule Train :  0.9422319481377514  Prule test :  0.9494095544820182
130 2005.1351996981564 1183.2711786169668 1193.2968546154575 Accuracy: 0.8871  test :  0.8393  Prule Train :  0.9422319481377514  Prule test :  0.9503120350471151
135 -2824.0913932999315 1170.3453578859067 1156.224900919407 Accuracy: 0.8874  test :  0.84  Prule Train :  0.9426213001824364  Prule test :  0.951216232987217
140 3198.2214717690595 1158.1002155463389 1174.0913229051841 Accuracy: 0.8883  test :  0.8393  Prule Train :  0.9420684831595761  Prule test :  0.9521221532091098
145 2850.9946308008302 1145.6263645583215 1159.8813377123256 Accuracy: 0.8897  test :  0.84  Prule Train :  0.9405704695472356  Prule test :  0.951216232987217
150 668.4905014497209 1132.8679681689428 1136.2104206761915 Accuracy: 0.8909  test :  0.8413  Prule Train :  0.9386795589031468  Prule test :  0.953029800638289
155 -2588.6334004058863 1120.3333607617715 1107.3901937597418 Accuracy: 0.8923  test :  0.842  Prule Train :  0.937174218800835  Prule test :  0.9557631557070413
160 -2526.4903473971826 1108.2351970718178 1095.602745334832 Accuracy: 0.8946  test :  0.8427  Prule Train :  0.9351035363098089  Prule test :  0.95667776159767
165 3128.849635145664 1096.6523077528382 1112.2965559285667 Accuracy: 0.8951  test :  0.8427  Prule Train :  0.9358818164066127  Prule test :  0.95667776159767
170 2716.1046645922006 1085.8713868348175 1099.4519101577785 Accuracy: 0.8957  test :  0.8427  Prule Train :  0.9349300793769566  Prule test :  0.9585122347742715
175 -726.5265625500225 1074.6711983955568 1071.0385655828065 Accuracy: 0.896  test :  0.84  Prule Train :  0.9335887162788549  Prule test :  0.9544438875663033
180 1820.0093686419584 1064.4104379313367 1073.5104847745465 Accuracy: 0.8966  test :  0.84  Prule Train :  0.9326356277968216  Prule test :  0.9524038461538463
185 269.9093190278232 1054.4869121469626 1055.8364587421017 Accuracy: 0.8971  test :  0.84  Prule Train :  0.931681745074387  Prule test :  0.9524038461538463
190 -2089.8505331056026 1043.9201401371388 1033.470887471611 Accuracy: 0.8986  test :  0.842  Prule Train :  0.9318924182040433  Prule test :  0.955159112825458
195 3276.229973171471 1034.3777885724116 1050.758938438269 Accuracy: 0.9006  test :  0.842  Prule Train :  0.931146100248267  Prule test :  0.955159112825458
Resultado | acc=0.8420 | bal_acc=0.6662 | f1=0.9064 | EOdds=0.0302 | EOp=0.0201 | p-rule=95.52 | score=0.6641 | tempo=0.11 min

FAGTB african_american_0:  67%|██████▋   | 40/60 [03:44<01:52,  5.64s/modelo]

----------------------------------------------------------------------------------------------------
Treino 41/120 | config=african_american_0 | lambda=0.005 | n_estimators=100 | learning_rate=0.05 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1824.553545196291 1829.2800288019087 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1707.2230942443693 1755.1206898458217 1763.6568053170436 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 585.8378080248099 1691.8033870747804 1694.7325761149045 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 330.9647057739646 1630.8281556950315 1632.4829792239016 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2745.054805662328 1575.7599843545422 1589.4852583828538 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1513.8723651340201 1524.8645569645382 1532.4339187902083 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 866.5412940963515 1477.2583205539966 1481.591027024478 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -249.66945183461837 1434.232009159397 1432.983661900224 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2868.431437253795 1395.4651242740756 1409.8072814603443 Accuracy: 0.85  test :  0.8313  Prule Train :  0.963119020020087  Prule test :  0.9616338630313785
45 1923.0022149518034 1359.0767942684602 1368.6918053432191 Accuracy: 0.8689  test :  0.8407  Prule Train :  0.9498623988291428  Prule test :  0.9607345903717943
50 1230.624103233613 1325.8241699485839 1331.9772904647516 Accuracy: 0.876  test :  0.8433  Prule Train :  0.9544577794712538  Prule test :  0.9605516817063166
55 2.5441201735299153 1293.60872621415 1293.6214468150174 Accuracy: 0.8803  test :  0.8433  Prule Train :  0.94491272582977  Prule test :  0.9545473242565093
60 3136.788476713915 1265.4213368481005 1281.10527923167 Accuracy: 0.8829  test :  0.8413  Prule Train :  0.9466976425561068  Prule test :  0.9534411704100557
65 1782.6945041901529 1238.7139891751542 1247.627461696105 Accuracy: 0.8849  test :  0.8413  Prule Train :  0.9442742823274597  Prule test :  0.9552520748172922
70 1349.780186359953 1213.6304446501258 1220.3793455819257 Accuracy: 0.8854  test :  0.8413  Prule Train :  0.9433350328926915  Prule test :  0.9532360720780294
75 -1633.0713272448822 1191.113991419992 1182.9486347837678 Accuracy: 0.8871  test :  0.842  Prule Train :  0.9405126309991145  Prule test :  0.9541430521656393
80 3194.089921698802 1168.9613312410017 1184.931780849496 Accuracy: 0.888  test :  0.8413  Prule Train :  0.9399585281480227  Prule test :  0.9550517598343685
85 2450.436519894767 1148.526795292726 1160.7789778922 Accuracy: 0.89  test :  0.8427  Prule Train :  0.9409601010590614  Prule test :  0.9568743776966478
90 1579.8637656956626 1128.0736424139104 1135.9729612423885 Accuracy: 0.8917  test :  0.8427  Prule Train :  0.9415756454109314  Prule test :  0.9587039654169093
95 -2230.907571858633 1108.5462024700546 1097.3916646107616 Accuracy: 0.894  test :  0.8427  Prule Train :  0.937782916070009  Prule test :  0.95667776159767
Resultado | acc=0.8427 | bal_acc=0.6622 | f1=0.9071 | EOdds=0.0474 | EOp=0.0161 | p-rule=95.46 | score=0.6593 | tempo=0.06 min

FAGTB african_american_0:  68%|██████▊   | 41/60 [03:48<01:36,  5.05s/modelo]

----------------------------------------------------------------------------------------------------
Treino 42/120 | config=african_american_0 | lambda=0.005 | n_estimators=200 | learning_rate=0.05 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1824.553545196291 1829.2800288019087 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1707.2230942443693 1755.1206898458217 1763.6568053170436 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 585.8378080248099 1691.8033870747804 1694.7325761149045 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 330.9647057739646 1630.8281556950315 1632.4829792239016 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2745.054805662328 1575.7599843545422 1589.4852583828538 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1513.8723651340201 1524.8645569645382 1532.4339187902083 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 866.5412940963515 1477.2583205539966 1481.591027024478 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -249.66945183461837 1434.232009159397 1432.983661900224 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2868.431437253795 1395.4651242740756 1409.8072814603443 Accuracy: 0.85  test :  0.8313  Prule Train :  0.963119020020087  Prule test :  0.9616338630313785
45 1923.0022149518034 1359.0767942684602 1368.6918053432191 Accuracy: 0.8689  test :  0.8407  Prule Train :  0.9498623988291428  Prule test :  0.9607345903717943
50 1230.624103233613 1325.8241699485839 1331.9772904647516 Accuracy: 0.876  test :  0.8433  Prule Train :  0.9544577794712538  Prule test :  0.9605516817063166
55 2.5441201735299153 1293.60872621415 1293.6214468150174 Accuracy: 0.8803  test :  0.8433  Prule Train :  0.94491272582977  Prule test :  0.9545473242565093
60 3136.788476713915 1265.4213368481005 1281.10527923167 Accuracy: 0.8829  test :  0.8413  Prule Train :  0.9466976425561068  Prule test :  0.9534411704100557
65 1782.6945041901529 1238.7139891751542 1247.627461696105 Accuracy: 0.8849  test :  0.8413  Prule Train :  0.9442742823274597  Prule test :  0.9552520748172922
70 1349.780186359953 1213.6304446501258 1220.3793455819257 Accuracy: 0.8854  test :  0.8413  Prule Train :  0.9433350328926915  Prule test :  0.9532360720780294
75 -1633.0713272448822 1191.113991419992 1182.9486347837678 Accuracy: 0.8871  test :  0.842  Prule Train :  0.9405126309991145  Prule test :  0.9541430521656393
80 3194.089921698802 1168.9613312410017 1184.931780849496 Accuracy: 0.888  test :  0.8413  Prule Train :  0.9399585281480227  Prule test :  0.9550517598343685
85 2450.436519894767 1148.526795292726 1160.7789778922 Accuracy: 0.89  test :  0.8427  Prule Train :  0.9409601010590614  Prule test :  0.9568743776966478
90 1579.8637656956626 1128.0736424139104 1135.9729612423885 Accuracy: 0.8917  test :  0.8427  Prule Train :  0.9415756454109314  Prule test :  0.9587039654169093
95 -2230.907571858633 1108.5462024700546 1097.3916646107616 Accuracy: 0.894  test :  0.8427  Prule Train :  0.937782916070009  Prule test :  0.95667776159767
100 3399.735578616072 1089.9642101169088 1106.962888009989 Accuracy: 0.8949  test :  0.842  Prule Train :  0.9337638464297089  Prule test :  0.9517012327169748
105 2008.9811630936902 1071.9378671197649 1081.9827729352332 Accuracy: 0.8966  test :  0.842  Prule Train :  0.934366706875754  Prule test :  0.9514889529298752
110 -1622.8291751835418 1054.2162106234655 1046.1020647475477 Accuracy: 0.8983  test :  0.8413  Prule Train :  0.933237140308234  Prule test :  0.9524038461538463
115 2695.559636150763 1038.257238984135 1051.735037164889 Accuracy: 0.9003  test :  0.8413  Prule Train :  0.9359716149763619  Prule test :  0.9524038461538463
120 2398.388279721911 1022.4772180393375 1034.469159437947 Accuracy: 0.9014  test :  0.8413  Prule Train :  0.9323158817812424  Prule test :  0.9524038461538463
125 -27.58426068779309 1006.1964432505139 1006.0585219470747 Accuracy: 0.9037  test :  0.842  Prule Train :  0.9319590333208755  Prule test :  0.953320500481232
130 3059.028369643072 989.2572593427672 1004.5524011909824 Accuracy: 0.9054  test :  0.8427  Prule Train :  0.9308168667144847  Prule test :  0.9542389210019269
135 2074.5836026608868 972.5515517087605 982.9244697220648 Accuracy: 0.9077  test :  0.8427  Prule Train :  0.9304547220589222  Prule test :  0.9560810810810811
140 1652.3899962547537 957.3089230294852 965.570873010759 Accuracy: 0.91  test :  0.8433  Prule Train :  0.9300907406595446  Prule test :  0.955159112825458
145 2126.1225555802857 941.6822301265377 952.312842904439 Accuracy: 0.912  test :  0.8427  Prule Train :  0.9293311241326562  Prule test :  0.9597868217054263
150 1665.9792778648646 927.9708616852274 936.3007580745518 Accuracy: 0.9131  test :  0.8427  Prule Train :  0.9291470864781853  Prule test :  0.9597868217054263
155 2762.9288175680467 914.3008579610504 928.1155020488907 Accuracy: 0.9143  test :  0.842  Prule Train :  0.9307259260473921  Prule test :  0.9607177497575169
160 2386.2643613748833 901.1582218573506 913.089543664225 Accuracy: 0.9183  test :  0.8427  Prule Train :  0.9345181015608374  Prule test :  0.9616504854368931
165 -1952.0732166301464 886.6883726716553 876.9280065885046 Accuracy: 0.9197  test :  0.8427  Prule Train :  0.934738948049756  Prule test :  0.9616504854368931
170 2884.521820866348 874.3022141266492 888.724823230981 Accuracy: 0.9223  test :  0.8433  Prule Train :  0.934781550759227  Prule test :  0.9586639932460954
175 2278.3010619912347 862.5789822025356 873.9704875124918 Accuracy: 0.9226  test :  0.8433  Prule Train :  0.9333987378143168  Prule test :  0.9526910088644998
180 991.3552111456074 850.5069060519644 855.4636821076924 Accuracy: 0.9231  test :  0.844  Prule Train :  0.9342006267643292  Prule test :  0.9536168504668949
185 -2024.086357470961 839.0349050582929 828.9144732709382 Accuracy: 0.9246  test :  0.8433  Prule Train :  0.9344221621969525  Prule test :  0.9524787265568773
190 2895.1870342253414 828.773689890402 843.2496250615286 Accuracy: 0.9254  test :  0.8433  Prule Train :  0.9338394275555888  Prule test :  0.9524787265568773
195 2100.7888296503024 818.7187587772256 829.222702925477 Accuracy: 0.9266  test :  0.8447  Prule Train :  0.9318669148537915  Prule test :  0.9524787265568773
Resultado | acc=0.8447 | bal_acc=0.6778 | f1=0.9074 | EOdds=0.0356 | EOp=0.0193 | p-rule=95.25 | score=0.6754 | tempo=0.11 min

FAGTB african_american_0:  70%|███████   | 42/60 [03:55<01:41,  5.64s/modelo]

----------------------------------------------------------------------------------------------------
Treino 43/120 | config=african_american_0 | lambda=0.005 | n_estimators=100 | learning_rate=0.05 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1824.553545196291 1829.2800288019087 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1707.2230942443693 1755.1206898458217 1763.6568053170436 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 585.8378080248099 1691.8033870747804 1694.7325761149045 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 330.9647057739646 1630.8281556950315 1632.4829792239016 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2745.054805662328 1575.7599843545422 1589.4852583828538 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1513.8723651340201 1524.8645569645382 1532.4339187902083 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 866.5412940963515 1477.2583205539966 1481.591027024478 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -249.66945183461837 1434.232009159397 1432.983661900224 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2868.431437253795 1395.4651242740756 1409.8072814603443 Accuracy: 0.85  test :  0.8313  Prule Train :  0.963119020020087  Prule test :  0.9616338630313785
45 1923.0022149518034 1359.0767942684602 1368.6918053432191 Accuracy: 0.8689  test :  0.8407  Prule Train :  0.9498623988291428  Prule test :  0.9607345903717943
50 1230.624103233613 1325.8241699485839 1331.9772904647516 Accuracy: 0.876  test :  0.8433  Prule Train :  0.9544577794712538  Prule test :  0.9605516817063166
55 2.5441201735299153 1293.60872621415 1293.6214468150174 Accuracy: 0.8803  test :  0.8433  Prule Train :  0.94491272582977  Prule test :  0.9545473242565093
60 3136.788476713915 1265.4213368481005 1281.10527923167 Accuracy: 0.8829  test :  0.8413  Prule Train :  0.9466976425561068  Prule test :  0.9534411704100557
65 1782.6945041901529 1238.7139891751542 1247.627461696105 Accuracy: 0.8849  test :  0.8413  Prule Train :  0.9442742823274597  Prule test :  0.9552520748172922
70 1349.780186359953 1213.6304446501258 1220.3793455819257 Accuracy: 0.8854  test :  0.8413  Prule Train :  0.9433350328926915  Prule test :  0.9532360720780294
75 -1633.0713272448822 1191.113991419992 1182.9486347837678 Accuracy: 0.8871  test :  0.842  Prule Train :  0.9405126309991145  Prule test :  0.9541430521656393
80 3194.089921698802 1168.9613312410017 1184.931780849496 Accuracy: 0.888  test :  0.8413  Prule Train :  0.9399585281480227  Prule test :  0.9550517598343685
85 2450.436519894767 1148.526795292726 1160.7789778922 Accuracy: 0.89  test :  0.8427  Prule Train :  0.9409601010590614  Prule test :  0.9568743776966478
90 1579.8637656956626 1128.0736424139104 1135.9729612423885 Accuracy: 0.8917  test :  0.8427  Prule Train :  0.9415756454109314  Prule test :  0.9587039654169093
95 -2230.907571858633 1108.5462024700546 1097.3916646107616 Accuracy: 0.894  test :  0.8427  Prule Train :  0.937782916070009  Prule test :  0.95667776159767
Resultado | acc=0.8427 | bal_acc=0.6622 | f1=0.9071 | EOdds=0.0474 | EOp=0.0161 | p-rule=95.46 | score=0.6593 | tempo=0.06 min

FAGTB african_american_0:  72%|███████▏  | 43/60 [03:59<01:25,  5.04s/modelo]

----------------------------------------------------------------------------------------------------
Treino 44/120 | config=african_american_0 | lambda=0.005 | n_estimators=200 | learning_rate=0.05 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1824.553545196291 1829.2800288019087 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1707.2230942443693 1755.1206898458217 1763.6568053170436 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 585.8378080248099 1691.8033870747804 1694.7325761149045 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 330.9647057739646 1630.8281556950315 1632.4829792239016 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2745.054805662328 1575.7599843545422 1589.4852583828538 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1513.8723651340201 1524.8645569645382 1532.4339187902083 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 866.5412940963515 1477.2583205539966 1481.591027024478 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -249.66945183461837 1434.232009159397 1432.983661900224 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2868.431437253795 1395.4651242740756 1409.8072814603443 Accuracy: 0.85  test :  0.8313  Prule Train :  0.963119020020087  Prule test :  0.9616338630313785
45 1923.0022149518034 1359.0767942684602 1368.6918053432191 Accuracy: 0.8689  test :  0.8407  Prule Train :  0.9498623988291428  Prule test :  0.9607345903717943
50 1230.624103233613 1325.8241699485839 1331.9772904647516 Accuracy: 0.876  test :  0.8433  Prule Train :  0.9544577794712538  Prule test :  0.9605516817063166
55 2.5441201735299153 1293.60872621415 1293.6214468150174 Accuracy: 0.8803  test :  0.8433  Prule Train :  0.94491272582977  Prule test :  0.9545473242565093
60 3136.788476713915 1265.4213368481005 1281.10527923167 Accuracy: 0.8829  test :  0.8413  Prule Train :  0.9466976425561068  Prule test :  0.9534411704100557
65 1782.6945041901529 1238.7139891751542 1247.627461696105 Accuracy: 0.8849  test :  0.8413  Prule Train :  0.9442742823274597  Prule test :  0.9552520748172922
70 1349.780186359953 1213.6304446501258 1220.3793455819257 Accuracy: 0.8854  test :  0.8413  Prule Train :  0.9433350328926915  Prule test :  0.9532360720780294
75 -1633.0713272448822 1191.113991419992 1182.9486347837678 Accuracy: 0.8871  test :  0.842  Prule Train :  0.9405126309991145  Prule test :  0.9541430521656393
80 3194.089921698802 1168.9613312410017 1184.931780849496 Accuracy: 0.888  test :  0.8413  Prule Train :  0.9399585281480227  Prule test :  0.9550517598343685
85 2450.436519894767 1148.526795292726 1160.7789778922 Accuracy: 0.89  test :  0.8427  Prule Train :  0.9409601010590614  Prule test :  0.9568743776966478
90 1579.8637656956626 1128.0736424139104 1135.9729612423885 Accuracy: 0.8917  test :  0.8427  Prule Train :  0.9415756454109314  Prule test :  0.9587039654169093
95 -2230.907571858633 1108.5462024700546 1097.3916646107616 Accuracy: 0.894  test :  0.8427  Prule Train :  0.937782916070009  Prule test :  0.95667776159767
100 3399.735578616072 1089.9642101169088 1106.962888009989 Accuracy: 0.8949  test :  0.842  Prule Train :  0.9337638464297089  Prule test :  0.9517012327169748
105 2008.9811630936902 1071.9378671197649 1081.9827729352332 Accuracy: 0.8966  test :  0.842  Prule Train :  0.934366706875754  Prule test :  0.9514889529298752
110 -1622.8291751835418 1054.2162106234655 1046.1020647475477 Accuracy: 0.8983  test :  0.8413  Prule Train :  0.933237140308234  Prule test :  0.9524038461538463
115 2695.559636150763 1038.257238984135 1051.735037164889 Accuracy: 0.9003  test :  0.8413  Prule Train :  0.9359716149763619  Prule test :  0.9524038461538463
120 2398.388279721911 1022.4772180393375 1034.469159437947 Accuracy: 0.9014  test :  0.8413  Prule Train :  0.9323158817812424  Prule test :  0.9524038461538463
125 -27.58426068779309 1006.1964432505139 1006.0585219470747 Accuracy: 0.9037  test :  0.842  Prule Train :  0.9319590333208755  Prule test :  0.953320500481232
130 3059.028369643072 989.2572593427672 1004.5524011909824 Accuracy: 0.9054  test :  0.8427  Prule Train :  0.9308168667144847  Prule test :  0.9542389210019269
135 2074.5836026608868 972.5515517087605 982.9244697220648 Accuracy: 0.9077  test :  0.8427  Prule Train :  0.9304547220589222  Prule test :  0.9560810810810811
140 1652.3899962547537 957.3089230294852 965.570873010759 Accuracy: 0.91  test :  0.8433  Prule Train :  0.9300907406595446  Prule test :  0.955159112825458
145 2126.1225555802857 941.6822301265377 952.312842904439 Accuracy: 0.912  test :  0.8427  Prule Train :  0.9293311241326562  Prule test :  0.9597868217054263
150 1665.9792778648646 927.9708616852274 936.3007580745518 Accuracy: 0.9131  test :  0.8427  Prule Train :  0.9291470864781853  Prule test :  0.9597868217054263
155 2762.9288175680467 914.3008579610504 928.1155020488907 Accuracy: 0.9143  test :  0.842  Prule Train :  0.9307259260473921  Prule test :  0.9607177497575169
160 2386.2643613748833 901.1582218573506 913.089543664225 Accuracy: 0.9183  test :  0.8427  Prule Train :  0.9345181015608374  Prule test :  0.9616504854368931
165 -1952.0732166301464 886.6883726716553 876.9280065885046 Accuracy: 0.9197  test :  0.8427  Prule Train :  0.934738948049756  Prule test :  0.9616504854368931
170 2884.521820866348 874.3022141266492 888.724823230981 Accuracy: 0.9223  test :  0.8433  Prule Train :  0.934781550759227  Prule test :  0.9586639932460954
175 2278.3010619912347 862.5789822025356 873.9704875124918 Accuracy: 0.9226  test :  0.8433  Prule Train :  0.9333987378143168  Prule test :  0.9526910088644998
180 991.3552111456074 850.5069060519644 855.4636821076924 Accuracy: 0.9231  test :  0.844  Prule Train :  0.9342006267643292  Prule test :  0.9536168504668949
185 -2024.086357470961 839.0349050582929 828.9144732709382 Accuracy: 0.9246  test :  0.8433  Prule Train :  0.9344221621969525  Prule test :  0.9524787265568773
190 2895.1870342253414 828.773689890402 843.2496250615286 Accuracy: 0.9254  test :  0.8433  Prule Train :  0.9338394275555888  Prule test :  0.9524787265568773
195 2100.7888296503024 818.7187587772256 829.222702925477 Accuracy: 0.9266  test :  0.8447  Prule Train :  0.9318669148537915  Prule test :  0.9524787265568773
Resultado | acc=0.8447 | bal_acc=0.6778 | f1=0.9074 | EOdds=0.0356 | EOp=0.0193 | p-rule=95.25 | score=0.6754 | tempo=0.12 min

FAGTB african_american_0:  73%|███████▎  | 44/60 [04:06<01:30,  5.63s/modelo]

----------------------------------------------------------------------------------------------------
Treino 45/120 | config=african_american_0 | lambda=0.005 | n_estimators=100 | learning_rate=0.1 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1810.1320867357554 1814.8585703413733 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1726.7876050563598 1678.4128955651768 1687.0468335904586 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 588.961265749668 1564.272884075607 1567.2176904043554 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 193.54342566930717 1465.907040394466 1466.8747575228126 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2790.7924501171806 1385.986878211536 1399.9408404621217 Accuracy: 0.8646  test :  0.84  Prule Train :  0.9542191517101046  Prule test :  0.9598316443282119
25 1501.2921146536546 1317.250606676998 1324.7570672502661 Accuracy: 0.8766  test :  0.8407  Prule Train :  0.9535296188563666  Prule test :  0.9529497257021207
30 941.185682495094 1256.778979564044 1261.4849079765193 Accuracy: 0.884  test :  0.84  Prule Train :  0.9448234609094144  Prule test :  0.9496253293807642
35 -709.2141615653873 1204.703466725429 1201.1573959176021 Accuracy: 0.8863  test :  0.8413  Prule Train :  0.9445034908194786  Prule test :  0.9532360720780294
40 2774.810475126465 1160.5809669611335 1174.4550193367659 Accuracy: 0.8894  test :  0.8427  Prule Train :  0.9419046120572319  Prule test :  0.95485029691458
45 2145.9149390581733 1119.4147231687161 1130.144297864007 Accuracy: 0.8926  test :  0.8433  Prule Train :  0.9392906235347396  Prule test :  0.9519122960009967
50 430.8628246153807 1081.2470890145428 1083.40140313762 Accuracy: 0.8954  test :  0.8447  Prule Train :  0.9345410115120474  Prule test :  0.953734137715831
55 -1320.6481681896241 1044.095097224684 1037.491856383736 Accuracy: 0.8997  test :  0.8433  Prule Train :  0.9334507667294681  Prule test :  0.9535279145456063
60 2944.3080856715187 1012.6333480679032 1027.3548884962606 Accuracy: 0.9037  test :  0.8447  Prule Train :  0.9337036419705865  Prule test :  0.9553616220735787
65 2077.8457071329562 980.723778272778 991.1130068084426 Accuracy: 0.9069  test :  0.8447  Prule Train :  0.9292794108310584  Prule test :  0.955159112825458
70 1592.955266802504 951.1420595742329 959.1068359082454 Accuracy: 0.9117  test :  0.844  Prule Train :  0.9306957807026014  Prule test :  0.9560810810810811
75 2349.373588796997 920.0992243662447 931.8460923102297 Accuracy: 0.9157  test :  0.8433  Prule Train :  0.930939096065498  Prule test :  0.9627675261206605
80 -1645.8172817036634 892.2617500098938 884.0326636013756 Accuracy: 0.9177  test :  0.8447  Prule Train :  0.9284062290149184  Prule test :  0.9568061172901922
85 2201.4088547760084 869.1883254192426 880.1953696931225 Accuracy: 0.9214  test :  0.8453  Prule Train :  0.9300201734242903  Prule test :  0.9595956394980353
90 1122.7166482891182 847.8060068787341 853.4195901201798 Accuracy: 0.922  test :  0.8447  Prule Train :  0.9290381965655857  Prule test :  0.9584691587993734
95 -1780.0303258215863 824.8212466223665 815.9210949932585 Accuracy: 0.9249  test :  0.8453  Prule Train :  0.9294631308945811  Prule test :  0.9554739426781255
Resultado | acc=0.8453 | bal_acc=0.6793 | f1=0.9078 | EOdds=0.0312 | EOp=0.0193 | p-rule=95.34 | score=0.6771 | tempo=0.06 min

FAGTB african_american_0:  75%|███████▌  | 45/60 [04:09<01:15,  5.04s/modelo]

----------------------------------------------------------------------------------------------------
Treino 46/120 | config=african_american_0 | lambda=0.005 | n_estimators=200 | learning_rate=0.1 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1810.1320867357554 1814.8585703413733 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1726.7876050563598 1678.4128955651768 1687.0468335904586 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 588.961265749668 1564.272884075607 1567.2176904043554 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 193.54342566930717 1465.907040394466 1466.8747575228126 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2790.7924501171806 1385.986878211536 1399.9408404621217 Accuracy: 0.8646  test :  0.84  Prule Train :  0.9542191517101046  Prule test :  0.9598316443282119
25 1501.2921146536546 1317.250606676998 1324.7570672502661 Accuracy: 0.8766  test :  0.8407  Prule Train :  0.9535296188563666  Prule test :  0.9529497257021207
30 941.185682495094 1256.778979564044 1261.4849079765193 Accuracy: 0.884  test :  0.84  Prule Train :  0.9448234609094144  Prule test :  0.9496253293807642
35 -709.2141615653873 1204.703466725429 1201.1573959176021 Accuracy: 0.8863  test :  0.8413  Prule Train :  0.9445034908194786  Prule test :  0.9532360720780294
40 2774.810475126465 1160.5809669611335 1174.4550193367659 Accuracy: 0.8894  test :  0.8427  Prule Train :  0.9419046120572319  Prule test :  0.95485029691458
45 2145.9149390581733 1119.4147231687161 1130.144297864007 Accuracy: 0.8926  test :  0.8433  Prule Train :  0.9392906235347396  Prule test :  0.9519122960009967
50 430.8628246153807 1081.2470890145428 1083.40140313762 Accuracy: 0.8954  test :  0.8447  Prule Train :  0.9345410115120474  Prule test :  0.953734137715831
55 -1320.6481681896241 1044.095097224684 1037.491856383736 Accuracy: 0.8997  test :  0.8433  Prule Train :  0.9334507667294681  Prule test :  0.9535279145456063
60 2944.3080856715187 1012.6333480679032 1027.3548884962606 Accuracy: 0.9037  test :  0.8447  Prule Train :  0.9337036419705865  Prule test :  0.9553616220735787
65 2077.8457071329562 980.723778272778 991.1130068084426 Accuracy: 0.9069  test :  0.8447  Prule Train :  0.9292794108310584  Prule test :  0.955159112825458
70 1592.955266802504 951.1420595742329 959.1068359082454 Accuracy: 0.9117  test :  0.844  Prule Train :  0.9306957807026014  Prule test :  0.9560810810810811
75 2349.373588796997 920.0992243662447 931.8460923102297 Accuracy: 0.9157  test :  0.8433  Prule Train :  0.930939096065498  Prule test :  0.9627675261206605
80 -1645.8172817036634 892.2617500098938 884.0326636013756 Accuracy: 0.9177  test :  0.8447  Prule Train :  0.9284062290149184  Prule test :  0.9568061172901922
85 2201.4088547760084 869.1883254192426 880.1953696931225 Accuracy: 0.9214  test :  0.8453  Prule Train :  0.9300201734242903  Prule test :  0.9595956394980353
90 1122.7166482891182 847.8060068787341 853.4195901201798 Accuracy: 0.922  test :  0.8447  Prule Train :  0.9290381965655857  Prule test :  0.9584691587993734
95 -1780.0303258215863 824.8212466223665 815.9210949932585 Accuracy: 0.9249  test :  0.8453  Prule Train :  0.9294631308945811  Prule test :  0.9554739426781255
100 -1283.8334393005364 803.3995068471435 796.9803396506409 Accuracy: 0.9277  test :  0.8453  Prule Train :  0.9334763568483575  Prule test :  0.9534070683956267
105 2147.629315139483 785.9030162918868 796.6411628675843 Accuracy: 0.9303  test :  0.8453  Prule Train :  0.9317166147081708  Prule test :  0.9552691915760869
110 -1650.7500892143817 766.5489761670824 758.2952257210103 Accuracy: 0.9331  test :  0.8447  Prule Train :  0.9285492896394585  Prule test :  0.9562029835522121
115 2254.3923392542274 750.3348170540986 761.6067787503697 Accuracy: 0.9351  test :  0.8447  Prule Train :  0.927765835148339  Prule test :  0.9562029835522121
120 2556.5954920507647 732.5030358435522 745.286013303806 Accuracy: 0.938  test :  0.8453  Prule Train :  0.9318189842752431  Prule test :  0.9571386029098953
125 1423.1612837588705 719.5834720424386 726.699278461233 Accuracy: 0.9394  test :  0.8453  Prule Train :  0.9284074300485833  Prule test :  0.9571386029098953
130 2387.396561128304 704.4655972417639 716.4025800474054 Accuracy: 0.9414  test :  0.8453  Prule Train :  0.9276178283075499  Prule test :  0.9610888728016012
135 1230.975100814048 692.7956980840178 698.950573588088 Accuracy: 0.9437  test :  0.844  Prule Train :  0.9290557934225003  Prule test :  0.9590153452685422
140 1696.4930133939463 680.1115216979131 688.5939867648826 Accuracy: 0.9451  test :  0.844  Prule Train :  0.9292734371970708  Prule test :  0.9529838022165389
145 454.15920325060665 666.874620501249 669.1454165175021 Accuracy: 0.9471  test :  0.844  Prule Train :  0.9266493662944977  Prule test :  0.9529838022165389
150 -858.9390483656143 653.6162894587715 649.3215942169434 Accuracy: 0.948  test :  0.844  Prule Train :  0.924214565342606  Prule test :  0.9529838022165389
155 1813.7745825946986 640.7614175108945 649.8302904238681 Accuracy: 0.9514  test :  0.8433  Prule Train :  0.9217813943400279  Prule test :  0.9499680306905371
160 -999.7916172351117 629.2606573796165 624.2616992934409 Accuracy: 0.9534  test :  0.844  Prule Train :  0.9191288934937273  Prule test :  0.9469522591645354
165 1499.7067831914783 619.6173087729846 627.1158426889422 Accuracy: 0.9549  test :  0.8447  Prule Train :  0.9174911673085652  Prule test :  0.9460247838862156
170 1196.8910062998834 609.7832922858931 615.7677473173926 Accuracy: 0.9566  test :  0.8433  Prule Train :  0.9180991377782458  Prule test :  0.9478815548065026
175 2336.339993085431 599.7312211098229 611.41292107525 Accuracy: 0.9569  test :  0.8447  Prule Train :  0.9185080906235812  Prule test :  0.9478815548065026
180 612.9056424772327 590.6379727704045 593.7025009827906 Accuracy: 0.9574  test :  0.8433  Prule Train :  0.9156377528403826  Prule test :  0.9497456286605959
185 -826.5396758826521 581.607531535878 577.4748331564647 Accuracy: 0.9583  test :  0.8433  Prule Train :  0.9150177445229685  Prule test :  0.9457909797557016
190 1679.0070848221808 571.3553648276973 579.7504002518082 Accuracy: 0.9591  test :  0.844  Prule Train :  0.9162432147165259  Prule test :  0.9427692833347571
195 -689.6192124455265 562.9577358843653 559.5096398221376 Accuracy: 0.9614  test :  0.844  Prule Train :  0.9158195580312163  Prule test :  0.9427692833347571
Resultado | acc=0.8433 | bal_acc=0.6846 | f1=0.9060 | EOdds=0.0348 | EOp=0.0237 | p-rule=94.77 | score=0.6821 | tempo=0.12 min

FAGTB african_american_0:  77%|███████▋  | 46/60 [04:17<01:18,  5.64s/modelo]

----------------------------------------------------------------------------------------------------
Treino 47/120 | config=african_american_0 | lambda=0.005 | n_estimators=100 | learning_rate=0.1 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1810.1320867357554 1814.8585703413733 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1726.7876050563598 1678.4128955651768 1687.0468335904586 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 588.961265749668 1564.272884075607 1567.2176904043554 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 193.54342566930717 1465.907040394466 1466.8747575228126 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2790.7924501171806 1385.986878211536 1399.9408404621217 Accuracy: 0.8646  test :  0.84  Prule Train :  0.9542191517101046  Prule test :  0.9598316443282119
25 1501.2921146536546 1317.250606676998 1324.7570672502661 Accuracy: 0.8766  test :  0.8407  Prule Train :  0.9535296188563666  Prule test :  0.9529497257021207
30 941.185682495094 1256.778979564044 1261.4849079765193 Accuracy: 0.884  test :  0.84  Prule Train :  0.9448234609094144  Prule test :  0.9496253293807642
35 -709.2141615653873 1204.703466725429 1201.1573959176021 Accuracy: 0.8863  test :  0.8413  Prule Train :  0.9445034908194786  Prule test :  0.9532360720780294
40 2774.810475126465 1160.5809669611335 1174.4550193367659 Accuracy: 0.8894  test :  0.8427  Prule Train :  0.9419046120572319  Prule test :  0.95485029691458
45 2145.9149390581733 1119.4147231687161 1130.144297864007 Accuracy: 0.8926  test :  0.8433  Prule Train :  0.9392906235347396  Prule test :  0.9519122960009967
50 430.8628246153807 1081.2470890145428 1083.40140313762 Accuracy: 0.8954  test :  0.8447  Prule Train :  0.9345410115120474  Prule test :  0.953734137715831
55 -1320.6481681896241 1044.095097224684 1037.491856383736 Accuracy: 0.8997  test :  0.8433  Prule Train :  0.9334507667294681  Prule test :  0.9535279145456063
60 2944.3080856715187 1012.6333480679032 1027.3548884962606 Accuracy: 0.9037  test :  0.8447  Prule Train :  0.9337036419705865  Prule test :  0.9553616220735787
65 2077.8457071329562 980.723778272778 991.1130068084426 Accuracy: 0.9069  test :  0.8447  Prule Train :  0.9292794108310584  Prule test :  0.955159112825458
70 1592.955266802504 951.1420595742329 959.1068359082454 Accuracy: 0.9117  test :  0.844  Prule Train :  0.9306957807026014  Prule test :  0.9560810810810811
75 2349.373588796997 920.0992243662447 931.8460923102297 Accuracy: 0.9157  test :  0.8433  Prule Train :  0.930939096065498  Prule test :  0.9627675261206605
80 -1645.8172817036634 892.2617500098938 884.0326636013756 Accuracy: 0.9177  test :  0.8447  Prule Train :  0.9284062290149184  Prule test :  0.9568061172901922
85 2201.4088547760084 869.1883254192426 880.1953696931225 Accuracy: 0.9214  test :  0.8453  Prule Train :  0.9300201734242903  Prule test :  0.9595956394980353
90 1122.7166482891182 847.8060068787341 853.4195901201798 Accuracy: 0.922  test :  0.8447  Prule Train :  0.9290381965655857  Prule test :  0.9584691587993734
95 -1780.0303258215863 824.8212466223665 815.9210949932585 Accuracy: 0.9249  test :  0.8453  Prule Train :  0.9294631308945811  Prule test :  0.9554739426781255
Resultado | acc=0.8453 | bal_acc=0.6793 | f1=0.9078 | EOdds=0.0312 | EOp=0.0193 | p-rule=95.34 | score=0.6771 | tempo=0.06 min

FAGTB african_american_0:  78%|███████▊  | 47/60 [04:20<01:05,  5.04s/modelo]

----------------------------------------------------------------------------------------------------
Treino 48/120 | config=african_american_0 | lambda=0.005 | n_estimators=200 | learning_rate=0.1 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1810.1320867357554 1814.8585703413733 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1726.7876050563598 1678.4128955651768 1687.0468335904586 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 588.961265749668 1564.272884075607 1567.2176904043554 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 193.54342566930717 1465.907040394466 1466.8747575228126 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2790.7924501171806 1385.986878211536 1399.9408404621217 Accuracy: 0.8646  test :  0.84  Prule Train :  0.9542191517101046  Prule test :  0.9598316443282119
25 1501.2921146536546 1317.250606676998 1324.7570672502661 Accuracy: 0.8766  test :  0.8407  Prule Train :  0.9535296188563666  Prule test :  0.9529497257021207
30 941.185682495094 1256.778979564044 1261.4849079765193 Accuracy: 0.884  test :  0.84  Prule Train :  0.9448234609094144  Prule test :  0.9496253293807642
35 -709.2141615653873 1204.703466725429 1201.1573959176021 Accuracy: 0.8863  test :  0.8413  Prule Train :  0.9445034908194786  Prule test :  0.9532360720780294
40 2774.810475126465 1160.5809669611335 1174.4550193367659 Accuracy: 0.8894  test :  0.8427  Prule Train :  0.9419046120572319  Prule test :  0.95485029691458
45 2145.9149390581733 1119.4147231687161 1130.144297864007 Accuracy: 0.8926  test :  0.8433  Prule Train :  0.9392906235347396  Prule test :  0.9519122960009967
50 430.8628246153807 1081.2470890145428 1083.40140313762 Accuracy: 0.8954  test :  0.8447  Prule Train :  0.9345410115120474  Prule test :  0.953734137715831
55 -1320.6481681896241 1044.095097224684 1037.491856383736 Accuracy: 0.8997  test :  0.8433  Prule Train :  0.9334507667294681  Prule test :  0.9535279145456063
60 2944.3080856715187 1012.6333480679032 1027.3548884962606 Accuracy: 0.9037  test :  0.8447  Prule Train :  0.9337036419705865  Prule test :  0.9553616220735787
65 2077.8457071329562 980.723778272778 991.1130068084426 Accuracy: 0.9069  test :  0.8447  Prule Train :  0.9292794108310584  Prule test :  0.955159112825458
70 1592.955266802504 951.1420595742329 959.1068359082454 Accuracy: 0.9117  test :  0.844  Prule Train :  0.9306957807026014  Prule test :  0.9560810810810811
75 2349.373588796997 920.0992243662447 931.8460923102297 Accuracy: 0.9157  test :  0.8433  Prule Train :  0.930939096065498  Prule test :  0.9627675261206605
80 -1645.8172817036634 892.2617500098938 884.0326636013756 Accuracy: 0.9177  test :  0.8447  Prule Train :  0.9284062290149184  Prule test :  0.9568061172901922
85 2201.4088547760084 869.1883254192426 880.1953696931225 Accuracy: 0.9214  test :  0.8453  Prule Train :  0.9300201734242903  Prule test :  0.9595956394980353
90 1122.7166482891182 847.8060068787341 853.4195901201798 Accuracy: 0.922  test :  0.8447  Prule Train :  0.9290381965655857  Prule test :  0.9584691587993734
95 -1780.0303258215863 824.8212466223665 815.9210949932585 Accuracy: 0.9249  test :  0.8453  Prule Train :  0.9294631308945811  Prule test :  0.9554739426781255
100 -1283.8334393005364 803.3995068471435 796.9803396506409 Accuracy: 0.9277  test :  0.8453  Prule Train :  0.9334763568483575  Prule test :  0.9534070683956267
105 2147.629315139483 785.9030162918868 796.6411628675843 Accuracy: 0.9303  test :  0.8453  Prule Train :  0.9317166147081708  Prule test :  0.9552691915760869
110 -1650.7500892143817 766.5489761670824 758.2952257210103 Accuracy: 0.9331  test :  0.8447  Prule Train :  0.9285492896394585  Prule test :  0.9562029835522121
115 2254.3923392542274 750.3348170540986 761.6067787503697 Accuracy: 0.9351  test :  0.8447  Prule Train :  0.927765835148339  Prule test :  0.9562029835522121
120 2556.5954920507647 732.5030358435522 745.286013303806 Accuracy: 0.938  test :  0.8453  Prule Train :  0.9318189842752431  Prule test :  0.9571386029098953
125 1423.1612837588705 719.5834720424386 726.699278461233 Accuracy: 0.9394  test :  0.8453  Prule Train :  0.9284074300485833  Prule test :  0.9571386029098953
130 2387.396561128304 704.4655972417639 716.4025800474054 Accuracy: 0.9414  test :  0.8453  Prule Train :  0.9276178283075499  Prule test :  0.9610888728016012
135 1230.975100814048 692.7956980840178 698.950573588088 Accuracy: 0.9437  test :  0.844  Prule Train :  0.9290557934225003  Prule test :  0.9590153452685422
140 1696.4930133939463 680.1115216979131 688.5939867648826 Accuracy: 0.9451  test :  0.844  Prule Train :  0.9292734371970708  Prule test :  0.9529838022165389
145 454.15920325060665 666.874620501249 669.1454165175021 Accuracy: 0.9471  test :  0.844  Prule Train :  0.9266493662944977  Prule test :  0.9529838022165389
150 -858.9390483656143 653.6162894587715 649.3215942169434 Accuracy: 0.948  test :  0.844  Prule Train :  0.924214565342606  Prule test :  0.9529838022165389
155 1813.7745825946986 640.7614175108945 649.8302904238681 Accuracy: 0.9514  test :  0.8433  Prule Train :  0.9217813943400279  Prule test :  0.9499680306905371
160 -999.7916172351117 629.2606573796165 624.2616992934409 Accuracy: 0.9534  test :  0.844  Prule Train :  0.9191288934937273  Prule test :  0.9469522591645354
165 1499.7067831914783 619.6173087729846 627.1158426889422 Accuracy: 0.9549  test :  0.8447  Prule Train :  0.9174911673085652  Prule test :  0.9460247838862156
170 1196.8910062998834 609.7832922858931 615.7677473173926 Accuracy: 0.9566  test :  0.8433  Prule Train :  0.9180991377782458  Prule test :  0.9478815548065026
175 2336.339993085431 599.7312211098229 611.41292107525 Accuracy: 0.9569  test :  0.8447  Prule Train :  0.9185080906235812  Prule test :  0.9478815548065026
180 612.9056424772327 590.6379727704045 593.7025009827906 Accuracy: 0.9574  test :  0.8433  Prule Train :  0.9156377528403826  Prule test :  0.9497456286605959
185 -826.5396758826521 581.607531535878 577.4748331564647 Accuracy: 0.9583  test :  0.8433  Prule Train :  0.9150177445229685  Prule test :  0.9457909797557016
190 1679.0070848221808 571.3553648276973 579.7504002518082 Accuracy: 0.9591  test :  0.844  Prule Train :  0.9162432147165259  Prule test :  0.9427692833347571
195 -689.6192124455265 562.9577358843653 559.5096398221376 Accuracy: 0.9614  test :  0.844  Prule Train :  0.9158195580312163  Prule test :  0.9427692833347571
Resultado | acc=0.8433 | bal_acc=0.6846 | f1=0.9060 | EOdds=0.0348 | EOp=0.0237 | p-rule=94.77 | score=0.6821 | tempo=0.11 min

FAGTB african_american_0:  80%|████████  | 48/60 [04:27<01:07,  5.64s/modelo]

----------------------------------------------------------------------------------------------------
Treino 49/120 | config=african_american_0 | lambda=0.01 | n_estimators=100 | learning_rate=0.03 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1830.435718121431 1839.8886853326662 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1698.2505257554474 1788.0335892594067 1805.0160945169614 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 583.023501654996 1747.985708731528 1753.8159437480776 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 390.1509596035212 1709.9006890155258 1713.802198611561 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2689.841714932315 1673.6914751061402 1700.5898922554634 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1500.5435522120229 1639.187803313616 1654.1932388357363 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 814.8316993336472 1605.7090965200246 1613.8574135133608 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 140.054991609346 1573.3247932979934 1574.725343214087 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2807.8601509457003 1543.3243374888575 1571.4029389983145 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 1658.3713118750563 1515.176072563631 1531.7597856823813 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 997.2665481772477 1487.6781619467251 1497.6508274284977 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -230.00573900210208 1461.661390165611 1459.3613327755902 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 2731.1758982757005 1437.9226774678518 1465.2344364506089 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 2083.4728817867626 1414.4550041878492 1435.2897330057167 Accuracy: 0.7831  test :  0.782  Prule Train :  0.9989586668041243  Prule test :  0.9991166077738517
70 1067.7263968117759 1392.0557792608838 1402.7330432290019 Accuracy: 0.864  test :  0.838  Prule Train :  0.9517636990802535  Prule test :  0.9685048218372017
75 -1018.6994502435102 1370.5091919851002 1360.3221974826652 Accuracy: 0.8663  test :  0.838  Prule Train :  0.95315600653955  Prule test :  0.9685048218372017
80 3036.6325007404103 1350.154110473724 1380.5204354811278 Accuracy: 0.8711  test :  0.84  Prule Train :  0.9529538956520203  Prule test :  0.9636283692584563
85 2329.2365335260756 1330.85868192643 1354.1510472616906 Accuracy: 0.8743  test :  0.838  Prule Train :  0.9538247313962371  Prule test :  0.9549470325984702
90 1048.6212127326605 1311.9915001392997 1322.477712266626 Accuracy: 0.8769  test :  0.8393  Prule Train :  0.9539200896257591  Prule test :  0.9567471212555833
95 -1580.058091062941 1294.4089819278565 1278.6084010172272 Accuracy: 0.88  test :  0.8387  Prule Train :  0.9462342820896719  Prule test :  0.9594600147941152
Resultado | acc=0.8393 | bal_acc=0.6469 | f1=0.9058 | EOdds=0.0550 | EOp=0.0143 | p-rule=95.66 | score=0.6437 | tempo=0.06 min

FAGTB african_american_0:  82%|████████▏ | 49/60 [04:31<00:55,  5.04s/modelo]

----------------------------------------------------------------------------------------------------
Treino 50/120 | config=african_american_0 | lambda=0.01 | n_estimators=200 | learning_rate=0.03 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1830.435718121431 1839.8886853326662 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1698.2505257554474 1788.0335892594067 1805.0160945169614 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 583.023501654996 1747.985708731528 1753.8159437480776 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 390.1509596035212 1709.9006890155258 1713.802198611561 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2689.841714932315 1673.6914751061402 1700.5898922554634 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1500.5435522120229 1639.187803313616 1654.1932388357363 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 814.8316993336472 1605.7090965200246 1613.8574135133608 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 140.054991609346 1573.3247932979934 1574.725343214087 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2807.8601509457003 1543.3243374888575 1571.4029389983145 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 1658.3713118750563 1515.176072563631 1531.7597856823813 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 997.2665481772477 1487.6781619467251 1497.6508274284977 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -230.00573900210208 1461.661390165611 1459.3613327755902 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 2731.1758982757005 1437.9226774678518 1465.2344364506089 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 2083.4728817867626 1414.4550041878492 1435.2897330057167 Accuracy: 0.7831  test :  0.782  Prule Train :  0.9989586668041243  Prule test :  0.9991166077738517
70 1067.7263968117759 1392.0557792608838 1402.7330432290019 Accuracy: 0.864  test :  0.838  Prule Train :  0.9517636990802535  Prule test :  0.9685048218372017
75 -1018.6994502435102 1370.5091919851002 1360.3221974826652 Accuracy: 0.8663  test :  0.838  Prule Train :  0.95315600653955  Prule test :  0.9685048218372017
80 3036.6325007404103 1350.154110473724 1380.5204354811278 Accuracy: 0.8711  test :  0.84  Prule Train :  0.9529538956520203  Prule test :  0.9636283692584563
85 2329.2365335260756 1330.85868192643 1354.1510472616906 Accuracy: 0.8743  test :  0.838  Prule Train :  0.9538247313962371  Prule test :  0.9549470325984702
90 1048.6212127326605 1311.9915001392997 1322.477712266626 Accuracy: 0.8769  test :  0.8393  Prule Train :  0.9539200896257591  Prule test :  0.9567471212555833
95 -1580.058091062941 1294.4089819278565 1278.6084010172272 Accuracy: 0.88  test :  0.8387  Prule Train :  0.9462342820896719  Prule test :  0.9594600147941152
100 2939.5346081060925 1278.3102416406655 1307.7055877217263 Accuracy: 0.8811  test :  0.8413  Prule Train :  0.9443658749636039  Prule test :  0.9592726148773955
105 2412.8240830453733 1261.8824439061696 1286.0106847366233 Accuracy: 0.8829  test :  0.8413  Prule Train :  0.9466976425561068  Prule test :  0.9610945951525661
110 1728.6294525110873 1246.5428124783166 1263.8291070034275 Accuracy: 0.8831  test :  0.8413  Prule Train :  0.9470873904534126  Prule test :  0.9610945951525661
115 -1754.6599786582537 1230.8030353282447 1213.2564355416623 Accuracy: 0.8843  test :  0.8413  Prule Train :  0.9469304687756384  Prule test :  0.9629235097009059
120 3480.092310338055 1217.5186441892206 1252.319567292601 Accuracy: 0.8843  test :  0.8407  Prule Train :  0.9469304687756384  Prule test :  0.962008183170772
125 2645.783110429021 1204.8746273229526 1231.3324584272427 Accuracy: 0.8846  test :  0.84  Prule Train :  0.945602375551549  Prule test :  0.9590841461398577
130 1933.2478154113219 1192.486583212578 1211.8190613666911 Accuracy: 0.8857  test :  0.8407  Prule Train :  0.9437241975102215  Prule test :  0.9599966905224836
135 -2806.6694179596116 1179.9281016472298 1151.8614074676339 Accuracy: 0.8871  test :  0.842  Prule Train :  0.9422319481377514  Prule test :  0.9541430521656393
140 3240.6126185388416 1168.420813649163 1200.8269398345515 Accuracy: 0.8877  test :  0.8433  Prule Train :  0.9412899141652296  Prule test :  0.9559622000248684
145 2859.1054239858495 1156.428938778607 1185.0199930184656 Accuracy: 0.8883  test :  0.8433  Prule Train :  0.9386271421308158  Prule test :  0.9559622000248684
150 86.86832803980906 1144.4055257260845 1145.2742090064826 Accuracy: 0.8889  test :  0.8433  Prule Train :  0.9394035086669041  Prule test :  0.9577882978281633
155 -2658.0422052908857 1132.8097798462252 1106.2293577933162 Accuracy: 0.8909  test :  0.844  Prule Train :  0.9421309348637803  Prule test :  0.9605405630518075
160 3029.9969750793502 1121.7272766622855 1152.027246413079 Accuracy: 0.8926  test :  0.8433  Prule Train :  0.9427496798815186  Prule test :  0.9575941196068632
165 2515.7512397439596 1111.0081248000765 1136.165637197516 Accuracy: 0.8931  test :  0.8453  Prule Train :  0.941801985710309  Prule test :  0.9585122347742715
170 1944.896521988725 1099.826360886752 1119.275326106639 Accuracy: 0.894  test :  0.8453  Prule Train :  0.9395132559525841  Prule test :  0.9603537568391597
175 -469.6387975941111 1087.978076566596 1083.281688590655 Accuracy: 0.894  test :  0.8453  Prule Train :  0.9395132559525841  Prule test :  0.9603537568391597
180 1707.276035325457 1076.6184745254577 1093.6912348787123 Accuracy: 0.8951  test :  0.846  Prule Train :  0.9376128055731602  Prule test :  0.9612771739130435
185 -240.65134365397836 1065.7490522826347 1063.3425388460946 Accuracy: 0.8971  test :  0.8467  Prule Train :  0.9334131481201204  Prule test :  0.9622023684981379
190 64.35430987841075 1054.4632846376162 1055.1068277364002 Accuracy: 0.8983  test :  0.8467  Prule Train :  0.933237140308234  Prule test :  0.9622023684981379
195 -653.0229826420718 1043.6372991495418 1037.107069323121 Accuracy: 0.8994  test :  0.8467  Prule Train :  0.933060691189673  Prule test :  0.9622023684981379
Resultado | acc=0.8460 | bal_acc=0.6698 | f1=0.9089 | EOdds=0.0259 | EOp=0.0161 | p-rule=95.92 | score=0.6680 | tempo=0.12 min

FAGTB african_american_0:  83%|████████▎ | 50/60 [04:38<00:56,  5.63s/modelo]

----------------------------------------------------------------------------------------------------
Treino 51/120 | config=african_american_0 | lambda=0.01 | n_estimators=100 | learning_rate=0.03 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1830.435718121431 1839.8886853326662 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1698.2505257554474 1788.0335892594067 1805.0160945169614 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 583.023501654996 1747.985708731528 1753.8159437480776 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 390.1509596035212 1709.9006890155258 1713.802198611561 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2689.841714932315 1673.6914751061402 1700.5898922554634 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1500.5435522120229 1639.187803313616 1654.1932388357363 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 814.8316993336472 1605.7090965200246 1613.8574135133608 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 140.054991609346 1573.3247932979934 1574.725343214087 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2807.8601509457003 1543.3243374888575 1571.4029389983145 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 1658.3713118750563 1515.176072563631 1531.7597856823813 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 997.2665481772477 1487.6781619467251 1497.6508274284977 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -230.00573900210208 1461.661390165611 1459.3613327755902 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 2731.1758982757005 1437.9226774678518 1465.2344364506089 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 2083.4728817867626 1414.4550041878492 1435.2897330057167 Accuracy: 0.7831  test :  0.782  Prule Train :  0.9989586668041243  Prule test :  0.9991166077738517
70 1067.7263968117759 1392.0557792608838 1402.7330432290019 Accuracy: 0.864  test :  0.838  Prule Train :  0.9517636990802535  Prule test :  0.9685048218372017
75 -1018.6994502435102 1370.5091919851002 1360.3221974826652 Accuracy: 0.8663  test :  0.838  Prule Train :  0.95315600653955  Prule test :  0.9685048218372017
80 3036.6325007404103 1350.154110473724 1380.5204354811278 Accuracy: 0.8711  test :  0.84  Prule Train :  0.9529538956520203  Prule test :  0.9636283692584563
85 2329.2365335260756 1330.85868192643 1354.1510472616906 Accuracy: 0.8743  test :  0.838  Prule Train :  0.9538247313962371  Prule test :  0.9549470325984702
90 1048.6212127326605 1311.9915001392997 1322.477712266626 Accuracy: 0.8769  test :  0.8393  Prule Train :  0.9539200896257591  Prule test :  0.9567471212555833
95 -1580.058091062941 1294.4089819278565 1278.6084010172272 Accuracy: 0.88  test :  0.8387  Prule Train :  0.9462342820896719  Prule test :  0.9594600147941152
Resultado | acc=0.8393 | bal_acc=0.6469 | f1=0.9058 | EOdds=0.0550 | EOp=0.0143 | p-rule=95.66 | score=0.6437 | tempo=0.06 min

FAGTB african_american_0:  85%|████████▌ | 51/60 [04:42<00:45,  5.04s/modelo]

----------------------------------------------------------------------------------------------------
Treino 52/120 | config=african_american_0 | lambda=0.01 | n_estimators=200 | learning_rate=0.03 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1830.435718121431 1839.8886853326662 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1698.2505257554474 1788.0335892594067 1805.0160945169614 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 583.023501654996 1747.985708731528 1753.8159437480776 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 390.1509596035212 1709.9006890155258 1713.802198611561 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2689.841714932315 1673.6914751061402 1700.5898922554634 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1500.5435522120229 1639.187803313616 1654.1932388357363 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 814.8316993336472 1605.7090965200246 1613.8574135133608 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 140.054991609346 1573.3247932979934 1574.725343214087 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2807.8601509457003 1543.3243374888575 1571.4029389983145 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 1658.3713118750563 1515.176072563631 1531.7597856823813 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 997.2665481772477 1487.6781619467251 1497.6508274284977 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -230.00573900210208 1461.661390165611 1459.3613327755902 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 2731.1758982757005 1437.9226774678518 1465.2344364506089 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 2083.4728817867626 1414.4550041878492 1435.2897330057167 Accuracy: 0.7831  test :  0.782  Prule Train :  0.9989586668041243  Prule test :  0.9991166077738517
70 1067.7263968117759 1392.0557792608838 1402.7330432290019 Accuracy: 0.864  test :  0.838  Prule Train :  0.9517636990802535  Prule test :  0.9685048218372017
75 -1018.6994502435102 1370.5091919851002 1360.3221974826652 Accuracy: 0.8663  test :  0.838  Prule Train :  0.95315600653955  Prule test :  0.9685048218372017
80 3036.6325007404103 1350.154110473724 1380.5204354811278 Accuracy: 0.8711  test :  0.84  Prule Train :  0.9529538956520203  Prule test :  0.9636283692584563
85 2329.2365335260756 1330.85868192643 1354.1510472616906 Accuracy: 0.8743  test :  0.838  Prule Train :  0.9538247313962371  Prule test :  0.9549470325984702
90 1048.6212127326605 1311.9915001392997 1322.477712266626 Accuracy: 0.8769  test :  0.8393  Prule Train :  0.9539200896257591  Prule test :  0.9567471212555833
95 -1580.058091062941 1294.4089819278565 1278.6084010172272 Accuracy: 0.88  test :  0.8387  Prule Train :  0.9462342820896719  Prule test :  0.9594600147941152
100 2939.5346081060925 1278.3102416406655 1307.7055877217263 Accuracy: 0.8811  test :  0.8413  Prule Train :  0.9443658749636039  Prule test :  0.9592726148773955
105 2412.8240830453733 1261.8824439061696 1286.0106847366233 Accuracy: 0.8829  test :  0.8413  Prule Train :  0.9466976425561068  Prule test :  0.9610945951525661
110 1728.6294525110873 1246.5428124783166 1263.8291070034275 Accuracy: 0.8831  test :  0.8413  Prule Train :  0.9470873904534126  Prule test :  0.9610945951525661
115 -1754.6599786582537 1230.8030353282447 1213.2564355416623 Accuracy: 0.8843  test :  0.8413  Prule Train :  0.9469304687756384  Prule test :  0.9629235097009059
120 3480.092310338055 1217.5186441892206 1252.319567292601 Accuracy: 0.8843  test :  0.8407  Prule Train :  0.9469304687756384  Prule test :  0.962008183170772
125 2645.783110429021 1204.8746273229526 1231.3324584272427 Accuracy: 0.8846  test :  0.84  Prule Train :  0.945602375551549  Prule test :  0.9590841461398577
130 1933.2478154113219 1192.486583212578 1211.8190613666911 Accuracy: 0.8857  test :  0.8407  Prule Train :  0.9437241975102215  Prule test :  0.9599966905224836
135 -2806.6694179596116 1179.9281016472298 1151.8614074676339 Accuracy: 0.8871  test :  0.842  Prule Train :  0.9422319481377514  Prule test :  0.9541430521656393
140 3240.6126185388416 1168.420813649163 1200.8269398345515 Accuracy: 0.8877  test :  0.8433  Prule Train :  0.9412899141652296  Prule test :  0.9559622000248684
145 2859.1054239858495 1156.428938778607 1185.0199930184656 Accuracy: 0.8883  test :  0.8433  Prule Train :  0.9386271421308158  Prule test :  0.9559622000248684
150 86.86832803980906 1144.4055257260845 1145.2742090064826 Accuracy: 0.8889  test :  0.8433  Prule Train :  0.9394035086669041  Prule test :  0.9577882978281633
155 -2658.0422052908857 1132.8097798462252 1106.2293577933162 Accuracy: 0.8909  test :  0.844  Prule Train :  0.9421309348637803  Prule test :  0.9605405630518075
160 3029.9969750793502 1121.7272766622855 1152.027246413079 Accuracy: 0.8926  test :  0.8433  Prule Train :  0.9427496798815186  Prule test :  0.9575941196068632
165 2515.7512397439596 1111.0081248000765 1136.165637197516 Accuracy: 0.8931  test :  0.8453  Prule Train :  0.941801985710309  Prule test :  0.9585122347742715
170 1944.896521988725 1099.826360886752 1119.275326106639 Accuracy: 0.894  test :  0.8453  Prule Train :  0.9395132559525841  Prule test :  0.9603537568391597
175 -469.6387975941111 1087.978076566596 1083.281688590655 Accuracy: 0.894  test :  0.8453  Prule Train :  0.9395132559525841  Prule test :  0.9603537568391597
180 1707.276035325457 1076.6184745254577 1093.6912348787123 Accuracy: 0.8951  test :  0.846  Prule Train :  0.9376128055731602  Prule test :  0.9612771739130435
185 -240.65134365397836 1065.7490522826347 1063.3425388460946 Accuracy: 0.8971  test :  0.8467  Prule Train :  0.9334131481201204  Prule test :  0.9622023684981379
190 64.35430987841075 1054.4632846376162 1055.1068277364002 Accuracy: 0.8983  test :  0.8467  Prule Train :  0.933237140308234  Prule test :  0.9622023684981379
195 -653.0229826420718 1043.6372991495418 1037.107069323121 Accuracy: 0.8994  test :  0.8467  Prule Train :  0.933060691189673  Prule test :  0.9622023684981379
Resultado | acc=0.8460 | bal_acc=0.6698 | f1=0.9089 | EOdds=0.0259 | EOp=0.0161 | p-rule=95.92 | score=0.6680 | tempo=0.11 min

FAGTB african_american_0:  87%|████████▋ | 52/60 [04:49<00:44,  5.62s/modelo]

----------------------------------------------------------------------------------------------------
Treino 53/120 | config=african_american_0 | lambda=0.01 | n_estimators=100 | learning_rate=0.05 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1824.6832277190458 1834.1361949302814 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1705.7493284327265 1755.353131114592 1772.4106243989197 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 585.7384599716995 1691.989853906676 1697.8472385063928 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 337.54053002459614 1632.0333647631192 1635.408770063365 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2731.9125322834084 1577.9393907287053 1605.2585160515396 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1509.8155091791907 1527.9901423458775 1543.0882974376693 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 856.9088934607929 1481.5625029641328 1490.131591898741 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -191.13685956489138 1439.2746806785624 1437.3633120829136 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2860.7046598799943 1400.9893470827462 1429.596393681546 Accuracy: 0.8474  test :  0.83  Prule Train :  0.9646646058510217  Prule test :  0.9675019104693722
45 1800.13636307457 1364.694590683716 1382.6959543144615 Accuracy: 0.8683  test :  0.8387  Prule Train :  0.9541689809320841  Prule test :  0.9694159270317804
50 1172.540121643693 1331.1759741008286 1342.9013753172655 Accuracy: 0.8751  test :  0.8393  Prule Train :  0.9515820501904018  Prule test :  0.9587427331531974
55 -205.4907235856523 1300.016364220522 1297.9614569846658 Accuracy: 0.8794  test :  0.84  Prule Train :  0.9488773946094756  Prule test :  0.9614587182329515
60 2965.7159056207965 1272.3949516025705 1302.0521106587787 Accuracy: 0.8823  test :  0.84  Prule Train :  0.9459191083105836  Prule test :  0.957457529513389
65 2229.1366699698233 1245.2251792279258 1267.516545927624 Accuracy: 0.8831  test :  0.8413  Prule Train :  0.9470873904534126  Prule test :  0.9629235097009059
70 1157.313405700704 1220.1972482419337 1231.7703822989408 Accuracy: 0.8843  test :  0.8427  Prule Train :  0.9469304687756384  Prule test :  0.9570698713440615
75 -1636.7130711066193 1196.8525671047169 1180.4854363936506 Accuracy: 0.8854  test :  0.8433  Prule Train :  0.9450533865207992  Prule test :  0.9579813664596273
80 3273.0944577655487 1176.2841059536972 1209.0150505313527 Accuracy: 0.8877  test :  0.8433  Prule Train :  0.9430109741386921  Prule test :  0.9579813664596273
85 2035.0880325551905 1155.9187102811916 1176.2695906067436 Accuracy: 0.8883  test :  0.844  Prule Train :  0.9420684831595761  Prule test :  0.9568743776966478
90 1604.0983799773321 1136.3781259245009 1152.4191097242742 Accuracy: 0.8906  test :  0.844  Prule Train :  0.9382907107014469  Prule test :  0.9568743776966478
95 -2219.2854228965575 1117.1638654901556 1094.97101126119 Accuracy: 0.8929  test :  0.8433  Prule Train :  0.9379526027034933  Prule test :  0.9575941196068632
Resultado | acc=0.8433 | bal_acc=0.6626 | f1=0.9075 | EOdds=0.0474 | EOp=0.0124 | p-rule=95.76 | score=0.6599 | tempo=0.06 min

FAGTB african_american_0:  88%|████████▊ | 53/60 [04:52<00:35,  5.03s/modelo]

----------------------------------------------------------------------------------------------------
Treino 54/120 | config=african_american_0 | lambda=0.01 | n_estimators=200 | learning_rate=0.05 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1824.6832277190458 1834.1361949302814 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1705.7493284327265 1755.353131114592 1772.4106243989197 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 585.7384599716995 1691.989853906676 1697.8472385063928 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 337.54053002459614 1632.0333647631192 1635.408770063365 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2731.9125322834084 1577.9393907287053 1605.2585160515396 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1509.8155091791907 1527.9901423458775 1543.0882974376693 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 856.9088934607929 1481.5625029641328 1490.131591898741 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -191.13685956489138 1439.2746806785624 1437.3633120829136 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2860.7046598799943 1400.9893470827462 1429.596393681546 Accuracy: 0.8474  test :  0.83  Prule Train :  0.9646646058510217  Prule test :  0.9675019104693722
45 1800.13636307457 1364.694590683716 1382.6959543144615 Accuracy: 0.8683  test :  0.8387  Prule Train :  0.9541689809320841  Prule test :  0.9694159270317804
50 1172.540121643693 1331.1759741008286 1342.9013753172655 Accuracy: 0.8751  test :  0.8393  Prule Train :  0.9515820501904018  Prule test :  0.9587427331531974
55 -205.4907235856523 1300.016364220522 1297.9614569846658 Accuracy: 0.8794  test :  0.84  Prule Train :  0.9488773946094756  Prule test :  0.9614587182329515
60 2965.7159056207965 1272.3949516025705 1302.0521106587787 Accuracy: 0.8823  test :  0.84  Prule Train :  0.9459191083105836  Prule test :  0.957457529513389
65 2229.1366699698233 1245.2251792279258 1267.516545927624 Accuracy: 0.8831  test :  0.8413  Prule Train :  0.9470873904534126  Prule test :  0.9629235097009059
70 1157.313405700704 1220.1972482419337 1231.7703822989408 Accuracy: 0.8843  test :  0.8427  Prule Train :  0.9469304687756384  Prule test :  0.9570698713440615
75 -1636.7130711066193 1196.8525671047169 1180.4854363936506 Accuracy: 0.8854  test :  0.8433  Prule Train :  0.9450533865207992  Prule test :  0.9579813664596273
80 3273.0944577655487 1176.2841059536972 1209.0150505313527 Accuracy: 0.8877  test :  0.8433  Prule Train :  0.9430109741386921  Prule test :  0.9579813664596273
85 2035.0880325551905 1155.9187102811916 1176.2695906067436 Accuracy: 0.8883  test :  0.844  Prule Train :  0.9420684831595761  Prule test :  0.9568743776966478
90 1604.0983799773321 1136.3781259245009 1152.4191097242742 Accuracy: 0.8906  test :  0.844  Prule Train :  0.9382907107014469  Prule test :  0.9568743776966478
95 -2219.2854228965575 1117.1638654901556 1094.97101126119 Accuracy: 0.8929  test :  0.8433  Prule Train :  0.9379526027034933  Prule test :  0.9575941196068632
100 2834.7877749161453 1099.1149675809452 1127.4628453301068 Accuracy: 0.8943  test :  0.8433  Prule Train :  0.9381730087971596  Prule test :  0.9575941196068632
105 2426.6535725381746 1080.8751386615263 1105.141674386908 Accuracy: 0.8951  test :  0.8447  Prule Train :  0.9358818164066127  Prule test :  0.9594321121588918
110 1701.4424025596015 1063.2630122383043 1080.2774362639002 Accuracy: 0.8974  test :  0.8447  Prule Train :  0.9320701076192283  Prule test :  0.9612771739130435
115 -2583.5768973662543 1046.4241036881076 1020.5883347144451 Accuracy: 0.8997  test :  0.8453  Prule Train :  0.9334507667294681  Prule test :  0.9603537568391597
120 2832.546176830747 1030.930111180364 1059.2555729486717 Accuracy: 0.9009  test :  0.8453  Prule Train :  0.9350143358529681  Prule test :  0.9601658708218146
125 -1715.0199476326786 1014.0904059332556 996.9402064569288 Accuracy: 0.9023  test :  0.8453  Prule Train :  0.9369761787733478  Prule test :  0.9581254454739843
130 2588.8104233651597 999.9721670661172 1025.8602712997686 Accuracy: 0.9043  test :  0.8453  Prule Train :  0.937985813990428  Prule test :  0.9581254454739843
135 1253.045817439329 983.0789406363645 995.6093988107577 Accuracy: 0.9057  test :  0.846  Prule Train :  0.9364567698112748  Prule test :  0.955159112825458
140 -1645.2339440522605 966.4136708053661 949.9613313648435 Accuracy: 0.9089  test :  0.8467  Prule Train :  0.9337813920090428  Prule test :  0.9560810810810811
145 -36.13578070495123 950.4943766003114 950.1330187932618 Accuracy: 0.9109  test :  0.846  Prule Train :  0.9347897504124368  Prule test :  0.9570048309178745
150 2906.34747102715 935.205417859431 964.2688925697025 Accuracy: 0.9131  test :  0.8447  Prule Train :  0.9344351135458524  Prule test :  0.9570048309178745
155 1506.325532670801 920.6766079547617 935.7398632814698 Accuracy: 0.914  test :  0.844  Prule Train :  0.9320946406445205  Prule test :  0.9579303675048355
160 1480.9472213248637 904.5444380719796 919.3539102852283 Accuracy: 0.916  test :  0.8433  Prule Train :  0.9313354090055003  Prule test :  0.9588576960309777
165 1194.3942773036033 891.6299730032414 903.5739157762775 Accuracy: 0.9186  test :  0.8433  Prule Train :  0.9331417862418967  Prule test :  0.9588576960309777
170 -862.1877624793032 878.8771983522429 870.25532072745 Accuracy: 0.9194  test :  0.8427  Prule Train :  0.9343391452490504  Prule test :  0.9616504854368931
175 2421.335564906636 866.9693959967019 891.1827516457683 Accuracy: 0.9203  test :  0.8427  Prule Train :  0.9337598319480476  Prule test :  0.9616504854368931
180 2086.700875430437 855.8807830481514 876.7477918024558 Accuracy: 0.9226  test :  0.8427  Prule Train :  0.9369686286214086  Prule test :  0.9616504854368931
185 -344.6824917278173 843.4981275632002 840.0513026459221 Accuracy: 0.9243  test :  0.8427  Prule Train :  0.9358085452269183  Prule test :  0.9616504854368931
190 1262.1598338718404 831.8109518691161 844.4325502078345 Accuracy: 0.9263  test :  0.8433  Prule Train :  0.9350474992600591  Prule test :  0.9586639932460954
195 196.63318977513927 820.164626697831 822.1309585955823 Accuracy: 0.9274  test :  0.8433  Prule Train :  0.9366631320881542  Prule test :  0.9566062449824649
Resultado | acc=0.8440 | bal_acc=0.6751 | f1=0.9071 | EOdds=0.0295 | EOp=0.0157 | p-rule=95.75 | score=0.6732 | tempo=0.12 min

FAGTB african_american_0:  90%|█████████ | 54/60 [04:59<00:33,  5.64s/modelo]

----------------------------------------------------------------------------------------------------
Treino 55/120 | config=african_american_0 | lambda=0.01 | n_estimators=100 | learning_rate=0.05 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1824.6832277190458 1834.1361949302814 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1705.7493284327265 1755.353131114592 1772.4106243989197 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 585.7384599716995 1691.989853906676 1697.8472385063928 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 337.54053002459614 1632.0333647631192 1635.408770063365 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2731.9125322834084 1577.9393907287053 1605.2585160515396 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1509.8155091791907 1527.9901423458775 1543.0882974376693 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 856.9088934607929 1481.5625029641328 1490.131591898741 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -191.13685956489138 1439.2746806785624 1437.3633120829136 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2860.7046598799943 1400.9893470827462 1429.596393681546 Accuracy: 0.8474  test :  0.83  Prule Train :  0.9646646058510217  Prule test :  0.9675019104693722
45 1800.13636307457 1364.694590683716 1382.6959543144615 Accuracy: 0.8683  test :  0.8387  Prule Train :  0.9541689809320841  Prule test :  0.9694159270317804
50 1172.540121643693 1331.1759741008286 1342.9013753172655 Accuracy: 0.8751  test :  0.8393  Prule Train :  0.9515820501904018  Prule test :  0.9587427331531974
55 -205.4907235856523 1300.016364220522 1297.9614569846658 Accuracy: 0.8794  test :  0.84  Prule Train :  0.9488773946094756  Prule test :  0.9614587182329515
60 2965.7159056207965 1272.3949516025705 1302.0521106587787 Accuracy: 0.8823  test :  0.84  Prule Train :  0.9459191083105836  Prule test :  0.957457529513389
65 2229.1366699698233 1245.2251792279258 1267.516545927624 Accuracy: 0.8831  test :  0.8413  Prule Train :  0.9470873904534126  Prule test :  0.9629235097009059
70 1157.313405700704 1220.1972482419337 1231.7703822989408 Accuracy: 0.8843  test :  0.8427  Prule Train :  0.9469304687756384  Prule test :  0.9570698713440615
75 -1636.7130711066193 1196.8525671047169 1180.4854363936506 Accuracy: 0.8854  test :  0.8433  Prule Train :  0.9450533865207992  Prule test :  0.9579813664596273
80 3273.0944577655487 1176.2841059536972 1209.0150505313527 Accuracy: 0.8877  test :  0.8433  Prule Train :  0.9430109741386921  Prule test :  0.9579813664596273
85 2035.0880325551905 1155.9187102811916 1176.2695906067436 Accuracy: 0.8883  test :  0.844  Prule Train :  0.9420684831595761  Prule test :  0.9568743776966478
90 1604.0983799773321 1136.3781259245009 1152.4191097242742 Accuracy: 0.8906  test :  0.844  Prule Train :  0.9382907107014469  Prule test :  0.9568743776966478
95 -2219.2854228965575 1117.1638654901556 1094.97101126119 Accuracy: 0.8929  test :  0.8433  Prule Train :  0.9379526027034933  Prule test :  0.9575941196068632
Resultado | acc=0.8433 | bal_acc=0.6626 | f1=0.9075 | EOdds=0.0474 | EOp=0.0124 | p-rule=95.76 | score=0.6599 | tempo=0.06 min

FAGTB african_american_0:  92%|█████████▏| 55/60 [05:03<00:25,  5.05s/modelo]

----------------------------------------------------------------------------------------------------
Treino 56/120 | config=african_american_0 | lambda=0.01 | n_estimators=200 | learning_rate=0.05 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1824.6832277190458 1834.1361949302814 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1705.7493284327265 1755.353131114592 1772.4106243989197 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 585.7384599716995 1691.989853906676 1697.8472385063928 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 337.54053002459614 1632.0333647631192 1635.408770063365 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2731.9125322834084 1577.9393907287053 1605.2585160515396 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 1509.8155091791907 1527.9901423458775 1543.0882974376693 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 856.9088934607929 1481.5625029641328 1490.131591898741 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -191.13685956489138 1439.2746806785624 1437.3633120829136 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 2860.7046598799943 1400.9893470827462 1429.596393681546 Accuracy: 0.8474  test :  0.83  Prule Train :  0.9646646058510217  Prule test :  0.9675019104693722
45 1800.13636307457 1364.694590683716 1382.6959543144615 Accuracy: 0.8683  test :  0.8387  Prule Train :  0.9541689809320841  Prule test :  0.9694159270317804
50 1172.540121643693 1331.1759741008286 1342.9013753172655 Accuracy: 0.8751  test :  0.8393  Prule Train :  0.9515820501904018  Prule test :  0.9587427331531974
55 -205.4907235856523 1300.016364220522 1297.9614569846658 Accuracy: 0.8794  test :  0.84  Prule Train :  0.9488773946094756  Prule test :  0.9614587182329515
60 2965.7159056207965 1272.3949516025705 1302.0521106587787 Accuracy: 0.8823  test :  0.84  Prule Train :  0.9459191083105836  Prule test :  0.957457529513389
65 2229.1366699698233 1245.2251792279258 1267.516545927624 Accuracy: 0.8831  test :  0.8413  Prule Train :  0.9470873904534126  Prule test :  0.9629235097009059
70 1157.313405700704 1220.1972482419337 1231.7703822989408 Accuracy: 0.8843  test :  0.8427  Prule Train :  0.9469304687756384  Prule test :  0.9570698713440615
75 -1636.7130711066193 1196.8525671047169 1180.4854363936506 Accuracy: 0.8854  test :  0.8433  Prule Train :  0.9450533865207992  Prule test :  0.9579813664596273
80 3273.0944577655487 1176.2841059536972 1209.0150505313527 Accuracy: 0.8877  test :  0.8433  Prule Train :  0.9430109741386921  Prule test :  0.9579813664596273
85 2035.0880325551905 1155.9187102811916 1176.2695906067436 Accuracy: 0.8883  test :  0.844  Prule Train :  0.9420684831595761  Prule test :  0.9568743776966478
90 1604.0983799773321 1136.3781259245009 1152.4191097242742 Accuracy: 0.8906  test :  0.844  Prule Train :  0.9382907107014469  Prule test :  0.9568743776966478
95 -2219.2854228965575 1117.1638654901556 1094.97101126119 Accuracy: 0.8929  test :  0.8433  Prule Train :  0.9379526027034933  Prule test :  0.9575941196068632
100 2834.7877749161453 1099.1149675809452 1127.4628453301068 Accuracy: 0.8943  test :  0.8433  Prule Train :  0.9381730087971596  Prule test :  0.9575941196068632
105 2426.6535725381746 1080.8751386615263 1105.141674386908 Accuracy: 0.8951  test :  0.8447  Prule Train :  0.9358818164066127  Prule test :  0.9594321121588918
110 1701.4424025596015 1063.2630122383043 1080.2774362639002 Accuracy: 0.8974  test :  0.8447  Prule Train :  0.9320701076192283  Prule test :  0.9612771739130435
115 -2583.5768973662543 1046.4241036881076 1020.5883347144451 Accuracy: 0.8997  test :  0.8453  Prule Train :  0.9334507667294681  Prule test :  0.9603537568391597
120 2832.546176830747 1030.930111180364 1059.2555729486717 Accuracy: 0.9009  test :  0.8453  Prule Train :  0.9350143358529681  Prule test :  0.9601658708218146
125 -1715.0199476326786 1014.0904059332556 996.9402064569288 Accuracy: 0.9023  test :  0.8453  Prule Train :  0.9369761787733478  Prule test :  0.9581254454739843
130 2588.8104233651597 999.9721670661172 1025.8602712997686 Accuracy: 0.9043  test :  0.8453  Prule Train :  0.937985813990428  Prule test :  0.9581254454739843
135 1253.045817439329 983.0789406363645 995.6093988107577 Accuracy: 0.9057  test :  0.846  Prule Train :  0.9364567698112748  Prule test :  0.955159112825458
140 -1645.2339440522605 966.4136708053661 949.9613313648435 Accuracy: 0.9089  test :  0.8467  Prule Train :  0.9337813920090428  Prule test :  0.9560810810810811
145 -36.13578070495123 950.4943766003114 950.1330187932618 Accuracy: 0.9109  test :  0.846  Prule Train :  0.9347897504124368  Prule test :  0.9570048309178745
150 2906.34747102715 935.205417859431 964.2688925697025 Accuracy: 0.9131  test :  0.8447  Prule Train :  0.9344351135458524  Prule test :  0.9570048309178745
155 1506.325532670801 920.6766079547617 935.7398632814698 Accuracy: 0.914  test :  0.844  Prule Train :  0.9320946406445205  Prule test :  0.9579303675048355
160 1480.9472213248637 904.5444380719796 919.3539102852283 Accuracy: 0.916  test :  0.8433  Prule Train :  0.9313354090055003  Prule test :  0.9588576960309777
165 1194.3942773036033 891.6299730032414 903.5739157762775 Accuracy: 0.9186  test :  0.8433  Prule Train :  0.9331417862418967  Prule test :  0.9588576960309777
170 -862.1877624793032 878.8771983522429 870.25532072745 Accuracy: 0.9194  test :  0.8427  Prule Train :  0.9343391452490504  Prule test :  0.9616504854368931
175 2421.335564906636 866.9693959967019 891.1827516457683 Accuracy: 0.9203  test :  0.8427  Prule Train :  0.9337598319480476  Prule test :  0.9616504854368931
180 2086.700875430437 855.8807830481514 876.7477918024558 Accuracy: 0.9226  test :  0.8427  Prule Train :  0.9369686286214086  Prule test :  0.9616504854368931
185 -344.6824917278173 843.4981275632002 840.0513026459221 Accuracy: 0.9243  test :  0.8427  Prule Train :  0.9358085452269183  Prule test :  0.9616504854368931
190 1262.1598338718404 831.8109518691161 844.4325502078345 Accuracy: 0.9263  test :  0.8433  Prule Train :  0.9350474992600591  Prule test :  0.9586639932460954
195 196.63318977513927 820.164626697831 822.1309585955823 Accuracy: 0.9274  test :  0.8433  Prule Train :  0.9366631320881542  Prule test :  0.9566062449824649
Resultado | acc=0.8440 | bal_acc=0.6751 | f1=0.9071 | EOdds=0.0295 | EOp=0.0157 | p-rule=95.75 | score=0.6732 | tempo=0.11 min

FAGTB african_american_0:  93%|█████████▎| 56/60 [05:10<00:22,  5.64s/modelo]

----------------------------------------------------------------------------------------------------
Treino 57/120 | config=african_american_0 | lambda=0.01 | n_estimators=100 | learning_rate=0.1 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1810.3902390860558 1819.8432062972913 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1723.352284963833 1679.1703346467602 1696.4038574963988 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 589.4380050583229 1567.229078572267 1573.1234586228502 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 209.2664898901566 1471.1067344337757 1473.1993993326778 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2769.633735055474 1392.381762790918 1420.0781001414728 Accuracy: 0.8634  test :  0.8387  Prule Train :  0.956050185226399  Prule test :  0.9638021045762298
25 1486.2354429526133 1322.903610406701 1337.765964836227 Accuracy: 0.876  test :  0.84  Prule Train :  0.9527496355280587  Prule test :  0.9594600147941152
30 915.259119901985 1261.6634779870988 1270.8160691861185 Accuracy: 0.8826  test :  0.8433  Prule Train :  0.9463082153070091  Prule test :  0.9561601091089436
35 -645.983337922918 1212.1667807756312 1205.706947396402 Accuracy: 0.8849  test :  0.8433  Prule Train :  0.9459923146754877  Prule test :  0.9579813664596273
40 2715.8397227127994 1167.8974893909412 1195.0558866180695 Accuracy: 0.8874  test :  0.8433  Prule Train :  0.9409011120528109  Prule test :  0.9559622000248684
45 2109.1083483344464 1129.0928836671405 1150.1839671504852 Accuracy: 0.8906  test :  0.8447  Prule Train :  0.9417403333153292  Prule test :  0.9539391802190508
50 317.3175397171433 1089.0630030386703 1092.2361784358416 Accuracy: 0.8957  test :  0.8447  Prule Train :  0.9401283506245818  Prule test :  0.9557631557070413
55 -1139.2660652521984 1053.656592520113 1042.2639318675913 Accuracy: 0.898  test :  0.8433  Prule Train :  0.9397927308086463  Prule test :  0.9573988222027316
60 2851.9835498873167 1020.7495976076634 1049.2694331065363 Accuracy: 0.9006  test :  0.842  Prule Train :  0.9381056314789145  Prule test :  0.9514889529298752
65 1597.0529763842096 990.8789704656102 1006.8495002294522 Accuracy: 0.9054  test :  0.8433  Prule Train :  0.9325639306725643  Prule test :  0.953320500481232
70 1323.8926133930845 960.7979613739057 974.0368875078366 Accuracy: 0.9106  test :  0.8427  Prule Train :  0.9308776194587489  Prule test :  0.9444386324643261
75 -1078.04286587225 929.5497077590194 918.769279100297 Accuracy: 0.9131  test :  0.8413  Prule Train :  0.9326709415275222  Prule test :  0.949924239235658
80 2494.2400798031213 904.436667643419 929.3790684414503 Accuracy: 0.9191  test :  0.842  Prule Train :  0.935717226584226  Prule test :  0.9508447084597236
85 2092.1853414707475 879.2902260030849 900.2120794177924 Accuracy: 0.9211  test :  0.8433  Prule Train :  0.9385271882256201  Prule test :  0.9547505587652342
90 355.97300297169994 853.479392434777 857.0391224644941 Accuracy: 0.9231  test :  0.8427  Prule Train :  0.9359866838285342  Prule test :  0.9517669632690929
95 -1255.6784430062842 830.2179019796604 817.6611175495975 Accuracy: 0.9246  test :  0.846  Prule Train :  0.9362113900591297  Prule test :  0.9485598883437657
Resultado | acc=0.8453 | bal_acc=0.6793 | f1=0.9078 | EOdds=0.0460 | EOp=0.0193 | p-rule=94.95 | score=0.6764 | tempo=0.06 min

FAGTB african_american_0:  95%|█████████▌| 57/60 [05:14<00:15,  5.05s/modelo]

----------------------------------------------------------------------------------------------------
Treino 58/120 | config=african_american_0 | lambda=0.01 | n_estimators=200 | learning_rate=0.1 | max_depth=3
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1810.3902390860558 1819.8432062972913 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1723.352284963833 1679.1703346467602 1696.4038574963988 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 589.4380050583229 1567.229078572267 1573.1234586228502 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 209.2664898901566 1471.1067344337757 1473.1993993326778 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2769.633735055474 1392.381762790918 1420.0781001414728 Accuracy: 0.8634  test :  0.8387  Prule Train :  0.956050185226399  Prule test :  0.9638021045762298
25 1486.2354429526133 1322.903610406701 1337.765964836227 Accuracy: 0.876  test :  0.84  Prule Train :  0.9527496355280587  Prule test :  0.9594600147941152
30 915.259119901985 1261.6634779870988 1270.8160691861185 Accuracy: 0.8826  test :  0.8433  Prule Train :  0.9463082153070091  Prule test :  0.9561601091089436
35 -645.983337922918 1212.1667807756312 1205.706947396402 Accuracy: 0.8849  test :  0.8433  Prule Train :  0.9459923146754877  Prule test :  0.9579813664596273
40 2715.8397227127994 1167.8974893909412 1195.0558866180695 Accuracy: 0.8874  test :  0.8433  Prule Train :  0.9409011120528109  Prule test :  0.9559622000248684
45 2109.1083483344464 1129.0928836671405 1150.1839671504852 Accuracy: 0.8906  test :  0.8447  Prule Train :  0.9417403333153292  Prule test :  0.9539391802190508
50 317.3175397171433 1089.0630030386703 1092.2361784358416 Accuracy: 0.8957  test :  0.8447  Prule Train :  0.9401283506245818  Prule test :  0.9557631557070413
55 -1139.2660652521984 1053.656592520113 1042.2639318675913 Accuracy: 0.898  test :  0.8433  Prule Train :  0.9397927308086463  Prule test :  0.9573988222027316
60 2851.9835498873167 1020.7495976076634 1049.2694331065363 Accuracy: 0.9006  test :  0.842  Prule Train :  0.9381056314789145  Prule test :  0.9514889529298752
65 1597.0529763842096 990.8789704656102 1006.8495002294522 Accuracy: 0.9054  test :  0.8433  Prule Train :  0.9325639306725643  Prule test :  0.953320500481232
70 1323.8926133930845 960.7979613739057 974.0368875078366 Accuracy: 0.9106  test :  0.8427  Prule Train :  0.9308776194587489  Prule test :  0.9444386324643261
75 -1078.04286587225 929.5497077590194 918.769279100297 Accuracy: 0.9131  test :  0.8413  Prule Train :  0.9326709415275222  Prule test :  0.949924239235658
80 2494.2400798031213 904.436667643419 929.3790684414503 Accuracy: 0.9191  test :  0.842  Prule Train :  0.935717226584226  Prule test :  0.9508447084597236
85 2092.1853414707475 879.2902260030849 900.2120794177924 Accuracy: 0.9211  test :  0.8433  Prule Train :  0.9385271882256201  Prule test :  0.9547505587652342
90 355.97300297169994 853.479392434777 857.0391224644941 Accuracy: 0.9231  test :  0.8427  Prule Train :  0.9359866838285342  Prule test :  0.9517669632690929
95 -1255.6784430062842 830.2179019796604 817.6611175495975 Accuracy: 0.9246  test :  0.846  Prule Train :  0.9362113900591297  Prule test :  0.9485598883437657
100 1649.480467725703 808.1017179506339 824.5965226278909 Accuracy: 0.9274  test :  0.8453  Prule Train :  0.9348675287661643  Prule test :  0.9494835104356292
105 1343.1036193102293 787.3855162277803 800.8165524208825 Accuracy: 0.9294  test :  0.8447  Prule Train :  0.9323042102670914  Prule test :  0.9504089329604204
110 2574.870838497592 769.4910206034193 795.2397289883952 Accuracy: 0.9314  test :  0.8447  Prule Train :  0.9315316106693688  Prule test :  0.9504089329604204
115 2047.1582804427026 752.9366084475396 773.4081912519666 Accuracy: 0.9334  test :  0.8447  Prule Train :  0.9325603961984327  Prule test :  0.9504089329604204
120 397.3261088395815 735.6101129856688 739.5833740740646 Accuracy: 0.9351  test :  0.844  Prule Train :  0.9295716314915893  Prule test :  0.9513361611876988
125 -1418.1015605549073 720.6604779438273 706.4794623382782 Accuracy: 0.9374  test :  0.8433  Prule Train :  0.9273832301276712  Prule test :  0.9483351007423119
130 -1243.4634801295024 704.6229578863947 692.1883230850997 Accuracy: 0.9406  test :  0.844  Prule Train :  0.9245852712319284  Prule test :  0.9492612092391305
135 1769.4595978469838 692.937197393723 710.6317933721928 Accuracy: 0.9417  test :  0.844  Prule Train :  0.9243889513248128  Prule test :  0.9492612092391305
140 1271.7751128097832 680.4936136029686 693.2113647310664 Accuracy: 0.9449  test :  0.8447  Prule Train :  0.9252137500225447  Prule test :  0.9501891283097454
145 -846.5492238256105 668.1895260959245 659.7240338576685 Accuracy: 0.946  test :  0.8453  Prule Train :  0.925017222980901  Prule test :  0.9511188632689528
150 1750.3061871530283 657.0377490303359 674.5408109018663 Accuracy: 0.9474  test :  0.844  Prule Train :  0.9233995613167306  Prule test :  0.9529838022165389
155 -1104.2021529020449 643.2438231194413 632.2018015904208 Accuracy: 0.9506  test :  0.8433  Prule Train :  0.9187269824306553  Prule test :  0.9539190169390281
160 2383.415524832042 631.6192756460202 655.4534308943406 Accuracy: 0.9517  test :  0.8447  Prule Train :  0.9185207968554677  Prule test :  0.9557949638749946
165 807.1656302603949 619.9773691600775 628.0490254626816 Accuracy: 0.9526  test :  0.8447  Prule Train :  0.9179071891603285  Prule test :  0.9557949638749946
170 -960.0539916160276 608.9134841705784 599.3129442544181 Accuracy: 0.9549  test :  0.8453  Prule Train :  0.9138165598261426  Prule test :  0.9567357069496748
175 1759.2267912205557 600.18393454437 617.7762024565757 Accuracy: 0.9563  test :  0.8453  Prule Train :  0.9121710226511192  Prule test :  0.9586227596261041
180 -942.5201252939775 589.2290454907105 579.8038442377707 Accuracy: 0.9583  test :  0.8453  Prule Train :  0.9113322461655845  Prule test :  0.9605172710087644
185 1443.7104417715695 581.3889857510405 595.8260901687562 Accuracy: 0.9589  test :  0.8447  Prule Train :  0.9139887809114083  Prule test :  0.9595690802180351
190 1132.216140904657 572.9543363865305 584.276497795577 Accuracy: 0.9603  test :  0.8447  Prule Train :  0.9123353901206326  Prule test :  0.9614673375478433
195 2226.1586787419365 564.0472478796598 586.3088346670792 Accuracy: 0.9614  test :  0.8447  Prule Train :  0.9102704649784602  Prule test :  0.9614673375478433
Resultado | acc=0.8447 | bal_acc=0.6876 | f1=0.9068 | EOdds=0.0141 | EOp=0.0141 | p-rule=96.15 | score=0.6865 | tempo=0.11 min

FAGTB african_american_0:  97%|█████████▋| 58/60 [05:21<00:11,  5.64s/modelo]

----------------------------------------------------------------------------------------------------
Treino 59/120 | config=african_american_0 | lambda=0.01 | n_estimators=100 | learning_rate=0.1 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1810.3902390860558 1819.8432062972913 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1723.352284963833 1679.1703346467602 1696.4038574963988 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 589.4380050583229 1567.229078572267 1573.1234586228502 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 209.2664898901566 1471.1067344337757 1473.1993993326778 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2769.633735055474 1392.381762790918 1420.0781001414728 Accuracy: 0.8634  test :  0.8387  Prule Train :  0.956050185226399  Prule test :  0.9638021045762298
25 1486.2354429526133 1322.903610406701 1337.765964836227 Accuracy: 0.876  test :  0.84  Prule Train :  0.9527496355280587  Prule test :  0.9594600147941152
30 915.259119901985 1261.6634779870988 1270.8160691861185 Accuracy: 0.8826  test :  0.8433  Prule Train :  0.9463082153070091  Prule test :  0.9561601091089436
35 -645.983337922918 1212.1667807756312 1205.706947396402 Accuracy: 0.8849  test :  0.8433  Prule Train :  0.9459923146754877  Prule test :  0.9579813664596273
40 2715.8397227127994 1167.8974893909412 1195.0558866180695 Accuracy: 0.8874  test :  0.8433  Prule Train :  0.9409011120528109  Prule test :  0.9559622000248684
45 2109.1083483344464 1129.0928836671405 1150.1839671504852 Accuracy: 0.8906  test :  0.8447  Prule Train :  0.9417403333153292  Prule test :  0.9539391802190508
50 317.3175397171433 1089.0630030386703 1092.2361784358416 Accuracy: 0.8957  test :  0.8447  Prule Train :  0.9401283506245818  Prule test :  0.9557631557070413
55 -1139.2660652521984 1053.656592520113 1042.2639318675913 Accuracy: 0.898  test :  0.8433  Prule Train :  0.9397927308086463  Prule test :  0.9573988222027316
60 2851.9835498873167 1020.7495976076634 1049.2694331065363 Accuracy: 0.9006  test :  0.842  Prule Train :  0.9381056314789145  Prule test :  0.9514889529298752
65 1597.0529763842096 990.8789704656102 1006.8495002294522 Accuracy: 0.9054  test :  0.8433  Prule Train :  0.9325639306725643  Prule test :  0.953320500481232
70 1323.8926133930845 960.7979613739057 974.0368875078366 Accuracy: 0.9106  test :  0.8427  Prule Train :  0.9308776194587489  Prule test :  0.9444386324643261
75 -1078.04286587225 929.5497077590194 918.769279100297 Accuracy: 0.9131  test :  0.8413  Prule Train :  0.9326709415275222  Prule test :  0.949924239235658
80 2494.2400798031213 904.436667643419 929.3790684414503 Accuracy: 0.9191  test :  0.842  Prule Train :  0.935717226584226  Prule test :  0.9508447084597236
85 2092.1853414707475 879.2902260030849 900.2120794177924 Accuracy: 0.9211  test :  0.8433  Prule Train :  0.9385271882256201  Prule test :  0.9547505587652342
90 355.97300297169994 853.479392434777 857.0391224644941 Accuracy: 0.9231  test :  0.8427  Prule Train :  0.9359866838285342  Prule test :  0.9517669632690929
95 -1255.6784430062842 830.2179019796604 817.6611175495975 Accuracy: 0.9246  test :  0.846  Prule Train :  0.9362113900591297  Prule test :  0.9485598883437657
Resultado | acc=0.8453 | bal_acc=0.6793 | f1=0.9078 | EOdds=0.0460 | EOp=0.0193 | p-rule=94.95 | score=0.6764 | tempo=0.06 min

FAGTB african_american_0:  98%|█████████▊| 59/60 [05:24<00:05,  5.04s/modelo]

----------------------------------------------------------------------------------------------------
Treino 60/120 | config=african_american_0 | lambda=0.01 | n_estimators=200 | learning_rate=0.1 | max_depth=5
----------------------------------------------------------------------------------------------------
0 945.2967211235476 1810.3902390860558 1819.8432062972913 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 1723.352284963833 1679.1703346467602 1696.4038574963988 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 589.4380050583229 1567.229078572267 1573.1234586228502 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 209.2664898901566 1471.1067344337757 1473.1993993326778 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 2769.633735055474 1392.381762790918 1420.0781001414728 Accuracy: 0.8634  test :  0.8387  Prule Train :  0.956050185226399  Prule test :  0.9638021045762298
25 1486.2354429526133 1322.903610406701 1337.765964836227 Accuracy: 0.876  test :  0.84  Prule Train :  0.9527496355280587  Prule test :  0.9594600147941152
30 915.259119901985 1261.6634779870988 1270.8160691861185 Accuracy: 0.8826  test :  0.8433  Prule Train :  0.9463082153070091  Prule test :  0.9561601091089436
35 -645.983337922918 1212.1667807756312 1205.706947396402 Accuracy: 0.8849  test :  0.8433  Prule Train :  0.9459923146754877  Prule test :  0.9579813664596273
40 2715.8397227127994 1167.8974893909412 1195.0558866180695 Accuracy: 0.8874  test :  0.8433  Prule Train :  0.9409011120528109  Prule test :  0.9559622000248684
45 2109.1083483344464 1129.0928836671405 1150.1839671504852 Accuracy: 0.8906  test :  0.8447  Prule Train :  0.9417403333153292  Prule test :  0.9539391802190508
50 317.3175397171433 1089.0630030386703 1092.2361784358416 Accuracy: 0.8957  test :  0.8447  Prule Train :  0.9401283506245818  Prule test :  0.9557631557070413
55 -1139.2660652521984 1053.656592520113 1042.2639318675913 Accuracy: 0.898  test :  0.8433  Prule Train :  0.9397927308086463  Prule test :  0.9573988222027316
60 2851.9835498873167 1020.7495976076634 1049.2694331065363 Accuracy: 0.9006  test :  0.842  Prule Train :  0.9381056314789145  Prule test :  0.9514889529298752
65 1597.0529763842096 990.8789704656102 1006.8495002294522 Accuracy: 0.9054  test :  0.8433  Prule Train :  0.9325639306725643  Prule test :  0.953320500481232
70 1323.8926133930845 960.7979613739057 974.0368875078366 Accuracy: 0.9106  test :  0.8427  Prule Train :  0.9308776194587489  Prule test :  0.9444386324643261
75 -1078.04286587225 929.5497077590194 918.769279100297 Accuracy: 0.9131  test :  0.8413  Prule Train :  0.9326709415275222  Prule test :  0.949924239235658
80 2494.2400798031213 904.436667643419 929.3790684414503 Accuracy: 0.9191  test :  0.842  Prule Train :  0.935717226584226  Prule test :  0.9508447084597236
85 2092.1853414707475 879.2902260030849 900.2120794177924 Accuracy: 0.9211  test :  0.8433  Prule Train :  0.9385271882256201  Prule test :  0.9547505587652342
90 355.97300297169994 853.479392434777 857.0391224644941 Accuracy: 0.9231  test :  0.8427  Prule Train :  0.9359866838285342  Prule test :  0.9517669632690929
95 -1255.6784430062842 830.2179019796604 817.6611175495975 Accuracy: 0.9246  test :  0.846  Prule Train :  0.9362113900591297  Prule test :  0.9485598883437657
100 1649.480467725703 808.1017179506339 824.5965226278909 Accuracy: 0.9274  test :  0.8453  Prule Train :  0.9348675287661643  Prule test :  0.9494835104356292
105 1343.1036193102293 787.3855162277803 800.8165524208825 Accuracy: 0.9294  test :  0.8447  Prule Train :  0.9323042102670914  Prule test :  0.9504089329604204
110 2574.870838497592 769.4910206034193 795.2397289883952 Accuracy: 0.9314  test :  0.8447  Prule Train :  0.9315316106693688  Prule test :  0.9504089329604204
115 2047.1582804427026 752.9366084475396 773.4081912519666 Accuracy: 0.9334  test :  0.8447  Prule Train :  0.9325603961984327  Prule test :  0.9504089329604204
120 397.3261088395815 735.6101129856688 739.5833740740646 Accuracy: 0.9351  test :  0.844  Prule Train :  0.9295716314915893  Prule test :  0.9513361611876988
125 -1418.1015605549073 720.6604779438273 706.4794623382782 Accuracy: 0.9374  test :  0.8433  Prule Train :  0.9273832301276712  Prule test :  0.9483351007423119
130 -1243.4634801295024 704.6229578863947 692.1883230850997 Accuracy: 0.9406  test :  0.844  Prule Train :  0.9245852712319284  Prule test :  0.9492612092391305
135 1769.4595978469838 692.937197393723 710.6317933721928 Accuracy: 0.9417  test :  0.844  Prule Train :  0.9243889513248128  Prule test :  0.9492612092391305
140 1271.7751128097832 680.4936136029686 693.2113647310664 Accuracy: 0.9449  test :  0.8447  Prule Train :  0.9252137500225447  Prule test :  0.9501891283097454
145 -846.5492238256105 668.1895260959245 659.7240338576685 Accuracy: 0.946  test :  0.8453  Prule Train :  0.925017222980901  Prule test :  0.9511188632689528
150 1750.3061871530283 657.0377490303359 674.5408109018663 Accuracy: 0.9474  test :  0.844  Prule Train :  0.9233995613167306  Prule test :  0.9529838022165389
155 -1104.2021529020449 643.2438231194413 632.2018015904208 Accuracy: 0.9506  test :  0.8433  Prule Train :  0.9187269824306553  Prule test :  0.9539190169390281
160 2383.415524832042 631.6192756460202 655.4534308943406 Accuracy: 0.9517  test :  0.8447  Prule Train :  0.9185207968554677  Prule test :  0.9557949638749946
165 807.1656302603949 619.9773691600775 628.0490254626816 Accuracy: 0.9526  test :  0.8447  Prule Train :  0.9179071891603285  Prule test :  0.9557949638749946
170 -960.0539916160276 608.9134841705784 599.3129442544181 Accuracy: 0.9549  test :  0.8453  Prule Train :  0.9138165598261426  Prule test :  0.9567357069496748
175 1759.2267912205557 600.18393454437 617.7762024565757 Accuracy: 0.9563  test :  0.8453  Prule Train :  0.9121710226511192  Prule test :  0.9586227596261041
180 -942.5201252939775 589.2290454907105 579.8038442377707 Accuracy: 0.9583  test :  0.8453  Prule Train :  0.9113322461655845  Prule test :  0.9605172710087644
185 1443.7104417715695 581.3889857510405 595.8260901687562 Accuracy: 0.9589  test :  0.8447  Prule Train :  0.9139887809114083  Prule test :  0.9595690802180351
190 1132.216140904657 572.9543363865305 584.276497795577 Accuracy: 0.9603  test :  0.8447  Prule Train :  0.9123353901206326  Prule test :  0.9614673375478433
195 2226.1586787419365 564.0472478796598 586.3088346670792 Accuracy: 0.9614  test :  0.8447  Prule Train :  0.9102704649784602  Prule test :  0.9614673375478433
Resultado | acc=0.8447 | bal_acc=0.6876 | f1=0.9068 | EOdds=0.0141 | EOp=0.0141 | p-rule=96.15 | score=0.6865 | tempo=0.11 min

FAGTB african_american_0: 100%|██████████| 60/60 [05:31<00:00,  5.53s/modelo]

====================================================================================================
Configuração sensível: caucasian_1
Atributo sensível: Applicant_Caucasian
====================================================================================================

FAGTB caucasian_1:   0%|          | 0/60 [00:00<?, ?modelo/s]

----------------------------------------------------------------------------------------------------
Treino 61/120 | config=caucasian_1 | lambda=0.0001 | n_estimators=100 | learning_rate=0.03 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1830.144982493527 1830.1604830895435 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2146.5179386115237 1787.124264566098 1787.338916359959 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2382.2778510869075 1747.0686755516572 1747.306903336766 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1220.4415832727045 1707.8074169760334 1707.9294611343607 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3316.403455476307 1668.6598687731785 1668.991509118726 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 342.7167462184426 1631.8096489855443 1631.8439206601663 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3707.6899101987647 1596.848759285168 1597.2195282761882 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 139.62603039430155 1563.8298113555688 1563.843773958608 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 3923.524848520531 1533.0971328689056 1533.489485353758 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 -103.22656786529457 1503.3141491850936 1503.303826528307 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 4182.485229206939 1475.7142205943287 1476.1324691172495 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -387.8585490927619 1449.8676393884375 1449.8288535335284 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 4477.084368576503 1424.9945263796917 1425.4422348165494 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 -707.1502276523472 1401.240473716669 1401.1697586939038 Accuracy: 0.7834  test :  0.782  Prule Train :  0.9999109504727481  Prule test :  0.998663101604278
70 4803.135210425493 1378.7864574003704 1379.266770921413 Accuracy: 0.8654  test :  0.8407  Prule Train :  0.9591759969684385  Prule test :  0.9679496825062445
75 -1054.017452052079 1357.1821034207683 1357.076701675563 Accuracy: 0.8683  test :  0.842  Prule Train :  0.9589339661541827  Prule test :  0.9679118196612622
80 5153.326032622092 1336.7077496340028 1337.2230822372649 Accuracy: 0.8726  test :  0.8427  Prule Train :  0.9567582176277828  Prule test :  0.9720423110680669
85 -1423.0286087314823 1316.9733131306193 1316.8310102697462 Accuracy: 0.8763  test :  0.842  Prule Train :  0.9558267994631631  Prule test :  0.9734269867248593
90 5523.799941043966 1298.1261157851295 1298.6784957792338 Accuracy: 0.8803  test :  0.8413  Prule Train :  0.9530441190015658  Prule test :  0.9720100624355945
95 -1809.2971041165085 1281.0796713430284 1280.8987416326167 Accuracy: 0.8829  test :  0.8427  Prule Train :  0.9509864881363054  Prule test :  0.9663423652785355
Resultado | acc=0.8420 | bal_acc=0.6541 | f1=0.9072 | EOdds=0.0437 | EOp=0.0009 | p-rule=96.77 | score=0.6519 | tempo=0.06 min

FAGTB caucasian_1:   2%|▏         | 1/60 [00:03<03:36,  3.67s/modelo]

----------------------------------------------------------------------------------------------------
Treino 62/120 | config=caucasian_1 | lambda=0.0001 | n_estimators=200 | learning_rate=0.03 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1830.144982493527 1830.1604830895435 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2146.5179386115237 1787.124264566098 1787.338916359959 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2382.2778510869075 1747.0686755516572 1747.306903336766 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1220.4415832727045 1707.8074169760334 1707.9294611343607 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3316.403455476307 1668.6598687731785 1668.991509118726 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 342.7167462184426 1631.8096489855443 1631.8439206601663 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3707.6899101987647 1596.848759285168 1597.2195282761882 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 139.62603039430155 1563.8298113555688 1563.843773958608 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 3923.524848520531 1533.0971328689056 1533.489485353758 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 -103.22656786529457 1503.3141491850936 1503.303826528307 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 4182.485229206939 1475.7142205943287 1476.1324691172495 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -387.8585490927619 1449.8676393884375 1449.8288535335284 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 4477.084368576503 1424.9945263796917 1425.4422348165494 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 -707.1502276523472 1401.240473716669 1401.1697586939038 Accuracy: 0.7834  test :  0.782  Prule Train :  0.9999109504727481  Prule test :  0.998663101604278
70 4803.135210425493 1378.7864574003704 1379.266770921413 Accuracy: 0.8654  test :  0.8407  Prule Train :  0.9591759969684385  Prule test :  0.9679496825062445
75 -1054.017452052079 1357.1821034207683 1357.076701675563 Accuracy: 0.8683  test :  0.842  Prule Train :  0.9589339661541827  Prule test :  0.9679118196612622
80 5153.326032622092 1336.7077496340028 1337.2230822372649 Accuracy: 0.8726  test :  0.8427  Prule Train :  0.9567582176277828  Prule test :  0.9720423110680669
85 -1423.0286087314823 1316.9733131306193 1316.8310102697462 Accuracy: 0.8763  test :  0.842  Prule Train :  0.9558267994631631  Prule test :  0.9734269867248593
90 5523.799941043966 1298.1261157851295 1298.6784957792338 Accuracy: 0.8803  test :  0.8413  Prule Train :  0.9530441190015658  Prule test :  0.9720100624355945
95 -1809.2971041165085 1281.0796713430284 1280.8987416326167 Accuracy: 0.8829  test :  0.8427  Prule Train :  0.9509864881363054  Prule test :  0.9663423652785355
100 5913.682573017884 1264.5707695406056 1265.1621377979072 Accuracy: 0.8834  test :  0.842  Prule Train :  0.950932471956238  Prule test :  0.9676823708206688
105 -2207.460046090966 1249.015899864272 1248.795153859663 Accuracy: 0.8849  test :  0.8407  Prule Train :  0.9514047206354899  Prule test :  0.9676050112784247
110 6315.845304331222 1233.4721487359075 1234.103733266341 Accuracy: 0.8854  test :  0.8407  Prule Train :  0.9513508279543711  Prule test :  0.964754922879961
115 -2615.356984724551 1217.3665906108863 1217.1050549124138 Accuracy: 0.8866  test :  0.8407  Prule Train :  0.9488105053163085  Prule test :  0.964754922879961
120 6729.478705001076 1201.9662659838073 1202.6392138543072 Accuracy: 0.8871  test :  0.8407  Prule Train :  0.9487549939872679  Prule test :  0.964754922879961
125 -3031.5918120790348 1187.7744142271702 1187.4712550459622 Accuracy: 0.8877  test :  0.8407  Prule Train :  0.9486994147544607  Prule test :  0.964754922879961
130 7166.152949934052 1174.4076415568215 1175.1242568518148 Accuracy: 0.8891  test :  0.8407  Prule Train :  0.9503886671268645  Prule test :  0.964754922879961
135 -3456.3064947650464 1160.4448437424066 1160.0992130929303 Accuracy: 0.8897  test :  0.8407  Prule Train :  0.950333919659073  Prule test :  0.9675272071411104
140 7612.138073095632 1147.4671678054524 1148.228381612762 Accuracy: 0.8914  test :  0.842  Prule Train :  0.9513930104336006  Prule test :  0.9646689288334556
145 -3885.506880388472 1134.2705122094776 1133.8819615214386 Accuracy: 0.8926  test :  0.842  Prule Train :  0.9488355023410374  Prule test :  0.9646689288334556
150 8071.4070551337745 1121.8066033223795 1122.6137440278926 Accuracy: 0.8929  test :  0.842  Prule Train :  0.9481961253178965  Prule test :  0.9646689288334556
155 -4320.04113082572 1109.5817636301492 1109.1497595170665 Accuracy: 0.8931  test :  0.842  Prule Train :  0.9475567482947557  Prule test :  0.9646689288334556
160 8532.036773765723 1097.4737215270068 1098.3269252043835 Accuracy: 0.8943  test :  0.8427  Prule Train :  0.9449992402021921  Prule test :  0.966056941680698
165 -4753.346999965424 1085.6587890010587 1085.1834543010623 Accuracy: 0.8966  test :  0.8427  Prule Train :  0.9435432097169622  Prule test :  0.966056941680698
170 8975.498345977541 1074.1228101074585 1075.0203599420563 Accuracy: 0.898  test :  0.8433  Prule Train :  0.9427833116913934  Prule test :  0.9674489545649643
175 -5163.256000429175 1063.0147495865313 1062.4984239864882 Accuracy: 0.8989  test :  0.842  Prule Train :  0.9433058191551088  Prule test :  0.9702096868553131
180 9289.998459027991 1052.1125005999575 1053.0415004458605 Accuracy: 0.9003  test :  0.8427  Prule Train :  0.9437703385723188  Prule test :  0.9715823117067598
185 -5450.3799316250515 1041.372203135813 1040.8271651426503 Accuracy: 0.9011  test :  0.8427  Prule Train :  0.9430672526647759  Prule test :  0.9715823117067598
190 9110.712814134638 1030.9435054596365 1031.85457674105 Accuracy: 0.9023  test :  0.842  Prule Train :  0.9429475257125598  Prule test :  0.972962928551519
195 -5416.604366379415 1020.9331245206042 1020.3914640839663 Accuracy: 0.904  test :  0.8427  Prule Train :  0.9427673775499862  Prule test :  0.9715150670506983
Resultado | acc=0.8413 | bal_acc=0.6668 | f1=0.9059 | EOdds=0.0198 | EOp=0.0035 | p-rule=96.86 | score=0.6657 | tempo=0.12 min

FAGTB caucasian_1:   3%|▎         | 2/60 [00:10<05:28,  5.66s/modelo]

----------------------------------------------------------------------------------------------------
Treino 63/120 | config=caucasian_1 | lambda=0.0001 | n_estimators=100 | learning_rate=0.03 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1830.144982493527 1830.1604830895435 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2146.5179386115237 1787.124264566098 1787.338916359959 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2382.2778510869075 1747.0686755516572 1747.306903336766 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1220.4415832727045 1707.8074169760334 1707.9294611343607 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3316.403455476307 1668.6598687731785 1668.991509118726 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 342.7167462184426 1631.8096489855443 1631.8439206601663 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3707.6899101987647 1596.848759285168 1597.2195282761882 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 139.62603039430155 1563.8298113555688 1563.843773958608 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 3923.524848520531 1533.0971328689056 1533.489485353758 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 -103.22656786529457 1503.3141491850936 1503.303826528307 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 4182.485229206939 1475.7142205943287 1476.1324691172495 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -387.8585490927619 1449.8676393884375 1449.8288535335284 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 4477.084368576503 1424.9945263796917 1425.4422348165494 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 -707.1502276523472 1401.240473716669 1401.1697586939038 Accuracy: 0.7834  test :  0.782  Prule Train :  0.9999109504727481  Prule test :  0.998663101604278
70 4803.135210425493 1378.7864574003704 1379.266770921413 Accuracy: 0.8654  test :  0.8407  Prule Train :  0.9591759969684385  Prule test :  0.9679496825062445
75 -1054.017452052079 1357.1821034207683 1357.076701675563 Accuracy: 0.8683  test :  0.842  Prule Train :  0.9589339661541827  Prule test :  0.9679118196612622
80 5153.326032622092 1336.7077496340028 1337.2230822372649 Accuracy: 0.8726  test :  0.8427  Prule Train :  0.9567582176277828  Prule test :  0.9720423110680669
85 -1423.0286087314823 1316.9733131306193 1316.8310102697462 Accuracy: 0.8763  test :  0.842  Prule Train :  0.9558267994631631  Prule test :  0.9734269867248593
90 5523.799941043966 1298.1261157851295 1298.6784957792338 Accuracy: 0.8803  test :  0.8413  Prule Train :  0.9530441190015658  Prule test :  0.9720100624355945
95 -1809.2971041165085 1281.0796713430284 1280.8987416326167 Accuracy: 0.8829  test :  0.8427  Prule Train :  0.9509864881363054  Prule test :  0.9663423652785355
Resultado | acc=0.8420 | bal_acc=0.6541 | f1=0.9072 | EOdds=0.0437 | EOp=0.0009 | p-rule=96.77 | score=0.6519 | tempo=0.06 min

FAGTB caucasian_1:   5%|▌         | 3/60 [00:14<04:30,  4.75s/modelo]

----------------------------------------------------------------------------------------------------
Treino 64/120 | config=caucasian_1 | lambda=0.0001 | n_estimators=200 | learning_rate=0.03 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1830.144982493527 1830.1604830895435 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2146.5179386115237 1787.124264566098 1787.338916359959 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2382.2778510869075 1747.0686755516572 1747.306903336766 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1220.4415832727045 1707.8074169760334 1707.9294611343607 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3316.403455476307 1668.6598687731785 1668.991509118726 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 342.7167462184426 1631.8096489855443 1631.8439206601663 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3707.6899101987647 1596.848759285168 1597.2195282761882 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 139.62603039430155 1563.8298113555688 1563.843773958608 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 3923.524848520531 1533.0971328689056 1533.489485353758 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 -103.22656786529457 1503.3141491850936 1503.303826528307 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 4182.485229206939 1475.7142205943287 1476.1324691172495 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -387.8585490927619 1449.8676393884375 1449.8288535335284 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 4477.084368576503 1424.9945263796917 1425.4422348165494 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 -707.1502276523472 1401.240473716669 1401.1697586939038 Accuracy: 0.7834  test :  0.782  Prule Train :  0.9999109504727481  Prule test :  0.998663101604278
70 4803.135210425493 1378.7864574003704 1379.266770921413 Accuracy: 0.8654  test :  0.8407  Prule Train :  0.9591759969684385  Prule test :  0.9679496825062445
75 -1054.017452052079 1357.1821034207683 1357.076701675563 Accuracy: 0.8683  test :  0.842  Prule Train :  0.9589339661541827  Prule test :  0.9679118196612622
80 5153.326032622092 1336.7077496340028 1337.2230822372649 Accuracy: 0.8726  test :  0.8427  Prule Train :  0.9567582176277828  Prule test :  0.9720423110680669
85 -1423.0286087314823 1316.9733131306193 1316.8310102697462 Accuracy: 0.8763  test :  0.842  Prule Train :  0.9558267994631631  Prule test :  0.9734269867248593
90 5523.799941043966 1298.1261157851295 1298.6784957792338 Accuracy: 0.8803  test :  0.8413  Prule Train :  0.9530441190015658  Prule test :  0.9720100624355945
95 -1809.2971041165085 1281.0796713430284 1280.8987416326167 Accuracy: 0.8829  test :  0.8427  Prule Train :  0.9509864881363054  Prule test :  0.9663423652785355
100 5913.682573017884 1264.5707695406056 1265.1621377979072 Accuracy: 0.8834  test :  0.842  Prule Train :  0.950932471956238  Prule test :  0.9676823708206688
105 -2207.460046090966 1249.015899864272 1248.795153859663 Accuracy: 0.8849  test :  0.8407  Prule Train :  0.9514047206354899  Prule test :  0.9676050112784247
110 6315.845304331222 1233.4721487359075 1234.103733266341 Accuracy: 0.8854  test :  0.8407  Prule Train :  0.9513508279543711  Prule test :  0.964754922879961
115 -2615.356984724551 1217.3665906108863 1217.1050549124138 Accuracy: 0.8866  test :  0.8407  Prule Train :  0.9488105053163085  Prule test :  0.964754922879961
120 6729.478705001076 1201.9662659838073 1202.6392138543072 Accuracy: 0.8871  test :  0.8407  Prule Train :  0.9487549939872679  Prule test :  0.964754922879961
125 -3031.5918120790348 1187.7744142271702 1187.4712550459622 Accuracy: 0.8877  test :  0.8407  Prule Train :  0.9486994147544607  Prule test :  0.964754922879961
130 7166.152949934052 1174.4076415568215 1175.1242568518148 Accuracy: 0.8891  test :  0.8407  Prule Train :  0.9503886671268645  Prule test :  0.964754922879961
135 -3456.3064947650464 1160.4448437424066 1160.0992130929303 Accuracy: 0.8897  test :  0.8407  Prule Train :  0.950333919659073  Prule test :  0.9675272071411104
140 7612.138073095632 1147.4671678054524 1148.228381612762 Accuracy: 0.8914  test :  0.842  Prule Train :  0.9513930104336006  Prule test :  0.9646689288334556
145 -3885.506880388472 1134.2705122094776 1133.8819615214386 Accuracy: 0.8926  test :  0.842  Prule Train :  0.9488355023410374  Prule test :  0.9646689288334556
150 8071.4070551337745 1121.8066033223795 1122.6137440278926 Accuracy: 0.8929  test :  0.842  Prule Train :  0.9481961253178965  Prule test :  0.9646689288334556
155 -4320.04113082572 1109.5817636301492 1109.1497595170665 Accuracy: 0.8931  test :  0.842  Prule Train :  0.9475567482947557  Prule test :  0.9646689288334556
160 8532.036773765723 1097.4737215270068 1098.3269252043835 Accuracy: 0.8943  test :  0.8427  Prule Train :  0.9449992402021921  Prule test :  0.966056941680698
165 -4753.346999965424 1085.6587890010587 1085.1834543010623 Accuracy: 0.8966  test :  0.8427  Prule Train :  0.9435432097169622  Prule test :  0.966056941680698
170 8975.498345977541 1074.1228101074585 1075.0203599420563 Accuracy: 0.898  test :  0.8433  Prule Train :  0.9427833116913934  Prule test :  0.9674489545649643
175 -5163.256000429175 1063.0147495865313 1062.4984239864882 Accuracy: 0.8989  test :  0.842  Prule Train :  0.9433058191551088  Prule test :  0.9702096868553131
180 9289.998459027991 1052.1125005999575 1053.0415004458605 Accuracy: 0.9003  test :  0.8427  Prule Train :  0.9437703385723188  Prule test :  0.9715823117067598
185 -5450.3799316250515 1041.372203135813 1040.8271651426503 Accuracy: 0.9011  test :  0.8427  Prule Train :  0.9430672526647759  Prule test :  0.9715823117067598
190 9110.712814134638 1030.9435054596365 1031.85457674105 Accuracy: 0.9023  test :  0.842  Prule Train :  0.9429475257125598  Prule test :  0.972962928551519
195 -5416.604366379415 1020.9331245206042 1020.3914640839663 Accuracy: 0.904  test :  0.8427  Prule Train :  0.9427673775499862  Prule test :  0.9715150670506983
Resultado | acc=0.8413 | bal_acc=0.6668 | f1=0.9059 | EOdds=0.0198 | EOp=0.0035 | p-rule=96.86 | score=0.6657 | tempo=0.12 min

FAGTB caucasian_1:   7%|▋         | 4/60 [00:21<05:20,  5.72s/modelo]

----------------------------------------------------------------------------------------------------
Treino 65/120 | config=caucasian_1 | lambda=0.0001 | n_estimators=100 | learning_rate=0.05 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1824.1995449475883 1824.2150455436051 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2131.0015581769176 1754.5577784271845 1754.770878583002 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2425.002817105802 1689.679807824651 1689.922308106362 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1128.5398555156848 1626.9059565520986 1627.0188105376503 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3452.643209701585 1569.8092718660414 1570.1545361870114 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 185.02193807251388 1518.7841086824874 1518.8026108762947 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3876.4143119088662 1471.7986617568388 1472.1863031880298 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -110.2621840779587 1429.1885578100782 1429.1775315916702 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 4177.295297775899 1389.9414192248805 1390.359148754658 Accuracy: 0.8643  test :  0.84  Prule Train :  0.9592724032508335  Prule test :  0.966582521937733
45 -467.9883185969901 1353.8959600455055 1353.8491612136459 Accuracy: 0.8689  test :  0.842  Prule Train :  0.9600893082820793  Prule test :  0.9679118196612622
50 4520.609658665777 1320.899160626207 1321.3512215920737 Accuracy: 0.8757  test :  0.842  Prule Train :  0.95708695345059  Prule test :  0.9734269867248593
55 -864.4647749121015 1289.5305132034869 1289.4440667259958 Accuracy: 0.8826  test :  0.842  Prule Train :  0.9516196349326677  Prule test :  0.9677592895678001
60 4895.563781428362 1261.9320572792572 1262.4216136573998 Accuracy: 0.884  test :  0.8407  Prule Train :  0.9520928532520969  Prule test :  0.9648829938992928
65 -1282.5711196662724 1236.2155404366376 1236.0872833246713 Accuracy: 0.8857  test :  0.84  Prule Train :  0.9507157472948555  Prule test :  0.9634640483200292
70 5286.728206602907 1209.4817248376312 1210.0103976582914 Accuracy: 0.8866  test :  0.8393  Prule Train :  0.9488105053163085  Prule test :  0.9619984802431609
75 -1711.750025486289 1185.1622222097703 1184.9910472072215 Accuracy: 0.8883  test :  0.84  Prule Train :  0.9486437674932165  Prule test :  0.9633747298572427
80 5710.368493983435 1162.4623337351054 1163.0333705845037 Accuracy: 0.8903  test :  0.8407  Prule Train :  0.9490583036595305  Prule test :  0.964754922879961
85 -2152.5948617274735 1140.2206726287923 1140.0054131426195 Accuracy: 0.8914  test :  0.8427  Prule Train :  0.9489470398561308  Prule test :  0.963284898806435
90 6151.3047091882245 1119.1415029416082 1119.7566334125272 Accuracy: 0.8929  test :  0.8433  Prule Train :  0.9481961253178965  Prule test :  0.9646689288334556
95 -2600.910493013317 1098.5835048823442 1098.3234138330427 Accuracy: 0.8946  test :  0.844  Prule Train :  0.9468031968031968  Prule test :  0.966056941680698
Resultado | acc=0.8440 | bal_acc=0.6642 | f1=0.9079 | EOdds=0.0236 | EOp=0.0064 | p-rule=96.60 | score=0.6628 | tempo=0.06 min

FAGTB caucasian_1:   8%|▊         | 5/60 [00:25<04:34,  4.99s/modelo]

----------------------------------------------------------------------------------------------------
Treino 66/120 | config=caucasian_1 | lambda=0.0001 | n_estimators=200 | learning_rate=0.05 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1824.1995449475883 1824.2150455436051 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2131.0015581769176 1754.5577784271845 1754.770878583002 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2425.002817105802 1689.679807824651 1689.922308106362 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1128.5398555156848 1626.9059565520986 1627.0188105376503 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3452.643209701585 1569.8092718660414 1570.1545361870114 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 185.02193807251388 1518.7841086824874 1518.8026108762947 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3876.4143119088662 1471.7986617568388 1472.1863031880298 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -110.2621840779587 1429.1885578100782 1429.1775315916702 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 4177.295297775899 1389.9414192248805 1390.359148754658 Accuracy: 0.8643  test :  0.84  Prule Train :  0.9592724032508335  Prule test :  0.966582521937733
45 -467.9883185969901 1353.8959600455055 1353.8491612136459 Accuracy: 0.8689  test :  0.842  Prule Train :  0.9600893082820793  Prule test :  0.9679118196612622
50 4520.609658665777 1320.899160626207 1321.3512215920737 Accuracy: 0.8757  test :  0.842  Prule Train :  0.95708695345059  Prule test :  0.9734269867248593
55 -864.4647749121015 1289.5305132034869 1289.4440667259958 Accuracy: 0.8826  test :  0.842  Prule Train :  0.9516196349326677  Prule test :  0.9677592895678001
60 4895.563781428362 1261.9320572792572 1262.4216136573998 Accuracy: 0.884  test :  0.8407  Prule Train :  0.9520928532520969  Prule test :  0.9648829938992928
65 -1282.5711196662724 1236.2155404366376 1236.0872833246713 Accuracy: 0.8857  test :  0.84  Prule Train :  0.9507157472948555  Prule test :  0.9634640483200292
70 5286.728206602907 1209.4817248376312 1210.0103976582914 Accuracy: 0.8866  test :  0.8393  Prule Train :  0.9488105053163085  Prule test :  0.9619984802431609
75 -1711.750025486289 1185.1622222097703 1184.9910472072215 Accuracy: 0.8883  test :  0.84  Prule Train :  0.9486437674932165  Prule test :  0.9633747298572427
80 5710.368493983435 1162.4623337351054 1163.0333705845037 Accuracy: 0.8903  test :  0.8407  Prule Train :  0.9490583036595305  Prule test :  0.964754922879961
85 -2152.5948617274735 1140.2206726287923 1140.0054131426195 Accuracy: 0.8914  test :  0.8427  Prule Train :  0.9489470398561308  Prule test :  0.963284898806435
90 6151.3047091882245 1119.1415029416082 1119.7566334125272 Accuracy: 0.8929  test :  0.8433  Prule Train :  0.9481961253178965  Prule test :  0.9646689288334556
95 -2600.910493013317 1098.5835048823442 1098.3234138330427 Accuracy: 0.8946  test :  0.844  Prule Train :  0.9468031968031968  Prule test :  0.966056941680698
100 6607.85593517917 1079.4849182835555 1080.1457038770736 Accuracy: 0.8966  test :  0.844  Prule Train :  0.9447658794144612  Prule test :  0.9660156968544975
105 -3047.922145921756 1061.08439637148 1060.7796041568877 Accuracy: 0.8986  test :  0.8433  Prule Train :  0.9427235316124205  Prule test :  0.9645390070921985
110 7074.677476623386 1043.450653598266 1044.158121345928 Accuracy: 0.9017  test :  0.8427  Prule Train :  0.9430074262788017  Prule test :  0.9687326549491212
115 -3492.708273710323 1025.815115975343 1025.465845147972 Accuracy: 0.9034  test :  0.8427  Prule Train :  0.9415976909773436  Prule test :  0.968657224146462
120 7538.817042331469 1009.6225051919799 1010.376386896213 Accuracy: 0.9057  test :  0.84  Prule Train :  0.9438208118158307  Prule test :  0.9686193440490569
125 -3925.2443263879536 994.3644599591503 993.9719355265115 Accuracy: 0.9069  test :  0.8393  Prule Train :  0.9449386130608839  Prule test :  0.9671714825482363
130 7972.662020614931 979.9508494718787 980.7481156739402 Accuracy: 0.9086  test :  0.8413  Prule Train :  0.9422836838567176  Prule test :  0.9657236210474156
135 -4317.2617741658905 966.8276074198629 966.3958812424463 Accuracy: 0.9109  test :  0.8413  Prule Train :  0.939562937062937  Prule test :  0.9657236210474156
140 8186.914785098396 953.4591965254763 954.2778880039862 Accuracy: 0.9123  test :  0.84  Prule Train :  0.9400259519232596  Prule test :  0.9685432520577731
145 -4492.167601830408 939.1174013958616 938.6681846356786 Accuracy: 0.9137  test :  0.84  Prule Train :  0.9429782947370887  Prule test :  0.9713793962804896
150 7867.109405067614 925.5808259046964 926.3675368452032 Accuracy: 0.9149  test :  0.84  Prule Train :  0.9428567239887995  Prule test :  0.9713793962804896
155 -4360.010710958591 912.8348198007398 912.3988187296438 Accuracy: 0.9169  test :  0.84  Prule Train :  0.9407708160856775  Prule test :  0.9713793962804896
160 7588.973543134834 898.2327106638179 898.9916080181314 Accuracy: 0.918  test :  0.84  Prule Train :  0.9406461550219432  Prule test :  0.9713793962804896
165 -4174.059823995642 886.4746103137559 886.0572043313564 Accuracy: 0.9194  test :  0.8407  Prule Train :  0.9411153176156336  Prule test :  0.9699230553565309
170 7407.866800215759 873.861588665223 874.6023753452447 Accuracy: 0.9203  test :  0.8407  Prule Train :  0.941648273716585  Prule test :  0.9699230553565309
175 -4002.6100629088323 862.4830443692846 862.0827833629937 Accuracy: 0.9211  test :  0.8407  Prule Train :  0.9421825799279886  Prule test :  0.9699230553565309
180 7251.422730411903 852.2720654907616 852.9972077638029 Accuracy: 0.922  test :  0.8407  Prule Train :  0.9414620022985044  Prule test :  0.9699230553565309
185 -3847.5120147230846 843.176661915722 842.7919107142498 Accuracy: 0.9229  test :  0.8413  Prule Train :  0.9419970892052112  Prule test :  0.9684667144325723
190 7088.148940562243 834.0049711765641 834.7137860706202 Accuracy: 0.9249  test :  0.8427  Prule Train :  0.9386346986346987  Prule test :  0.9684282772820865
195 -3717.89200749229 824.7937075910324 824.4219183902833 Accuracy: 0.9254  test :  0.8427  Prule Train :  0.9385705357751101  Prule test :  0.9684282772820865
Resultado | acc=0.8420 | bal_acc=0.6738 | f1=0.9058 | EOdds=0.0265 | EOp=0.0021 | p-rule=96.70 | score=0.6725 | tempo=0.12 min

FAGTB caucasian_1:  10%|█         | 6/60 [00:32<05:10,  5.75s/modelo]

----------------------------------------------------------------------------------------------------
Treino 67/120 | config=caucasian_1 | lambda=0.0001 | n_estimators=100 | learning_rate=0.05 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1824.1995449475883 1824.2150455436051 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2131.0015581769176 1754.5577784271845 1754.770878583002 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2425.002817105802 1689.679807824651 1689.922308106362 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1128.5398555156848 1626.9059565520986 1627.0188105376503 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3452.643209701585 1569.8092718660414 1570.1545361870114 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 185.02193807251388 1518.7841086824874 1518.8026108762947 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3876.4143119088662 1471.7986617568388 1472.1863031880298 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -110.2621840779587 1429.1885578100782 1429.1775315916702 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 4177.295297775899 1389.9414192248805 1390.359148754658 Accuracy: 0.8643  test :  0.84  Prule Train :  0.9592724032508335  Prule test :  0.966582521937733
45 -467.9883185969901 1353.8959600455055 1353.8491612136459 Accuracy: 0.8689  test :  0.842  Prule Train :  0.9600893082820793  Prule test :  0.9679118196612622
50 4520.609658665777 1320.899160626207 1321.3512215920737 Accuracy: 0.8757  test :  0.842  Prule Train :  0.95708695345059  Prule test :  0.9734269867248593
55 -864.4647749121015 1289.5305132034869 1289.4440667259958 Accuracy: 0.8826  test :  0.842  Prule Train :  0.9516196349326677  Prule test :  0.9677592895678001
60 4895.563781428362 1261.9320572792572 1262.4216136573998 Accuracy: 0.884  test :  0.8407  Prule Train :  0.9520928532520969  Prule test :  0.9648829938992928
65 -1282.5711196662724 1236.2155404366376 1236.0872833246713 Accuracy: 0.8857  test :  0.84  Prule Train :  0.9507157472948555  Prule test :  0.9634640483200292
70 5286.728206602907 1209.4817248376312 1210.0103976582914 Accuracy: 0.8866  test :  0.8393  Prule Train :  0.9488105053163085  Prule test :  0.9619984802431609
75 -1711.750025486289 1185.1622222097703 1184.9910472072215 Accuracy: 0.8883  test :  0.84  Prule Train :  0.9486437674932165  Prule test :  0.9633747298572427
80 5710.368493983435 1162.4623337351054 1163.0333705845037 Accuracy: 0.8903  test :  0.8407  Prule Train :  0.9490583036595305  Prule test :  0.964754922879961
85 -2152.5948617274735 1140.2206726287923 1140.0054131426195 Accuracy: 0.8914  test :  0.8427  Prule Train :  0.9489470398561308  Prule test :  0.963284898806435
90 6151.3047091882245 1119.1415029416082 1119.7566334125272 Accuracy: 0.8929  test :  0.8433  Prule Train :  0.9481961253178965  Prule test :  0.9646689288334556
95 -2600.910493013317 1098.5835048823442 1098.3234138330427 Accuracy: 0.8946  test :  0.844  Prule Train :  0.9468031968031968  Prule test :  0.966056941680698
Resultado | acc=0.8440 | bal_acc=0.6642 | f1=0.9079 | EOdds=0.0236 | EOp=0.0064 | p-rule=96.60 | score=0.6628 | tempo=0.06 min

FAGTB caucasian_1:  12%|█▏        | 7/60 [00:36<04:28,  5.08s/modelo]

----------------------------------------------------------------------------------------------------
Treino 68/120 | config=caucasian_1 | lambda=0.0001 | n_estimators=200 | learning_rate=0.05 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1824.1995449475883 1824.2150455436051 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2131.0015581769176 1754.5577784271845 1754.770878583002 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2425.002817105802 1689.679807824651 1689.922308106362 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1128.5398555156848 1626.9059565520986 1627.0188105376503 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3452.643209701585 1569.8092718660414 1570.1545361870114 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 185.02193807251388 1518.7841086824874 1518.8026108762947 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3876.4143119088662 1471.7986617568388 1472.1863031880298 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -110.2621840779587 1429.1885578100782 1429.1775315916702 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 4177.295297775899 1389.9414192248805 1390.359148754658 Accuracy: 0.8643  test :  0.84  Prule Train :  0.9592724032508335  Prule test :  0.966582521937733
45 -467.9883185969901 1353.8959600455055 1353.8491612136459 Accuracy: 0.8689  test :  0.842  Prule Train :  0.9600893082820793  Prule test :  0.9679118196612622
50 4520.609658665777 1320.899160626207 1321.3512215920737 Accuracy: 0.8757  test :  0.842  Prule Train :  0.95708695345059  Prule test :  0.9734269867248593
55 -864.4647749121015 1289.5305132034869 1289.4440667259958 Accuracy: 0.8826  test :  0.842  Prule Train :  0.9516196349326677  Prule test :  0.9677592895678001
60 4895.563781428362 1261.9320572792572 1262.4216136573998 Accuracy: 0.884  test :  0.8407  Prule Train :  0.9520928532520969  Prule test :  0.9648829938992928
65 -1282.5711196662724 1236.2155404366376 1236.0872833246713 Accuracy: 0.8857  test :  0.84  Prule Train :  0.9507157472948555  Prule test :  0.9634640483200292
70 5286.728206602907 1209.4817248376312 1210.0103976582914 Accuracy: 0.8866  test :  0.8393  Prule Train :  0.9488105053163085  Prule test :  0.9619984802431609
75 -1711.750025486289 1185.1622222097703 1184.9910472072215 Accuracy: 0.8883  test :  0.84  Prule Train :  0.9486437674932165  Prule test :  0.9633747298572427
80 5710.368493983435 1162.4623337351054 1163.0333705845037 Accuracy: 0.8903  test :  0.8407  Prule Train :  0.9490583036595305  Prule test :  0.964754922879961
85 -2152.5948617274735 1140.2206726287923 1140.0054131426195 Accuracy: 0.8914  test :  0.8427  Prule Train :  0.9489470398561308  Prule test :  0.963284898806435
90 6151.3047091882245 1119.1415029416082 1119.7566334125272 Accuracy: 0.8929  test :  0.8433  Prule Train :  0.9481961253178965  Prule test :  0.9646689288334556
95 -2600.910493013317 1098.5835048823442 1098.3234138330427 Accuracy: 0.8946  test :  0.844  Prule Train :  0.9468031968031968  Prule test :  0.966056941680698
100 6607.85593517917 1079.4849182835555 1080.1457038770736 Accuracy: 0.8966  test :  0.844  Prule Train :  0.9447658794144612  Prule test :  0.9660156968544975
105 -3047.922145921756 1061.08439637148 1060.7796041568877 Accuracy: 0.8986  test :  0.8433  Prule Train :  0.9427235316124205  Prule test :  0.9645390070921985
110 7074.677476623386 1043.450653598266 1044.158121345928 Accuracy: 0.9017  test :  0.8427  Prule Train :  0.9430074262788017  Prule test :  0.9687326549491212
115 -3492.708273710323 1025.815115975343 1025.465845147972 Accuracy: 0.9034  test :  0.8427  Prule Train :  0.9415976909773436  Prule test :  0.968657224146462
120 7538.817042331469 1009.6225051919799 1010.376386896213 Accuracy: 0.9057  test :  0.84  Prule Train :  0.9438208118158307  Prule test :  0.9686193440490569
125 -3925.2443263879536 994.3644599591503 993.9719355265115 Accuracy: 0.9069  test :  0.8393  Prule Train :  0.9449386130608839  Prule test :  0.9671714825482363
130 7972.662020614931 979.9508494718787 980.7481156739402 Accuracy: 0.9086  test :  0.8413  Prule Train :  0.9422836838567176  Prule test :  0.9657236210474156
135 -4317.2617741658905 966.8276074198629 966.3958812424463 Accuracy: 0.9109  test :  0.8413  Prule Train :  0.939562937062937  Prule test :  0.9657236210474156
140 8186.914785098396 953.4591965254763 954.2778880039862 Accuracy: 0.9123  test :  0.84  Prule Train :  0.9400259519232596  Prule test :  0.9685432520577731
145 -4492.167601830408 939.1174013958616 938.6681846356786 Accuracy: 0.9137  test :  0.84  Prule Train :  0.9429782947370887  Prule test :  0.9713793962804896
150 7867.109405067614 925.5808259046964 926.3675368452032 Accuracy: 0.9149  test :  0.84  Prule Train :  0.9428567239887995  Prule test :  0.9713793962804896
155 -4360.010710958591 912.8348198007398 912.3988187296438 Accuracy: 0.9169  test :  0.84  Prule Train :  0.9407708160856775  Prule test :  0.9713793962804896
160 7588.973543134834 898.2327106638179 898.9916080181314 Accuracy: 0.918  test :  0.84  Prule Train :  0.9406461550219432  Prule test :  0.9713793962804896
165 -4174.059823995642 886.4746103137559 886.0572043313564 Accuracy: 0.9194  test :  0.8407  Prule Train :  0.9411153176156336  Prule test :  0.9699230553565309
170 7407.866800215759 873.861588665223 874.6023753452447 Accuracy: 0.9203  test :  0.8407  Prule Train :  0.941648273716585  Prule test :  0.9699230553565309
175 -4002.6100629088323 862.4830443692846 862.0827833629937 Accuracy: 0.9211  test :  0.8407  Prule Train :  0.9421825799279886  Prule test :  0.9699230553565309
180 7251.422730411903 852.2720654907616 852.9972077638029 Accuracy: 0.922  test :  0.8407  Prule Train :  0.9414620022985044  Prule test :  0.9699230553565309
185 -3847.5120147230846 843.176661915722 842.7919107142498 Accuracy: 0.9229  test :  0.8413  Prule Train :  0.9419970892052112  Prule test :  0.9684667144325723
190 7088.148940562243 834.0049711765641 834.7137860706202 Accuracy: 0.9249  test :  0.8427  Prule Train :  0.9386346986346987  Prule test :  0.9684282772820865
195 -3717.89200749229 824.7937075910324 824.4219183902833 Accuracy: 0.9254  test :  0.8427  Prule Train :  0.9385705357751101  Prule test :  0.9684282772820865
Resultado | acc=0.8420 | bal_acc=0.6738 | f1=0.9058 | EOdds=0.0265 | EOp=0.0021 | p-rule=96.70 | score=0.6725 | tempo=0.11 min

FAGTB caucasian_1:  13%|█▎        | 8/60 [00:43<04:55,  5.69s/modelo]

----------------------------------------------------------------------------------------------------
Treino 69/120 | config=caucasian_1 | lambda=0.0001 | n_estimators=100 | learning_rate=0.1 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1809.4273089684498 1809.4428095644666 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2091.7154538673067 1675.0871396571888 1675.2963112025752 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2519.277629518021 1557.4505984126722 1557.7025261756241 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 903.3953223130509 1461.611120611155 1461.7014601433864 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3692.765047093889 1381.1236809222996 1381.4929574270088 Accuracy: 0.8654  test :  0.8407  Prule Train :  0.9591759969684385  Prule test :  0.9679496825062445
25 -120.33408590827923 1312.8845459554916 1312.8725125469007 Accuracy: 0.8774  test :  0.842  Prule Train :  0.9557251001425758  Prule test :  0.9734269867248593
30 4103.917670707846 1255.9782307498929 1256.3886225169636 Accuracy: 0.8846  test :  0.8413  Prule Train :  0.9496105520495765  Prule test :  0.9634194528875379
35 -580.2302170208822 1203.9814491648572 1203.9234261431552 Accuracy: 0.8874  test :  0.8413  Prule Train :  0.9469052633377618  Prule test :  0.9633747298572427
40 4467.311053529995 1158.5467950878992 1158.9935261932524 Accuracy: 0.8914  test :  0.842  Prule Train :  0.947726306842329  Prule test :  0.9619517243478526
45 -1050.316090514807 1115.9234553477215 1115.81842373867 Accuracy: 0.8946  test :  0.842  Prule Train :  0.9455807781961628  Prule test :  0.9646257462115415
50 4874.47609791831 1076.6040252850607 1077.0914728948524 Accuracy: 0.8983  test :  0.842  Prule Train :  0.9421419624997663  Prule test :  0.964582439144031
55 -1516.9028344360004 1039.207328028941 1039.0556377454973 Accuracy: 0.9017  test :  0.842  Prule Train :  0.9405536707516905  Prule test :  0.9673307263601933
60 5299.122257256127 1006.2506177360444 1006.7805299617701 Accuracy: 0.9051  test :  0.8427  Prule Train :  0.9389555199611066  Prule test :  0.968657224146462
65 -1968.8427411461385 977.7185520760263 977.5216678019117 Accuracy: 0.9089  test :  0.8433  Prule Train :  0.9403987569926435  Prule test :  0.9672114670954971
70 5738.6245115389 945.1894139039832 945.7632763551372 Accuracy: 0.9143  test :  0.8407  Prule Train :  0.9429175475687103  Prule test :  0.9699953408914428
75 -2401.3065793128853 915.6868577882265 915.4467271302951 Accuracy: 0.9163  test :  0.84  Prule Train :  0.9420801700398677  Prule test :  0.9656390743904333
80 6195.393326885536 889.9994144644992 890.6189537971877 Accuracy: 0.9203  test :  0.8407  Prule Train :  0.9378958583504037  Prule test :  0.967050827423168
85 -2823.8970011362935 866.9663532143475 866.6839635142337 Accuracy: 0.9229  test :  0.842  Prule Train :  0.938232128859108  Prule test :  0.967050827423168
90 6655.204220543387 844.5981604037013 845.2636808257557 Accuracy: 0.9249  test :  0.8433  Prule Train :  0.9373794564149892  Prule test :  0.9669698009608784
95 -3219.9367825227823 827.5621901879812 827.2401965097289 Accuracy: 0.9263  test :  0.8427  Prule Train :  0.9340811472791168  Prule test :  0.9683897272471647
Resultado | acc=0.8427 | bal_acc=0.6765 | f1=0.9061 | EOdds=0.0121 | EOp=0.0039 | p-rule=96.84 | score=0.6757 | tempo=0.06 min

FAGTB caucasian_1:  15%|█▌        | 9/60 [00:46<04:17,  5.06s/modelo]

----------------------------------------------------------------------------------------------------
Treino 70/120 | config=caucasian_1 | lambda=0.0001 | n_estimators=200 | learning_rate=0.1 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1809.4273089684498 1809.4428095644666 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2091.7154538673067 1675.0871396571888 1675.2963112025752 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2519.277629518021 1557.4505984126722 1557.7025261756241 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 903.3953223130509 1461.611120611155 1461.7014601433864 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3692.765047093889 1381.1236809222996 1381.4929574270088 Accuracy: 0.8654  test :  0.8407  Prule Train :  0.9591759969684385  Prule test :  0.9679496825062445
25 -120.33408590827923 1312.8845459554916 1312.8725125469007 Accuracy: 0.8774  test :  0.842  Prule Train :  0.9557251001425758  Prule test :  0.9734269867248593
30 4103.917670707846 1255.9782307498929 1256.3886225169636 Accuracy: 0.8846  test :  0.8413  Prule Train :  0.9496105520495765  Prule test :  0.9634194528875379
35 -580.2302170208822 1203.9814491648572 1203.9234261431552 Accuracy: 0.8874  test :  0.8413  Prule Train :  0.9469052633377618  Prule test :  0.9633747298572427
40 4467.311053529995 1158.5467950878992 1158.9935261932524 Accuracy: 0.8914  test :  0.842  Prule Train :  0.947726306842329  Prule test :  0.9619517243478526
45 -1050.316090514807 1115.9234553477215 1115.81842373867 Accuracy: 0.8946  test :  0.842  Prule Train :  0.9455807781961628  Prule test :  0.9646257462115415
50 4874.47609791831 1076.6040252850607 1077.0914728948524 Accuracy: 0.8983  test :  0.842  Prule Train :  0.9421419624997663  Prule test :  0.964582439144031
55 -1516.9028344360004 1039.207328028941 1039.0556377454973 Accuracy: 0.9017  test :  0.842  Prule Train :  0.9405536707516905  Prule test :  0.9673307263601933
60 5299.122257256127 1006.2506177360444 1006.7805299617701 Accuracy: 0.9051  test :  0.8427  Prule Train :  0.9389555199611066  Prule test :  0.968657224146462
65 -1968.8427411461385 977.7185520760263 977.5216678019117 Accuracy: 0.9089  test :  0.8433  Prule Train :  0.9403987569926435  Prule test :  0.9672114670954971
70 5738.6245115389 945.1894139039832 945.7632763551372 Accuracy: 0.9143  test :  0.8407  Prule Train :  0.9429175475687103  Prule test :  0.9699953408914428
75 -2401.3065793128853 915.6868577882265 915.4467271302951 Accuracy: 0.9163  test :  0.84  Prule Train :  0.9420801700398677  Prule test :  0.9656390743904333
80 6195.393326885536 889.9994144644992 890.6189537971877 Accuracy: 0.9203  test :  0.8407  Prule Train :  0.9378958583504037  Prule test :  0.967050827423168
85 -2823.8970011362935 866.9663532143475 866.6839635142337 Accuracy: 0.9229  test :  0.842  Prule Train :  0.938232128859108  Prule test :  0.967050827423168
90 6655.204220543387 844.5981604037013 845.2636808257557 Accuracy: 0.9249  test :  0.8433  Prule Train :  0.9373794564149892  Prule test :  0.9669698009608784
95 -3219.9367825227823 827.5621901879812 827.2401965097289 Accuracy: 0.9263  test :  0.8427  Prule Train :  0.9340811472791168  Prule test :  0.9683897272471647
100 6946.094649547738 807.9498428383848 808.6444523033397 Accuracy: 0.928  test :  0.8433  Prule Train :  0.9326260355485261  Prule test :  0.9668882978723404
105 -3418.610153660228 790.1233916063281 789.7815305909621 Accuracy: 0.9297  test :  0.842  Prule Train :  0.9311672212435572  Prule test :  0.9697404757421704
110 6670.388406289145 772.9945967893664 773.6616356299953 Accuracy: 0.9331  test :  0.842  Prule Train :  0.9282384282384283  Prule test :  0.9668063139396221
115 -3297.4819756035913 755.585142090538 755.2553938929777 Accuracy: 0.9351  test :  0.842  Prule Train :  0.9273606053158769  Prule test :  0.9639175257731959
120 6396.100266196738 741.888633710187 742.5282437368068 Accuracy: 0.9377  test :  0.8433  Prule Train :  0.9301926144031407  Prule test :  0.9668063139396221
125 -3123.4027068554933 726.8176306473651 726.5052903766795 Accuracy: 0.94  test :  0.844  Prule Train :  0.9261160590640359  Prule test :  0.9625000000000001
130 6159.808683153424 711.9555960483337 712.5715769166491 Accuracy: 0.9423  test :  0.8433  Prule Train :  0.9232957824597696  Prule test :  0.9610372340425534
135 -2980.2184506745375 697.0274711330543 696.7294492879869 Accuracy: 0.9434  test :  0.842  Prule Train :  0.9231459675761028  Prule test :  0.9610372340425534
140 6034.499959174349 683.9390649891811 684.5425149850985 Accuracy: 0.9451  test :  0.8413  Prule Train :  0.9229205203398753  Prule test :  0.9567047833286467
145 -2790.666428493942 668.5476808990313 668.2686142561818 Accuracy: 0.9477  test :  0.8413  Prule Train :  0.9219461004713267  Prule test :  0.9567047833286467
150 5622.015647517429 656.7331277813093 657.2953293460611 Accuracy: 0.95  test :  0.8413  Prule Train :  0.9203697576996345  Prule test :  0.9566489361702127
155 -2749.674257119757 644.2150565656025 643.9400891398905 Accuracy: 0.9509  test :  0.8413  Prule Train :  0.9196182114470052  Prule test :  0.9536630840096513
160 5882.013558636081 633.4386986518134 634.026900007677 Accuracy: 0.9526  test :  0.8413  Prule Train :  0.9181121908394636  Prule test :  0.9537234042553192
165 -2426.9357666929695 622.6559178457344 622.413224269065 Accuracy: 0.9537  test :  0.8413  Prule Train :  0.9192278118758275  Prule test :  0.9537234042553192
170 5063.350737860244 613.3060192824823 613.8123543562684 Accuracy: 0.9554  test :  0.8413  Prule Train :  0.9164420648795647  Prule test :  0.9537234042553192
175 -2500.9260440394455 603.2267556783447 602.9766630739407 Accuracy: 0.9563  test :  0.8413  Prule Train :  0.9156845326226433  Prule test :  0.9537234042553192
180 5592.584408820356 594.0258089267313 594.5850673676133 Accuracy: 0.9591  test :  0.8407  Prule Train :  0.9152794917500799  Prule test :  0.9522606382978726
185 -2257.5894080789444 584.8376185224247 584.6118595816167 Accuracy: 0.96  test :  0.8413  Prule Train :  0.9132410073586544  Prule test :  0.950862311369388
190 4833.841130283369 576.6833662181075 577.1667503311359 Accuracy: 0.9609  test :  0.8413  Prule Train :  0.9137559648030852  Prule test :  0.950862311369388
195 -2327.626996955444 567.3436537713136 567.1108910716181 Accuracy: 0.9614  test :  0.8413  Prule Train :  0.9136735344986817  Prule test :  0.950862311369388
Resultado | acc=0.8413 | bal_acc=0.6800 | f1=0.9050 | EOdds=0.0458 | EOp=0.0146 | p-rule=95.09 | score=0.6773 | tempo=0.12 min

FAGTB caucasian_1:  17%|█▋        | 10/60 [00:53<04:43,  5.67s/modelo]

----------------------------------------------------------------------------------------------------
Treino 71/120 | config=caucasian_1 | lambda=0.0001 | n_estimators=100 | learning_rate=0.1 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1809.4273089684498 1809.4428095644666 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2091.7154538673067 1675.0871396571888 1675.2963112025752 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2519.277629518021 1557.4505984126722 1557.7025261756241 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 903.3953223130509 1461.611120611155 1461.7014601433864 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3692.765047093889 1381.1236809222996 1381.4929574270088 Accuracy: 0.8654  test :  0.8407  Prule Train :  0.9591759969684385  Prule test :  0.9679496825062445
25 -120.33408590827923 1312.8845459554916 1312.8725125469007 Accuracy: 0.8774  test :  0.842  Prule Train :  0.9557251001425758  Prule test :  0.9734269867248593
30 4103.917670707846 1255.9782307498929 1256.3886225169636 Accuracy: 0.8846  test :  0.8413  Prule Train :  0.9496105520495765  Prule test :  0.9634194528875379
35 -580.2302170208822 1203.9814491648572 1203.9234261431552 Accuracy: 0.8874  test :  0.8413  Prule Train :  0.9469052633377618  Prule test :  0.9633747298572427
40 4467.311053529995 1158.5467950878992 1158.9935261932524 Accuracy: 0.8914  test :  0.842  Prule Train :  0.947726306842329  Prule test :  0.9619517243478526
45 -1050.316090514807 1115.9234553477215 1115.81842373867 Accuracy: 0.8946  test :  0.842  Prule Train :  0.9455807781961628  Prule test :  0.9646257462115415
50 4874.47609791831 1076.6040252850607 1077.0914728948524 Accuracy: 0.8983  test :  0.842  Prule Train :  0.9421419624997663  Prule test :  0.964582439144031
55 -1516.9028344360004 1039.207328028941 1039.0556377454973 Accuracy: 0.9017  test :  0.842  Prule Train :  0.9405536707516905  Prule test :  0.9673307263601933
60 5299.122257256127 1006.2506177360444 1006.7805299617701 Accuracy: 0.9051  test :  0.8427  Prule Train :  0.9389555199611066  Prule test :  0.968657224146462
65 -1968.8427411461385 977.7185520760263 977.5216678019117 Accuracy: 0.9089  test :  0.8433  Prule Train :  0.9403987569926435  Prule test :  0.9672114670954971
70 5738.6245115389 945.1894139039832 945.7632763551372 Accuracy: 0.9143  test :  0.8407  Prule Train :  0.9429175475687103  Prule test :  0.9699953408914428
75 -2401.3065793128853 915.6868577882265 915.4467271302951 Accuracy: 0.9163  test :  0.84  Prule Train :  0.9420801700398677  Prule test :  0.9656390743904333
80 6195.393326885536 889.9994144644992 890.6189537971877 Accuracy: 0.9203  test :  0.8407  Prule Train :  0.9378958583504037  Prule test :  0.967050827423168
85 -2823.8970011362935 866.9663532143475 866.6839635142337 Accuracy: 0.9229  test :  0.842  Prule Train :  0.938232128859108  Prule test :  0.967050827423168
90 6655.204220543387 844.5981604037013 845.2636808257557 Accuracy: 0.9249  test :  0.8433  Prule Train :  0.9373794564149892  Prule test :  0.9669698009608784
95 -3219.9367825227823 827.5621901879812 827.2401965097289 Accuracy: 0.9263  test :  0.8427  Prule Train :  0.9340811472791168  Prule test :  0.9683897272471647
Resultado | acc=0.8427 | bal_acc=0.6765 | f1=0.9061 | EOdds=0.0121 | EOp=0.0039 | p-rule=96.84 | score=0.6757 | tempo=0.06 min

FAGTB caucasian_1:  18%|█▊        | 11/60 [00:57<04:07,  5.05s/modelo]

----------------------------------------------------------------------------------------------------
Treino 72/120 | config=caucasian_1 | lambda=0.0001 | n_estimators=200 | learning_rate=0.1 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1809.4273089684498 1809.4428095644666 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2091.7154538673067 1675.0871396571888 1675.2963112025752 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2519.277629518021 1557.4505984126722 1557.7025261756241 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 903.3953223130509 1461.611120611155 1461.7014601433864 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3692.765047093889 1381.1236809222996 1381.4929574270088 Accuracy: 0.8654  test :  0.8407  Prule Train :  0.9591759969684385  Prule test :  0.9679496825062445
25 -120.33408590827923 1312.8845459554916 1312.8725125469007 Accuracy: 0.8774  test :  0.842  Prule Train :  0.9557251001425758  Prule test :  0.9734269867248593
30 4103.917670707846 1255.9782307498929 1256.3886225169636 Accuracy: 0.8846  test :  0.8413  Prule Train :  0.9496105520495765  Prule test :  0.9634194528875379
35 -580.2302170208822 1203.9814491648572 1203.9234261431552 Accuracy: 0.8874  test :  0.8413  Prule Train :  0.9469052633377618  Prule test :  0.9633747298572427
40 4467.311053529995 1158.5467950878992 1158.9935261932524 Accuracy: 0.8914  test :  0.842  Prule Train :  0.947726306842329  Prule test :  0.9619517243478526
45 -1050.316090514807 1115.9234553477215 1115.81842373867 Accuracy: 0.8946  test :  0.842  Prule Train :  0.9455807781961628  Prule test :  0.9646257462115415
50 4874.47609791831 1076.6040252850607 1077.0914728948524 Accuracy: 0.8983  test :  0.842  Prule Train :  0.9421419624997663  Prule test :  0.964582439144031
55 -1516.9028344360004 1039.207328028941 1039.0556377454973 Accuracy: 0.9017  test :  0.842  Prule Train :  0.9405536707516905  Prule test :  0.9673307263601933
60 5299.122257256127 1006.2506177360444 1006.7805299617701 Accuracy: 0.9051  test :  0.8427  Prule Train :  0.9389555199611066  Prule test :  0.968657224146462
65 -1968.8427411461385 977.7185520760263 977.5216678019117 Accuracy: 0.9089  test :  0.8433  Prule Train :  0.9403987569926435  Prule test :  0.9672114670954971
70 5738.6245115389 945.1894139039832 945.7632763551372 Accuracy: 0.9143  test :  0.8407  Prule Train :  0.9429175475687103  Prule test :  0.9699953408914428
75 -2401.3065793128853 915.6868577882265 915.4467271302951 Accuracy: 0.9163  test :  0.84  Prule Train :  0.9420801700398677  Prule test :  0.9656390743904333
80 6195.393326885536 889.9994144644992 890.6189537971877 Accuracy: 0.9203  test :  0.8407  Prule Train :  0.9378958583504037  Prule test :  0.967050827423168
85 -2823.8970011362935 866.9663532143475 866.6839635142337 Accuracy: 0.9229  test :  0.842  Prule Train :  0.938232128859108  Prule test :  0.967050827423168
90 6655.204220543387 844.5981604037013 845.2636808257557 Accuracy: 0.9249  test :  0.8433  Prule Train :  0.9373794564149892  Prule test :  0.9669698009608784
95 -3219.9367825227823 827.5621901879812 827.2401965097289 Accuracy: 0.9263  test :  0.8427  Prule Train :  0.9340811472791168  Prule test :  0.9683897272471647
100 6946.094649547738 807.9498428383848 808.6444523033397 Accuracy: 0.928  test :  0.8433  Prule Train :  0.9326260355485261  Prule test :  0.9668882978723404
105 -3418.610153660228 790.1233916063281 789.7815305909621 Accuracy: 0.9297  test :  0.842  Prule Train :  0.9311672212435572  Prule test :  0.9697404757421704
110 6670.388406289145 772.9945967893664 773.6616356299953 Accuracy: 0.9331  test :  0.842  Prule Train :  0.9282384282384283  Prule test :  0.9668063139396221
115 -3297.4819756035913 755.585142090538 755.2553938929777 Accuracy: 0.9351  test :  0.842  Prule Train :  0.9273606053158769  Prule test :  0.9639175257731959
120 6396.100266196738 741.888633710187 742.5282437368068 Accuracy: 0.9377  test :  0.8433  Prule Train :  0.9301926144031407  Prule test :  0.9668063139396221
125 -3123.4027068554933 726.8176306473651 726.5052903766795 Accuracy: 0.94  test :  0.844  Prule Train :  0.9261160590640359  Prule test :  0.9625000000000001
130 6159.808683153424 711.9555960483337 712.5715769166491 Accuracy: 0.9423  test :  0.8433  Prule Train :  0.9232957824597696  Prule test :  0.9610372340425534
135 -2980.2184506745375 697.0274711330543 696.7294492879869 Accuracy: 0.9434  test :  0.842  Prule Train :  0.9231459675761028  Prule test :  0.9610372340425534
140 6034.499959174349 683.9390649891811 684.5425149850985 Accuracy: 0.9451  test :  0.8413  Prule Train :  0.9229205203398753  Prule test :  0.9567047833286467
145 -2790.666428493942 668.5476808990313 668.2686142561818 Accuracy: 0.9477  test :  0.8413  Prule Train :  0.9219461004713267  Prule test :  0.9567047833286467
150 5622.015647517429 656.7331277813093 657.2953293460611 Accuracy: 0.95  test :  0.8413  Prule Train :  0.9203697576996345  Prule test :  0.9566489361702127
155 -2749.674257119757 644.2150565656025 643.9400891398905 Accuracy: 0.9509  test :  0.8413  Prule Train :  0.9196182114470052  Prule test :  0.9536630840096513
160 5882.013558636081 633.4386986518134 634.026900007677 Accuracy: 0.9526  test :  0.8413  Prule Train :  0.9181121908394636  Prule test :  0.9537234042553192
165 -2426.9357666929695 622.6559178457344 622.413224269065 Accuracy: 0.9537  test :  0.8413  Prule Train :  0.9192278118758275  Prule test :  0.9537234042553192
170 5063.350737860244 613.3060192824823 613.8123543562684 Accuracy: 0.9554  test :  0.8413  Prule Train :  0.9164420648795647  Prule test :  0.9537234042553192
175 -2500.9260440394455 603.2267556783447 602.9766630739407 Accuracy: 0.9563  test :  0.8413  Prule Train :  0.9156845326226433  Prule test :  0.9537234042553192
180 5592.584408820356 594.0258089267313 594.5850673676133 Accuracy: 0.9591  test :  0.8407  Prule Train :  0.9152794917500799  Prule test :  0.9522606382978726
185 -2257.5894080789444 584.8376185224247 584.6118595816167 Accuracy: 0.96  test :  0.8413  Prule Train :  0.9132410073586544  Prule test :  0.950862311369388
190 4833.841130283369 576.6833662181075 577.1667503311359 Accuracy: 0.9609  test :  0.8413  Prule Train :  0.9137559648030852  Prule test :  0.950862311369388
195 -2327.626996955444 567.3436537713136 567.1108910716181 Accuracy: 0.9614  test :  0.8413  Prule Train :  0.9136735344986817  Prule test :  0.950862311369388
Resultado | acc=0.8413 | bal_acc=0.6800 | f1=0.9050 | EOdds=0.0458 | EOp=0.0146 | p-rule=95.09 | score=0.6773 | tempo=0.12 min

FAGTB caucasian_1:  20%|██        | 12/60 [01:04<04:31,  5.66s/modelo]

----------------------------------------------------------------------------------------------------
Treino 73/120 | config=caucasian_1 | lambda=0.0005 | n_estimators=100 | learning_rate=0.03 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1830.0991544749081 1830.176657454992 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2146.1188693726895 1787.1405352285997 1788.2135946632857 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2382.9073887244417 1746.895256563711 1748.086710258073 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1219.72745637686 1708.6564854072622 1709.2663491354506 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3317.695718527576 1669.6948831824038 1671.3537310416675 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 341.82340673720455 1632.477938827909 1632.6488505312777 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3707.78479072924 1597.643666675795 1599.4975590711597 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 140.26704438839067 1564.4166264358041 1564.4867599579984 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 3922.040775812721 1533.6620984240753 1535.6231188119818 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 -101.50143176151832 1504.010981839971 1503.9602311240901 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 4179.611172321327 1476.5400566417306 1478.6298622278914 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -385.27038233859594 1450.2616993226134 1450.069064131444 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 4473.161275093524 1425.0838204597308 1427.3204010972775 Accuracy: 0.7811  test :  0.782  Prule Train :  1.0  Prule test :  0.998663101604278
65 -702.9495620241883 1401.3726429625867 1401.0211681815745 Accuracy: 0.7834  test :  0.782  Prule Train :  0.9999109504727481  Prule test :  0.998663101604278
70 4796.949873148699 1379.1650943181232 1381.5635692546978 Accuracy: 0.8651  test :  0.84  Prule Train :  0.959799648461916  Prule test :  0.966582521937733
75 -1047.92445230961 1357.5631362134561 1357.0391739873012 Accuracy: 0.868  test :  0.8413  Prule Train :  0.9583573371907707  Prule test :  0.9665427788979506
80 5144.732979526533 1337.11926076721 1339.6916272569733 Accuracy: 0.8726  test :  0.8433  Prule Train :  0.9579644927076952  Prule test :  0.9706615691489362
85 -1414.7156872282383 1317.2957541362994 1316.5883962926853 Accuracy: 0.8766  test :  0.8427  Prule Train :  0.9564064397296659  Prule test :  0.9748156129541384
90 5512.298857083852 1299.0307954130942 1301.7869448416363 Accuracy: 0.8803  test :  0.8427  Prule Train :  0.9554697686164515  Prule test :  0.9747872340425532
95 -1798.7709705750347 1281.9356671609305 1281.0362816756428 Accuracy: 0.8829  test :  0.8433  Prule Train :  0.9509864881363054  Prule test :  0.9705243161094227
Resultado | acc=0.8413 | bal_acc=0.6537 | f1=0.9067 | EOdds=0.0312 | EOp=0.0027 | p-rule=96.91 | score=0.6520 | tempo=0.06 min

FAGTB caucasian_1:  22%|██▏       | 13/60 [01:08<03:57,  5.05s/modelo]

----------------------------------------------------------------------------------------------------
Treino 74/120 | config=caucasian_1 | lambda=0.0005 | n_estimators=200 | learning_rate=0.03 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1830.0991544749081 1830.176657454992 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2146.1188693726895 1787.1405352285997 1788.2135946632857 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2382.9073887244417 1746.895256563711 1748.086710258073 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1219.72745637686 1708.6564854072622 1709.2663491354506 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3317.695718527576 1669.6948831824038 1671.3537310416675 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 341.82340673720455 1632.477938827909 1632.6488505312777 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3707.78479072924 1597.643666675795 1599.4975590711597 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 140.26704438839067 1564.4166264358041 1564.4867599579984 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 3922.040775812721 1533.6620984240753 1535.6231188119818 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 -101.50143176151832 1504.010981839971 1503.9602311240901 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 4179.611172321327 1476.5400566417306 1478.6298622278914 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -385.27038233859594 1450.2616993226134 1450.069064131444 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 4473.161275093524 1425.0838204597308 1427.3204010972775 Accuracy: 0.7811  test :  0.782  Prule Train :  1.0  Prule test :  0.998663101604278
65 -702.9495620241883 1401.3726429625867 1401.0211681815745 Accuracy: 0.7834  test :  0.782  Prule Train :  0.9999109504727481  Prule test :  0.998663101604278
70 4796.949873148699 1379.1650943181232 1381.5635692546978 Accuracy: 0.8651  test :  0.84  Prule Train :  0.959799648461916  Prule test :  0.966582521937733
75 -1047.92445230961 1357.5631362134561 1357.0391739873012 Accuracy: 0.868  test :  0.8413  Prule Train :  0.9583573371907707  Prule test :  0.9665427788979506
80 5144.732979526533 1337.11926076721 1339.6916272569733 Accuracy: 0.8726  test :  0.8433  Prule Train :  0.9579644927076952  Prule test :  0.9706615691489362
85 -1414.7156872282383 1317.2957541362994 1316.5883962926853 Accuracy: 0.8766  test :  0.8427  Prule Train :  0.9564064397296659  Prule test :  0.9748156129541384
90 5512.298857083852 1299.0307954130942 1301.7869448416363 Accuracy: 0.8803  test :  0.8427  Prule Train :  0.9554697686164515  Prule test :  0.9747872340425532
95 -1798.7709705750347 1281.9356671609305 1281.0362816756428 Accuracy: 0.8829  test :  0.8433  Prule Train :  0.9509864881363054  Prule test :  0.9705243161094227
100 5896.968870064693 1265.3280101926657 1268.276494627698 Accuracy: 0.8837  test :  0.8413  Prule Train :  0.950298939330018  Prule test :  0.9690667518948043
105 -2194.9080698298694 1250.0569342087367 1248.9594801738217 Accuracy: 0.8843  test :  0.842  Prule Train :  0.9502444709761783  Prule test :  0.9676437463854138
110 6296.217392743172 1234.399847140147 1237.5479558365182 Accuracy: 0.8849  test :  0.8427  Prule Train :  0.9501899361569893  Prule test :  0.9633747298572427
115 -2599.8998187720495 1218.3154141025998 1217.0154641932138 Accuracy: 0.8857  test :  0.842  Prule Train :  0.9507157472948555  Prule test :  0.9619517243478526
120 6704.55706879058 1203.1821093056565 1206.5343878400517 Accuracy: 0.8871  test :  0.842  Prule Train :  0.9487549939872679  Prule test :  0.9619517243478526
125 -3012.898707044131 1189.2083117472116 1187.7018623936897 Accuracy: 0.8871  test :  0.8413  Prule Train :  0.9487549939872679  Prule test :  0.9633298786807294
130 7138.446936180284 1175.7196960561475 1179.2889195242376 Accuracy: 0.8883  test :  0.8413  Prule Train :  0.9510803738744914  Prule test :  0.9633298786807294
135 -3435.190394338334 1162.2357371984194 1160.5181420012502 Accuracy: 0.8886  test :  0.842  Prule Train :  0.9516635010197241  Prule test :  0.9619048344814974
140 7577.460812600713 1149.3901420615623 1153.1788724678627 Accuracy: 0.8909  test :  0.8427  Prule Train :  0.9502242229514956  Prule test :  0.9604797902822655
145 -3859.544087800402 1136.2564021783473 1134.326630134447 Accuracy: 0.8917  test :  0.8433  Prule Train :  0.9483084483084484  Prule test :  0.9618578100674624
150 8023.386591048782 1123.8173482061493 1127.829041501674 Accuracy: 0.8929  test :  0.8433  Prule Train :  0.9481961253178965  Prule test :  0.9618578100674624
155 -4288.425523235592 1111.3921221029557 1109.2479093413378 Accuracy: 0.8931  test :  0.8433  Prule Train :  0.9475567482947557  Prule test :  0.9618578100674624
160 8476.969707985943 1099.5601353092313 1103.7986201632243 Accuracy: 0.8937  test :  0.8433  Prule Train :  0.947500089653936  Prule test :  0.9618578100674624
165 -4717.973237317887 1087.551033312834 1085.1920466941751 Accuracy: 0.8957  test :  0.8447  Prule Train :  0.9430216962524655  Prule test :  0.9646257462115415
170 8915.791568595576 1075.9820989905647 1080.4399947748625 Accuracy: 0.898  test :  0.844  Prule Train :  0.9427833116913934  Prule test :  0.9631945507423849
175 -5128.066086807583 1065.0533875947092 1062.4893545513055 Accuracy: 0.8986  test :  0.8433  Prule Train :  0.9427235316124205  Prule test :  0.964582439144031
180 9241.273849475197 1054.1874031252185 1058.8080400499562 Accuracy: 0.8997  test :  0.8433  Prule Train :  0.9438296191542945  Prule test :  0.964582439144031
185 -5429.365227784509 1043.6302181916612 1040.9155355777689 Accuracy: 0.9003  test :  0.8433  Prule Train :  0.9437703385723188  Prule test :  0.9673702496617882
190 9109.978175438953 1033.4671746676786 1038.0221637553982 Accuracy: 0.9011  test :  0.8427  Prule Train :  0.9430672526647759  Prule test :  0.9687702066077531
195 -5423.557451972674 1023.3990152254613 1020.6872364994749 Accuracy: 0.9023  test :  0.8433  Prule Train :  0.9417191647674918  Prule test :  0.9701742213999383
Resultado | acc=0.8427 | bal_acc=0.6655 | f1=0.9069 | EOdds=0.0217 | EOp=0.0033 | p-rule=96.87 | score=0.6643 | tempo=0.12 min

FAGTB caucasian_1:  23%|██▎       | 14/60 [01:15<04:20,  5.66s/modelo]

----------------------------------------------------------------------------------------------------
Treino 75/120 | config=caucasian_1 | lambda=0.0005 | n_estimators=100 | learning_rate=0.03 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1830.0991544749081 1830.176657454992 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2146.1188693726895 1787.1405352285997 1788.2135946632857 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2382.9073887244417 1746.895256563711 1748.086710258073 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1219.72745637686 1708.6564854072622 1709.2663491354506 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3317.695718527576 1669.6948831824038 1671.3537310416675 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 341.82340673720455 1632.477938827909 1632.6488505312777 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3707.78479072924 1597.643666675795 1599.4975590711597 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 140.26704438839067 1564.4166264358041 1564.4867599579984 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 3922.040775812721 1533.6620984240753 1535.6231188119818 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 -101.50143176151832 1504.010981839971 1503.9602311240901 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 4179.611172321327 1476.5400566417306 1478.6298622278914 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -385.27038233859594 1450.2616993226134 1450.069064131444 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 4473.161275093524 1425.0838204597308 1427.3204010972775 Accuracy: 0.7811  test :  0.782  Prule Train :  1.0  Prule test :  0.998663101604278
65 -702.9495620241883 1401.3726429625867 1401.0211681815745 Accuracy: 0.7834  test :  0.782  Prule Train :  0.9999109504727481  Prule test :  0.998663101604278
70 4796.949873148699 1379.1650943181232 1381.5635692546978 Accuracy: 0.8651  test :  0.84  Prule Train :  0.959799648461916  Prule test :  0.966582521937733
75 -1047.92445230961 1357.5631362134561 1357.0391739873012 Accuracy: 0.868  test :  0.8413  Prule Train :  0.9583573371907707  Prule test :  0.9665427788979506
80 5144.732979526533 1337.11926076721 1339.6916272569733 Accuracy: 0.8726  test :  0.8433  Prule Train :  0.9579644927076952  Prule test :  0.9706615691489362
85 -1414.7156872282383 1317.2957541362994 1316.5883962926853 Accuracy: 0.8766  test :  0.8427  Prule Train :  0.9564064397296659  Prule test :  0.9748156129541384
90 5512.298857083852 1299.0307954130942 1301.7869448416363 Accuracy: 0.8803  test :  0.8427  Prule Train :  0.9554697686164515  Prule test :  0.9747872340425532
95 -1798.7709705750347 1281.9356671609305 1281.0362816756428 Accuracy: 0.8829  test :  0.8433  Prule Train :  0.9509864881363054  Prule test :  0.9705243161094227
Resultado | acc=0.8413 | bal_acc=0.6537 | f1=0.9067 | EOdds=0.0312 | EOp=0.0027 | p-rule=96.91 | score=0.6520 | tempo=0.06 min

FAGTB caucasian_1:  25%|██▌       | 15/60 [01:19<03:47,  5.06s/modelo]

----------------------------------------------------------------------------------------------------
Treino 76/120 | config=caucasian_1 | lambda=0.0005 | n_estimators=200 | learning_rate=0.03 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1830.0991544749081 1830.176657454992 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2146.1188693726895 1787.1405352285997 1788.2135946632857 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2382.9073887244417 1746.895256563711 1748.086710258073 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1219.72745637686 1708.6564854072622 1709.2663491354506 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3317.695718527576 1669.6948831824038 1671.3537310416675 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 341.82340673720455 1632.477938827909 1632.6488505312777 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3707.78479072924 1597.643666675795 1599.4975590711597 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 140.26704438839067 1564.4166264358041 1564.4867599579984 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 3922.040775812721 1533.6620984240753 1535.6231188119818 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 -101.50143176151832 1504.010981839971 1503.9602311240901 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 4179.611172321327 1476.5400566417306 1478.6298622278914 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -385.27038233859594 1450.2616993226134 1450.069064131444 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 4473.161275093524 1425.0838204597308 1427.3204010972775 Accuracy: 0.7811  test :  0.782  Prule Train :  1.0  Prule test :  0.998663101604278
65 -702.9495620241883 1401.3726429625867 1401.0211681815745 Accuracy: 0.7834  test :  0.782  Prule Train :  0.9999109504727481  Prule test :  0.998663101604278
70 4796.949873148699 1379.1650943181232 1381.5635692546978 Accuracy: 0.8651  test :  0.84  Prule Train :  0.959799648461916  Prule test :  0.966582521937733
75 -1047.92445230961 1357.5631362134561 1357.0391739873012 Accuracy: 0.868  test :  0.8413  Prule Train :  0.9583573371907707  Prule test :  0.9665427788979506
80 5144.732979526533 1337.11926076721 1339.6916272569733 Accuracy: 0.8726  test :  0.8433  Prule Train :  0.9579644927076952  Prule test :  0.9706615691489362
85 -1414.7156872282383 1317.2957541362994 1316.5883962926853 Accuracy: 0.8766  test :  0.8427  Prule Train :  0.9564064397296659  Prule test :  0.9748156129541384
90 5512.298857083852 1299.0307954130942 1301.7869448416363 Accuracy: 0.8803  test :  0.8427  Prule Train :  0.9554697686164515  Prule test :  0.9747872340425532
95 -1798.7709705750347 1281.9356671609305 1281.0362816756428 Accuracy: 0.8829  test :  0.8433  Prule Train :  0.9509864881363054  Prule test :  0.9705243161094227
100 5896.968870064693 1265.3280101926657 1268.276494627698 Accuracy: 0.8837  test :  0.8413  Prule Train :  0.950298939330018  Prule test :  0.9690667518948043
105 -2194.9080698298694 1250.0569342087367 1248.9594801738217 Accuracy: 0.8843  test :  0.842  Prule Train :  0.9502444709761783  Prule test :  0.9676437463854138
110 6296.217392743172 1234.399847140147 1237.5479558365182 Accuracy: 0.8849  test :  0.8427  Prule Train :  0.9501899361569893  Prule test :  0.9633747298572427
115 -2599.8998187720495 1218.3154141025998 1217.0154641932138 Accuracy: 0.8857  test :  0.842  Prule Train :  0.9507157472948555  Prule test :  0.9619517243478526
120 6704.55706879058 1203.1821093056565 1206.5343878400517 Accuracy: 0.8871  test :  0.842  Prule Train :  0.9487549939872679  Prule test :  0.9619517243478526
125 -3012.898707044131 1189.2083117472116 1187.7018623936897 Accuracy: 0.8871  test :  0.8413  Prule Train :  0.9487549939872679  Prule test :  0.9633298786807294
130 7138.446936180284 1175.7196960561475 1179.2889195242376 Accuracy: 0.8883  test :  0.8413  Prule Train :  0.9510803738744914  Prule test :  0.9633298786807294
135 -3435.190394338334 1162.2357371984194 1160.5181420012502 Accuracy: 0.8886  test :  0.842  Prule Train :  0.9516635010197241  Prule test :  0.9619048344814974
140 7577.460812600713 1149.3901420615623 1153.1788724678627 Accuracy: 0.8909  test :  0.8427  Prule Train :  0.9502242229514956  Prule test :  0.9604797902822655
145 -3859.544087800402 1136.2564021783473 1134.326630134447 Accuracy: 0.8917  test :  0.8433  Prule Train :  0.9483084483084484  Prule test :  0.9618578100674624
150 8023.386591048782 1123.8173482061493 1127.829041501674 Accuracy: 0.8929  test :  0.8433  Prule Train :  0.9481961253178965  Prule test :  0.9618578100674624
155 -4288.425523235592 1111.3921221029557 1109.2479093413378 Accuracy: 0.8931  test :  0.8433  Prule Train :  0.9475567482947557  Prule test :  0.9618578100674624
160 8476.969707985943 1099.5601353092313 1103.7986201632243 Accuracy: 0.8937  test :  0.8433  Prule Train :  0.947500089653936  Prule test :  0.9618578100674624
165 -4717.973237317887 1087.551033312834 1085.1920466941751 Accuracy: 0.8957  test :  0.8447  Prule Train :  0.9430216962524655  Prule test :  0.9646257462115415
170 8915.791568595576 1075.9820989905647 1080.4399947748625 Accuracy: 0.898  test :  0.844  Prule Train :  0.9427833116913934  Prule test :  0.9631945507423849
175 -5128.066086807583 1065.0533875947092 1062.4893545513055 Accuracy: 0.8986  test :  0.8433  Prule Train :  0.9427235316124205  Prule test :  0.964582439144031
180 9241.273849475197 1054.1874031252185 1058.8080400499562 Accuracy: 0.8997  test :  0.8433  Prule Train :  0.9438296191542945  Prule test :  0.964582439144031
185 -5429.365227784509 1043.6302181916612 1040.9155355777689 Accuracy: 0.9003  test :  0.8433  Prule Train :  0.9437703385723188  Prule test :  0.9673702496617882
190 9109.978175438953 1033.4671746676786 1038.0221637553982 Accuracy: 0.9011  test :  0.8427  Prule Train :  0.9430672526647759  Prule test :  0.9687702066077531
195 -5423.557451972674 1023.3990152254613 1020.6872364994749 Accuracy: 0.9023  test :  0.8433  Prule Train :  0.9417191647674918  Prule test :  0.9701742213999383
Resultado | acc=0.8427 | bal_acc=0.6655 | f1=0.9069 | EOdds=0.0217 | EOp=0.0033 | p-rule=96.87 | score=0.6643 | tempo=0.12 min

FAGTB caucasian_1:  27%|██▋       | 16/60 [01:26<04:09,  5.66s/modelo]

----------------------------------------------------------------------------------------------------
Treino 77/120 | config=caucasian_1 | lambda=0.0005 | n_estimators=100 | learning_rate=0.05 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1824.1232966433322 1824.2007996234165 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2131.2908579052164 1754.6048033711654 1755.6704488001183 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2426.122991455062 1690.2895902017908 1691.5026516975183 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1127.4028145202785 1627.4721708324905 1628.0358722397505 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3453.606017568153 1571.0244371321712 1572.7512401409554 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 184.67932911048905 1519.5126088933732 1519.6049485579285 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3876.783766042059 1472.4724530701621 1474.4108449531832 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -110.46182871147877 1429.761779055496 1429.7065481411403 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 4176.311719107869 1390.4254971596563 1392.5136530192103 Accuracy: 0.8649  test :  0.84  Prule Train :  0.9592242290084017  Prule test :  0.966582521937733
45 -466.76392429131045 1353.757019817153 1353.523637855007 Accuracy: 0.8691  test :  0.842  Prule Train :  0.9594630269329065  Prule test :  0.9679118196612622
50 4517.306094670399 1320.3277582481996 1322.5864112955346 Accuracy: 0.8766  test :  0.842  Prule Train :  0.9576176250933535  Prule test :  0.9734269867248593
55 -861.7233300690348 1289.4131466494941 1288.9822849844595 Accuracy: 0.8826  test :  0.8427  Prule Train :  0.9528330698348979  Prule test :  0.9719777217956111
60 4889.182715791907 1262.0112221294758 1264.4558134873719 Accuracy: 0.8837  test :  0.8407  Prule Train :  0.9515123088293821  Prule test :  0.9676823708206688
65 -1276.791810954116 1235.8512828369355 1235.2128869314583 Accuracy: 0.8849  test :  0.8413  Prule Train :  0.9501899361569893  Prule test :  0.9633747298572427
70 5278.355536581248 1209.255773425156 1211.8949511934466 Accuracy: 0.8863  test :  0.8413  Prule Train :  0.9506614005391512  Prule test :  0.9633747298572427
75 -1703.2697218706064 1186.0742871700108 1185.2226523090753 Accuracy: 0.888  test :  0.8413  Prule Train :  0.9504979609082487  Prule test :  0.9633747298572427
80 5696.421159695693 1164.0137478443548 1166.8619584242028 Accuracy: 0.8891  test :  0.842  Prule Train :  0.9516095356586155  Prule test :  0.9619517243478526
85 -2139.7031568066486 1141.873461974497 1140.8036103960937 Accuracy: 0.8911  test :  0.8433  Prule Train :  0.948364506375556  Prule test :  0.9619048344814974
90 6130.965365118267 1120.7900922742715 1123.8555749568307 Accuracy: 0.8926  test :  0.842  Prule Train :  0.9476133372875843  Prule test :  0.9618578100674624
95 -2581.5206295905964 1101.2497330747246 1099.958972759929 Accuracy: 0.894  test :  0.8413  Prule Train :  0.9456386172253332  Prule test :  0.96043072132849
Resultado | acc=0.8413 | bal_acc=0.6602 | f1=0.9063 | EOdds=0.0380 | EOp=0.0100 | p-rule=96.04 | score=0.6581 | tempo=0.06 min

FAGTB caucasian_1:  28%|██▊       | 17/60 [01:29<03:38,  5.08s/modelo]

----------------------------------------------------------------------------------------------------
Treino 78/120 | config=caucasian_1 | lambda=0.0005 | n_estimators=200 | learning_rate=0.05 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1824.1232966433322 1824.2007996234165 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2131.2908579052164 1754.6048033711654 1755.6704488001183 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2426.122991455062 1690.2895902017908 1691.5026516975183 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1127.4028145202785 1627.4721708324905 1628.0358722397505 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3453.606017568153 1571.0244371321712 1572.7512401409554 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 184.67932911048905 1519.5126088933732 1519.6049485579285 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3876.783766042059 1472.4724530701621 1474.4108449531832 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -110.46182871147877 1429.761779055496 1429.7065481411403 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 4176.311719107869 1390.4254971596563 1392.5136530192103 Accuracy: 0.8649  test :  0.84  Prule Train :  0.9592242290084017  Prule test :  0.966582521937733
45 -466.76392429131045 1353.757019817153 1353.523637855007 Accuracy: 0.8691  test :  0.842  Prule Train :  0.9594630269329065  Prule test :  0.9679118196612622
50 4517.306094670399 1320.3277582481996 1322.5864112955346 Accuracy: 0.8766  test :  0.842  Prule Train :  0.9576176250933535  Prule test :  0.9734269867248593
55 -861.7233300690348 1289.4131466494941 1288.9822849844595 Accuracy: 0.8826  test :  0.8427  Prule Train :  0.9528330698348979  Prule test :  0.9719777217956111
60 4889.182715791907 1262.0112221294758 1264.4558134873719 Accuracy: 0.8837  test :  0.8407  Prule Train :  0.9515123088293821  Prule test :  0.9676823708206688
65 -1276.791810954116 1235.8512828369355 1235.2128869314583 Accuracy: 0.8849  test :  0.8413  Prule Train :  0.9501899361569893  Prule test :  0.9633747298572427
70 5278.355536581248 1209.255773425156 1211.8949511934466 Accuracy: 0.8863  test :  0.8413  Prule Train :  0.9506614005391512  Prule test :  0.9633747298572427
75 -1703.2697218706064 1186.0742871700108 1185.2226523090753 Accuracy: 0.888  test :  0.8413  Prule Train :  0.9504979609082487  Prule test :  0.9633747298572427
80 5696.421159695693 1164.0137478443548 1166.8619584242028 Accuracy: 0.8891  test :  0.842  Prule Train :  0.9516095356586155  Prule test :  0.9619517243478526
85 -2139.7031568066486 1141.873461974497 1140.8036103960937 Accuracy: 0.8911  test :  0.8433  Prule Train :  0.948364506375556  Prule test :  0.9619048344814974
90 6130.965365118267 1120.7900922742715 1123.8555749568307 Accuracy: 0.8926  test :  0.842  Prule Train :  0.9476133372875843  Prule test :  0.9618578100674624
95 -2581.5206295905964 1101.2497330747246 1099.958972759929 Accuracy: 0.894  test :  0.8413  Prule Train :  0.9456386172253332  Prule test :  0.96043072132849
100 6577.323029781819 1081.5573360509327 1084.8459975658238 Accuracy: 0.8963  test :  0.8413  Prule Train :  0.9429622102035896  Prule test :  0.9603815113719734
105 -3025.476992999796 1062.4347314380543 1060.9219929415544 Accuracy: 0.8994  test :  0.8427  Prule Train :  0.942021536215483  Prule test :  0.9659743329956094
110 7031.510778597769 1044.8166770518112 1048.33243244111 Accuracy: 0.9009  test :  0.844  Prule Train :  0.9424836714440674  Prule test :  0.9660156968544975
115 -3464.7281482819617 1027.0843153283458 1025.3519512542048 Accuracy: 0.9029  test :  0.8453  Prule Train :  0.9441181619952568  Prule test :  0.9631036811887874
120 7485.611106652539 1010.4525640458278 1014.1953695991539 Accuracy: 0.9043  test :  0.8433  Prule Train :  0.9433533112837028  Prule test :  0.9644079555966697
125 -3895.2013738757287 992.7254179247884 990.7778172378506 Accuracy: 0.9054  test :  0.8413  Prule Train :  0.9444681511929334  Prule test :  0.9686193440490569
130 7917.379541997562 977.0463629211383 981.0050526921372 Accuracy: 0.908  test :  0.8407  Prule Train :  0.9435815952669886  Prule test :  0.9671714825482363
135 -4283.25854882555 962.8929327023081 960.7513034278953 Accuracy: 0.9097  test :  0.842  Prule Train :  0.9434013974351686  Prule test :  0.9643199529935674
140 8156.315631073168 949.9277546396579 954.0059124551944 Accuracy: 0.9109  test :  0.842  Prule Train :  0.9445233129443654  Prule test :  0.9643199529935674
145 -4478.012834613737 936.1061064151968 933.8670999978899 Accuracy: 0.9126  test :  0.8413  Prule Train :  0.9406149406149408  Prule test :  0.9657236210474156
150 7867.461430184863 923.3014611431789 927.2351918582713 Accuracy: 0.9149  test :  0.8413  Prule Train :  0.9403661664968197  Prule test :  0.968505039193729
155 -4362.038783347529 910.3523708411747 908.1713514495008 Accuracy: 0.9171  test :  0.8413  Prule Train :  0.9413636143314783  Prule test :  0.968505039193729
160 7573.954121792147 897.4621142206747 901.2490912815707 Accuracy: 0.9189  test :  0.8413  Prule Train :  0.9436816870445189  Prule test :  0.968505039193729
165 -4180.689161148151 884.5806010141407 882.4902564335666 Accuracy: 0.9211  test :  0.8413  Prule Train :  0.9409282700421941  Prule test :  0.9655966156526066
170 7391.358148477496 873.1239934173187 876.8196724915574 Accuracy: 0.922  test :  0.8413  Prule Train :  0.9389542946504972  Prule test :  0.9655966156526066
175 -4004.10390559994 861.5415565920739 859.5395046392739 Accuracy: 0.9229  test :  0.8413  Prule Train :  0.938232128859108  Prule test :  0.9655966156526066
180 7220.201958199561 850.7694446854172 854.3795456645171 Accuracy: 0.9237  test :  0.8413  Prule Train :  0.938762780233928  Prule test :  0.9655966156526066
185 -3852.9092736884295 840.2141669645235 838.2877123276794 Accuracy: 0.9251  test :  0.8413  Prule Train :  0.9379746179746181  Prule test :  0.9655966156526066
190 7078.760639893539 829.465077699236 833.0044580191827 Accuracy: 0.9257  test :  0.8413  Prule Train :  0.9379100357499339  Prule test :  0.9655966156526066
195 -3705.2148996134565 819.5383696210808 817.685762171274 Accuracy: 0.9266  test :  0.8407  Prule Train :  0.9384419651595224  Prule test :  0.9641424038820454
Resultado | acc=0.8413 | bal_acc=0.6723 | f1=0.9055 | EOdds=0.0337 | EOp=0.0056 | p-rule=96.27 | score=0.6705 | tempo=0.12 min

FAGTB caucasian_1:  30%|███       | 18/60 [01:36<03:58,  5.67s/modelo]

----------------------------------------------------------------------------------------------------
Treino 79/120 | config=caucasian_1 | lambda=0.0005 | n_estimators=100 | learning_rate=0.05 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1824.1232966433322 1824.2007996234165 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2131.2908579052164 1754.6048033711654 1755.6704488001183 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2426.122991455062 1690.2895902017908 1691.5026516975183 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1127.4028145202785 1627.4721708324905 1628.0358722397505 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3453.606017568153 1571.0244371321712 1572.7512401409554 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 184.67932911048905 1519.5126088933732 1519.6049485579285 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3876.783766042059 1472.4724530701621 1474.4108449531832 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -110.46182871147877 1429.761779055496 1429.7065481411403 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 4176.311719107869 1390.4254971596563 1392.5136530192103 Accuracy: 0.8649  test :  0.84  Prule Train :  0.9592242290084017  Prule test :  0.966582521937733
45 -466.76392429131045 1353.757019817153 1353.523637855007 Accuracy: 0.8691  test :  0.842  Prule Train :  0.9594630269329065  Prule test :  0.9679118196612622
50 4517.306094670399 1320.3277582481996 1322.5864112955346 Accuracy: 0.8766  test :  0.842  Prule Train :  0.9576176250933535  Prule test :  0.9734269867248593
55 -861.7233300690348 1289.4131466494941 1288.9822849844595 Accuracy: 0.8826  test :  0.8427  Prule Train :  0.9528330698348979  Prule test :  0.9719777217956111
60 4889.182715791907 1262.0112221294758 1264.4558134873719 Accuracy: 0.8837  test :  0.8407  Prule Train :  0.9515123088293821  Prule test :  0.9676823708206688
65 -1276.791810954116 1235.8512828369355 1235.2128869314583 Accuracy: 0.8849  test :  0.8413  Prule Train :  0.9501899361569893  Prule test :  0.9633747298572427
70 5278.355536581248 1209.255773425156 1211.8949511934466 Accuracy: 0.8863  test :  0.8413  Prule Train :  0.9506614005391512  Prule test :  0.9633747298572427
75 -1703.2697218706064 1186.0742871700108 1185.2226523090753 Accuracy: 0.888  test :  0.8413  Prule Train :  0.9504979609082487  Prule test :  0.9633747298572427
80 5696.421159695693 1164.0137478443548 1166.8619584242028 Accuracy: 0.8891  test :  0.842  Prule Train :  0.9516095356586155  Prule test :  0.9619517243478526
85 -2139.7031568066486 1141.873461974497 1140.8036103960937 Accuracy: 0.8911  test :  0.8433  Prule Train :  0.948364506375556  Prule test :  0.9619048344814974
90 6130.965365118267 1120.7900922742715 1123.8555749568307 Accuracy: 0.8926  test :  0.842  Prule Train :  0.9476133372875843  Prule test :  0.9618578100674624
95 -2581.5206295905964 1101.2497330747246 1099.958972759929 Accuracy: 0.894  test :  0.8413  Prule Train :  0.9456386172253332  Prule test :  0.96043072132849
Resultado | acc=0.8413 | bal_acc=0.6602 | f1=0.9063 | EOdds=0.0380 | EOp=0.0100 | p-rule=96.04 | score=0.6581 | tempo=0.06 min

FAGTB caucasian_1:  32%|███▏      | 19/60 [01:40<03:27,  5.07s/modelo]

----------------------------------------------------------------------------------------------------
Treino 80/120 | config=caucasian_1 | lambda=0.0005 | n_estimators=200 | learning_rate=0.05 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1824.1232966433322 1824.2007996234165 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2131.2908579052164 1754.6048033711654 1755.6704488001183 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2426.122991455062 1690.2895902017908 1691.5026516975183 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1127.4028145202785 1627.4721708324905 1628.0358722397505 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3453.606017568153 1571.0244371321712 1572.7512401409554 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 184.67932911048905 1519.5126088933732 1519.6049485579285 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3876.783766042059 1472.4724530701621 1474.4108449531832 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -110.46182871147877 1429.761779055496 1429.7065481411403 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 4176.311719107869 1390.4254971596563 1392.5136530192103 Accuracy: 0.8649  test :  0.84  Prule Train :  0.9592242290084017  Prule test :  0.966582521937733
45 -466.76392429131045 1353.757019817153 1353.523637855007 Accuracy: 0.8691  test :  0.842  Prule Train :  0.9594630269329065  Prule test :  0.9679118196612622
50 4517.306094670399 1320.3277582481996 1322.5864112955346 Accuracy: 0.8766  test :  0.842  Prule Train :  0.9576176250933535  Prule test :  0.9734269867248593
55 -861.7233300690348 1289.4131466494941 1288.9822849844595 Accuracy: 0.8826  test :  0.8427  Prule Train :  0.9528330698348979  Prule test :  0.9719777217956111
60 4889.182715791907 1262.0112221294758 1264.4558134873719 Accuracy: 0.8837  test :  0.8407  Prule Train :  0.9515123088293821  Prule test :  0.9676823708206688
65 -1276.791810954116 1235.8512828369355 1235.2128869314583 Accuracy: 0.8849  test :  0.8413  Prule Train :  0.9501899361569893  Prule test :  0.9633747298572427
70 5278.355536581248 1209.255773425156 1211.8949511934466 Accuracy: 0.8863  test :  0.8413  Prule Train :  0.9506614005391512  Prule test :  0.9633747298572427
75 -1703.2697218706064 1186.0742871700108 1185.2226523090753 Accuracy: 0.888  test :  0.8413  Prule Train :  0.9504979609082487  Prule test :  0.9633747298572427
80 5696.421159695693 1164.0137478443548 1166.8619584242028 Accuracy: 0.8891  test :  0.842  Prule Train :  0.9516095356586155  Prule test :  0.9619517243478526
85 -2139.7031568066486 1141.873461974497 1140.8036103960937 Accuracy: 0.8911  test :  0.8433  Prule Train :  0.948364506375556  Prule test :  0.9619048344814974
90 6130.965365118267 1120.7900922742715 1123.8555749568307 Accuracy: 0.8926  test :  0.842  Prule Train :  0.9476133372875843  Prule test :  0.9618578100674624
95 -2581.5206295905964 1101.2497330747246 1099.958972759929 Accuracy: 0.894  test :  0.8413  Prule Train :  0.9456386172253332  Prule test :  0.96043072132849
100 6577.323029781819 1081.5573360509327 1084.8459975658238 Accuracy: 0.8963  test :  0.8413  Prule Train :  0.9429622102035896  Prule test :  0.9603815113719734
105 -3025.476992999796 1062.4347314380543 1060.9219929415544 Accuracy: 0.8994  test :  0.8427  Prule Train :  0.942021536215483  Prule test :  0.9659743329956094
110 7031.510778597769 1044.8166770518112 1048.33243244111 Accuracy: 0.9009  test :  0.844  Prule Train :  0.9424836714440674  Prule test :  0.9660156968544975
115 -3464.7281482819617 1027.0843153283458 1025.3519512542048 Accuracy: 0.9029  test :  0.8453  Prule Train :  0.9441181619952568  Prule test :  0.9631036811887874
120 7485.611106652539 1010.4525640458278 1014.1953695991539 Accuracy: 0.9043  test :  0.8433  Prule Train :  0.9433533112837028  Prule test :  0.9644079555966697
125 -3895.2013738757287 992.7254179247884 990.7778172378506 Accuracy: 0.9054  test :  0.8413  Prule Train :  0.9444681511929334  Prule test :  0.9686193440490569
130 7917.379541997562 977.0463629211383 981.0050526921372 Accuracy: 0.908  test :  0.8407  Prule Train :  0.9435815952669886  Prule test :  0.9671714825482363
135 -4283.25854882555 962.8929327023081 960.7513034278953 Accuracy: 0.9097  test :  0.842  Prule Train :  0.9434013974351686  Prule test :  0.9643199529935674
140 8156.315631073168 949.9277546396579 954.0059124551944 Accuracy: 0.9109  test :  0.842  Prule Train :  0.9445233129443654  Prule test :  0.9643199529935674
145 -4478.012834613737 936.1061064151968 933.8670999978899 Accuracy: 0.9126  test :  0.8413  Prule Train :  0.9406149406149408  Prule test :  0.9657236210474156
150 7867.461430184863 923.3014611431789 927.2351918582713 Accuracy: 0.9149  test :  0.8413  Prule Train :  0.9403661664968197  Prule test :  0.968505039193729
155 -4362.038783347529 910.3523708411747 908.1713514495008 Accuracy: 0.9171  test :  0.8413  Prule Train :  0.9413636143314783  Prule test :  0.968505039193729
160 7573.954121792147 897.4621142206747 901.2490912815707 Accuracy: 0.9189  test :  0.8413  Prule Train :  0.9436816870445189  Prule test :  0.968505039193729
165 -4180.689161148151 884.5806010141407 882.4902564335666 Accuracy: 0.9211  test :  0.8413  Prule Train :  0.9409282700421941  Prule test :  0.9655966156526066
170 7391.358148477496 873.1239934173187 876.8196724915574 Accuracy: 0.922  test :  0.8413  Prule Train :  0.9389542946504972  Prule test :  0.9655966156526066
175 -4004.10390559994 861.5415565920739 859.5395046392739 Accuracy: 0.9229  test :  0.8413  Prule Train :  0.938232128859108  Prule test :  0.9655966156526066
180 7220.201958199561 850.7694446854172 854.3795456645171 Accuracy: 0.9237  test :  0.8413  Prule Train :  0.938762780233928  Prule test :  0.9655966156526066
185 -3852.9092736884295 840.2141669645235 838.2877123276794 Accuracy: 0.9251  test :  0.8413  Prule Train :  0.9379746179746181  Prule test :  0.9655966156526066
190 7078.760639893539 829.465077699236 833.0044580191827 Accuracy: 0.9257  test :  0.8413  Prule Train :  0.9379100357499339  Prule test :  0.9655966156526066
195 -3705.2148996134565 819.5383696210808 817.685762171274 Accuracy: 0.9266  test :  0.8407  Prule Train :  0.9384419651595224  Prule test :  0.9641424038820454
Resultado | acc=0.8413 | bal_acc=0.6723 | f1=0.9055 | EOdds=0.0337 | EOp=0.0056 | p-rule=96.27 | score=0.6705 | tempo=0.12 min

FAGTB caucasian_1:  33%|███▎      | 20/60 [01:47<03:46,  5.66s/modelo]

----------------------------------------------------------------------------------------------------
Treino 81/120 | config=caucasian_1 | lambda=0.0005 | n_estimators=100 | learning_rate=0.1 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1809.275475967545 1809.3529789476293 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2091.4270114428214 1675.1599913985217 1676.2057049042432 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2523.380747031068 1557.2801366712326 1558.541827044748 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 899.6020567299299 1461.5885461499893 1462.0383471783543 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3694.1647871075834 1381.097237466166 1382.9443198597198 Accuracy: 0.8654  test :  0.8407  Prule Train :  0.9591759969684385  Prule test :  0.9679496825062445
25 -121.29763607091877 1312.6581539125082 1312.5975050944726 Accuracy: 0.8771  test :  0.842  Prule Train :  0.9551455215494026  Prule test :  0.9734269867248593
30 4100.808204846874 1255.6871620628986 1257.737566165322 Accuracy: 0.8846  test :  0.8427  Prule Train :  0.9496105520495765  Prule test :  0.9661799670791928
35 -579.3477281847462 1202.8384017329345 1202.548727868842 Accuracy: 0.8866  test :  0.842  Prule Train :  0.9488105053163085  Prule test :  0.964754922879961
40 4467.06398237758 1157.5038225108426 1159.7373545020314 Accuracy: 0.8906  test :  0.8433  Prule Train :  0.9472015823947156  Prule test :  0.9646689288334556
45 -1050.0025686143367 1113.8873749350996 1113.3623736507925 Accuracy: 0.8946  test :  0.8447  Prule Train :  0.9455807781961628  Prule test :  0.9646689288334556
50 4873.400966616537 1076.3333288201648 1078.770029303473 Accuracy: 0.8977  test :  0.846  Prule Train :  0.94342466088302  Prule test :  0.9617633552732281
55 -1516.9225520733119 1038.2588369543882 1037.5003756783517 Accuracy: 0.9043  test :  0.8433  Prule Train :  0.9421216464694726  Prule test :  0.9644517658650738
60 5302.992829447655 1006.0137338423721 1008.6652302570958 Accuracy: 0.9063  test :  0.8413  Prule Train :  0.9425261330616249  Prule test :  0.9629203594478585
65 -1967.4097284504685 976.8853617324622 975.901656868237 Accuracy: 0.9109  test :  0.842  Prule Train :  0.939562937062937  Prule test :  0.9643199529935674
70 5742.888869967223 947.6942894740423 950.5657339090259 Accuracy: 0.9129  test :  0.842  Prule Train :  0.939963545226703  Prule test :  0.9642757595465947
75 -2406.1051022182965 919.2647700486873 918.061717497578 Accuracy: 0.9154  test :  0.84  Prule Train :  0.9390601023766854  Prule test :  0.9656390743904333
80 6198.4997497311415 892.1775811186744 895.2768309935401 Accuracy: 0.9189  test :  0.84  Prule Train :  0.9399277904009763  Prule test :  0.968505039193729
85 -2831.069599862811 869.4740950259263 868.0585602259949 Accuracy: 0.9211  test :  0.84  Prule Train :  0.9421825799279886  Prule test :  0.9684667144325723
90 6662.133306642426 850.1782650632526 853.5093317165738 Accuracy: 0.9223  test :  0.8407  Prule Train :  0.9420589978611538  Prule test :  0.9698867536032946
95 -3232.2158126885156 830.2765845983034 828.660476691959 Accuracy: 0.9243  test :  0.8393  Prule Train :  0.93995485995486  Prule test :  0.9698503452369793
Resultado | acc=0.8407 | bal_acc=0.6719 | f1=0.9050 | EOdds=0.0212 | EOp=0.0005 | p-rule=96.99 | score=0.6708 | tempo=0.06 min

FAGTB caucasian_1:  35%|███▌      | 21/60 [01:51<03:17,  5.08s/modelo]

----------------------------------------------------------------------------------------------------
Treino 82/120 | config=caucasian_1 | lambda=0.0005 | n_estimators=200 | learning_rate=0.1 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1809.275475967545 1809.3529789476293 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2091.4270114428214 1675.1599913985217 1676.2057049042432 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2523.380747031068 1557.2801366712326 1558.541827044748 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 899.6020567299299 1461.5885461499893 1462.0383471783543 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3694.1647871075834 1381.097237466166 1382.9443198597198 Accuracy: 0.8654  test :  0.8407  Prule Train :  0.9591759969684385  Prule test :  0.9679496825062445
25 -121.29763607091877 1312.6581539125082 1312.5975050944726 Accuracy: 0.8771  test :  0.842  Prule Train :  0.9551455215494026  Prule test :  0.9734269867248593
30 4100.808204846874 1255.6871620628986 1257.737566165322 Accuracy: 0.8846  test :  0.8427  Prule Train :  0.9496105520495765  Prule test :  0.9661799670791928
35 -579.3477281847462 1202.8384017329345 1202.548727868842 Accuracy: 0.8866  test :  0.842  Prule Train :  0.9488105053163085  Prule test :  0.964754922879961
40 4467.06398237758 1157.5038225108426 1159.7373545020314 Accuracy: 0.8906  test :  0.8433  Prule Train :  0.9472015823947156  Prule test :  0.9646689288334556
45 -1050.0025686143367 1113.8873749350996 1113.3623736507925 Accuracy: 0.8946  test :  0.8447  Prule Train :  0.9455807781961628  Prule test :  0.9646689288334556
50 4873.400966616537 1076.3333288201648 1078.770029303473 Accuracy: 0.8977  test :  0.846  Prule Train :  0.94342466088302  Prule test :  0.9617633552732281
55 -1516.9225520733119 1038.2588369543882 1037.5003756783517 Accuracy: 0.9043  test :  0.8433  Prule Train :  0.9421216464694726  Prule test :  0.9644517658650738
60 5302.992829447655 1006.0137338423721 1008.6652302570958 Accuracy: 0.9063  test :  0.8413  Prule Train :  0.9425261330616249  Prule test :  0.9629203594478585
65 -1967.4097284504685 976.8853617324622 975.901656868237 Accuracy: 0.9109  test :  0.842  Prule Train :  0.939562937062937  Prule test :  0.9643199529935674
70 5742.888869967223 947.6942894740423 950.5657339090259 Accuracy: 0.9129  test :  0.842  Prule Train :  0.939963545226703  Prule test :  0.9642757595465947
75 -2406.1051022182965 919.2647700486873 918.061717497578 Accuracy: 0.9154  test :  0.84  Prule Train :  0.9390601023766854  Prule test :  0.9656390743904333
80 6198.4997497311415 892.1775811186744 895.2768309935401 Accuracy: 0.9189  test :  0.84  Prule Train :  0.9399277904009763  Prule test :  0.968505039193729
85 -2831.069599862811 869.4740950259263 868.0585602259949 Accuracy: 0.9211  test :  0.84  Prule Train :  0.9421825799279886  Prule test :  0.9684667144325723
90 6662.133306642426 850.1782650632526 853.5093317165738 Accuracy: 0.9223  test :  0.8407  Prule Train :  0.9420589978611538  Prule test :  0.9698867536032946
95 -3232.2158126885156 830.2765845983034 828.660476691959 Accuracy: 0.9243  test :  0.8393  Prule Train :  0.93995485995486  Prule test :  0.9698503452369793
100 6950.6353411484015 813.8279702336043 817.3032879041787 Accuracy: 0.926  test :  0.8407  Prule Train :  0.939764645871516  Prule test :  0.9669698009608784
105 -3432.767565272461 797.6233098761577 795.9069260935215 Accuracy: 0.9289  test :  0.84  Prule Train :  0.9394460039003755  Prule test :  0.9683897272471647
110 6695.1665495862535 781.6289116906512 784.9764949654443 Accuracy: 0.9317  test :  0.842  Prule Train :  0.9353321864503971  Prule test :  0.9640528483184626
115 -3310.0175289833714 765.1041150716176 763.4491063071258 Accuracy: 0.9331  test :  0.8427  Prule Train :  0.9357974505221623  Prule test :  0.9654684912675351
120 6437.370889442218 750.5789964330347 753.7976818777557 Accuracy: 0.9343  test :  0.8413  Prule Train :  0.9356643356643359  Prule test :  0.9654255319148937
125 -3129.421208661047 734.552342495848 732.9876318915176 Accuracy: 0.9363  test :  0.8413  Prule Train :  0.9335290298063085  Prule test :  0.9654255319148937
130 6181.056936306869 720.3912276219407 723.4817560900941 Accuracy: 0.9389  test :  0.842  Prule Train :  0.9313186277816503  Prule test :  0.9639627659574468
135 -2998.6466085694087 703.1954407586827 701.6961174543981 Accuracy: 0.9414  test :  0.8413  Prule Train :  0.9290996803883403  Prule test :  0.9625472552879059
140 6122.615639256079 689.0146780732027 692.0759858928307 Accuracy: 0.9437  test :  0.8413  Prule Train :  0.9300865047471382  Prule test :  0.9625000000000001
145 -2757.9935675908127 673.9175963026966 672.5385995189012 Accuracy: 0.9443  test :  0.8413  Prule Train :  0.9300156505848615  Prule test :  0.9625000000000001
150 5459.763826883413 660.6354762314458 663.3653581448874 Accuracy: 0.9457  test :  0.84  Prule Train :  0.9266533380375553  Prule test :  0.9624050712357999
155 -2745.27872086247 648.3810930687844 647.008453708353 Accuracy: 0.9477  test :  0.84  Prule Train :  0.9232157270992222  Prule test :  0.9623573965240894
160 5916.098311650068 636.9163124989536 639.8743616547786 Accuracy: 0.95  test :  0.8407  Prule Train :  0.9216408321466686  Prule test :  0.9609379903345256
165 -2434.405833515528 624.3009090938914 623.0837061771335 Accuracy: 0.9523  test :  0.8413  Prule Train :  0.9238873106060607  Prule test :  0.9623573965240894
170 5088.3108223612835 614.1374002928762 616.6815557040569 Accuracy: 0.954  test :  0.8413  Prule Train :  0.9223809654057373  Prule test :  0.9623095807629357
175 -2505.5214333662516 603.0349806236038 601.7822199069207 Accuracy: 0.9549  test :  0.8407  Prule Train :  0.9203477964886049  Prule test :  0.9608381593856226
180 5600.392256465153 594.0787383152721 596.8789344435047 Accuracy: 0.9557  test :  0.8413  Prule Train :  0.9208706871892249  Prule test :  0.9623095807629357
185 -2259.2477523743605 583.7818492193567 582.6522253431694 Accuracy: 0.9577  test :  0.8413  Prule Train :  0.9186769657357893  Prule test :  0.9623095807629357
190 4848.04295378453 575.7754172020459 578.1994386789381 Accuracy: 0.958  test :  0.8413  Prule Train :  0.9179974709386474  Prule test :  0.9623095807629357
195 -2327.8798503656762 565.374366108586 564.2104261834031 Accuracy: 0.96  test :  0.8413  Prule Train :  0.9145182264868336  Prule test :  0.9593667380083092
Resultado | acc=0.8407 | bal_acc=0.6818 | f1=0.9044 | EOdds=0.0189 | EOp=0.0131 | p-rule=95.79 | score=0.6804 | tempo=0.12 min

FAGTB caucasian_1:  37%|███▋      | 22/60 [01:58<03:35,  5.66s/modelo]

----------------------------------------------------------------------------------------------------
Treino 83/120 | config=caucasian_1 | lambda=0.0005 | n_estimators=100 | learning_rate=0.1 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1809.275475967545 1809.3529789476293 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2091.4270114428214 1675.1599913985217 1676.2057049042432 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2523.380747031068 1557.2801366712326 1558.541827044748 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 899.6020567299299 1461.5885461499893 1462.0383471783543 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3694.1647871075834 1381.097237466166 1382.9443198597198 Accuracy: 0.8654  test :  0.8407  Prule Train :  0.9591759969684385  Prule test :  0.9679496825062445
25 -121.29763607091877 1312.6581539125082 1312.5975050944726 Accuracy: 0.8771  test :  0.842  Prule Train :  0.9551455215494026  Prule test :  0.9734269867248593
30 4100.808204846874 1255.6871620628986 1257.737566165322 Accuracy: 0.8846  test :  0.8427  Prule Train :  0.9496105520495765  Prule test :  0.9661799670791928
35 -579.3477281847462 1202.8384017329345 1202.548727868842 Accuracy: 0.8866  test :  0.842  Prule Train :  0.9488105053163085  Prule test :  0.964754922879961
40 4467.06398237758 1157.5038225108426 1159.7373545020314 Accuracy: 0.8906  test :  0.8433  Prule Train :  0.9472015823947156  Prule test :  0.9646689288334556
45 -1050.0025686143367 1113.8873749350996 1113.3623736507925 Accuracy: 0.8946  test :  0.8447  Prule Train :  0.9455807781961628  Prule test :  0.9646689288334556
50 4873.400966616537 1076.3333288201648 1078.770029303473 Accuracy: 0.8977  test :  0.846  Prule Train :  0.94342466088302  Prule test :  0.9617633552732281
55 -1516.9225520733119 1038.2588369543882 1037.5003756783517 Accuracy: 0.9043  test :  0.8433  Prule Train :  0.9421216464694726  Prule test :  0.9644517658650738
60 5302.992829447655 1006.0137338423721 1008.6652302570958 Accuracy: 0.9063  test :  0.8413  Prule Train :  0.9425261330616249  Prule test :  0.9629203594478585
65 -1967.4097284504685 976.8853617324622 975.901656868237 Accuracy: 0.9109  test :  0.842  Prule Train :  0.939562937062937  Prule test :  0.9643199529935674
70 5742.888869967223 947.6942894740423 950.5657339090259 Accuracy: 0.9129  test :  0.842  Prule Train :  0.939963545226703  Prule test :  0.9642757595465947
75 -2406.1051022182965 919.2647700486873 918.061717497578 Accuracy: 0.9154  test :  0.84  Prule Train :  0.9390601023766854  Prule test :  0.9656390743904333
80 6198.4997497311415 892.1775811186744 895.2768309935401 Accuracy: 0.9189  test :  0.84  Prule Train :  0.9399277904009763  Prule test :  0.968505039193729
85 -2831.069599862811 869.4740950259263 868.0585602259949 Accuracy: 0.9211  test :  0.84  Prule Train :  0.9421825799279886  Prule test :  0.9684667144325723
90 6662.133306642426 850.1782650632526 853.5093317165738 Accuracy: 0.9223  test :  0.8407  Prule Train :  0.9420589978611538  Prule test :  0.9698867536032946
95 -3232.2158126885156 830.2765845983034 828.660476691959 Accuracy: 0.9243  test :  0.8393  Prule Train :  0.93995485995486  Prule test :  0.9698503452369793
Resultado | acc=0.8407 | bal_acc=0.6719 | f1=0.9050 | EOdds=0.0212 | EOp=0.0005 | p-rule=96.99 | score=0.6708 | tempo=0.06 min

FAGTB caucasian_1:  38%|███▊      | 23/60 [02:01<03:07,  5.06s/modelo]

----------------------------------------------------------------------------------------------------
Treino 84/120 | config=caucasian_1 | lambda=0.0005 | n_estimators=200 | learning_rate=0.1 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1809.275475967545 1809.3529789476293 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2091.4270114428214 1675.1599913985217 1676.2057049042432 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2523.380747031068 1557.2801366712326 1558.541827044748 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 899.6020567299299 1461.5885461499893 1462.0383471783543 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3694.1647871075834 1381.097237466166 1382.9443198597198 Accuracy: 0.8654  test :  0.8407  Prule Train :  0.9591759969684385  Prule test :  0.9679496825062445
25 -121.29763607091877 1312.6581539125082 1312.5975050944726 Accuracy: 0.8771  test :  0.842  Prule Train :  0.9551455215494026  Prule test :  0.9734269867248593
30 4100.808204846874 1255.6871620628986 1257.737566165322 Accuracy: 0.8846  test :  0.8427  Prule Train :  0.9496105520495765  Prule test :  0.9661799670791928
35 -579.3477281847462 1202.8384017329345 1202.548727868842 Accuracy: 0.8866  test :  0.842  Prule Train :  0.9488105053163085  Prule test :  0.964754922879961
40 4467.06398237758 1157.5038225108426 1159.7373545020314 Accuracy: 0.8906  test :  0.8433  Prule Train :  0.9472015823947156  Prule test :  0.9646689288334556
45 -1050.0025686143367 1113.8873749350996 1113.3623736507925 Accuracy: 0.8946  test :  0.8447  Prule Train :  0.9455807781961628  Prule test :  0.9646689288334556
50 4873.400966616537 1076.3333288201648 1078.770029303473 Accuracy: 0.8977  test :  0.846  Prule Train :  0.94342466088302  Prule test :  0.9617633552732281
55 -1516.9225520733119 1038.2588369543882 1037.5003756783517 Accuracy: 0.9043  test :  0.8433  Prule Train :  0.9421216464694726  Prule test :  0.9644517658650738
60 5302.992829447655 1006.0137338423721 1008.6652302570958 Accuracy: 0.9063  test :  0.8413  Prule Train :  0.9425261330616249  Prule test :  0.9629203594478585
65 -1967.4097284504685 976.8853617324622 975.901656868237 Accuracy: 0.9109  test :  0.842  Prule Train :  0.939562937062937  Prule test :  0.9643199529935674
70 5742.888869967223 947.6942894740423 950.5657339090259 Accuracy: 0.9129  test :  0.842  Prule Train :  0.939963545226703  Prule test :  0.9642757595465947
75 -2406.1051022182965 919.2647700486873 918.061717497578 Accuracy: 0.9154  test :  0.84  Prule Train :  0.9390601023766854  Prule test :  0.9656390743904333
80 6198.4997497311415 892.1775811186744 895.2768309935401 Accuracy: 0.9189  test :  0.84  Prule Train :  0.9399277904009763  Prule test :  0.968505039193729
85 -2831.069599862811 869.4740950259263 868.0585602259949 Accuracy: 0.9211  test :  0.84  Prule Train :  0.9421825799279886  Prule test :  0.9684667144325723
90 6662.133306642426 850.1782650632526 853.5093317165738 Accuracy: 0.9223  test :  0.8407  Prule Train :  0.9420589978611538  Prule test :  0.9698867536032946
95 -3232.2158126885156 830.2765845983034 828.660476691959 Accuracy: 0.9243  test :  0.8393  Prule Train :  0.93995485995486  Prule test :  0.9698503452369793
100 6950.6353411484015 813.8279702336043 817.3032879041787 Accuracy: 0.926  test :  0.8407  Prule Train :  0.939764645871516  Prule test :  0.9669698009608784
105 -3432.767565272461 797.6233098761577 795.9069260935215 Accuracy: 0.9289  test :  0.84  Prule Train :  0.9394460039003755  Prule test :  0.9683897272471647
110 6695.1665495862535 781.6289116906512 784.9764949654443 Accuracy: 0.9317  test :  0.842  Prule Train :  0.9353321864503971  Prule test :  0.9640528483184626
115 -3310.0175289833714 765.1041150716176 763.4491063071258 Accuracy: 0.9331  test :  0.8427  Prule Train :  0.9357974505221623  Prule test :  0.9654684912675351
120 6437.370889442218 750.5789964330347 753.7976818777557 Accuracy: 0.9343  test :  0.8413  Prule Train :  0.9356643356643359  Prule test :  0.9654255319148937
125 -3129.421208661047 734.552342495848 732.9876318915176 Accuracy: 0.9363  test :  0.8413  Prule Train :  0.9335290298063085  Prule test :  0.9654255319148937
130 6181.056936306869 720.3912276219407 723.4817560900941 Accuracy: 0.9389  test :  0.842  Prule Train :  0.9313186277816503  Prule test :  0.9639627659574468
135 -2998.6466085694087 703.1954407586827 701.6961174543981 Accuracy: 0.9414  test :  0.8413  Prule Train :  0.9290996803883403  Prule test :  0.9625472552879059
140 6122.615639256079 689.0146780732027 692.0759858928307 Accuracy: 0.9437  test :  0.8413  Prule Train :  0.9300865047471382  Prule test :  0.9625000000000001
145 -2757.9935675908127 673.9175963026966 672.5385995189012 Accuracy: 0.9443  test :  0.8413  Prule Train :  0.9300156505848615  Prule test :  0.9625000000000001
150 5459.763826883413 660.6354762314458 663.3653581448874 Accuracy: 0.9457  test :  0.84  Prule Train :  0.9266533380375553  Prule test :  0.9624050712357999
155 -2745.27872086247 648.3810930687844 647.008453708353 Accuracy: 0.9477  test :  0.84  Prule Train :  0.9232157270992222  Prule test :  0.9623573965240894
160 5916.098311650068 636.9163124989536 639.8743616547786 Accuracy: 0.95  test :  0.8407  Prule Train :  0.9216408321466686  Prule test :  0.9609379903345256
165 -2434.405833515528 624.3009090938914 623.0837061771335 Accuracy: 0.9523  test :  0.8413  Prule Train :  0.9238873106060607  Prule test :  0.9623573965240894
170 5088.3108223612835 614.1374002928762 616.6815557040569 Accuracy: 0.954  test :  0.8413  Prule Train :  0.9223809654057373  Prule test :  0.9623095807629357
175 -2505.5214333662516 603.0349806236038 601.7822199069207 Accuracy: 0.9549  test :  0.8407  Prule Train :  0.9203477964886049  Prule test :  0.9608381593856226
180 5600.392256465153 594.0787383152721 596.8789344435047 Accuracy: 0.9557  test :  0.8413  Prule Train :  0.9208706871892249  Prule test :  0.9623095807629357
185 -2259.2477523743605 583.7818492193567 582.6522253431694 Accuracy: 0.9577  test :  0.8413  Prule Train :  0.9186769657357893  Prule test :  0.9623095807629357
190 4848.04295378453 575.7754172020459 578.1994386789381 Accuracy: 0.958  test :  0.8413  Prule Train :  0.9179974709386474  Prule test :  0.9623095807629357
195 -2327.8798503656762 565.374366108586 564.2104261834031 Accuracy: 0.96  test :  0.8413  Prule Train :  0.9145182264868336  Prule test :  0.9593667380083092
Resultado | acc=0.8407 | bal_acc=0.6818 | f1=0.9044 | EOdds=0.0189 | EOp=0.0131 | p-rule=95.79 | score=0.6804 | tempo=0.11 min

FAGTB caucasian_1:  40%|████      | 24/60 [02:08<03:23,  5.65s/modelo]

----------------------------------------------------------------------------------------------------
Treino 85/120 | config=caucasian_1 | lambda=0.001 | n_estimators=100 | learning_rate=0.03 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1830.0992975710415 1830.2543035312096 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2146.562821798611 1787.602168150932 1789.748730972731 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2381.69005988484 1747.37704191557 1749.758731975455 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1221.0590978217629 1708.2392179557387 1709.4602770535603 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3316.705557796087 1669.459362201812 1672.776067759608 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 341.7709727577888 1632.5826696450188 1632.9244406177766 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3707.899318011561 1597.7973044841006 1601.5052038021122 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 139.566689424231 1564.5360290319456 1564.6755957213702 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 3922.2160086662916 1533.4940295900878 1537.416245598754 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 -101.71955329970311 1504.1470000216618 1504.045280468362 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 4178.789779769477 1476.7049579494096 1480.8837477291788 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -384.55690879906865 1450.525941609393 1450.141384700594 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 4471.459135427103 1426.097644448938 1430.5691035843652 Accuracy: 0.7811  test :  0.782  Prule Train :  1.0  Prule test :  0.998663101604278
65 -701.6469521689895 1402.135869441266 1401.434222489097 Accuracy: 0.7837  test :  0.782  Prule Train :  0.9995272096726876  Prule test :  0.998663101604278
70 4793.432451966453 1379.5792366960818 1384.372669148048 Accuracy: 0.8654  test :  0.8407  Prule Train :  0.9591759969684385  Prule test :  0.9679496825062445
75 -1045.4283782210316 1358.1898019920864 1357.1443736138656 Accuracy: 0.8686  test :  0.8413  Prule Train :  0.9583084384528427  Prule test :  0.9693207160508709
80 5138.765306525325 1337.7525594608178 1342.8913247673433 Accuracy: 0.8726  test :  0.8427  Prule Train :  0.9579644927076952  Prule test :  0.9692847442281576
85 -1409.7945447869477 1318.2009103892042 1316.7911158444172 Accuracy: 0.8763  test :  0.842  Prule Train :  0.9558267994631631  Prule test :  0.9734269867248593
90 5500.260782636854 1299.97587725822 1305.4761380408568 Accuracy: 0.8794  test :  0.842  Prule Train :  0.9549400953656272  Prule test :  0.9705931381463295
95 -1789.4361321010874 1282.5053858151957 1280.7159496830945 Accuracy: 0.8829  test :  0.8427  Prule Train :  0.9509864881363054  Prule test :  0.9663019394785565
Resultado | acc=0.8413 | bal_acc=0.6537 | f1=0.9067 | EOdds=0.0437 | EOp=0.0061 | p-rule=96.35 | score=0.6513 | tempo=0.06 min

FAGTB caucasian_1:  42%|████▏     | 25/60 [02:12<02:56,  5.05s/modelo]

----------------------------------------------------------------------------------------------------
Treino 86/120 | config=caucasian_1 | lambda=0.001 | n_estimators=200 | learning_rate=0.03 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1830.0992975710415 1830.2543035312096 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2146.562821798611 1787.602168150932 1789.748730972731 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2381.69005988484 1747.37704191557 1749.758731975455 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1221.0590978217629 1708.2392179557387 1709.4602770535603 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3316.705557796087 1669.459362201812 1672.776067759608 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 341.7709727577888 1632.5826696450188 1632.9244406177766 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3707.899318011561 1597.7973044841006 1601.5052038021122 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 139.566689424231 1564.5360290319456 1564.6755957213702 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 3922.2160086662916 1533.4940295900878 1537.416245598754 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 -101.71955329970311 1504.1470000216618 1504.045280468362 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 4178.789779769477 1476.7049579494096 1480.8837477291788 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -384.55690879906865 1450.525941609393 1450.141384700594 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 4471.459135427103 1426.097644448938 1430.5691035843652 Accuracy: 0.7811  test :  0.782  Prule Train :  1.0  Prule test :  0.998663101604278
65 -701.6469521689895 1402.135869441266 1401.434222489097 Accuracy: 0.7837  test :  0.782  Prule Train :  0.9995272096726876  Prule test :  0.998663101604278
70 4793.432451966453 1379.5792366960818 1384.372669148048 Accuracy: 0.8654  test :  0.8407  Prule Train :  0.9591759969684385  Prule test :  0.9679496825062445
75 -1045.4283782210316 1358.1898019920864 1357.1443736138656 Accuracy: 0.8686  test :  0.8413  Prule Train :  0.9583084384528427  Prule test :  0.9693207160508709
80 5138.765306525325 1337.7525594608178 1342.8913247673433 Accuracy: 0.8726  test :  0.8427  Prule Train :  0.9579644927076952  Prule test :  0.9692847442281576
85 -1409.7945447869477 1318.2009103892042 1316.7911158444172 Accuracy: 0.8763  test :  0.842  Prule Train :  0.9558267994631631  Prule test :  0.9734269867248593
90 5500.260782636854 1299.97587725822 1305.4761380408568 Accuracy: 0.8794  test :  0.842  Prule Train :  0.9549400953656272  Prule test :  0.9705931381463295
95 -1789.4361321010874 1282.5053858151957 1280.7159496830945 Accuracy: 0.8829  test :  0.8427  Prule Train :  0.9509864881363054  Prule test :  0.9663019394785565
100 5881.705093909813 1266.123442561412 1272.005147655322 Accuracy: 0.8831  test :  0.8413  Prule Train :  0.9515660045824579  Prule test :  0.9634194528875379
105 -2181.1432219601047 1250.1059507720506 1247.9248075500902 Accuracy: 0.8843  test :  0.8413  Prule Train :  0.9490318740775778  Prule test :  0.9633747298572427
110 6271.276642948447 1234.4527609498946 1240.724037592843 Accuracy: 0.8851  test :  0.8413  Prule Train :  0.9495556304586202  Prule test :  0.9633747298572427
115 -2581.637635126617 1218.6667780315188 1216.085140396392 Accuracy: 0.8863  test :  0.8413  Prule Train :  0.9494455859758242  Prule test :  0.9633747298572427
120 6673.4793760052335 1203.5720405810068 1210.2455199570122 Accuracy: 0.8871  test :  0.8413  Prule Train :  0.9487549939872679  Prule test :  0.9633747298572427
125 -2989.011303217698 1190.1001321420813 1187.1111208388638 Accuracy: 0.888  test :  0.8407  Prule Train :  0.9504979609082487  Prule test :  0.964754922879961
130 7096.389407143524 1176.9828737611836 1184.079263168327 Accuracy: 0.8883  test :  0.8407  Prule Train :  0.9510803738744914  Prule test :  0.964754922879961
135 -3405.198805262917 1164.154218622622 1160.749019817359 Accuracy: 0.8891  test :  0.8407  Prule Train :  0.9503886671268645  Prule test :  0.964754922879961
140 7527.723124492717 1151.3384618549385 1158.8661849794312 Accuracy: 0.8903  test :  0.8413  Prule Train :  0.9490583036595305  Prule test :  0.9633298786807294
145 -3823.6584916145835 1138.1328392091295 1134.3091807175151 Accuracy: 0.8911  test :  0.8427  Prule Train :  0.948364506375556  Prule test :  0.963284898806435
150 7961.905754925545 1125.519399393775 1133.4813051487008 Accuracy: 0.8923  test :  0.8427  Prule Train :  0.9494748793641783  Prule test :  0.963284898806435
155 -4244.761315793147 1113.1812332025822 1108.9364718867891 Accuracy: 0.8929  test :  0.8433  Prule Train :  0.9481961253178965  Prule test :  0.9646689288334556
160 8402.012326980013 1101.410424474157 1109.8124368011368 Accuracy: 0.8943  test :  0.8427  Prule Train :  0.9474433612364648  Prule test :  0.9603815113719734
165 -4667.631134262288 1089.3999803125075 1084.7323491782454 Accuracy: 0.8963  test :  0.8427  Prule Train :  0.9441837685830291  Prule test :  0.9603815113719734
170 8832.560604469472 1078.1619938390031 1086.9945544434727 Accuracy: 0.8974  test :  0.842  Prule Train :  0.942843018058801  Prule test :  0.9617633552732281
175 -5076.203168357937 1067.179020916019 1062.102817747661 Accuracy: 0.8983  test :  0.8407  Prule Train :  0.94336527669861  Prule test :  0.9644954495142047
180 9168.176414600457 1056.9064720476117 1066.074648462212 Accuracy: 0.8997  test :  0.8407  Prule Train :  0.9426037497730947  Prule test :  0.9616683552853766
185 -5396.591192171927 1046.2081912545968 1040.8116000624248 Accuracy: 0.9009  test :  0.8413  Prule Train :  0.9437109845778576  Prule test :  0.9602330293819655
190 9121.149657988786 1036.4256372880855 1045.546786946074 Accuracy: 0.902  test :  0.8407  Prule Train :  0.9448223406039783  Prule test :  0.9616206493666215
195 -5436.800487795137 1026.7109393674732 1021.2741388796778 Accuracy: 0.9029  test :  0.84  Prule Train :  0.9428875508279974  Prule test :  0.9630122856175141
Resultado | acc=0.8407 | bal_acc=0.6642 | f1=0.9056 | EOdds=0.0466 | EOp=0.0052 | p-rule=96.16 | score=0.6617 | tempo=0.12 min

FAGTB caucasian_1:  43%|████▎     | 26/60 [02:19<03:12,  5.65s/modelo]

----------------------------------------------------------------------------------------------------
Treino 87/120 | config=caucasian_1 | lambda=0.001 | n_estimators=100 | learning_rate=0.03 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1830.0992975710415 1830.2543035312096 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2146.562821798611 1787.602168150932 1789.748730972731 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2381.69005988484 1747.37704191557 1749.758731975455 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1221.0590978217629 1708.2392179557387 1709.4602770535603 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3316.705557796087 1669.459362201812 1672.776067759608 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 341.7709727577888 1632.5826696450188 1632.9244406177766 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3707.899318011561 1597.7973044841006 1601.5052038021122 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 139.566689424231 1564.5360290319456 1564.6755957213702 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 3922.2160086662916 1533.4940295900878 1537.416245598754 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 -101.71955329970311 1504.1470000216618 1504.045280468362 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 4178.789779769477 1476.7049579494096 1480.8837477291788 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -384.55690879906865 1450.525941609393 1450.141384700594 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 4471.459135427103 1426.097644448938 1430.5691035843652 Accuracy: 0.7811  test :  0.782  Prule Train :  1.0  Prule test :  0.998663101604278
65 -701.6469521689895 1402.135869441266 1401.434222489097 Accuracy: 0.7837  test :  0.782  Prule Train :  0.9995272096726876  Prule test :  0.998663101604278
70 4793.432451966453 1379.5792366960818 1384.372669148048 Accuracy: 0.8654  test :  0.8407  Prule Train :  0.9591759969684385  Prule test :  0.9679496825062445
75 -1045.4283782210316 1358.1898019920864 1357.1443736138656 Accuracy: 0.8686  test :  0.8413  Prule Train :  0.9583084384528427  Prule test :  0.9693207160508709
80 5138.765306525325 1337.7525594608178 1342.8913247673433 Accuracy: 0.8726  test :  0.8427  Prule Train :  0.9579644927076952  Prule test :  0.9692847442281576
85 -1409.7945447869477 1318.2009103892042 1316.7911158444172 Accuracy: 0.8763  test :  0.842  Prule Train :  0.9558267994631631  Prule test :  0.9734269867248593
90 5500.260782636854 1299.97587725822 1305.4761380408568 Accuracy: 0.8794  test :  0.842  Prule Train :  0.9549400953656272  Prule test :  0.9705931381463295
95 -1789.4361321010874 1282.5053858151957 1280.7159496830945 Accuracy: 0.8829  test :  0.8427  Prule Train :  0.9509864881363054  Prule test :  0.9663019394785565
Resultado | acc=0.8413 | bal_acc=0.6537 | f1=0.9067 | EOdds=0.0437 | EOp=0.0061 | p-rule=96.35 | score=0.6513 | tempo=0.06 min

FAGTB caucasian_1:  45%|████▌     | 27/60 [02:23<02:46,  5.06s/modelo]

----------------------------------------------------------------------------------------------------
Treino 88/120 | config=caucasian_1 | lambda=0.001 | n_estimators=200 | learning_rate=0.03 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1830.0992975710415 1830.2543035312096 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2146.562821798611 1787.602168150932 1789.748730972731 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2381.69005988484 1747.37704191557 1749.758731975455 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1221.0590978217629 1708.2392179557387 1709.4602770535603 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3316.705557796087 1669.459362201812 1672.776067759608 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 341.7709727577888 1632.5826696450188 1632.9244406177766 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3707.899318011561 1597.7973044841006 1601.5052038021122 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 139.566689424231 1564.5360290319456 1564.6755957213702 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 3922.2160086662916 1533.4940295900878 1537.416245598754 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 -101.71955329970311 1504.1470000216618 1504.045280468362 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 4178.789779769477 1476.7049579494096 1480.8837477291788 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -384.55690879906865 1450.525941609393 1450.141384700594 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 4471.459135427103 1426.097644448938 1430.5691035843652 Accuracy: 0.7811  test :  0.782  Prule Train :  1.0  Prule test :  0.998663101604278
65 -701.6469521689895 1402.135869441266 1401.434222489097 Accuracy: 0.7837  test :  0.782  Prule Train :  0.9995272096726876  Prule test :  0.998663101604278
70 4793.432451966453 1379.5792366960818 1384.372669148048 Accuracy: 0.8654  test :  0.8407  Prule Train :  0.9591759969684385  Prule test :  0.9679496825062445
75 -1045.4283782210316 1358.1898019920864 1357.1443736138656 Accuracy: 0.8686  test :  0.8413  Prule Train :  0.9583084384528427  Prule test :  0.9693207160508709
80 5138.765306525325 1337.7525594608178 1342.8913247673433 Accuracy: 0.8726  test :  0.8427  Prule Train :  0.9579644927076952  Prule test :  0.9692847442281576
85 -1409.7945447869477 1318.2009103892042 1316.7911158444172 Accuracy: 0.8763  test :  0.842  Prule Train :  0.9558267994631631  Prule test :  0.9734269867248593
90 5500.260782636854 1299.97587725822 1305.4761380408568 Accuracy: 0.8794  test :  0.842  Prule Train :  0.9549400953656272  Prule test :  0.9705931381463295
95 -1789.4361321010874 1282.5053858151957 1280.7159496830945 Accuracy: 0.8829  test :  0.8427  Prule Train :  0.9509864881363054  Prule test :  0.9663019394785565
100 5881.705093909813 1266.123442561412 1272.005147655322 Accuracy: 0.8831  test :  0.8413  Prule Train :  0.9515660045824579  Prule test :  0.9634194528875379
105 -2181.1432219601047 1250.1059507720506 1247.9248075500902 Accuracy: 0.8843  test :  0.8413  Prule Train :  0.9490318740775778  Prule test :  0.9633747298572427
110 6271.276642948447 1234.4527609498946 1240.724037592843 Accuracy: 0.8851  test :  0.8413  Prule Train :  0.9495556304586202  Prule test :  0.9633747298572427
115 -2581.637635126617 1218.6667780315188 1216.085140396392 Accuracy: 0.8863  test :  0.8413  Prule Train :  0.9494455859758242  Prule test :  0.9633747298572427
120 6673.4793760052335 1203.5720405810068 1210.2455199570122 Accuracy: 0.8871  test :  0.8413  Prule Train :  0.9487549939872679  Prule test :  0.9633747298572427
125 -2989.011303217698 1190.1001321420813 1187.1111208388638 Accuracy: 0.888  test :  0.8407  Prule Train :  0.9504979609082487  Prule test :  0.964754922879961
130 7096.389407143524 1176.9828737611836 1184.079263168327 Accuracy: 0.8883  test :  0.8407  Prule Train :  0.9510803738744914  Prule test :  0.964754922879961
135 -3405.198805262917 1164.154218622622 1160.749019817359 Accuracy: 0.8891  test :  0.8407  Prule Train :  0.9503886671268645  Prule test :  0.964754922879961
140 7527.723124492717 1151.3384618549385 1158.8661849794312 Accuracy: 0.8903  test :  0.8413  Prule Train :  0.9490583036595305  Prule test :  0.9633298786807294
145 -3823.6584916145835 1138.1328392091295 1134.3091807175151 Accuracy: 0.8911  test :  0.8427  Prule Train :  0.948364506375556  Prule test :  0.963284898806435
150 7961.905754925545 1125.519399393775 1133.4813051487008 Accuracy: 0.8923  test :  0.8427  Prule Train :  0.9494748793641783  Prule test :  0.963284898806435
155 -4244.761315793147 1113.1812332025822 1108.9364718867891 Accuracy: 0.8929  test :  0.8433  Prule Train :  0.9481961253178965  Prule test :  0.9646689288334556
160 8402.012326980013 1101.410424474157 1109.8124368011368 Accuracy: 0.8943  test :  0.8427  Prule Train :  0.9474433612364648  Prule test :  0.9603815113719734
165 -4667.631134262288 1089.3999803125075 1084.7323491782454 Accuracy: 0.8963  test :  0.8427  Prule Train :  0.9441837685830291  Prule test :  0.9603815113719734
170 8832.560604469472 1078.1619938390031 1086.9945544434727 Accuracy: 0.8974  test :  0.842  Prule Train :  0.942843018058801  Prule test :  0.9617633552732281
175 -5076.203168357937 1067.179020916019 1062.102817747661 Accuracy: 0.8983  test :  0.8407  Prule Train :  0.94336527669861  Prule test :  0.9644954495142047
180 9168.176414600457 1056.9064720476117 1066.074648462212 Accuracy: 0.8997  test :  0.8407  Prule Train :  0.9426037497730947  Prule test :  0.9616683552853766
185 -5396.591192171927 1046.2081912545968 1040.8116000624248 Accuracy: 0.9009  test :  0.8413  Prule Train :  0.9437109845778576  Prule test :  0.9602330293819655
190 9121.149657988786 1036.4256372880855 1045.546786946074 Accuracy: 0.902  test :  0.8407  Prule Train :  0.9448223406039783  Prule test :  0.9616206493666215
195 -5436.800487795137 1026.7109393674732 1021.2741388796778 Accuracy: 0.9029  test :  0.84  Prule Train :  0.9428875508279974  Prule test :  0.9630122856175141
Resultado | acc=0.8407 | bal_acc=0.6642 | f1=0.9056 | EOdds=0.0466 | EOp=0.0052 | p-rule=96.16 | score=0.6617 | tempo=0.12 min

FAGTB caucasian_1:  47%|████▋     | 28/60 [02:30<03:00,  5.65s/modelo]

----------------------------------------------------------------------------------------------------
Treino 89/120 | config=caucasian_1 | lambda=0.001 | n_estimators=100 | learning_rate=0.05 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1824.1235342867683 1824.2785402469367 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2130.3375447311437 1754.8411185570649 1756.9714561017959 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2426.458102770973 1690.4042801191747 1692.8307382219457 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1125.768069435397 1627.6554910379468 1628.7812591073825 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3456.3521833663935 1571.2432327530573 1574.6995849364237 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 182.373097109453 1519.7833451871202 1519.9657182842295 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3878.394968189609 1472.7867722960323 1476.665167264222 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -111.71083532886732 1429.9937660101923 1429.8820551748631 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 4175.348264330405 1390.9784030122028 1395.153751276533 Accuracy: 0.8649  test :  0.84  Prule Train :  0.9592242290084017  Prule test :  0.966582521937733
45 -466.7209018318169 1354.331725446309 1353.8650045444772 Accuracy: 0.8689  test :  0.842  Prule Train :  0.9576829107515027  Prule test :  0.9679118196612622
50 4514.607843024865 1321.0631744764264 1325.5777823194512 Accuracy: 0.8763  test :  0.8427  Prule Train :  0.9570368988197974  Prule test :  0.9720423110680669
55 -858.3549853268792 1290.2475482703767 1289.38919328505 Accuracy: 0.882  test :  0.8427  Prule Train :  0.9516731999994326  Prule test :  0.969176213857065
60 4878.731933649389 1262.7690971881184 1267.6478291217677 Accuracy: 0.8837  test :  0.8413  Prule Train :  0.9515123088293821  Prule test :  0.9691033434650457
65 -1269.6938452110867 1236.4209634628542 1235.1512696176433 Accuracy: 0.8849  test :  0.8413  Prule Train :  0.9501899361569893  Prule test :  0.9634194528875379
70 5263.417856229702 1209.47575976284 1214.7391776190696 Accuracy: 0.8866  test :  0.842  Prule Train :  0.9500259316885235  Prule test :  0.9619517243478526
75 -1692.002130541963 1186.1780602371653 1184.4860581066232 Accuracy: 0.8883  test :  0.842  Prule Train :  0.9486437674932165  Prule test :  0.9619517243478526
80 5672.972955065737 1165.075583283835 1170.7485562389006 Accuracy: 0.8903  test :  0.842  Prule Train :  0.9478389993411453  Prule test :  0.9619517243478526
85 -2124.0824247748906 1142.4116622529514 1140.2875798281766 Accuracy: 0.892  test :  0.8433  Prule Train :  0.9476698567607659  Prule test :  0.9591057133290719
90 6097.115983771023 1122.0498763421826 1128.1469923259538 Accuracy: 0.8931  test :  0.8427  Prule Train :  0.9475567482947557  Prule test :  0.96043072132849
95 -2560.3305141070805 1101.769514925326 1099.209184411219 Accuracy: 0.8946  test :  0.8427  Prule Train :  0.9480271217794322  Prule test :  0.9603321598040716
Resultado | acc=0.8427 | bal_acc=0.6633 | f1=0.9070 | EOdds=0.0485 | EOp=0.0065 | p-rule=96.03 | score=0.6607 | tempo=0.06 min

FAGTB caucasian_1:  48%|████▊     | 29/60 [02:34<02:36,  5.06s/modelo]

----------------------------------------------------------------------------------------------------
Treino 90/120 | config=caucasian_1 | lambda=0.001 | n_estimators=200 | learning_rate=0.05 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1824.1235342867683 1824.2785402469367 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2130.3375447311437 1754.8411185570649 1756.9714561017959 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2426.458102770973 1690.4042801191747 1692.8307382219457 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1125.768069435397 1627.6554910379468 1628.7812591073825 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3456.3521833663935 1571.2432327530573 1574.6995849364237 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 182.373097109453 1519.7833451871202 1519.9657182842295 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3878.394968189609 1472.7867722960323 1476.665167264222 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -111.71083532886732 1429.9937660101923 1429.8820551748631 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 4175.348264330405 1390.9784030122028 1395.153751276533 Accuracy: 0.8649  test :  0.84  Prule Train :  0.9592242290084017  Prule test :  0.966582521937733
45 -466.7209018318169 1354.331725446309 1353.8650045444772 Accuracy: 0.8689  test :  0.842  Prule Train :  0.9576829107515027  Prule test :  0.9679118196612622
50 4514.607843024865 1321.0631744764264 1325.5777823194512 Accuracy: 0.8763  test :  0.8427  Prule Train :  0.9570368988197974  Prule test :  0.9720423110680669
55 -858.3549853268792 1290.2475482703767 1289.38919328505 Accuracy: 0.882  test :  0.8427  Prule Train :  0.9516731999994326  Prule test :  0.969176213857065
60 4878.731933649389 1262.7690971881184 1267.6478291217677 Accuracy: 0.8837  test :  0.8413  Prule Train :  0.9515123088293821  Prule test :  0.9691033434650457
65 -1269.6938452110867 1236.4209634628542 1235.1512696176433 Accuracy: 0.8849  test :  0.8413  Prule Train :  0.9501899361569893  Prule test :  0.9634194528875379
70 5263.417856229702 1209.47575976284 1214.7391776190696 Accuracy: 0.8866  test :  0.842  Prule Train :  0.9500259316885235  Prule test :  0.9619517243478526
75 -1692.002130541963 1186.1780602371653 1184.4860581066232 Accuracy: 0.8883  test :  0.842  Prule Train :  0.9486437674932165  Prule test :  0.9619517243478526
80 5672.972955065737 1165.075583283835 1170.7485562389006 Accuracy: 0.8903  test :  0.842  Prule Train :  0.9478389993411453  Prule test :  0.9619517243478526
85 -2124.0824247748906 1142.4116622529514 1140.2875798281766 Accuracy: 0.892  test :  0.8433  Prule Train :  0.9476698567607659  Prule test :  0.9591057133290719
90 6097.115983771023 1122.0498763421826 1128.1469923259538 Accuracy: 0.8931  test :  0.8427  Prule Train :  0.9475567482947557  Prule test :  0.96043072132849
95 -2560.3305141070805 1101.769514925326 1099.209184411219 Accuracy: 0.8946  test :  0.8427  Prule Train :  0.9480271217794322  Prule test :  0.9603321598040716
100 6534.2939029785 1082.3861316012596 1088.9204255042382 Accuracy: 0.8966  test :  0.8427  Prule Train :  0.9447658794144612  Prule test :  0.9603321598040716
105 -2999.9304127712026 1063.3096066721328 1060.3096762593618 Accuracy: 0.8983  test :  0.844  Prule Train :  0.94336527669861  Prule test :  0.9631036811887874
110 6979.724508045112 1045.3607961045986 1052.3405206126438 Accuracy: 0.9009  test :  0.8433  Prule Train :  0.9437109845778576  Prule test :  0.9644954495142047
115 -3435.7547315363117 1027.9206480784553 1024.484893346919 Accuracy: 0.9029  test :  0.8427  Prule Train :  0.9428875508279974  Prule test :  0.9658912461126334
120 7428.5148338348245 1010.6519688068836 1018.0804836407185 Accuracy: 0.9051  test :  0.8413  Prule Train :  0.9401844532279314  Prule test :  0.9658495220474869
125 -3862.216410239269 994.9002562557582 991.038039845519 Accuracy: 0.9063  test :  0.842  Prule Train :  0.9400607684189773  Prule test :  0.9644079555966697
130 7856.240896739913 978.6793495471431 986.535590443883 Accuracy: 0.9089  test :  0.842  Prule Train :  0.9403987569926435  Prule test :  0.961572805369954
135 -4253.416247390554 964.6699184660972 960.4165022187067 Accuracy: 0.9109  test :  0.8413  Prule Train :  0.9408007044029558  Prule test :  0.9629663891458526
140 8108.734842333966 950.9380587040009 959.0467935463348 Accuracy: 0.9117  test :  0.8407  Prule Train :  0.9400882805138124  Prule test :  0.9615248226950357
145 -4470.3235043813675 936.8046829257642 932.3343594213827 Accuracy: 0.9131  test :  0.8413  Prule Train :  0.9368353798891973  Prule test :  0.9600330420282246
150 7850.097370779717 923.9907264133658 931.8408237841455 Accuracy: 0.914  test :  0.8413  Prule Train :  0.9373579636737531  Prule test :  0.9600330420282246
155 -4369.443602037176 910.3831317484535 906.0136881464163 Accuracy: 0.9149  test :  0.842  Prule Train :  0.937881858835435  Prule test :  0.9614284388916378
160 7537.840774628715 897.3663945739336 904.9042353485623 Accuracy: 0.9171  test :  0.8427  Prule Train :  0.9388702340244189  Prule test :  0.962827898045774
165 -4190.462212845223 883.7660004390355 879.5755382261902 Accuracy: 0.9191  test :  0.8433  Prule Train :  0.9405211791575429  Prule test :  0.9642314372557533
170 7358.931262481023 871.8854710069238 879.2444022694049 Accuracy: 0.92  test :  0.8427  Prule Train :  0.9385521885521885  Prule test :  0.9656390743904333
175 -4013.274747938757 859.4832367327508 855.469961984812 Accuracy: 0.9229  test :  0.842  Prule Train :  0.938232128859108  Prule test :  0.9641869855567634
180 7170.010318873828 848.2772227984216 855.4472331172954 Accuracy: 0.924  test :  0.8413  Prule Train :  0.9381035367084827  Prule test :  0.9655966156526066
185 -3866.1252337357955 837.6662591853274 833.8001339515915 Accuracy: 0.9243  test :  0.842  Prule Train :  0.9374442931830377  Prule test :  0.9612828078894238
190 7061.655905477325 827.1506926995114 834.2123486049888 Accuracy: 0.9254  test :  0.842  Prule Train :  0.9373145373145373  Prule test :  0.9612828078894238
195 -3700.2718484722473 816.4051391922019 812.7048673437295 Accuracy: 0.926  test :  0.8427  Prule Train :  0.9359943759943761  Prule test :  0.959830719055754
Resultado | acc=0.8427 | bal_acc=0.6743 | f1=0.9063 | EOdds=0.0265 | EOp=0.0106 | p-rule=95.98 | score=0.6726 | tempo=0.12 min

FAGTB caucasian_1:  50%|█████     | 30/60 [02:41<02:49,  5.65s/modelo]

----------------------------------------------------------------------------------------------------
Treino 91/120 | config=caucasian_1 | lambda=0.001 | n_estimators=100 | learning_rate=0.05 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1824.1235342867683 1824.2785402469367 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2130.3375447311437 1754.8411185570649 1756.9714561017959 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2426.458102770973 1690.4042801191747 1692.8307382219457 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1125.768069435397 1627.6554910379468 1628.7812591073825 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3456.3521833663935 1571.2432327530573 1574.6995849364237 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 182.373097109453 1519.7833451871202 1519.9657182842295 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3878.394968189609 1472.7867722960323 1476.665167264222 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -111.71083532886732 1429.9937660101923 1429.8820551748631 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 4175.348264330405 1390.9784030122028 1395.153751276533 Accuracy: 0.8649  test :  0.84  Prule Train :  0.9592242290084017  Prule test :  0.966582521937733
45 -466.7209018318169 1354.331725446309 1353.8650045444772 Accuracy: 0.8689  test :  0.842  Prule Train :  0.9576829107515027  Prule test :  0.9679118196612622
50 4514.607843024865 1321.0631744764264 1325.5777823194512 Accuracy: 0.8763  test :  0.8427  Prule Train :  0.9570368988197974  Prule test :  0.9720423110680669
55 -858.3549853268792 1290.2475482703767 1289.38919328505 Accuracy: 0.882  test :  0.8427  Prule Train :  0.9516731999994326  Prule test :  0.969176213857065
60 4878.731933649389 1262.7690971881184 1267.6478291217677 Accuracy: 0.8837  test :  0.8413  Prule Train :  0.9515123088293821  Prule test :  0.9691033434650457
65 -1269.6938452110867 1236.4209634628542 1235.1512696176433 Accuracy: 0.8849  test :  0.8413  Prule Train :  0.9501899361569893  Prule test :  0.9634194528875379
70 5263.417856229702 1209.47575976284 1214.7391776190696 Accuracy: 0.8866  test :  0.842  Prule Train :  0.9500259316885235  Prule test :  0.9619517243478526
75 -1692.002130541963 1186.1780602371653 1184.4860581066232 Accuracy: 0.8883  test :  0.842  Prule Train :  0.9486437674932165  Prule test :  0.9619517243478526
80 5672.972955065737 1165.075583283835 1170.7485562389006 Accuracy: 0.8903  test :  0.842  Prule Train :  0.9478389993411453  Prule test :  0.9619517243478526
85 -2124.0824247748906 1142.4116622529514 1140.2875798281766 Accuracy: 0.892  test :  0.8433  Prule Train :  0.9476698567607659  Prule test :  0.9591057133290719
90 6097.115983771023 1122.0498763421826 1128.1469923259538 Accuracy: 0.8931  test :  0.8427  Prule Train :  0.9475567482947557  Prule test :  0.96043072132849
95 -2560.3305141070805 1101.769514925326 1099.209184411219 Accuracy: 0.8946  test :  0.8427  Prule Train :  0.9480271217794322  Prule test :  0.9603321598040716
Resultado | acc=0.8427 | bal_acc=0.6633 | f1=0.9070 | EOdds=0.0485 | EOp=0.0065 | p-rule=96.03 | score=0.6607 | tempo=0.06 min

FAGTB caucasian_1:  52%|█████▏    | 31/60 [02:44<02:26,  5.06s/modelo]

----------------------------------------------------------------------------------------------------
Treino 92/120 | config=caucasian_1 | lambda=0.001 | n_estimators=200 | learning_rate=0.05 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1824.1235342867683 1824.2785402469367 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2130.3375447311437 1754.8411185570649 1756.9714561017959 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2426.458102770973 1690.4042801191747 1692.8307382219457 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1125.768069435397 1627.6554910379468 1628.7812591073825 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3456.3521833663935 1571.2432327530573 1574.6995849364237 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 182.373097109453 1519.7833451871202 1519.9657182842295 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3878.394968189609 1472.7867722960323 1476.665167264222 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -111.71083532886732 1429.9937660101923 1429.8820551748631 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 4175.348264330405 1390.9784030122028 1395.153751276533 Accuracy: 0.8649  test :  0.84  Prule Train :  0.9592242290084017  Prule test :  0.966582521937733
45 -466.7209018318169 1354.331725446309 1353.8650045444772 Accuracy: 0.8689  test :  0.842  Prule Train :  0.9576829107515027  Prule test :  0.9679118196612622
50 4514.607843024865 1321.0631744764264 1325.5777823194512 Accuracy: 0.8763  test :  0.8427  Prule Train :  0.9570368988197974  Prule test :  0.9720423110680669
55 -858.3549853268792 1290.2475482703767 1289.38919328505 Accuracy: 0.882  test :  0.8427  Prule Train :  0.9516731999994326  Prule test :  0.969176213857065
60 4878.731933649389 1262.7690971881184 1267.6478291217677 Accuracy: 0.8837  test :  0.8413  Prule Train :  0.9515123088293821  Prule test :  0.9691033434650457
65 -1269.6938452110867 1236.4209634628542 1235.1512696176433 Accuracy: 0.8849  test :  0.8413  Prule Train :  0.9501899361569893  Prule test :  0.9634194528875379
70 5263.417856229702 1209.47575976284 1214.7391776190696 Accuracy: 0.8866  test :  0.842  Prule Train :  0.9500259316885235  Prule test :  0.9619517243478526
75 -1692.002130541963 1186.1780602371653 1184.4860581066232 Accuracy: 0.8883  test :  0.842  Prule Train :  0.9486437674932165  Prule test :  0.9619517243478526
80 5672.972955065737 1165.075583283835 1170.7485562389006 Accuracy: 0.8903  test :  0.842  Prule Train :  0.9478389993411453  Prule test :  0.9619517243478526
85 -2124.0824247748906 1142.4116622529514 1140.2875798281766 Accuracy: 0.892  test :  0.8433  Prule Train :  0.9476698567607659  Prule test :  0.9591057133290719
90 6097.115983771023 1122.0498763421826 1128.1469923259538 Accuracy: 0.8931  test :  0.8427  Prule Train :  0.9475567482947557  Prule test :  0.96043072132849
95 -2560.3305141070805 1101.769514925326 1099.209184411219 Accuracy: 0.8946  test :  0.8427  Prule Train :  0.9480271217794322  Prule test :  0.9603321598040716
100 6534.2939029785 1082.3861316012596 1088.9204255042382 Accuracy: 0.8966  test :  0.8427  Prule Train :  0.9447658794144612  Prule test :  0.9603321598040716
105 -2999.9304127712026 1063.3096066721328 1060.3096762593618 Accuracy: 0.8983  test :  0.844  Prule Train :  0.94336527669861  Prule test :  0.9631036811887874
110 6979.724508045112 1045.3607961045986 1052.3405206126438 Accuracy: 0.9009  test :  0.8433  Prule Train :  0.9437109845778576  Prule test :  0.9644954495142047
115 -3435.7547315363117 1027.9206480784553 1024.484893346919 Accuracy: 0.9029  test :  0.8427  Prule Train :  0.9428875508279974  Prule test :  0.9658912461126334
120 7428.5148338348245 1010.6519688068836 1018.0804836407185 Accuracy: 0.9051  test :  0.8413  Prule Train :  0.9401844532279314  Prule test :  0.9658495220474869
125 -3862.216410239269 994.9002562557582 991.038039845519 Accuracy: 0.9063  test :  0.842  Prule Train :  0.9400607684189773  Prule test :  0.9644079555966697
130 7856.240896739913 978.6793495471431 986.535590443883 Accuracy: 0.9089  test :  0.842  Prule Train :  0.9403987569926435  Prule test :  0.961572805369954
135 -4253.416247390554 964.6699184660972 960.4165022187067 Accuracy: 0.9109  test :  0.8413  Prule Train :  0.9408007044029558  Prule test :  0.9629663891458526
140 8108.734842333966 950.9380587040009 959.0467935463348 Accuracy: 0.9117  test :  0.8407  Prule Train :  0.9400882805138124  Prule test :  0.9615248226950357
145 -4470.3235043813675 936.8046829257642 932.3343594213827 Accuracy: 0.9131  test :  0.8413  Prule Train :  0.9368353798891973  Prule test :  0.9600330420282246
150 7850.097370779717 923.9907264133658 931.8408237841455 Accuracy: 0.914  test :  0.8413  Prule Train :  0.9373579636737531  Prule test :  0.9600330420282246
155 -4369.443602037176 910.3831317484535 906.0136881464163 Accuracy: 0.9149  test :  0.842  Prule Train :  0.937881858835435  Prule test :  0.9614284388916378
160 7537.840774628715 897.3663945739336 904.9042353485623 Accuracy: 0.9171  test :  0.8427  Prule Train :  0.9388702340244189  Prule test :  0.962827898045774
165 -4190.462212845223 883.7660004390355 879.5755382261902 Accuracy: 0.9191  test :  0.8433  Prule Train :  0.9405211791575429  Prule test :  0.9642314372557533
170 7358.931262481023 871.8854710069238 879.2444022694049 Accuracy: 0.92  test :  0.8427  Prule Train :  0.9385521885521885  Prule test :  0.9656390743904333
175 -4013.274747938757 859.4832367327508 855.469961984812 Accuracy: 0.9229  test :  0.842  Prule Train :  0.938232128859108  Prule test :  0.9641869855567634
180 7170.010318873828 848.2772227984216 855.4472331172954 Accuracy: 0.924  test :  0.8413  Prule Train :  0.9381035367084827  Prule test :  0.9655966156526066
185 -3866.1252337357955 837.6662591853274 833.8001339515915 Accuracy: 0.9243  test :  0.842  Prule Train :  0.9374442931830377  Prule test :  0.9612828078894238
190 7061.655905477325 827.1506926995114 834.2123486049888 Accuracy: 0.9254  test :  0.842  Prule Train :  0.9373145373145373  Prule test :  0.9612828078894238
195 -3700.2718484722473 816.4051391922019 812.7048673437295 Accuracy: 0.926  test :  0.8427  Prule Train :  0.9359943759943761  Prule test :  0.959830719055754
Resultado | acc=0.8427 | bal_acc=0.6743 | f1=0.9063 | EOdds=0.0265 | EOp=0.0106 | p-rule=95.98 | score=0.6726 | tempo=0.12 min

FAGTB caucasian_1:  53%|█████▎    | 32/60 [02:51<02:38,  5.65s/modelo]

----------------------------------------------------------------------------------------------------
Treino 93/120 | config=caucasian_1 | lambda=0.001 | n_estimators=100 | learning_rate=0.1 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1809.2759468661936 1809.4309528263618 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2091.995283595845 1675.1617726853253 1677.253767968921 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2522.1064828620993 1557.372633948323 1559.8947404311853 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 900.8552467845175 1461.607989416617 1462.5088446634018 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3693.3429670631485 1381.5749784786706 1385.2683214457338 Accuracy: 0.8657  test :  0.8407  Prule Train :  0.9597517328609765  Prule test :  0.9679496825062445
25 -119.25952396196652 1313.1239689922118 1313.0047094682495 Accuracy: 0.8771  test :  0.842  Prule Train :  0.9551455215494026  Prule test :  0.9734269867248593
30 4099.360611178644 1255.1558653499926 1259.2552259611712 Accuracy: 0.8846  test :  0.8427  Prule Train :  0.9483983414513579  Prule test :  0.9633747298572427
35 -576.8354696694894 1204.1235147306675 1203.5466792609977 Accuracy: 0.8877  test :  0.8427  Prule Train :  0.9486994147544607  Prule test :  0.9604797902822655
40 4461.5615325839135 1159.2566263017377 1163.7181878343217 Accuracy: 0.8906  test :  0.8427  Prule Train :  0.9484204956597595  Prule test :  0.96043072132849
45 -1041.002132735499 1115.3840756421312 1114.3430735093957 Accuracy: 0.8931  test :  0.842  Prule Train :  0.9475567482947557  Prule test :  0.9617633552732281
50 4852.624358541274 1076.3678077281688 1081.22043208671 Accuracy: 0.8974  test :  0.8427  Prule Train :  0.9465165265041731  Prule test :  0.9631036811887874
55 -1501.0508143875186 1039.6431277248307 1038.1420769104432 Accuracy: 0.9017  test :  0.8427  Prule Train :  0.9454672705293052  Prule test :  0.9630580494404133
60 5274.408886498559 1005.2262943484453 1010.5007032349438 Accuracy: 0.9057  test :  0.8407  Prule Train :  0.9438208118158307  Prule test :  0.9643640181576756
65 -1945.117867546759 974.2213123224728 972.2761944549261 Accuracy: 0.9097  test :  0.8407  Prule Train :  0.9421620046620045  Prule test :  0.9671313814279512
70 5703.557383149922 946.1004363159841 951.803993699134 Accuracy: 0.9129  test :  0.84  Prule Train :  0.9412046678504359  Prule test :  0.9656390743904333
75 -2374.7379748062067 919.3033941441693 916.928656169363 Accuracy: 0.9169  test :  0.84  Prule Train :  0.9395244989958645  Prule test :  0.9655966156526066
80 6165.568775164464 894.7278302377447 900.8933990129092 Accuracy: 0.9194  test :  0.8393  Prule Train :  0.9411153176156336  Prule test :  0.9670103735086134
85 -2794.8421304026087 872.1967098713033 869.4018677409007 Accuracy: 0.92  test :  0.84  Prule Train :  0.9398018279888147  Prule test :  0.9655113246396706
90 6612.479391249075 849.8993670499534 856.5118464412025 Accuracy: 0.9209  test :  0.8393  Prule Train :  0.9403331224963103  Prule test :  0.9640528483184626
95 -3185.812656934917 830.0674499535944 826.8816372966595 Accuracy: 0.9234  test :  0.84  Prule Train :  0.940677765550862  Prule test :  0.9625943719972547
Resultado | acc=0.8400 | bal_acc=0.6726 | f1=0.9045 | EOdds=0.0265 | EOp=0.0075 | p-rule=96.26 | score=0.6710 | tempo=0.06 min

FAGTB caucasian_1:  55%|█████▌    | 33/60 [02:55<02:16,  5.06s/modelo]

----------------------------------------------------------------------------------------------------
Treino 94/120 | config=caucasian_1 | lambda=0.001 | n_estimators=200 | learning_rate=0.1 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1809.2759468661936 1809.4309528263618 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2091.995283595845 1675.1617726853253 1677.253767968921 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2522.1064828620993 1557.372633948323 1559.8947404311853 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 900.8552467845175 1461.607989416617 1462.5088446634018 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3693.3429670631485 1381.5749784786706 1385.2683214457338 Accuracy: 0.8657  test :  0.8407  Prule Train :  0.9597517328609765  Prule test :  0.9679496825062445
25 -119.25952396196652 1313.1239689922118 1313.0047094682495 Accuracy: 0.8771  test :  0.842  Prule Train :  0.9551455215494026  Prule test :  0.9734269867248593
30 4099.360611178644 1255.1558653499926 1259.2552259611712 Accuracy: 0.8846  test :  0.8427  Prule Train :  0.9483983414513579  Prule test :  0.9633747298572427
35 -576.8354696694894 1204.1235147306675 1203.5466792609977 Accuracy: 0.8877  test :  0.8427  Prule Train :  0.9486994147544607  Prule test :  0.9604797902822655
40 4461.5615325839135 1159.2566263017377 1163.7181878343217 Accuracy: 0.8906  test :  0.8427  Prule Train :  0.9484204956597595  Prule test :  0.96043072132849
45 -1041.002132735499 1115.3840756421312 1114.3430735093957 Accuracy: 0.8931  test :  0.842  Prule Train :  0.9475567482947557  Prule test :  0.9617633552732281
50 4852.624358541274 1076.3678077281688 1081.22043208671 Accuracy: 0.8974  test :  0.8427  Prule Train :  0.9465165265041731  Prule test :  0.9631036811887874
55 -1501.0508143875186 1039.6431277248307 1038.1420769104432 Accuracy: 0.9017  test :  0.8427  Prule Train :  0.9454672705293052  Prule test :  0.9630580494404133
60 5274.408886498559 1005.2262943484453 1010.5007032349438 Accuracy: 0.9057  test :  0.8407  Prule Train :  0.9438208118158307  Prule test :  0.9643640181576756
65 -1945.117867546759 974.2213123224728 972.2761944549261 Accuracy: 0.9097  test :  0.8407  Prule Train :  0.9421620046620045  Prule test :  0.9671313814279512
70 5703.557383149922 946.1004363159841 951.803993699134 Accuracy: 0.9129  test :  0.84  Prule Train :  0.9412046678504359  Prule test :  0.9656390743904333
75 -2374.7379748062067 919.3033941441693 916.928656169363 Accuracy: 0.9169  test :  0.84  Prule Train :  0.9395244989958645  Prule test :  0.9655966156526066
80 6165.568775164464 894.7278302377447 900.8933990129092 Accuracy: 0.9194  test :  0.8393  Prule Train :  0.9411153176156336  Prule test :  0.9670103735086134
85 -2794.8421304026087 872.1967098713033 869.4018677409007 Accuracy: 0.92  test :  0.84  Prule Train :  0.9398018279888147  Prule test :  0.9655113246396706
90 6612.479391249075 849.8993670499534 856.5118464412025 Accuracy: 0.9209  test :  0.8393  Prule Train :  0.9403331224963103  Prule test :  0.9640528483184626
95 -3185.812656934917 830.0674499535944 826.8816372966595 Accuracy: 0.9234  test :  0.84  Prule Train :  0.940677765550862  Prule test :  0.9625943719972547
100 6918.443557788727 810.3659456307088 817.2843891884975 Accuracy: 0.9263  test :  0.8407  Prule Train :  0.9378453714118048  Prule test :  0.9611358956760466
105 -3405.4554609152124 791.4649515570172 788.059496096102 Accuracy: 0.9291  test :  0.8413  Prule Train :  0.9375208125208125  Prule test :  0.9596260193082764
110 6699.3385139339225 773.8685479365054 780.5678864504393 Accuracy: 0.9326  test :  0.8413  Prule Train :  0.9371285991004299  Prule test :  0.9625472552879059
115 -3301.9080709713016 756.4728455488473 753.1709374778759 Accuracy: 0.9346  test :  0.8427  Prule Train :  0.933732933732934  Prule test :  0.9625472552879059
120 6428.567788264863 740.2267805353463 746.6553483236111 Accuracy: 0.9363  test :  0.846  Prule Train :  0.9322633748547795  Prule test :  0.9610372340425534
125 -3124.94794966618 724.0705503698184 720.9456024201523 Accuracy: 0.9391  test :  0.8467  Prule Train :  0.934458582654459  Prule test :  0.9595744680851065
130 6167.063866303035 709.7582369721956 715.9253008384985 Accuracy: 0.9406  test :  0.8447  Prule Train :  0.9336521542973155  Prule test :  0.9610372340425534
135 -2981.9662699191704 693.5065671287776 690.5246008588585 Accuracy: 0.9411  test :  0.844  Prule Train :  0.9323107000526355  Prule test :  0.9625000000000001
140 6051.94593560489 681.1896214037238 687.2415673393285 Accuracy: 0.9423  test :  0.8447  Prule Train :  0.9296277915632755  Prule test :  0.960987685269326
145 -2787.0629507637877 664.9454745210603 662.1584115702965 Accuracy: 0.9454  test :  0.844  Prule Train :  0.9298736669202989  Prule test :  0.9595227650173911
150 5593.909326139243 651.6540957957359 657.2480051218752 Accuracy: 0.9477  test :  0.844  Prule Train :  0.9257599173347715  Prule test :  0.9623573965240894
155 -2745.446970870359 639.172738426478 636.4272914556077 Accuracy: 0.95  test :  0.8447  Prule Train :  0.9229135562685207  Prule test :  0.9608881485904648
160 5860.681793782364 627.1635234722975 633.0242052660799 Accuracy: 0.9509  test :  0.8433  Prule Train :  0.9234374029695667  Prule test :  0.9580038285319776
165 -2422.8444665699326 613.7821623721834 611.3593179056135 Accuracy: 0.9534  test :  0.8433  Prule Train :  0.9224573472130476  Prule test :  0.9580038285319776
170 5043.050881140787 601.4160360731157 606.4590869542567 Accuracy: 0.956  test :  0.842  Prule Train :  0.9227539345186403  Prule test :  0.9580038285319776
175 -2481.9208721451478 591.2544936754899 588.7725728033447 Accuracy: 0.9577  test :  0.8427  Prule Train :  0.9225243213455394  Prule test :  0.9536025858281556
180 5532.886261461777 579.7046279611316 585.2375142225934 Accuracy: 0.9597  test :  0.8413  Prule Train :  0.9190412034448733  Prule test :  0.953541908922342
185 -2242.4518683682545 568.3999587860537 566.1575069176855 Accuracy: 0.9609  test :  0.8407  Prule Train :  0.917598685467538  Prule test :  0.9520726609887175
190 4799.905519827602 560.0113515673858 564.8112570872133 Accuracy: 0.9617  test :  0.84  Prule Train :  0.9168364443954995  Prule test :  0.953541908922342
195 -2300.5207131153475 551.6980435417784 549.3975228286631 Accuracy: 0.9626  test :  0.8407  Prule Train :  0.917358156517158  Prule test :  0.9550111568559666
Resultado | acc=0.8400 | bal_acc=0.6814 | f1=0.9039 | EOdds=0.0314 | EOp=0.0148 | p-rule=95.35 | score=0.6793 | tempo=0.12 min

FAGTB caucasian_1:  57%|█████▋    | 34/60 [03:02<02:27,  5.66s/modelo]

----------------------------------------------------------------------------------------------------
Treino 95/120 | config=caucasian_1 | lambda=0.001 | n_estimators=100 | learning_rate=0.1 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1809.2759468661936 1809.4309528263618 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2091.995283595845 1675.1617726853253 1677.253767968921 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2522.1064828620993 1557.372633948323 1559.8947404311853 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 900.8552467845175 1461.607989416617 1462.5088446634018 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3693.3429670631485 1381.5749784786706 1385.2683214457338 Accuracy: 0.8657  test :  0.8407  Prule Train :  0.9597517328609765  Prule test :  0.9679496825062445
25 -119.25952396196652 1313.1239689922118 1313.0047094682495 Accuracy: 0.8771  test :  0.842  Prule Train :  0.9551455215494026  Prule test :  0.9734269867248593
30 4099.360611178644 1255.1558653499926 1259.2552259611712 Accuracy: 0.8846  test :  0.8427  Prule Train :  0.9483983414513579  Prule test :  0.9633747298572427
35 -576.8354696694894 1204.1235147306675 1203.5466792609977 Accuracy: 0.8877  test :  0.8427  Prule Train :  0.9486994147544607  Prule test :  0.9604797902822655
40 4461.5615325839135 1159.2566263017377 1163.7181878343217 Accuracy: 0.8906  test :  0.8427  Prule Train :  0.9484204956597595  Prule test :  0.96043072132849
45 -1041.002132735499 1115.3840756421312 1114.3430735093957 Accuracy: 0.8931  test :  0.842  Prule Train :  0.9475567482947557  Prule test :  0.9617633552732281
50 4852.624358541274 1076.3678077281688 1081.22043208671 Accuracy: 0.8974  test :  0.8427  Prule Train :  0.9465165265041731  Prule test :  0.9631036811887874
55 -1501.0508143875186 1039.6431277248307 1038.1420769104432 Accuracy: 0.9017  test :  0.8427  Prule Train :  0.9454672705293052  Prule test :  0.9630580494404133
60 5274.408886498559 1005.2262943484453 1010.5007032349438 Accuracy: 0.9057  test :  0.8407  Prule Train :  0.9438208118158307  Prule test :  0.9643640181576756
65 -1945.117867546759 974.2213123224728 972.2761944549261 Accuracy: 0.9097  test :  0.8407  Prule Train :  0.9421620046620045  Prule test :  0.9671313814279512
70 5703.557383149922 946.1004363159841 951.803993699134 Accuracy: 0.9129  test :  0.84  Prule Train :  0.9412046678504359  Prule test :  0.9656390743904333
75 -2374.7379748062067 919.3033941441693 916.928656169363 Accuracy: 0.9169  test :  0.84  Prule Train :  0.9395244989958645  Prule test :  0.9655966156526066
80 6165.568775164464 894.7278302377447 900.8933990129092 Accuracy: 0.9194  test :  0.8393  Prule Train :  0.9411153176156336  Prule test :  0.9670103735086134
85 -2794.8421304026087 872.1967098713033 869.4018677409007 Accuracy: 0.92  test :  0.84  Prule Train :  0.9398018279888147  Prule test :  0.9655113246396706
90 6612.479391249075 849.8993670499534 856.5118464412025 Accuracy: 0.9209  test :  0.8393  Prule Train :  0.9403331224963103  Prule test :  0.9640528483184626
95 -3185.812656934917 830.0674499535944 826.8816372966595 Accuracy: 0.9234  test :  0.84  Prule Train :  0.940677765550862  Prule test :  0.9625943719972547
Resultado | acc=0.8400 | bal_acc=0.6726 | f1=0.9045 | EOdds=0.0265 | EOp=0.0075 | p-rule=96.26 | score=0.6710 | tempo=0.06 min

FAGTB caucasian_1:  58%|█████▊    | 35/60 [03:06<02:06,  5.06s/modelo]

----------------------------------------------------------------------------------------------------
Treino 96/120 | config=caucasian_1 | lambda=0.001 | n_estimators=200 | learning_rate=0.1 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1809.2759468661936 1809.4309528263618 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2091.995283595845 1675.1617726853253 1677.253767968921 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2522.1064828620993 1557.372633948323 1559.8947404311853 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 900.8552467845175 1461.607989416617 1462.5088446634018 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3693.3429670631485 1381.5749784786706 1385.2683214457338 Accuracy: 0.8657  test :  0.8407  Prule Train :  0.9597517328609765  Prule test :  0.9679496825062445
25 -119.25952396196652 1313.1239689922118 1313.0047094682495 Accuracy: 0.8771  test :  0.842  Prule Train :  0.9551455215494026  Prule test :  0.9734269867248593
30 4099.360611178644 1255.1558653499926 1259.2552259611712 Accuracy: 0.8846  test :  0.8427  Prule Train :  0.9483983414513579  Prule test :  0.9633747298572427
35 -576.8354696694894 1204.1235147306675 1203.5466792609977 Accuracy: 0.8877  test :  0.8427  Prule Train :  0.9486994147544607  Prule test :  0.9604797902822655
40 4461.5615325839135 1159.2566263017377 1163.7181878343217 Accuracy: 0.8906  test :  0.8427  Prule Train :  0.9484204956597595  Prule test :  0.96043072132849
45 -1041.002132735499 1115.3840756421312 1114.3430735093957 Accuracy: 0.8931  test :  0.842  Prule Train :  0.9475567482947557  Prule test :  0.9617633552732281
50 4852.624358541274 1076.3678077281688 1081.22043208671 Accuracy: 0.8974  test :  0.8427  Prule Train :  0.9465165265041731  Prule test :  0.9631036811887874
55 -1501.0508143875186 1039.6431277248307 1038.1420769104432 Accuracy: 0.9017  test :  0.8427  Prule Train :  0.9454672705293052  Prule test :  0.9630580494404133
60 5274.408886498559 1005.2262943484453 1010.5007032349438 Accuracy: 0.9057  test :  0.8407  Prule Train :  0.9438208118158307  Prule test :  0.9643640181576756
65 -1945.117867546759 974.2213123224728 972.2761944549261 Accuracy: 0.9097  test :  0.8407  Prule Train :  0.9421620046620045  Prule test :  0.9671313814279512
70 5703.557383149922 946.1004363159841 951.803993699134 Accuracy: 0.9129  test :  0.84  Prule Train :  0.9412046678504359  Prule test :  0.9656390743904333
75 -2374.7379748062067 919.3033941441693 916.928656169363 Accuracy: 0.9169  test :  0.84  Prule Train :  0.9395244989958645  Prule test :  0.9655966156526066
80 6165.568775164464 894.7278302377447 900.8933990129092 Accuracy: 0.9194  test :  0.8393  Prule Train :  0.9411153176156336  Prule test :  0.9670103735086134
85 -2794.8421304026087 872.1967098713033 869.4018677409007 Accuracy: 0.92  test :  0.84  Prule Train :  0.9398018279888147  Prule test :  0.9655113246396706
90 6612.479391249075 849.8993670499534 856.5118464412025 Accuracy: 0.9209  test :  0.8393  Prule Train :  0.9403331224963103  Prule test :  0.9640528483184626
95 -3185.812656934917 830.0674499535944 826.8816372966595 Accuracy: 0.9234  test :  0.84  Prule Train :  0.940677765550862  Prule test :  0.9625943719972547
100 6918.443557788727 810.3659456307088 817.2843891884975 Accuracy: 0.9263  test :  0.8407  Prule Train :  0.9378453714118048  Prule test :  0.9611358956760466
105 -3405.4554609152124 791.4649515570172 788.059496096102 Accuracy: 0.9291  test :  0.8413  Prule Train :  0.9375208125208125  Prule test :  0.9596260193082764
110 6699.3385139339225 773.8685479365054 780.5678864504393 Accuracy: 0.9326  test :  0.8413  Prule Train :  0.9371285991004299  Prule test :  0.9625472552879059
115 -3301.9080709713016 756.4728455488473 753.1709374778759 Accuracy: 0.9346  test :  0.8427  Prule Train :  0.933732933732934  Prule test :  0.9625472552879059
120 6428.567788264863 740.2267805353463 746.6553483236111 Accuracy: 0.9363  test :  0.846  Prule Train :  0.9322633748547795  Prule test :  0.9610372340425534
125 -3124.94794966618 724.0705503698184 720.9456024201523 Accuracy: 0.9391  test :  0.8467  Prule Train :  0.934458582654459  Prule test :  0.9595744680851065
130 6167.063866303035 709.7582369721956 715.9253008384985 Accuracy: 0.9406  test :  0.8447  Prule Train :  0.9336521542973155  Prule test :  0.9610372340425534
135 -2981.9662699191704 693.5065671287776 690.5246008588585 Accuracy: 0.9411  test :  0.844  Prule Train :  0.9323107000526355  Prule test :  0.9625000000000001
140 6051.94593560489 681.1896214037238 687.2415673393285 Accuracy: 0.9423  test :  0.8447  Prule Train :  0.9296277915632755  Prule test :  0.960987685269326
145 -2787.0629507637877 664.9454745210603 662.1584115702965 Accuracy: 0.9454  test :  0.844  Prule Train :  0.9298736669202989  Prule test :  0.9595227650173911
150 5593.909326139243 651.6540957957359 657.2480051218752 Accuracy: 0.9477  test :  0.844  Prule Train :  0.9257599173347715  Prule test :  0.9623573965240894
155 -2745.446970870359 639.172738426478 636.4272914556077 Accuracy: 0.95  test :  0.8447  Prule Train :  0.9229135562685207  Prule test :  0.9608881485904648
160 5860.681793782364 627.1635234722975 633.0242052660799 Accuracy: 0.9509  test :  0.8433  Prule Train :  0.9234374029695667  Prule test :  0.9580038285319776
165 -2422.8444665699326 613.7821623721834 611.3593179056135 Accuracy: 0.9534  test :  0.8433  Prule Train :  0.9224573472130476  Prule test :  0.9580038285319776
170 5043.050881140787 601.4160360731157 606.4590869542567 Accuracy: 0.956  test :  0.842  Prule Train :  0.9227539345186403  Prule test :  0.9580038285319776
175 -2481.9208721451478 591.2544936754899 588.7725728033447 Accuracy: 0.9577  test :  0.8427  Prule Train :  0.9225243213455394  Prule test :  0.9536025858281556
180 5532.886261461777 579.7046279611316 585.2375142225934 Accuracy: 0.9597  test :  0.8413  Prule Train :  0.9190412034448733  Prule test :  0.953541908922342
185 -2242.4518683682545 568.3999587860537 566.1575069176855 Accuracy: 0.9609  test :  0.8407  Prule Train :  0.917598685467538  Prule test :  0.9520726609887175
190 4799.905519827602 560.0113515673858 564.8112570872133 Accuracy: 0.9617  test :  0.84  Prule Train :  0.9168364443954995  Prule test :  0.953541908922342
195 -2300.5207131153475 551.6980435417784 549.3975228286631 Accuracy: 0.9626  test :  0.8407  Prule Train :  0.917358156517158  Prule test :  0.9550111568559666
Resultado | acc=0.8400 | bal_acc=0.6814 | f1=0.9039 | EOdds=0.0314 | EOp=0.0148 | p-rule=95.35 | score=0.6793 | tempo=0.12 min

FAGTB caucasian_1:  60%|██████    | 36/60 [03:13<02:15,  5.65s/modelo]

----------------------------------------------------------------------------------------------------
Treino 97/120 | config=caucasian_1 | lambda=0.005 | n_estimators=100 | learning_rate=0.03 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1830.2316561235134 1831.0066859243548 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2147.402745358721 1787.8766533818136 1798.6136671086074 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2377.502682451639 1747.6259922008921 1759.5135056131503 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1229.1491466455977 1707.6937837061155 1713.8395294393436 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3299.7126380069185 1670.3924701384822 1686.8910333285166 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 357.69350398403446 1634.5971672518601 1636.3856347717801 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3682.97294207666 1601.2679947302408 1619.6828594406238 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 164.87404790379486 1568.6909917633993 1569.5153620029182 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 3882.107726446574 1538.0465380347507 1557.4570766669835 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 -62.439943112756964 1508.1569582576035 1507.84475854204 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 4117.978753539059 1480.822511556005 1501.4124053237006 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -326.6494017668605 1454.5305525714414 1452.897305562607 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 4383.85626562653 1430.43669827824 1452.3559796063728 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 -621.2716297359689 1406.8504878180238 1403.744129669344 Accuracy: 0.7831  test :  0.782  Prule Train :  0.9995052343068962  Prule test :  0.998663101604278
70 4675.595200390704 1384.8297717326022 1408.2077477345556 Accuracy: 0.8651  test :  0.8393  Prule Train :  0.959799648461916  Prule test :  0.9652192179575669
75 -939.7815200943709 1363.365132280157 1358.6662246796855 Accuracy: 0.8677  test :  0.8407  Prule Train :  0.9577814012910167  Prule test :  0.9651776054814282
80 4987.199835735735 1343.3841236706849 1368.3201228493635 Accuracy: 0.8731  test :  0.842  Prule Train :  0.956708145832013  Prule test :  0.9679118196612622
85 -1276.0373639292332 1323.933699692771 1317.5535128731244 Accuracy: 0.8771  test :  0.842  Prule Train :  0.9551455215494026  Prule test :  0.9678357712765958
90 5314.671074465444 1305.9741967713144 1332.5475521436417 Accuracy: 0.8797  test :  0.842  Prule Train :  0.9530967210189566  Prule test :  0.9649677673193913
95 -1626.6345520145103 1288.3396780903745 1280.2065053303018 Accuracy: 0.8814  test :  0.8413  Prule Train :  0.9517266999018823  Prule test :  0.963508516700006
Resultado | acc=0.8407 | bal_acc=0.6521 | f1=0.9064 | EOdds=0.0509 | EOp=0.0061 | p-rule=96.21 | score=0.6494 | tempo=0.06 min

FAGTB caucasian_1:  62%|██████▏   | 37/60 [03:16<01:56,  5.05s/modelo]

----------------------------------------------------------------------------------------------------
Treino 98/120 | config=caucasian_1 | lambda=0.005 | n_estimators=200 | learning_rate=0.03 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1830.2316561235134 1831.0066859243548 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2147.402745358721 1787.8766533818136 1798.6136671086074 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2377.502682451639 1747.6259922008921 1759.5135056131503 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1229.1491466455977 1707.6937837061155 1713.8395294393436 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3299.7126380069185 1670.3924701384822 1686.8910333285166 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 357.69350398403446 1634.5971672518601 1636.3856347717801 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3682.97294207666 1601.2679947302408 1619.6828594406238 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 164.87404790379486 1568.6909917633993 1569.5153620029182 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 3882.107726446574 1538.0465380347507 1557.4570766669835 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 -62.439943112756964 1508.1569582576035 1507.84475854204 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 4117.978753539059 1480.822511556005 1501.4124053237006 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -326.6494017668605 1454.5305525714414 1452.897305562607 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 4383.85626562653 1430.43669827824 1452.3559796063728 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 -621.2716297359689 1406.8504878180238 1403.744129669344 Accuracy: 0.7831  test :  0.782  Prule Train :  0.9995052343068962  Prule test :  0.998663101604278
70 4675.595200390704 1384.8297717326022 1408.2077477345556 Accuracy: 0.8651  test :  0.8393  Prule Train :  0.959799648461916  Prule test :  0.9652192179575669
75 -939.7815200943709 1363.365132280157 1358.6662246796855 Accuracy: 0.8677  test :  0.8407  Prule Train :  0.9577814012910167  Prule test :  0.9651776054814282
80 4987.199835735735 1343.3841236706849 1368.3201228493635 Accuracy: 0.8731  test :  0.842  Prule Train :  0.956708145832013  Prule test :  0.9679118196612622
85 -1276.0373639292332 1323.933699692771 1317.5535128731244 Accuracy: 0.8771  test :  0.842  Prule Train :  0.9551455215494026  Prule test :  0.9678357712765958
90 5314.671074465444 1305.9741967713144 1332.5475521436417 Accuracy: 0.8797  test :  0.842  Prule Train :  0.9530967210189566  Prule test :  0.9649677673193913
95 -1626.6345520145103 1288.3396780903745 1280.2065053303018 Accuracy: 0.8814  test :  0.8413  Prule Train :  0.9517266999018823  Prule test :  0.963508516700006
100 5656.403753195944 1272.130560249539 1300.4125790155188 Accuracy: 0.8829  test :  0.8407  Prule Train :  0.9509864881363054  Prule test :  0.9620915924107414
105 -1988.0510050713528 1255.7977030726006 1245.8574480472437 Accuracy: 0.8837  test :  0.8407  Prule Train :  0.950298939330018  Prule test :  0.9620915924107414
110 6012.485905415199 1240.3839919931775 1270.4464215202536 Accuracy: 0.8851  test :  0.84  Prule Train :  0.9519859086138868  Prule test :  0.9634640483200292
115 -2359.654967212401 1225.8801049264698 1214.0818300904075 Accuracy: 0.8857  test :  0.84  Prule Train :  0.9519323382404068  Prule test :  0.9634194528875379
120 6379.070438277702 1212.2098683563668 1244.1052205477554 Accuracy: 0.8863  test :  0.842  Prule Train :  0.9506614005391512  Prule test :  0.9592072115822383
125 -2737.5771634726907 1199.5391549023827 1185.851269085019 Accuracy: 0.8866  test :  0.842  Prule Train :  0.9500259316885235  Prule test :  0.9592072115822383
130 6759.682653125174 1186.9544280230675 1220.7528412886932 Accuracy: 0.8871  test :  0.842  Prule Train :  0.9499711297876435  Prule test :  0.9592072115822383
135 -3121.5687027397003 1174.5506783319993 1158.942834818301 Accuracy: 0.8889  test :  0.8427  Prule Train :  0.9498063211298506  Prule test :  0.9605775075987841
140 7144.243328962037 1162.7007188599746 1198.4219355047846 Accuracy: 0.8906  test :  0.8427  Prule Train :  0.9496409054420103  Prule test :  0.9605287188384622
145 -3511.727478311379 1151.3822506502788 1133.823613258722 Accuracy: 0.8911  test :  0.8427  Prule Train :  0.948364506375556  Prule test :  0.9605287188384622
150 7532.946328419506 1140.6727730201249 1178.3375046622223 Accuracy: 0.8911  test :  0.8433  Prule Train :  0.948364506375556  Prule test :  0.9619048344814974
155 -3901.3038803694353 1129.7191856638824 1110.2126662620353 Accuracy: 0.8917  test :  0.8427  Prule Train :  0.9483084483084484  Prule test :  0.963284898806435
160 7922.72802074042 1119.023397398808 1158.6370375025099 Accuracy: 0.892  test :  0.842  Prule Train :  0.9476698567607659  Prule test :  0.9646257462115415
165 -4288.924106946182 1107.806630415575 1086.3620098808442 Accuracy: 0.8929  test :  0.8407  Prule Train :  0.9457540821177184  Prule test :  0.964582439144031
170 8305.86663897851 1097.3746589379132 1138.9039921328058 Accuracy: 0.8937  test :  0.84  Prule Train :  0.9450574011114883  Prule test :  0.9631491814335642
175 -4670.515400173634 1086.7515860335347 1063.3990090326668 Accuracy: 0.8951  test :  0.84  Prule Train :  0.9430811091327694  Prule test :  0.9631491814335642
180 8663.872098920092 1077.140818820028 1120.4601793146285 Accuracy: 0.8971  test :  0.8413  Prule Train :  0.9422620919848277  Prule test :  0.9659328495879965
185 -5030.590125181467 1067.8683989387682 1042.7154483128609 Accuracy: 0.8974  test :  0.8413  Prule Train :  0.9416215331187604  Prule test :  0.9659328495879965
190 8911.554329567016 1058.800315180025 1103.3580868278602 Accuracy: 0.8989  test :  0.8413  Prule Train :  0.9408592641165128  Prule test :  0.9658912461126334
195 -5288.810987446002 1050.1313703121953 1023.6873153749651 Accuracy: 0.9006  test :  0.8413  Prule Train :  0.9406761347428838  Prule test :  0.9658912461126334
Resultado | acc=0.8420 | bal_acc=0.6640 | f1=0.9065 | EOdds=0.0289 | EOp=0.0067 | p-rule=96.45 | score=0.6623 | tempo=0.12 min

FAGTB caucasian_1:  63%|██████▎   | 38/60 [03:23<02:04,  5.66s/modelo]

----------------------------------------------------------------------------------------------------
Treino 99/120 | config=caucasian_1 | lambda=0.005 | n_estimators=100 | learning_rate=0.03 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1830.2316561235134 1831.0066859243548 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2147.402745358721 1787.8766533818136 1798.6136671086074 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2377.502682451639 1747.6259922008921 1759.5135056131503 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1229.1491466455977 1707.6937837061155 1713.8395294393436 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3299.7126380069185 1670.3924701384822 1686.8910333285166 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 357.69350398403446 1634.5971672518601 1636.3856347717801 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3682.97294207666 1601.2679947302408 1619.6828594406238 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 164.87404790379486 1568.6909917633993 1569.5153620029182 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 3882.107726446574 1538.0465380347507 1557.4570766669835 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 -62.439943112756964 1508.1569582576035 1507.84475854204 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 4117.978753539059 1480.822511556005 1501.4124053237006 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -326.6494017668605 1454.5305525714414 1452.897305562607 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 4383.85626562653 1430.43669827824 1452.3559796063728 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 -621.2716297359689 1406.8504878180238 1403.744129669344 Accuracy: 0.7831  test :  0.782  Prule Train :  0.9995052343068962  Prule test :  0.998663101604278
70 4675.595200390704 1384.8297717326022 1408.2077477345556 Accuracy: 0.8651  test :  0.8393  Prule Train :  0.959799648461916  Prule test :  0.9652192179575669
75 -939.7815200943709 1363.365132280157 1358.6662246796855 Accuracy: 0.8677  test :  0.8407  Prule Train :  0.9577814012910167  Prule test :  0.9651776054814282
80 4987.199835735735 1343.3841236706849 1368.3201228493635 Accuracy: 0.8731  test :  0.842  Prule Train :  0.956708145832013  Prule test :  0.9679118196612622
85 -1276.0373639292332 1323.933699692771 1317.5535128731244 Accuracy: 0.8771  test :  0.842  Prule Train :  0.9551455215494026  Prule test :  0.9678357712765958
90 5314.671074465444 1305.9741967713144 1332.5475521436417 Accuracy: 0.8797  test :  0.842  Prule Train :  0.9530967210189566  Prule test :  0.9649677673193913
95 -1626.6345520145103 1288.3396780903745 1280.2065053303018 Accuracy: 0.8814  test :  0.8413  Prule Train :  0.9517266999018823  Prule test :  0.963508516700006
Resultado | acc=0.8407 | bal_acc=0.6521 | f1=0.9064 | EOdds=0.0509 | EOp=0.0061 | p-rule=96.21 | score=0.6494 | tempo=0.06 min

FAGTB caucasian_1:  65%|██████▌   | 39/60 [03:27<01:46,  5.06s/modelo]

----------------------------------------------------------------------------------------------------
Treino 100/120 | config=caucasian_1 | lambda=0.005 | n_estimators=200 | learning_rate=0.03 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1830.2316561235134 1831.0066859243548 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2147.402745358721 1787.8766533818136 1798.6136671086074 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2377.502682451639 1747.6259922008921 1759.5135056131503 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1229.1491466455977 1707.6937837061155 1713.8395294393436 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3299.7126380069185 1670.3924701384822 1686.8910333285166 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 357.69350398403446 1634.5971672518601 1636.3856347717801 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3682.97294207666 1601.2679947302408 1619.6828594406238 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 164.87404790379486 1568.6909917633993 1569.5153620029182 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 3882.107726446574 1538.0465380347507 1557.4570766669835 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 -62.439943112756964 1508.1569582576035 1507.84475854204 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 4117.978753539059 1480.822511556005 1501.4124053237006 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -326.6494017668605 1454.5305525714414 1452.897305562607 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 4383.85626562653 1430.43669827824 1452.3559796063728 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 -621.2716297359689 1406.8504878180238 1403.744129669344 Accuracy: 0.7831  test :  0.782  Prule Train :  0.9995052343068962  Prule test :  0.998663101604278
70 4675.595200390704 1384.8297717326022 1408.2077477345556 Accuracy: 0.8651  test :  0.8393  Prule Train :  0.959799648461916  Prule test :  0.9652192179575669
75 -939.7815200943709 1363.365132280157 1358.6662246796855 Accuracy: 0.8677  test :  0.8407  Prule Train :  0.9577814012910167  Prule test :  0.9651776054814282
80 4987.199835735735 1343.3841236706849 1368.3201228493635 Accuracy: 0.8731  test :  0.842  Prule Train :  0.956708145832013  Prule test :  0.9679118196612622
85 -1276.0373639292332 1323.933699692771 1317.5535128731244 Accuracy: 0.8771  test :  0.842  Prule Train :  0.9551455215494026  Prule test :  0.9678357712765958
90 5314.671074465444 1305.9741967713144 1332.5475521436417 Accuracy: 0.8797  test :  0.842  Prule Train :  0.9530967210189566  Prule test :  0.9649677673193913
95 -1626.6345520145103 1288.3396780903745 1280.2065053303018 Accuracy: 0.8814  test :  0.8413  Prule Train :  0.9517266999018823  Prule test :  0.963508516700006
100 5656.403753195944 1272.130560249539 1300.4125790155188 Accuracy: 0.8829  test :  0.8407  Prule Train :  0.9509864881363054  Prule test :  0.9620915924107414
105 -1988.0510050713528 1255.7977030726006 1245.8574480472437 Accuracy: 0.8837  test :  0.8407  Prule Train :  0.950298939330018  Prule test :  0.9620915924107414
110 6012.485905415199 1240.3839919931775 1270.4464215202536 Accuracy: 0.8851  test :  0.84  Prule Train :  0.9519859086138868  Prule test :  0.9634640483200292
115 -2359.654967212401 1225.8801049264698 1214.0818300904075 Accuracy: 0.8857  test :  0.84  Prule Train :  0.9519323382404068  Prule test :  0.9634194528875379
120 6379.070438277702 1212.2098683563668 1244.1052205477554 Accuracy: 0.8863  test :  0.842  Prule Train :  0.9506614005391512  Prule test :  0.9592072115822383
125 -2737.5771634726907 1199.5391549023827 1185.851269085019 Accuracy: 0.8866  test :  0.842  Prule Train :  0.9500259316885235  Prule test :  0.9592072115822383
130 6759.682653125174 1186.9544280230675 1220.7528412886932 Accuracy: 0.8871  test :  0.842  Prule Train :  0.9499711297876435  Prule test :  0.9592072115822383
135 -3121.5687027397003 1174.5506783319993 1158.942834818301 Accuracy: 0.8889  test :  0.8427  Prule Train :  0.9498063211298506  Prule test :  0.9605775075987841
140 7144.243328962037 1162.7007188599746 1198.4219355047846 Accuracy: 0.8906  test :  0.8427  Prule Train :  0.9496409054420103  Prule test :  0.9605287188384622
145 -3511.727478311379 1151.3822506502788 1133.823613258722 Accuracy: 0.8911  test :  0.8427  Prule Train :  0.948364506375556  Prule test :  0.9605287188384622
150 7532.946328419506 1140.6727730201249 1178.3375046622223 Accuracy: 0.8911  test :  0.8433  Prule Train :  0.948364506375556  Prule test :  0.9619048344814974
155 -3901.3038803694353 1129.7191856638824 1110.2126662620353 Accuracy: 0.8917  test :  0.8427  Prule Train :  0.9483084483084484  Prule test :  0.963284898806435
160 7922.72802074042 1119.023397398808 1158.6370375025099 Accuracy: 0.892  test :  0.842  Prule Train :  0.9476698567607659  Prule test :  0.9646257462115415
165 -4288.924106946182 1107.806630415575 1086.3620098808442 Accuracy: 0.8929  test :  0.8407  Prule Train :  0.9457540821177184  Prule test :  0.964582439144031
170 8305.86663897851 1097.3746589379132 1138.9039921328058 Accuracy: 0.8937  test :  0.84  Prule Train :  0.9450574011114883  Prule test :  0.9631491814335642
175 -4670.515400173634 1086.7515860335347 1063.3990090326668 Accuracy: 0.8951  test :  0.84  Prule Train :  0.9430811091327694  Prule test :  0.9631491814335642
180 8663.872098920092 1077.140818820028 1120.4601793146285 Accuracy: 0.8971  test :  0.8413  Prule Train :  0.9422620919848277  Prule test :  0.9659328495879965
185 -5030.590125181467 1067.8683989387682 1042.7154483128609 Accuracy: 0.8974  test :  0.8413  Prule Train :  0.9416215331187604  Prule test :  0.9659328495879965
190 8911.554329567016 1058.800315180025 1103.3580868278602 Accuracy: 0.8989  test :  0.8413  Prule Train :  0.9408592641165128  Prule test :  0.9658912461126334
195 -5288.810987446002 1050.1313703121953 1023.6873153749651 Accuracy: 0.9006  test :  0.8413  Prule Train :  0.9406761347428838  Prule test :  0.9658912461126334
Resultado | acc=0.8420 | bal_acc=0.6640 | f1=0.9065 | EOdds=0.0289 | EOp=0.0067 | p-rule=96.45 | score=0.6623 | tempo=0.12 min

FAGTB caucasian_1:  67%|██████▋   | 40/60 [03:34<01:52,  5.65s/modelo]

----------------------------------------------------------------------------------------------------
Treino 101/120 | config=caucasian_1 | lambda=0.005 | n_estimators=100 | learning_rate=0.05 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1824.3437455341652 1825.1187753350066 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2133.2637414961528 1755.5079681232307 1766.1742868307115 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2416.8616154502483 1689.520393050862 1701.6047011281132 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1141.8589365704956 1628.3742147876983 1634.0835094705508 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3427.689807341443 1573.8678452033732 1591.0062942400805 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 206.11574781432256 1522.0457944825666 1523.0763732216383 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3836.8436142136857 1475.8891517249758 1495.073369796044 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -71.19326177563036 1433.438436778204 1433.082470469326 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 4109.937772075924 1395.4728657185926 1416.0225545789722 Accuracy: 0.8486  test :  0.8307  Prule Train :  0.9635268312954264  Prule test :  0.9724843467165197
45 -404.5648023388287 1359.2761002689026 1357.2532762572087 Accuracy: 0.868  test :  0.8407  Prule Train :  0.957156625425856  Prule test :  0.9651776054814282
50 4422.499497327243 1327.2830393777003 1349.3955368643367 Accuracy: 0.874  test :  0.842  Prule Train :  0.9584455092929669  Prule test :  0.9679118196612622
55 -773.6161998303386 1295.3332369131858 1291.465155914034 Accuracy: 0.8809  test :  0.842  Prule Train :  0.9517801347588581  Prule test :  0.9677208850578203
60 4763.077614501608 1265.893293291672 1289.7086813641802 Accuracy: 0.8829  test :  0.8413  Prule Train :  0.9509864881363054  Prule test :  0.9634640483200292
65 -1164.8558101229194 1238.9034060048582 1233.0791269542437 Accuracy: 0.8849  test :  0.842  Prule Train :  0.9501899361569893  Prule test :  0.9620451027407654
70 5125.6262872215575 1214.7455547846796 1240.3736862207872 Accuracy: 0.8851  test :  0.8413  Prule Train :  0.9495556304586202  Prule test :  0.9606261571615018
75 -1567.4691282985618 1192.8453049730203 1185.0079593315277 Accuracy: 0.8869  test :  0.8407  Prule Train :  0.950606987304235  Prule test :  0.9592072115822383
80 5509.634408901133 1172.0346279048324 1199.582799949338 Accuracy: 0.8877  test :  0.842  Prule Train :  0.9499162608097735  Prule test :  0.9591565349544073
85 -1977.1119183577603 1151.2665224765165 1141.3809628847275 Accuracy: 0.8894  test :  0.8413  Prule Train :  0.9509717276588442  Prule test :  0.9576827078196817
90 5899.2829836748315 1131.6260475251033 1161.1224624434772 Accuracy: 0.8917  test :  0.8413  Prule Train :  0.9495302894196564  Prule test :  0.9576827078196817
95 -2388.928767533607 1112.3087565984274 1100.3641127607593 Accuracy: 0.8931  test :  0.842  Prule Train :  0.9487796306257846  Prule test :  0.9590547460830336
Resultado | acc=0.8420 | bal_acc=0.6607 | f1=0.9067 | EOdds=0.0380 | EOp=0.0082 | p-rule=96.18 | score=0.6585 | tempo=0.06 min

FAGTB caucasian_1:  68%|██████▊   | 41/60 [03:38<01:35,  5.05s/modelo]

----------------------------------------------------------------------------------------------------
Treino 102/120 | config=caucasian_1 | lambda=0.005 | n_estimators=200 | learning_rate=0.05 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1824.3437455341652 1825.1187753350066 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2133.2637414961528 1755.5079681232307 1766.1742868307115 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2416.8616154502483 1689.520393050862 1701.6047011281132 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1141.8589365704956 1628.3742147876983 1634.0835094705508 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3427.689807341443 1573.8678452033732 1591.0062942400805 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 206.11574781432256 1522.0457944825666 1523.0763732216383 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3836.8436142136857 1475.8891517249758 1495.073369796044 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -71.19326177563036 1433.438436778204 1433.082470469326 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 4109.937772075924 1395.4728657185926 1416.0225545789722 Accuracy: 0.8486  test :  0.8307  Prule Train :  0.9635268312954264  Prule test :  0.9724843467165197
45 -404.5648023388287 1359.2761002689026 1357.2532762572087 Accuracy: 0.868  test :  0.8407  Prule Train :  0.957156625425856  Prule test :  0.9651776054814282
50 4422.499497327243 1327.2830393777003 1349.3955368643367 Accuracy: 0.874  test :  0.842  Prule Train :  0.9584455092929669  Prule test :  0.9679118196612622
55 -773.6161998303386 1295.3332369131858 1291.465155914034 Accuracy: 0.8809  test :  0.842  Prule Train :  0.9517801347588581  Prule test :  0.9677208850578203
60 4763.077614501608 1265.893293291672 1289.7086813641802 Accuracy: 0.8829  test :  0.8413  Prule Train :  0.9509864881363054  Prule test :  0.9634640483200292
65 -1164.8558101229194 1238.9034060048582 1233.0791269542437 Accuracy: 0.8849  test :  0.842  Prule Train :  0.9501899361569893  Prule test :  0.9620451027407654
70 5125.6262872215575 1214.7455547846796 1240.3736862207872 Accuracy: 0.8851  test :  0.8413  Prule Train :  0.9495556304586202  Prule test :  0.9606261571615018
75 -1567.4691282985618 1192.8453049730203 1185.0079593315277 Accuracy: 0.8869  test :  0.8407  Prule Train :  0.950606987304235  Prule test :  0.9592072115822383
80 5509.634408901133 1172.0346279048324 1199.582799949338 Accuracy: 0.8877  test :  0.842  Prule Train :  0.9499162608097735  Prule test :  0.9591565349544073
85 -1977.1119183577603 1151.2665224765165 1141.3809628847275 Accuracy: 0.8894  test :  0.8413  Prule Train :  0.9509717276588442  Prule test :  0.9576827078196817
90 5899.2829836748315 1131.6260475251033 1161.1224624434772 Accuracy: 0.8917  test :  0.8413  Prule Train :  0.9495302894196564  Prule test :  0.9576827078196817
95 -2388.928767533607 1112.3087565984274 1100.3641127607593 Accuracy: 0.8931  test :  0.842  Prule Train :  0.9487796306257846  Prule test :  0.9590547460830336
100 6297.504972312765 1094.1306940901268 1125.6182189516903 Accuracy: 0.8943  test :  0.842  Prule Train :  0.9462205486820872  Prule test :  0.9618106505258011
105 -2800.9555556999294 1075.8026512859165 1061.7978735074166 Accuracy: 0.8957  test :  0.8427  Prule Train :  0.9442425390701252  Prule test :  0.9603321598040716
110 6692.397654572309 1059.3080097205734 1092.769997993435 Accuracy: 0.8969  test :  0.8413  Prule Train :  0.9429026508508949  Prule test :  0.9602826660126308
115 -3212.4426379688925 1044.4942511250185 1028.432037935174 Accuracy: 0.8991  test :  0.842  Prule Train :  0.9402179149248859  Prule test :  0.9616683552853766
120 7097.74539853558 1030.8549962254908 1066.3437232181686 Accuracy: 0.9014  test :  0.8427  Prule Train :  0.9399720049070699  Prule test :  0.9630580494404133
125 -3619.4643924033403 1017.9191615360463 999.8218395740296 Accuracy: 0.9029  test :  0.8433  Prule Train :  0.9392048611862854  Prule test :  0.9616206493666215
130 7495.878083050202 1004.8492773987297 1042.3286678139807 Accuracy: 0.904  test :  0.8433  Prule Train :  0.9390803451559806  Prule test :  0.9616206493666215
135 -4010.484230305067 989.6061955844616 969.5537744329363 Accuracy: 0.9057  test :  0.8433  Prule Train :  0.9401226492587589  Prule test :  0.9616206493666215
140 7836.665574982634 975.3044872688251 1014.4878151437383 Accuracy: 0.9077  test :  0.8433  Prule Train :  0.9429929604602094  Prule test :  0.9616206493666215
145 -4328.534887992967 961.1553072762163 939.5126328362514 Accuracy: 0.9103  test :  0.844  Prule Train :  0.9408624708624707  Prule test :  0.9601832492928299
150 7871.473609742874 949.107489297478 988.4648573461922 Accuracy: 0.912  test :  0.844  Prule Train :  0.9394377003888894  Prule test :  0.9601832492928299
155 -4404.17037102144 936.0003489957846 913.9794971406775 Accuracy: 0.914  test :  0.844  Prule Train :  0.939838496927581  Prule test :  0.9573084491452465
160 7542.660556788971 924.9791683932451 962.6924711771899 Accuracy: 0.9149  test :  0.842  Prule Train :  0.9403661664968197  Prule test :  0.955814884379715
165 -4267.145550064695 912.6518582035237 891.3161304532002 Accuracy: 0.9169  test :  0.844  Prule Train :  0.9407708160856775  Prule test :  0.9600330420282246
170 7310.78839310716 900.4055882282737 936.9595301938095 Accuracy: 0.9171  test :  0.8433  Prule Train :  0.9413636143314783  Prule test :  0.9614284388916378
175 -4094.06311011438 887.2897776790012 866.8194621284292 Accuracy: 0.9197  test :  0.844  Prule Train :  0.9404585728022242  Prule test :  0.9571457246085909
180 7119.9441305893615 875.8870747156899 911.4867953686368 Accuracy: 0.9206  test :  0.8433  Prule Train :  0.9409906981064475  Prule test :  0.955702065898774
185 -3939.973143957157 864.2638594947568 844.5639937749711 Accuracy: 0.9214  test :  0.844  Prule Train :  0.9415241714165085  Prule test :  0.9599321750441328
190 6981.586141945881 853.6615611497393 888.5694918594688 Accuracy: 0.9229  test :  0.8447  Prule Train :  0.9407405108102636  Prule test :  0.958484313543312
195 -3790.9566799076874 843.0232309317861 824.0684475322478 Accuracy: 0.9246  test :  0.8447  Prule Train :  0.9418108909526584  Prule test :  0.9584315489113581
Resultado | acc=0.8440 | bal_acc=0.6751 | f1=0.9071 | EOdds=0.0390 | EOp=0.0105 | p-rule=95.70 | score=0.6729 | tempo=0.11 min

FAGTB caucasian_1:  70%|███████   | 42/60 [03:45<01:41,  5.64s/modelo]

----------------------------------------------------------------------------------------------------
Treino 103/120 | config=caucasian_1 | lambda=0.005 | n_estimators=100 | learning_rate=0.05 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1824.3437455341652 1825.1187753350066 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2133.2637414961528 1755.5079681232307 1766.1742868307115 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2416.8616154502483 1689.520393050862 1701.6047011281132 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1141.8589365704956 1628.3742147876983 1634.0835094705508 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3427.689807341443 1573.8678452033732 1591.0062942400805 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 206.11574781432256 1522.0457944825666 1523.0763732216383 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3836.8436142136857 1475.8891517249758 1495.073369796044 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -71.19326177563036 1433.438436778204 1433.082470469326 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 4109.937772075924 1395.4728657185926 1416.0225545789722 Accuracy: 0.8486  test :  0.8307  Prule Train :  0.9635268312954264  Prule test :  0.9724843467165197
45 -404.5648023388287 1359.2761002689026 1357.2532762572087 Accuracy: 0.868  test :  0.8407  Prule Train :  0.957156625425856  Prule test :  0.9651776054814282
50 4422.499497327243 1327.2830393777003 1349.3955368643367 Accuracy: 0.874  test :  0.842  Prule Train :  0.9584455092929669  Prule test :  0.9679118196612622
55 -773.6161998303386 1295.3332369131858 1291.465155914034 Accuracy: 0.8809  test :  0.842  Prule Train :  0.9517801347588581  Prule test :  0.9677208850578203
60 4763.077614501608 1265.893293291672 1289.7086813641802 Accuracy: 0.8829  test :  0.8413  Prule Train :  0.9509864881363054  Prule test :  0.9634640483200292
65 -1164.8558101229194 1238.9034060048582 1233.0791269542437 Accuracy: 0.8849  test :  0.842  Prule Train :  0.9501899361569893  Prule test :  0.9620451027407654
70 5125.6262872215575 1214.7455547846796 1240.3736862207872 Accuracy: 0.8851  test :  0.8413  Prule Train :  0.9495556304586202  Prule test :  0.9606261571615018
75 -1567.4691282985618 1192.8453049730203 1185.0079593315277 Accuracy: 0.8869  test :  0.8407  Prule Train :  0.950606987304235  Prule test :  0.9592072115822383
80 5509.634408901133 1172.0346279048324 1199.582799949338 Accuracy: 0.8877  test :  0.842  Prule Train :  0.9499162608097735  Prule test :  0.9591565349544073
85 -1977.1119183577603 1151.2665224765165 1141.3809628847275 Accuracy: 0.8894  test :  0.8413  Prule Train :  0.9509717276588442  Prule test :  0.9576827078196817
90 5899.2829836748315 1131.6260475251033 1161.1224624434772 Accuracy: 0.8917  test :  0.8413  Prule Train :  0.9495302894196564  Prule test :  0.9576827078196817
95 -2388.928767533607 1112.3087565984274 1100.3641127607593 Accuracy: 0.8931  test :  0.842  Prule Train :  0.9487796306257846  Prule test :  0.9590547460830336
Resultado | acc=0.8420 | bal_acc=0.6607 | f1=0.9067 | EOdds=0.0380 | EOp=0.0082 | p-rule=96.18 | score=0.6585 | tempo=0.06 min

FAGTB caucasian_1:  72%|███████▏  | 43/60 [03:49<01:25,  5.05s/modelo]

----------------------------------------------------------------------------------------------------
Treino 104/120 | config=caucasian_1 | lambda=0.005 | n_estimators=200 | learning_rate=0.05 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1824.3437455341652 1825.1187753350066 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2133.2637414961528 1755.5079681232307 1766.1742868307115 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2416.8616154502483 1689.520393050862 1701.6047011281132 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1141.8589365704956 1628.3742147876983 1634.0835094705508 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3427.689807341443 1573.8678452033732 1591.0062942400805 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 206.11574781432256 1522.0457944825666 1523.0763732216383 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3836.8436142136857 1475.8891517249758 1495.073369796044 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -71.19326177563036 1433.438436778204 1433.082470469326 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 4109.937772075924 1395.4728657185926 1416.0225545789722 Accuracy: 0.8486  test :  0.8307  Prule Train :  0.9635268312954264  Prule test :  0.9724843467165197
45 -404.5648023388287 1359.2761002689026 1357.2532762572087 Accuracy: 0.868  test :  0.8407  Prule Train :  0.957156625425856  Prule test :  0.9651776054814282
50 4422.499497327243 1327.2830393777003 1349.3955368643367 Accuracy: 0.874  test :  0.842  Prule Train :  0.9584455092929669  Prule test :  0.9679118196612622
55 -773.6161998303386 1295.3332369131858 1291.465155914034 Accuracy: 0.8809  test :  0.842  Prule Train :  0.9517801347588581  Prule test :  0.9677208850578203
60 4763.077614501608 1265.893293291672 1289.7086813641802 Accuracy: 0.8829  test :  0.8413  Prule Train :  0.9509864881363054  Prule test :  0.9634640483200292
65 -1164.8558101229194 1238.9034060048582 1233.0791269542437 Accuracy: 0.8849  test :  0.842  Prule Train :  0.9501899361569893  Prule test :  0.9620451027407654
70 5125.6262872215575 1214.7455547846796 1240.3736862207872 Accuracy: 0.8851  test :  0.8413  Prule Train :  0.9495556304586202  Prule test :  0.9606261571615018
75 -1567.4691282985618 1192.8453049730203 1185.0079593315277 Accuracy: 0.8869  test :  0.8407  Prule Train :  0.950606987304235  Prule test :  0.9592072115822383
80 5509.634408901133 1172.0346279048324 1199.582799949338 Accuracy: 0.8877  test :  0.842  Prule Train :  0.9499162608097735  Prule test :  0.9591565349544073
85 -1977.1119183577603 1151.2665224765165 1141.3809628847275 Accuracy: 0.8894  test :  0.8413  Prule Train :  0.9509717276588442  Prule test :  0.9576827078196817
90 5899.2829836748315 1131.6260475251033 1161.1224624434772 Accuracy: 0.8917  test :  0.8413  Prule Train :  0.9495302894196564  Prule test :  0.9576827078196817
95 -2388.928767533607 1112.3087565984274 1100.3641127607593 Accuracy: 0.8931  test :  0.842  Prule Train :  0.9487796306257846  Prule test :  0.9590547460830336
100 6297.504972312765 1094.1306940901268 1125.6182189516903 Accuracy: 0.8943  test :  0.842  Prule Train :  0.9462205486820872  Prule test :  0.9618106505258011
105 -2800.9555556999294 1075.8026512859165 1061.7978735074166 Accuracy: 0.8957  test :  0.8427  Prule Train :  0.9442425390701252  Prule test :  0.9603321598040716
110 6692.397654572309 1059.3080097205734 1092.769997993435 Accuracy: 0.8969  test :  0.8413  Prule Train :  0.9429026508508949  Prule test :  0.9602826660126308
115 -3212.4426379688925 1044.4942511250185 1028.432037935174 Accuracy: 0.8991  test :  0.842  Prule Train :  0.9402179149248859  Prule test :  0.9616683552853766
120 7097.74539853558 1030.8549962254908 1066.3437232181686 Accuracy: 0.9014  test :  0.8427  Prule Train :  0.9399720049070699  Prule test :  0.9630580494404133
125 -3619.4643924033403 1017.9191615360463 999.8218395740296 Accuracy: 0.9029  test :  0.8433  Prule Train :  0.9392048611862854  Prule test :  0.9616206493666215
130 7495.878083050202 1004.8492773987297 1042.3286678139807 Accuracy: 0.904  test :  0.8433  Prule Train :  0.9390803451559806  Prule test :  0.9616206493666215
135 -4010.484230305067 989.6061955844616 969.5537744329363 Accuracy: 0.9057  test :  0.8433  Prule Train :  0.9401226492587589  Prule test :  0.9616206493666215
140 7836.665574982634 975.3044872688251 1014.4878151437383 Accuracy: 0.9077  test :  0.8433  Prule Train :  0.9429929604602094  Prule test :  0.9616206493666215
145 -4328.534887992967 961.1553072762163 939.5126328362514 Accuracy: 0.9103  test :  0.844  Prule Train :  0.9408624708624707  Prule test :  0.9601832492928299
150 7871.473609742874 949.107489297478 988.4648573461922 Accuracy: 0.912  test :  0.844  Prule Train :  0.9394377003888894  Prule test :  0.9601832492928299
155 -4404.17037102144 936.0003489957846 913.9794971406775 Accuracy: 0.914  test :  0.844  Prule Train :  0.939838496927581  Prule test :  0.9573084491452465
160 7542.660556788971 924.9791683932451 962.6924711771899 Accuracy: 0.9149  test :  0.842  Prule Train :  0.9403661664968197  Prule test :  0.955814884379715
165 -4267.145550064695 912.6518582035237 891.3161304532002 Accuracy: 0.9169  test :  0.844  Prule Train :  0.9407708160856775  Prule test :  0.9600330420282246
170 7310.78839310716 900.4055882282737 936.9595301938095 Accuracy: 0.9171  test :  0.8433  Prule Train :  0.9413636143314783  Prule test :  0.9614284388916378
175 -4094.06311011438 887.2897776790012 866.8194621284292 Accuracy: 0.9197  test :  0.844  Prule Train :  0.9404585728022242  Prule test :  0.9571457246085909
180 7119.9441305893615 875.8870747156899 911.4867953686368 Accuracy: 0.9206  test :  0.8433  Prule Train :  0.9409906981064475  Prule test :  0.955702065898774
185 -3939.973143957157 864.2638594947568 844.5639937749711 Accuracy: 0.9214  test :  0.844  Prule Train :  0.9415241714165085  Prule test :  0.9599321750441328
190 6981.586141945881 853.6615611497393 888.5694918594688 Accuracy: 0.9229  test :  0.8447  Prule Train :  0.9407405108102636  Prule test :  0.958484313543312
195 -3790.9566799076874 843.0232309317861 824.0684475322478 Accuracy: 0.9246  test :  0.8447  Prule Train :  0.9418108909526584  Prule test :  0.9584315489113581
Resultado | acc=0.8440 | bal_acc=0.6751 | f1=0.9071 | EOdds=0.0390 | EOp=0.0105 | p-rule=95.70 | score=0.6729 | tempo=0.11 min

FAGTB caucasian_1:  73%|███████▎  | 44/60 [03:56<01:30,  5.64s/modelo]

----------------------------------------------------------------------------------------------------
Treino 105/120 | config=caucasian_1 | lambda=0.005 | n_estimators=100 | learning_rate=0.1 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1809.714413443474 1810.4894432443155 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2096.264927960864 1674.88943102669 1685.3707556664942 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2508.5597071422317 1560.4948027844248 1573.0376013201358 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 920.7277815477819 1464.1721773647364 1468.7758162724754 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3658.6935449297944 1385.4230791960076 1403.7165469206564 Accuracy: 0.8646  test :  0.8407  Prule Train :  0.9586494990928784  Prule test :  0.9625041146721728
25 -92.48223149502485 1315.2792524061838 1314.8168412487087 Accuracy: 0.8763  test :  0.842  Prule Train :  0.9558267994631631  Prule test :  0.9678357712765958
30 4050.6078219110755 1256.2491692274866 1276.502208337042 Accuracy: 0.8826  test :  0.8413  Prule Train :  0.9504076771270928  Prule test :  0.9634194528875379
35 -531.1693666961617 1203.0664617677533 1200.4106149342724 Accuracy: 0.886  test :  0.8407  Prule Train :  0.9488659488659489  Prule test :  0.9647977353666332
40 4391.096018107652 1160.824021002903 1182.7795010934412 Accuracy: 0.89  test :  0.842  Prule Train :  0.9484764162875752  Prule test :  0.9619048344814974
45 -978.3969662071739 1118.7949977946787 1113.9030129636428 Accuracy: 0.8931  test :  0.8413  Prule Train :  0.9475567482947557  Prule test :  0.9604797902822655
50 4754.622089977236 1081.7365063251289 1105.509616775015 Accuracy: 0.8966  test :  0.842  Prule Train :  0.9411023847946925  Prule test :  0.9646257462115415
55 -1420.9607729864465 1047.845458845201 1040.7406549802686 Accuracy: 0.8994  test :  0.8407  Prule Train :  0.942021536215483  Prule test :  0.9645390070921985
60 5143.6861391692055 1016.3904074473443 1042.1088381431905 Accuracy: 0.9037  test :  0.84  Prule Train :  0.9421821712324505  Prule test :  0.9630580494404133
65 -1858.2667078297409 984.3636068190399 975.0722732798912 Accuracy: 0.908  test :  0.84  Prule Train :  0.9398746632391493  Prule test :  0.9629663891458526
70 5534.4686863814795 955.9492389326244 983.6215823645318 Accuracy: 0.9123  test :  0.842  Prule Train :  0.9363141025641025  Prule test :  0.9614767007380416
75 -2274.1341230808425 927.594964618321 916.2242940029168 Accuracy: 0.9151  test :  0.8427  Prule Train :  0.9372296461380527  Prule test :  0.9600330420282246
80 5917.969511420279 900.7574585643779 930.3473061214792 Accuracy: 0.9191  test :  0.8427  Prule Train :  0.9355334002689166  Prule test :  0.959982681840673
85 -2669.755527258186 875.0612820274862 861.7125043911952 Accuracy: 0.9229  test :  0.8427  Prule Train :  0.933234379854721  Prule test :  0.959982681840673
90 6311.818336712329 853.6641017902938 885.2231934738554 Accuracy: 0.9251  test :  0.8427  Prule Train :  0.9329648607672675  Prule test :  0.9627814651696543
95 -3041.1190594128057 830.8888288923348 815.6832335952707 Accuracy: 0.9283  test :  0.8427  Prule Train :  0.9332189319474762  Prule test :  0.9655540325846548
Resultado | acc=0.8407 | bal_acc=0.6719 | f1=0.9050 | EOdds=0.0212 | EOp=0.0073 | p-rule=96.41 | score=0.6706 | tempo=0.06 min

FAGTB caucasian_1:  75%|███████▌  | 45/60 [03:59<01:15,  5.05s/modelo]

----------------------------------------------------------------------------------------------------
Treino 106/120 | config=caucasian_1 | lambda=0.005 | n_estimators=200 | learning_rate=0.1 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1809.714413443474 1810.4894432443155 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2096.264927960864 1674.88943102669 1685.3707556664942 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2508.5597071422317 1560.4948027844248 1573.0376013201358 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 920.7277815477819 1464.1721773647364 1468.7758162724754 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3658.6935449297944 1385.4230791960076 1403.7165469206564 Accuracy: 0.8646  test :  0.8407  Prule Train :  0.9586494990928784  Prule test :  0.9625041146721728
25 -92.48223149502485 1315.2792524061838 1314.8168412487087 Accuracy: 0.8763  test :  0.842  Prule Train :  0.9558267994631631  Prule test :  0.9678357712765958
30 4050.6078219110755 1256.2491692274866 1276.502208337042 Accuracy: 0.8826  test :  0.8413  Prule Train :  0.9504076771270928  Prule test :  0.9634194528875379
35 -531.1693666961617 1203.0664617677533 1200.4106149342724 Accuracy: 0.886  test :  0.8407  Prule Train :  0.9488659488659489  Prule test :  0.9647977353666332
40 4391.096018107652 1160.824021002903 1182.7795010934412 Accuracy: 0.89  test :  0.842  Prule Train :  0.9484764162875752  Prule test :  0.9619048344814974
45 -978.3969662071739 1118.7949977946787 1113.9030129636428 Accuracy: 0.8931  test :  0.8413  Prule Train :  0.9475567482947557  Prule test :  0.9604797902822655
50 4754.622089977236 1081.7365063251289 1105.509616775015 Accuracy: 0.8966  test :  0.842  Prule Train :  0.9411023847946925  Prule test :  0.9646257462115415
55 -1420.9607729864465 1047.845458845201 1040.7406549802686 Accuracy: 0.8994  test :  0.8407  Prule Train :  0.942021536215483  Prule test :  0.9645390070921985
60 5143.6861391692055 1016.3904074473443 1042.1088381431905 Accuracy: 0.9037  test :  0.84  Prule Train :  0.9421821712324505  Prule test :  0.9630580494404133
65 -1858.2667078297409 984.3636068190399 975.0722732798912 Accuracy: 0.908  test :  0.84  Prule Train :  0.9398746632391493  Prule test :  0.9629663891458526
70 5534.4686863814795 955.9492389326244 983.6215823645318 Accuracy: 0.9123  test :  0.842  Prule Train :  0.9363141025641025  Prule test :  0.9614767007380416
75 -2274.1341230808425 927.594964618321 916.2242940029168 Accuracy: 0.9151  test :  0.8427  Prule Train :  0.9372296461380527  Prule test :  0.9600330420282246
80 5917.969511420279 900.7574585643779 930.3473061214792 Accuracy: 0.9191  test :  0.8427  Prule Train :  0.9355334002689166  Prule test :  0.959982681840673
85 -2669.755527258186 875.0612820274862 861.7125043911952 Accuracy: 0.9229  test :  0.8427  Prule Train :  0.933234379854721  Prule test :  0.959982681840673
90 6311.818336712329 853.6641017902938 885.2231934738554 Accuracy: 0.9251  test :  0.8427  Prule Train :  0.9329648607672675  Prule test :  0.9627814651696543
95 -3041.1190594128057 830.8888288923348 815.6832335952707 Accuracy: 0.9283  test :  0.8427  Prule Train :  0.9332189319474762  Prule test :  0.9655540325846548
100 6622.672521779673 811.821805600388 844.9351682092863 Accuracy: 0.9309  test :  0.8407  Prule Train :  0.93102905586982  Prule test :  0.964097691660696
105 -3329.953394156886 794.0651356497932 777.4153686790088 Accuracy: 0.9311  test :  0.8407  Prule Train :  0.9316224459627901  Prule test :  0.9640078732777205
110 6603.443723873821 776.8481604515911 809.8653790709602 Accuracy: 0.934  test :  0.8407  Prule Train :  0.9338007276547609  Prule test :  0.9668473662770657
115 -3326.882847085678 759.6296609645594 742.9952467291312 Accuracy: 0.9354  test :  0.84  Prule Train :  0.9317349317349317  Prule test :  0.9682733948408963
120 6332.170686404683 744.9169240035407 776.577777435564 Accuracy: 0.9366  test :  0.8407  Prule Train :  0.9303329149482995  Prule test :  0.9668063139396221
125 -3170.4783389809436 729.4135517799089 713.5611600850041 Accuracy: 0.938  test :  0.8393  Prule Train :  0.9320563755011056  Prule test :  0.9638721521370741
130 6119.738441761128 712.7305834822155 743.3292756910212 Accuracy: 0.9394  test :  0.8393  Prule Train :  0.92998148689467  Prule test :  0.9638721521370741
135 -3010.5954473869465 698.1953409849036 683.1423637479688 Accuracy: 0.9423  test :  0.8387  Prule Train :  0.9321720484511183  Prule test :  0.9652958923913385
140 5932.5366401621095 686.0075336632693 715.67021686408 Accuracy: 0.9429  test :  0.8393  Prule Train :  0.9321025882111854  Prule test :  0.9638721521370741
145 -2869.299994323498 672.3884932084387 658.0419932368213 Accuracy: 0.9463  test :  0.84  Prule Train :  0.929128767106732  Prule test :  0.9624050712357999
150 5761.923360408959 659.0971992945438 687.9068160965885 Accuracy: 0.9474  test :  0.8407  Prule Train :  0.9302636757182211  Prule test :  0.960987685269326
155 -2740.6699302353904 646.9522058112774 633.2488561601006 Accuracy: 0.9503  test :  0.8393  Prule Train :  0.9286251942501943  Prule test :  0.9638721521370741
160 5609.153014176072 633.4663301395087 661.5120952103891 Accuracy: 0.952  test :  0.8407  Prule Train :  0.92840796950386  Prule test :  0.9638266444577142
165 -2626.7112293804635 621.7708245272456 608.6372683803434 Accuracy: 0.9529  test :  0.84  Prule Train :  0.9276567644713858  Prule test :  0.9652524235175626
170 5469.788411889858 612.0819762911724 639.4309183506217 Accuracy: 0.954  test :  0.842  Prule Train :  0.9249423335585214  Prule test :  0.9608881485904648
175 -2522.7726495340175 601.8986677182281 589.2848044705579 Accuracy: 0.9549  test :  0.842  Prule Train :  0.9241883742210326  Prule test :  0.9608881485904648
180 5326.883926014679 593.0159294808188 619.6503491108922 Accuracy: 0.9551  test :  0.842  Prule Train :  0.9260771929182655  Prule test :  0.9608881485904648
185 -2432.131345826904 584.1195826395665 571.9589259104318 Accuracy: 0.9557  test :  0.842  Prule Train :  0.9260028801913619  Prule test :  0.9608881485904648
190 5219.457899523817 575.6865924429671 601.7838819405863 Accuracy: 0.9571  test :  0.8413  Prule Train :  0.9251726866405765  Prule test :  0.9623095807629357
195 -2345.181529009569 567.4084078817427 555.6825002366949 Accuracy: 0.9577  test :  0.8407  Prule Train :  0.9238101348193092  Prule test :  0.9637352245862885
Resultado | acc=0.8393 | bal_acc=0.6798 | f1=0.9036 | EOdds=0.0261 | EOp=0.0012 | p-rule=96.66 | score=0.6785 | tempo=0.12 min

FAGTB caucasian_1:  77%|███████▋  | 46/60 [04:06<01:19,  5.65s/modelo]

----------------------------------------------------------------------------------------------------
Treino 107/120 | config=caucasian_1 | lambda=0.005 | n_estimators=100 | learning_rate=0.1 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1809.714413443474 1810.4894432443155 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2096.264927960864 1674.88943102669 1685.3707556664942 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2508.5597071422317 1560.4948027844248 1573.0376013201358 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 920.7277815477819 1464.1721773647364 1468.7758162724754 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3658.6935449297944 1385.4230791960076 1403.7165469206564 Accuracy: 0.8646  test :  0.8407  Prule Train :  0.9586494990928784  Prule test :  0.9625041146721728
25 -92.48223149502485 1315.2792524061838 1314.8168412487087 Accuracy: 0.8763  test :  0.842  Prule Train :  0.9558267994631631  Prule test :  0.9678357712765958
30 4050.6078219110755 1256.2491692274866 1276.502208337042 Accuracy: 0.8826  test :  0.8413  Prule Train :  0.9504076771270928  Prule test :  0.9634194528875379
35 -531.1693666961617 1203.0664617677533 1200.4106149342724 Accuracy: 0.886  test :  0.8407  Prule Train :  0.9488659488659489  Prule test :  0.9647977353666332
40 4391.096018107652 1160.824021002903 1182.7795010934412 Accuracy: 0.89  test :  0.842  Prule Train :  0.9484764162875752  Prule test :  0.9619048344814974
45 -978.3969662071739 1118.7949977946787 1113.9030129636428 Accuracy: 0.8931  test :  0.8413  Prule Train :  0.9475567482947557  Prule test :  0.9604797902822655
50 4754.622089977236 1081.7365063251289 1105.509616775015 Accuracy: 0.8966  test :  0.842  Prule Train :  0.9411023847946925  Prule test :  0.9646257462115415
55 -1420.9607729864465 1047.845458845201 1040.7406549802686 Accuracy: 0.8994  test :  0.8407  Prule Train :  0.942021536215483  Prule test :  0.9645390070921985
60 5143.6861391692055 1016.3904074473443 1042.1088381431905 Accuracy: 0.9037  test :  0.84  Prule Train :  0.9421821712324505  Prule test :  0.9630580494404133
65 -1858.2667078297409 984.3636068190399 975.0722732798912 Accuracy: 0.908  test :  0.84  Prule Train :  0.9398746632391493  Prule test :  0.9629663891458526
70 5534.4686863814795 955.9492389326244 983.6215823645318 Accuracy: 0.9123  test :  0.842  Prule Train :  0.9363141025641025  Prule test :  0.9614767007380416
75 -2274.1341230808425 927.594964618321 916.2242940029168 Accuracy: 0.9151  test :  0.8427  Prule Train :  0.9372296461380527  Prule test :  0.9600330420282246
80 5917.969511420279 900.7574585643779 930.3473061214792 Accuracy: 0.9191  test :  0.8427  Prule Train :  0.9355334002689166  Prule test :  0.959982681840673
85 -2669.755527258186 875.0612820274862 861.7125043911952 Accuracy: 0.9229  test :  0.8427  Prule Train :  0.933234379854721  Prule test :  0.959982681840673
90 6311.818336712329 853.6641017902938 885.2231934738554 Accuracy: 0.9251  test :  0.8427  Prule Train :  0.9329648607672675  Prule test :  0.9627814651696543
95 -3041.1190594128057 830.8888288923348 815.6832335952707 Accuracy: 0.9283  test :  0.8427  Prule Train :  0.9332189319474762  Prule test :  0.9655540325846548
Resultado | acc=0.8407 | bal_acc=0.6719 | f1=0.9050 | EOdds=0.0212 | EOp=0.0073 | p-rule=96.41 | score=0.6706 | tempo=0.06 min

FAGTB caucasian_1:  78%|███████▊  | 47/60 [04:10<01:05,  5.06s/modelo]

----------------------------------------------------------------------------------------------------
Treino 108/120 | config=caucasian_1 | lambda=0.005 | n_estimators=200 | learning_rate=0.1 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1809.714413443474 1810.4894432443155 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2096.264927960864 1674.88943102669 1685.3707556664942 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2508.5597071422317 1560.4948027844248 1573.0376013201358 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 920.7277815477819 1464.1721773647364 1468.7758162724754 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3658.6935449297944 1385.4230791960076 1403.7165469206564 Accuracy: 0.8646  test :  0.8407  Prule Train :  0.9586494990928784  Prule test :  0.9625041146721728
25 -92.48223149502485 1315.2792524061838 1314.8168412487087 Accuracy: 0.8763  test :  0.842  Prule Train :  0.9558267994631631  Prule test :  0.9678357712765958
30 4050.6078219110755 1256.2491692274866 1276.502208337042 Accuracy: 0.8826  test :  0.8413  Prule Train :  0.9504076771270928  Prule test :  0.9634194528875379
35 -531.1693666961617 1203.0664617677533 1200.4106149342724 Accuracy: 0.886  test :  0.8407  Prule Train :  0.9488659488659489  Prule test :  0.9647977353666332
40 4391.096018107652 1160.824021002903 1182.7795010934412 Accuracy: 0.89  test :  0.842  Prule Train :  0.9484764162875752  Prule test :  0.9619048344814974
45 -978.3969662071739 1118.7949977946787 1113.9030129636428 Accuracy: 0.8931  test :  0.8413  Prule Train :  0.9475567482947557  Prule test :  0.9604797902822655
50 4754.622089977236 1081.7365063251289 1105.509616775015 Accuracy: 0.8966  test :  0.842  Prule Train :  0.9411023847946925  Prule test :  0.9646257462115415
55 -1420.9607729864465 1047.845458845201 1040.7406549802686 Accuracy: 0.8994  test :  0.8407  Prule Train :  0.942021536215483  Prule test :  0.9645390070921985
60 5143.6861391692055 1016.3904074473443 1042.1088381431905 Accuracy: 0.9037  test :  0.84  Prule Train :  0.9421821712324505  Prule test :  0.9630580494404133
65 -1858.2667078297409 984.3636068190399 975.0722732798912 Accuracy: 0.908  test :  0.84  Prule Train :  0.9398746632391493  Prule test :  0.9629663891458526
70 5534.4686863814795 955.9492389326244 983.6215823645318 Accuracy: 0.9123  test :  0.842  Prule Train :  0.9363141025641025  Prule test :  0.9614767007380416
75 -2274.1341230808425 927.594964618321 916.2242940029168 Accuracy: 0.9151  test :  0.8427  Prule Train :  0.9372296461380527  Prule test :  0.9600330420282246
80 5917.969511420279 900.7574585643779 930.3473061214792 Accuracy: 0.9191  test :  0.8427  Prule Train :  0.9355334002689166  Prule test :  0.959982681840673
85 -2669.755527258186 875.0612820274862 861.7125043911952 Accuracy: 0.9229  test :  0.8427  Prule Train :  0.933234379854721  Prule test :  0.959982681840673
90 6311.818336712329 853.6641017902938 885.2231934738554 Accuracy: 0.9251  test :  0.8427  Prule Train :  0.9329648607672675  Prule test :  0.9627814651696543
95 -3041.1190594128057 830.8888288923348 815.6832335952707 Accuracy: 0.9283  test :  0.8427  Prule Train :  0.9332189319474762  Prule test :  0.9655540325846548
100 6622.672521779673 811.821805600388 844.9351682092863 Accuracy: 0.9309  test :  0.8407  Prule Train :  0.93102905586982  Prule test :  0.964097691660696
105 -3329.953394156886 794.0651356497932 777.4153686790088 Accuracy: 0.9311  test :  0.8407  Prule Train :  0.9316224459627901  Prule test :  0.9640078732777205
110 6603.443723873821 776.8481604515911 809.8653790709602 Accuracy: 0.934  test :  0.8407  Prule Train :  0.9338007276547609  Prule test :  0.9668473662770657
115 -3326.882847085678 759.6296609645594 742.9952467291312 Accuracy: 0.9354  test :  0.84  Prule Train :  0.9317349317349317  Prule test :  0.9682733948408963
120 6332.170686404683 744.9169240035407 776.577777435564 Accuracy: 0.9366  test :  0.8407  Prule Train :  0.9303329149482995  Prule test :  0.9668063139396221
125 -3170.4783389809436 729.4135517799089 713.5611600850041 Accuracy: 0.938  test :  0.8393  Prule Train :  0.9320563755011056  Prule test :  0.9638721521370741
130 6119.738441761128 712.7305834822155 743.3292756910212 Accuracy: 0.9394  test :  0.8393  Prule Train :  0.92998148689467  Prule test :  0.9638721521370741
135 -3010.5954473869465 698.1953409849036 683.1423637479688 Accuracy: 0.9423  test :  0.8387  Prule Train :  0.9321720484511183  Prule test :  0.9652958923913385
140 5932.5366401621095 686.0075336632693 715.67021686408 Accuracy: 0.9429  test :  0.8393  Prule Train :  0.9321025882111854  Prule test :  0.9638721521370741
145 -2869.299994323498 672.3884932084387 658.0419932368213 Accuracy: 0.9463  test :  0.84  Prule Train :  0.929128767106732  Prule test :  0.9624050712357999
150 5761.923360408959 659.0971992945438 687.9068160965885 Accuracy: 0.9474  test :  0.8407  Prule Train :  0.9302636757182211  Prule test :  0.960987685269326
155 -2740.6699302353904 646.9522058112774 633.2488561601006 Accuracy: 0.9503  test :  0.8393  Prule Train :  0.9286251942501943  Prule test :  0.9638721521370741
160 5609.153014176072 633.4663301395087 661.5120952103891 Accuracy: 0.952  test :  0.8407  Prule Train :  0.92840796950386  Prule test :  0.9638266444577142
165 -2626.7112293804635 621.7708245272456 608.6372683803434 Accuracy: 0.9529  test :  0.84  Prule Train :  0.9276567644713858  Prule test :  0.9652524235175626
170 5469.788411889858 612.0819762911724 639.4309183506217 Accuracy: 0.954  test :  0.842  Prule Train :  0.9249423335585214  Prule test :  0.9608881485904648
175 -2522.7726495340175 601.8986677182281 589.2848044705579 Accuracy: 0.9549  test :  0.842  Prule Train :  0.9241883742210326  Prule test :  0.9608881485904648
180 5326.883926014679 593.0159294808188 619.6503491108922 Accuracy: 0.9551  test :  0.842  Prule Train :  0.9260771929182655  Prule test :  0.9608881485904648
185 -2432.131345826904 584.1195826395665 571.9589259104318 Accuracy: 0.9557  test :  0.842  Prule Train :  0.9260028801913619  Prule test :  0.9608881485904648
190 5219.457899523817 575.6865924429671 601.7838819405863 Accuracy: 0.9571  test :  0.8413  Prule Train :  0.9251726866405765  Prule test :  0.9623095807629357
195 -2345.181529009569 567.4084078817427 555.6825002366949 Accuracy: 0.9577  test :  0.8407  Prule Train :  0.9238101348193092  Prule test :  0.9637352245862885
Resultado | acc=0.8393 | bal_acc=0.6798 | f1=0.9036 | EOdds=0.0261 | EOp=0.0012 | p-rule=96.66 | score=0.6785 | tempo=0.12 min

FAGTB caucasian_1:  80%|████████  | 48/60 [04:17<01:07,  5.65s/modelo]

----------------------------------------------------------------------------------------------------
Treino 109/120 | config=caucasian_1 | lambda=0.01 | n_estimators=100 | learning_rate=0.03 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1830.377670308327 1831.9277299100097 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2148.1912926140967 1787.7954596674779 1809.277372593619 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2374.845766427118 1747.6729200537936 1771.4213777180648 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1232.2086243787448 1707.8693342815964 1720.1914205253836 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3292.0305848845437 1671.2063670318978 1704.1266728807432 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 363.9694667215231 1635.2498848056935 1638.8895794729087 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3672.462157276103 1601.673945431488 1638.3985670042493 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 173.5457637032039 1569.6043362327355 1571.3397938697676 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 3866.292479178128 1539.4762174693724 1578.1391422611537 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 -47.75341930669712 1510.3729002648568 1509.8953660717898 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 4091.9067294998586 1483.7983741162525 1524.717441411251 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -301.74468228209673 1457.7099866338062 1454.6925398109854 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 4342.412411251029 1434.021495065161 1477.4456191776712 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 -581.2357588621929 1410.6127512839903 1404.8003936953685 Accuracy: 0.7817  test :  0.7813  Prule Train :  0.9999777750759242  Prule test :  1.0
70 4613.358802479437 1388.5948452611979 1434.7284332859922 Accuracy: 0.8646  test :  0.8367  Prule Train :  0.961046951448871  Prule test :  0.9653020917497082
75 -880.8313875223773 1367.3236370392974 1358.5153231640736 Accuracy: 0.8666  test :  0.8393  Prule Train :  0.9602805047516586  Prule test :  0.9652192179575669
80 4900.52954826086 1347.264143384842 1396.2694388674508 Accuracy: 0.8711  test :  0.8407  Prule Train :  0.9562814119776144  Prule test :  0.9679496825062445
85 -1196.1088817931877 1327.2337346867298 1315.272645868798 Accuracy: 0.8763  test :  0.842  Prule Train :  0.9570368988197974  Prule test :  0.9678357712765958
90 5200.567147973245 1309.0838743812933 1361.089545861026 Accuracy: 0.8803  test :  0.8407  Prule Train :  0.9542562060810237  Prule test :  0.9621841755319148
95 -1522.9579124252293 1291.2196036717492 1275.990024547497 Accuracy: 0.8809  test :  0.8413  Prule Train :  0.9542042457441119  Prule test :  0.9607712765957447
Resultado | acc=0.8420 | bal_acc=0.6530 | f1=0.9072 | EOdds=0.0509 | EOp=0.0060 | p-rule=96.21 | score=0.6503 | tempo=0.06 min

FAGTB caucasian_1:  82%|████████▏ | 49/60 [04:21<00:55,  5.06s/modelo]

----------------------------------------------------------------------------------------------------
Treino 110/120 | config=caucasian_1 | lambda=0.01 | n_estimators=200 | learning_rate=0.03 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1830.377670308327 1831.9277299100097 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2148.1912926140967 1787.7954596674779 1809.277372593619 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2374.845766427118 1747.6729200537936 1771.4213777180648 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1232.2086243787448 1707.8693342815964 1720.1914205253836 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3292.0305848845437 1671.2063670318978 1704.1266728807432 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 363.9694667215231 1635.2498848056935 1638.8895794729087 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3672.462157276103 1601.673945431488 1638.3985670042493 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 173.5457637032039 1569.6043362327355 1571.3397938697676 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 3866.292479178128 1539.4762174693724 1578.1391422611537 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 -47.75341930669712 1510.3729002648568 1509.8953660717898 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 4091.9067294998586 1483.7983741162525 1524.717441411251 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -301.74468228209673 1457.7099866338062 1454.6925398109854 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 4342.412411251029 1434.021495065161 1477.4456191776712 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 -581.2357588621929 1410.6127512839903 1404.8003936953685 Accuracy: 0.7817  test :  0.7813  Prule Train :  0.9999777750759242  Prule test :  1.0
70 4613.358802479437 1388.5948452611979 1434.7284332859922 Accuracy: 0.8646  test :  0.8367  Prule Train :  0.961046951448871  Prule test :  0.9653020917497082
75 -880.8313875223773 1367.3236370392974 1358.5153231640736 Accuracy: 0.8666  test :  0.8393  Prule Train :  0.9602805047516586  Prule test :  0.9652192179575669
80 4900.52954826086 1347.264143384842 1396.2694388674508 Accuracy: 0.8711  test :  0.8407  Prule Train :  0.9562814119776144  Prule test :  0.9679496825062445
85 -1196.1088817931877 1327.2337346867298 1315.272645868798 Accuracy: 0.8763  test :  0.842  Prule Train :  0.9570368988197974  Prule test :  0.9678357712765958
90 5200.567147973245 1309.0838743812933 1361.089545861026 Accuracy: 0.8803  test :  0.8407  Prule Train :  0.9542562060810237  Prule test :  0.9621841755319148
95 -1522.9579124252293 1291.2196036717492 1275.990024547497 Accuracy: 0.8809  test :  0.8413  Prule Train :  0.9542042457441119  Prule test :  0.9607712765957447
100 5510.738324584524 1274.9578427267506 1330.0652259725957 Accuracy: 0.882  test :  0.842  Prule Train :  0.9541001350873379  Prule test :  0.9621379498199208
105 -1857.6888124057102 1259.7934269278644 1241.216538803807 Accuracy: 0.8826  test :  0.8413  Prule Train :  0.9528330698348979  Prule test :  0.963508516700006
110 5833.0271857758125 1245.5516855411456 1303.8819573989035 Accuracy: 0.8849  test :  0.8413  Prule Train :  0.9514047206354899  Prule test :  0.963508516700006
115 -2199.0256536749694 1231.5471382501107 1209.556881713361 Accuracy: 0.8857  test :  0.842  Prule Train :  0.949500641808334  Prule test :  0.964840425531915
120 6161.28496702076 1217.9025670012563 1279.515416671464 Accuracy: 0.8871  test :  0.8413  Prule Train :  0.9499711297876435  Prule test :  0.9662207408760237
125 -2544.6985803148214 1205.4030253587239 1179.9560395555754 Accuracy: 0.888  test :  0.8427  Prule Train :  0.9492800141514951  Prule test :  0.9661390762843799
130 6495.179015241523 1193.8459847516624 1258.7977749040776 Accuracy: 0.8889  test :  0.8433  Prule Train :  0.9498063211298506  Prule test :  0.9675272071411104
135 -2894.2874115154987 1182.5909301448455 1153.6480560296905 Accuracy: 0.8891  test :  0.8433  Prule Train :  0.94916929475753  Prule test :  0.9703154699858973
140 6835.038869201654 1171.4516483986226 1239.8020370906393 Accuracy: 0.89  test :  0.8433  Prule Train :  0.9496961116593016  Prule test :  0.9674489545649643
145 -3245.075291974607 1160.364362552059 1127.9136096323127 Accuracy: 0.8909  test :  0.8433  Prule Train :  0.9502242229514956  Prule test :  0.9674489545649643
150 7177.774038968302 1149.8146603717673 1221.5924007614503 Accuracy: 0.8909  test :  0.8433  Prule Train :  0.9502242229514956  Prule test :  0.9674489545649643
155 -3595.133589817424 1138.7378683302059 1102.7865324320314 Accuracy: 0.8923  test :  0.8427  Prule Train :  0.9506989420835577  Prule test :  0.9660156968544975
160 7518.682007771273 1127.6101164896645 1202.796936567377 Accuracy: 0.8934  test :  0.8427  Prule Train :  0.9481398601398601  Prule test :  0.9660156968544975
165 -3942.95774463031 1116.1182962860696 1076.6887188397666 Accuracy: 0.8943  test :  0.842  Prule Train :  0.9462205486820872  Prule test :  0.964582439144031
170 7859.429878115645 1105.66535917085 1184.2596579520064 Accuracy: 0.8943  test :  0.8413  Prule Train :  0.9462205486820872  Prule test :  0.9659743329956094
175 -4286.031157445195 1095.08080001894 1052.2204884444877 Accuracy: 0.8949  test :  0.842  Prule Train :  0.9461630323699289  Prule test :  0.9616683552853766
180 8189.816428055969 1086.0671701543072 1167.965334434867 Accuracy: 0.896  test :  0.8433  Prule Train :  0.9472727560327807  Prule test :  0.9644517658650738
185 -4620.24117033714 1077.0547253678237 1030.8523136644524 Accuracy: 0.8974  test :  0.8427  Prule Train :  0.9465165265041731  Prule test :  0.968657224146462
190 8484.818740749377 1068.6446290868482 1153.4928164943422 Accuracy: 0.8991  test :  0.842  Prule Train :  0.9475733760563481  Prule test :  0.9700672055498775
195 -4922.64009745966 1059.289015175292 1010.0626142006953 Accuracy: 0.9003  test :  0.842  Prule Train :  0.9474592363619023  Prule test :  0.9700672055498775
Resultado | acc=0.8420 | bal_acc=0.6673 | f1=0.9063 | EOdds=0.0198 | EOp=0.0017 | p-rule=97.01 | score=0.6662 | tempo=0.12 min

FAGTB caucasian_1:  83%|████████▎ | 50/60 [04:28<00:56,  5.65s/modelo]

----------------------------------------------------------------------------------------------------
Treino 111/120 | config=caucasian_1 | lambda=0.01 | n_estimators=100 | learning_rate=0.03 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1830.377670308327 1831.9277299100097 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2148.1912926140967 1787.7954596674779 1809.277372593619 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2374.845766427118 1747.6729200537936 1771.4213777180648 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1232.2086243787448 1707.8693342815964 1720.1914205253836 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3292.0305848845437 1671.2063670318978 1704.1266728807432 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 363.9694667215231 1635.2498848056935 1638.8895794729087 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3672.462157276103 1601.673945431488 1638.3985670042493 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 173.5457637032039 1569.6043362327355 1571.3397938697676 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 3866.292479178128 1539.4762174693724 1578.1391422611537 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 -47.75341930669712 1510.3729002648568 1509.8953660717898 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 4091.9067294998586 1483.7983741162525 1524.717441411251 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -301.74468228209673 1457.7099866338062 1454.6925398109854 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 4342.412411251029 1434.021495065161 1477.4456191776712 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 -581.2357588621929 1410.6127512839903 1404.8003936953685 Accuracy: 0.7817  test :  0.7813  Prule Train :  0.9999777750759242  Prule test :  1.0
70 4613.358802479437 1388.5948452611979 1434.7284332859922 Accuracy: 0.8646  test :  0.8367  Prule Train :  0.961046951448871  Prule test :  0.9653020917497082
75 -880.8313875223773 1367.3236370392974 1358.5153231640736 Accuracy: 0.8666  test :  0.8393  Prule Train :  0.9602805047516586  Prule test :  0.9652192179575669
80 4900.52954826086 1347.264143384842 1396.2694388674508 Accuracy: 0.8711  test :  0.8407  Prule Train :  0.9562814119776144  Prule test :  0.9679496825062445
85 -1196.1088817931877 1327.2337346867298 1315.272645868798 Accuracy: 0.8763  test :  0.842  Prule Train :  0.9570368988197974  Prule test :  0.9678357712765958
90 5200.567147973245 1309.0838743812933 1361.089545861026 Accuracy: 0.8803  test :  0.8407  Prule Train :  0.9542562060810237  Prule test :  0.9621841755319148
95 -1522.9579124252293 1291.2196036717492 1275.990024547497 Accuracy: 0.8809  test :  0.8413  Prule Train :  0.9542042457441119  Prule test :  0.9607712765957447
Resultado | acc=0.8420 | bal_acc=0.6530 | f1=0.9072 | EOdds=0.0509 | EOp=0.0060 | p-rule=96.21 | score=0.6503 | tempo=0.06 min

FAGTB caucasian_1:  85%|████████▌ | 51/60 [04:31<00:45,  5.05s/modelo]

----------------------------------------------------------------------------------------------------
Treino 112/120 | config=caucasian_1 | lambda=0.01 | n_estimators=200 | learning_rate=0.03 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1830.377670308327 1831.9277299100097 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2148.1912926140967 1787.7954596674779 1809.277372593619 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2374.845766427118 1747.6729200537936 1771.4213777180648 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1232.2086243787448 1707.8693342815964 1720.1914205253836 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3292.0305848845437 1671.2063670318978 1704.1266728807432 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 363.9694667215231 1635.2498848056935 1638.8895794729087 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3672.462157276103 1601.673945431488 1638.3985670042493 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 173.5457637032039 1569.6043362327355 1571.3397938697676 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 3866.292479178128 1539.4762174693724 1578.1391422611537 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
45 -47.75341930669712 1510.3729002648568 1509.8953660717898 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
50 4091.9067294998586 1483.7983741162525 1524.717441411251 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
55 -301.74468228209673 1457.7099866338062 1454.6925398109854 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
60 4342.412411251029 1434.021495065161 1477.4456191776712 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
65 -581.2357588621929 1410.6127512839903 1404.8003936953685 Accuracy: 0.7817  test :  0.7813  Prule Train :  0.9999777750759242  Prule test :  1.0
70 4613.358802479437 1388.5948452611979 1434.7284332859922 Accuracy: 0.8646  test :  0.8367  Prule Train :  0.961046951448871  Prule test :  0.9653020917497082
75 -880.8313875223773 1367.3236370392974 1358.5153231640736 Accuracy: 0.8666  test :  0.8393  Prule Train :  0.9602805047516586  Prule test :  0.9652192179575669
80 4900.52954826086 1347.264143384842 1396.2694388674508 Accuracy: 0.8711  test :  0.8407  Prule Train :  0.9562814119776144  Prule test :  0.9679496825062445
85 -1196.1088817931877 1327.2337346867298 1315.272645868798 Accuracy: 0.8763  test :  0.842  Prule Train :  0.9570368988197974  Prule test :  0.9678357712765958
90 5200.567147973245 1309.0838743812933 1361.089545861026 Accuracy: 0.8803  test :  0.8407  Prule Train :  0.9542562060810237  Prule test :  0.9621841755319148
95 -1522.9579124252293 1291.2196036717492 1275.990024547497 Accuracy: 0.8809  test :  0.8413  Prule Train :  0.9542042457441119  Prule test :  0.9607712765957447
100 5510.738324584524 1274.9578427267506 1330.0652259725957 Accuracy: 0.882  test :  0.842  Prule Train :  0.9541001350873379  Prule test :  0.9621379498199208
105 -1857.6888124057102 1259.7934269278644 1241.216538803807 Accuracy: 0.8826  test :  0.8413  Prule Train :  0.9528330698348979  Prule test :  0.963508516700006
110 5833.0271857758125 1245.5516855411456 1303.8819573989035 Accuracy: 0.8849  test :  0.8413  Prule Train :  0.9514047206354899  Prule test :  0.963508516700006
115 -2199.0256536749694 1231.5471382501107 1209.556881713361 Accuracy: 0.8857  test :  0.842  Prule Train :  0.949500641808334  Prule test :  0.964840425531915
120 6161.28496702076 1217.9025670012563 1279.515416671464 Accuracy: 0.8871  test :  0.8413  Prule Train :  0.9499711297876435  Prule test :  0.9662207408760237
125 -2544.6985803148214 1205.4030253587239 1179.9560395555754 Accuracy: 0.888  test :  0.8427  Prule Train :  0.9492800141514951  Prule test :  0.9661390762843799
130 6495.179015241523 1193.8459847516624 1258.7977749040776 Accuracy: 0.8889  test :  0.8433  Prule Train :  0.9498063211298506  Prule test :  0.9675272071411104
135 -2894.2874115154987 1182.5909301448455 1153.6480560296905 Accuracy: 0.8891  test :  0.8433  Prule Train :  0.94916929475753  Prule test :  0.9703154699858973
140 6835.038869201654 1171.4516483986226 1239.8020370906393 Accuracy: 0.89  test :  0.8433  Prule Train :  0.9496961116593016  Prule test :  0.9674489545649643
145 -3245.075291974607 1160.364362552059 1127.9136096323127 Accuracy: 0.8909  test :  0.8433  Prule Train :  0.9502242229514956  Prule test :  0.9674489545649643
150 7177.774038968302 1149.8146603717673 1221.5924007614503 Accuracy: 0.8909  test :  0.8433  Prule Train :  0.9502242229514956  Prule test :  0.9674489545649643
155 -3595.133589817424 1138.7378683302059 1102.7865324320314 Accuracy: 0.8923  test :  0.8427  Prule Train :  0.9506989420835577  Prule test :  0.9660156968544975
160 7518.682007771273 1127.6101164896645 1202.796936567377 Accuracy: 0.8934  test :  0.8427  Prule Train :  0.9481398601398601  Prule test :  0.9660156968544975
165 -3942.95774463031 1116.1182962860696 1076.6887188397666 Accuracy: 0.8943  test :  0.842  Prule Train :  0.9462205486820872  Prule test :  0.964582439144031
170 7859.429878115645 1105.66535917085 1184.2596579520064 Accuracy: 0.8943  test :  0.8413  Prule Train :  0.9462205486820872  Prule test :  0.9659743329956094
175 -4286.031157445195 1095.08080001894 1052.2204884444877 Accuracy: 0.8949  test :  0.842  Prule Train :  0.9461630323699289  Prule test :  0.9616683552853766
180 8189.816428055969 1086.0671701543072 1167.965334434867 Accuracy: 0.896  test :  0.8433  Prule Train :  0.9472727560327807  Prule test :  0.9644517658650738
185 -4620.24117033714 1077.0547253678237 1030.8523136644524 Accuracy: 0.8974  test :  0.8427  Prule Train :  0.9465165265041731  Prule test :  0.968657224146462
190 8484.818740749377 1068.6446290868482 1153.4928164943422 Accuracy: 0.8991  test :  0.842  Prule Train :  0.9475733760563481  Prule test :  0.9700672055498775
195 -4922.64009745966 1059.289015175292 1010.0626142006953 Accuracy: 0.9003  test :  0.842  Prule Train :  0.9474592363619023  Prule test :  0.9700672055498775
Resultado | acc=0.8420 | bal_acc=0.6673 | f1=0.9063 | EOdds=0.0198 | EOp=0.0017 | p-rule=97.01 | score=0.6662 | tempo=0.12 min

FAGTB caucasian_1:  87%|████████▋ | 52/60 [04:38<00:45,  5.65s/modelo]

----------------------------------------------------------------------------------------------------
Treino 113/120 | config=caucasian_1 | lambda=0.01 | n_estimators=100 | learning_rate=0.05 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1824.5866782961893 1826.1367378978723 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2133.0385525077954 1754.8137838333362 1776.1441693584143 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2416.492254797496 1689.4670762458418 1713.6319987938168 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1140.8813912816613 1628.8676809962744 1640.276494909091 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3424.4319844961633 1574.429158118202 1608.6734779631636 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 207.670863580441 1524.3026871879292 1526.3793958237338 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3829.441144143989 1479.0187055033655 1517.3131169448054 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -62.59855343678346 1436.048841346992 1435.422855812624 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 4086.532677517866 1397.493161365649 1438.3584881408274 Accuracy: 0.8489  test :  0.828  Prule Train :  0.9617316803157512  Prule test :  0.9725152610679786
45 -380.37950795932977 1361.6099705180613 1357.8061754384678 Accuracy: 0.8669  test :  0.84  Prule Train :  0.9584549584549584  Prule test :  0.9638162830477448
50 4373.188710793114 1328.9751455585665 1372.7070326664975 Accuracy: 0.8754  test :  0.842  Prule Train :  0.9565072520856893  Prule test :  0.9678738494039536
55 -727.3530887024082 1298.1286615281938 1290.8551306411696 Accuracy: 0.8797  test :  0.8407  Prule Train :  0.9543081032442735  Prule test :  0.9650520597555454
60 4681.451639025503 1269.814746909894 1316.6292633001488 Accuracy: 0.882  test :  0.8413  Prule Train :  0.9528859285253923  Prule test :  0.963508516700006
65 -1090.9411737624844 1244.3173128597973 1233.4079011221725 Accuracy: 0.8846  test :  0.842  Prule Train :  0.952039413577875  Prule test :  0.9620915924107414
70 5007.97358771092 1220.6879382227264 1270.7676740998356 Accuracy: 0.8866  test :  0.842  Prule Train :  0.9488105053163085  Prule test :  0.964840425531915
75 -1463.9101504776345 1196.8144013560166 1182.1752998512402 Accuracy: 0.8877  test :  0.8427  Prule Train :  0.9486994147544607  Prule test :  0.9633747298572427
80 5343.023705559346 1176.7814008168489 1230.2116378724422 Accuracy: 0.8891  test :  0.844  Prule Train :  0.94916929475753  Prule test :  0.9633298786807294
85 -1840.8153890195056 1157.7111460731821 1139.302992182987 Accuracy: 0.8909  test :  0.844  Prule Train :  0.9502242229514956  Prule test :  0.9633298786807294
90 5690.774161704315 1138.1842326242133 1195.0919742412566 Accuracy: 0.8914  test :  0.844  Prule Train :  0.9489470398561308  Prule test :  0.9660980679872828
95 -2218.5769425965173 1119.1608904775799 1096.9751210516147 Accuracy: 0.892  test :  0.842  Prule Train :  0.9488913053756324  Prule test :  0.9618106505258011
Resultado | acc=0.8433 | bal_acc=0.6626 | f1=0.9075 | EOdds=0.0308 | EOp=0.0098 | p-rule=96.18 | score=0.6608 | tempo=0.06 min

FAGTB caucasian_1:  88%|████████▊ | 53/60 [04:42<00:35,  5.05s/modelo]

----------------------------------------------------------------------------------------------------
Treino 114/120 | config=caucasian_1 | lambda=0.01 | n_estimators=200 | learning_rate=0.05 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1824.5866782961893 1826.1367378978723 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2133.0385525077954 1754.8137838333362 1776.1441693584143 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2416.492254797496 1689.4670762458418 1713.6319987938168 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1140.8813912816613 1628.8676809962744 1640.276494909091 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3424.4319844961633 1574.429158118202 1608.6734779631636 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 207.670863580441 1524.3026871879292 1526.3793958237338 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3829.441144143989 1479.0187055033655 1517.3131169448054 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -62.59855343678346 1436.048841346992 1435.422855812624 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 4086.532677517866 1397.493161365649 1438.3584881408274 Accuracy: 0.8489  test :  0.828  Prule Train :  0.9617316803157512  Prule test :  0.9725152610679786
45 -380.37950795932977 1361.6099705180613 1357.8061754384678 Accuracy: 0.8669  test :  0.84  Prule Train :  0.9584549584549584  Prule test :  0.9638162830477448
50 4373.188710793114 1328.9751455585665 1372.7070326664975 Accuracy: 0.8754  test :  0.842  Prule Train :  0.9565072520856893  Prule test :  0.9678738494039536
55 -727.3530887024082 1298.1286615281938 1290.8551306411696 Accuracy: 0.8797  test :  0.8407  Prule Train :  0.9543081032442735  Prule test :  0.9650520597555454
60 4681.451639025503 1269.814746909894 1316.6292633001488 Accuracy: 0.882  test :  0.8413  Prule Train :  0.9528859285253923  Prule test :  0.963508516700006
65 -1090.9411737624844 1244.3173128597973 1233.4079011221725 Accuracy: 0.8846  test :  0.842  Prule Train :  0.952039413577875  Prule test :  0.9620915924107414
70 5007.97358771092 1220.6879382227264 1270.7676740998356 Accuracy: 0.8866  test :  0.842  Prule Train :  0.9488105053163085  Prule test :  0.964840425531915
75 -1463.9101504776345 1196.8144013560166 1182.1752998512402 Accuracy: 0.8877  test :  0.8427  Prule Train :  0.9486994147544607  Prule test :  0.9633747298572427
80 5343.023705559346 1176.7814008168489 1230.2116378724422 Accuracy: 0.8891  test :  0.844  Prule Train :  0.94916929475753  Prule test :  0.9633298786807294
85 -1840.8153890195056 1157.7111460731821 1139.302992182987 Accuracy: 0.8909  test :  0.844  Prule Train :  0.9502242229514956  Prule test :  0.9633298786807294
90 5690.774161704315 1138.1842326242133 1195.0919742412566 Accuracy: 0.8914  test :  0.844  Prule Train :  0.9489470398561308  Prule test :  0.9660980679872828
95 -2218.5769425965173 1119.1608904775799 1096.9751210516147 Accuracy: 0.892  test :  0.842  Prule Train :  0.9488913053756324  Prule test :  0.9618106505258011
100 6037.017297909586 1101.5728899671874 1161.9430629462831 Accuracy: 0.8929  test :  0.8433  Prule Train :  0.9494194011117087  Prule test :  0.9618106505258011
105 -2593.77799488845 1084.1360135572231 1058.1982336083386 Accuracy: 0.8946  test :  0.842  Prule Train :  0.9480271217794322  Prule test :  0.9617633552732281
110 6385.6879430059 1069.1342203101772 1132.9910997402362 Accuracy: 0.8969  test :  0.8427  Prule Train :  0.9453487084579002  Prule test :  0.9631491814335642
115 -2965.2916197311997 1052.9800333305548 1023.3271171332426 Accuracy: 0.8983  test :  0.8413  Prule Train :  0.94336527669861  Prule test :  0.9659328495879965
120 6734.737312028688 1039.7252603725956 1107.0726334928827 Accuracy: 0.9003  test :  0.8427  Prule Train :  0.9437703385723188  Prule test :  0.9658495220474869
125 -3335.160495092711 1026.4840736400745 993.1324686891475 Accuracy: 0.9026  test :  0.8427  Prule Train :  0.9435324807533244  Prule test :  0.9658495220474869
130 7086.7714875464835 1013.1064247679085 1083.9741396433733 Accuracy: 0.9054  test :  0.8433  Prule Train :  0.9444681511929334  Prule test :  0.967251335577309
135 -3696.7805597798038 1000.5732863861606 963.6054807883625 Accuracy: 0.906  test :  0.8433  Prule Train :  0.9456457922792088  Prule test :  0.967251335577309
140 7414.371428206527 988.4246089287658 1062.568323210831 Accuracy: 0.9069  test :  0.8453  Prule Train :  0.9461774180875305  Prule test :  0.968657224146462
145 -4028.899037460962 977.066394002349 936.7774036277394 Accuracy: 0.908  test :  0.8467  Prule Train :  0.9448203264568036  Prule test :  0.9657657100445324
150 7630.588726734695 964.3113913590844 1040.6172786264315 Accuracy: 0.9094  test :  0.8473  Prule Train :  0.9452929215131968  Prule test :  0.9671714825482363
155 -4256.91399924608 950.8125580155851 908.2434180231243 Accuracy: 0.9106  test :  0.8467  Prule Train :  0.9439318769312508  Prule test :  0.9628741959426027
160 7534.517598425211 938.4087422556086 1013.7539182398606 Accuracy: 0.9114  test :  0.8467  Prule Train :  0.9444636867834361  Prule test :  0.9628741959426027
165 -4254.360995123327 925.7508156506084 883.2072056993752 Accuracy: 0.9134  test :  0.8467  Prule Train :  0.942386343516287  Prule test :  0.962827898045774
170 7250.999934721276 913.8730756048667 986.3830749520794 Accuracy: 0.9137  test :  0.8473  Prule Train :  0.9429782947370887  Prule test :  0.9642314372557533
175 -4115.099302409928 901.6673437180905 860.5163506939912 Accuracy: 0.9146  test :  0.8473  Prule Train :  0.9422641050548028  Prule test :  0.9642314372557533
180 7043.480773790137 891.0687265259402 961.5035342638416 Accuracy: 0.9163  test :  0.8487  Prule Train :  0.9395874565685887  Prule test :  0.9641869855567634
185 -3962.6427239428313 879.4269319902307 839.8005047508025 Accuracy: 0.9171  test :  0.8487  Prule Train :  0.9388702340244189  Prule test :  0.9641869855567634
190 6874.518313033351 869.1252366630936 937.870419793427 Accuracy: 0.9186  test :  0.8487  Prule Train :  0.9368427542231069  Prule test :  0.9641869855567634
195 -3820.816035511036 858.9180401701261 820.7098798150157 Accuracy: 0.92  test :  0.848  Prule Train :  0.9348127193117741  Prule test :  0.9656390743904333
Resultado | acc=0.8480 | bal_acc=0.6799 | f1=0.9096 | EOdds=0.0246 | EOp=0.0034 | p-rule=96.56 | score=0.6786 | tempo=0.11 min

FAGTB caucasian_1:  90%|█████████ | 54/60 [04:49<00:33,  5.64s/modelo]

----------------------------------------------------------------------------------------------------
Treino 115/120 | config=caucasian_1 | lambda=0.01 | n_estimators=100 | learning_rate=0.05 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1824.5866782961893 1826.1367378978723 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2133.0385525077954 1754.8137838333362 1776.1441693584143 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2416.492254797496 1689.4670762458418 1713.6319987938168 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1140.8813912816613 1628.8676809962744 1640.276494909091 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3424.4319844961633 1574.429158118202 1608.6734779631636 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 207.670863580441 1524.3026871879292 1526.3793958237338 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3829.441144143989 1479.0187055033655 1517.3131169448054 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -62.59855343678346 1436.048841346992 1435.422855812624 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 4086.532677517866 1397.493161365649 1438.3584881408274 Accuracy: 0.8489  test :  0.828  Prule Train :  0.9617316803157512  Prule test :  0.9725152610679786
45 -380.37950795932977 1361.6099705180613 1357.8061754384678 Accuracy: 0.8669  test :  0.84  Prule Train :  0.9584549584549584  Prule test :  0.9638162830477448
50 4373.188710793114 1328.9751455585665 1372.7070326664975 Accuracy: 0.8754  test :  0.842  Prule Train :  0.9565072520856893  Prule test :  0.9678738494039536
55 -727.3530887024082 1298.1286615281938 1290.8551306411696 Accuracy: 0.8797  test :  0.8407  Prule Train :  0.9543081032442735  Prule test :  0.9650520597555454
60 4681.451639025503 1269.814746909894 1316.6292633001488 Accuracy: 0.882  test :  0.8413  Prule Train :  0.9528859285253923  Prule test :  0.963508516700006
65 -1090.9411737624844 1244.3173128597973 1233.4079011221725 Accuracy: 0.8846  test :  0.842  Prule Train :  0.952039413577875  Prule test :  0.9620915924107414
70 5007.97358771092 1220.6879382227264 1270.7676740998356 Accuracy: 0.8866  test :  0.842  Prule Train :  0.9488105053163085  Prule test :  0.964840425531915
75 -1463.9101504776345 1196.8144013560166 1182.1752998512402 Accuracy: 0.8877  test :  0.8427  Prule Train :  0.9486994147544607  Prule test :  0.9633747298572427
80 5343.023705559346 1176.7814008168489 1230.2116378724422 Accuracy: 0.8891  test :  0.844  Prule Train :  0.94916929475753  Prule test :  0.9633298786807294
85 -1840.8153890195056 1157.7111460731821 1139.302992182987 Accuracy: 0.8909  test :  0.844  Prule Train :  0.9502242229514956  Prule test :  0.9633298786807294
90 5690.774161704315 1138.1842326242133 1195.0919742412566 Accuracy: 0.8914  test :  0.844  Prule Train :  0.9489470398561308  Prule test :  0.9660980679872828
95 -2218.5769425965173 1119.1608904775799 1096.9751210516147 Accuracy: 0.892  test :  0.842  Prule Train :  0.9488913053756324  Prule test :  0.9618106505258011
Resultado | acc=0.8433 | bal_acc=0.6626 | f1=0.9075 | EOdds=0.0308 | EOp=0.0098 | p-rule=96.18 | score=0.6608 | tempo=0.06 min

FAGTB caucasian_1:  92%|█████████▏| 55/60 [04:53<00:25,  5.05s/modelo]

----------------------------------------------------------------------------------------------------
Treino 116/120 | config=caucasian_1 | lambda=0.01 | n_estimators=200 | learning_rate=0.05 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1824.5866782961893 1826.1367378978723 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2133.0385525077954 1754.8137838333362 1776.1441693584143 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2416.492254797496 1689.4670762458418 1713.6319987938168 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 1140.8813912816613 1628.8676809962744 1640.276494909091 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3424.4319844961633 1574.429158118202 1608.6734779631636 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
25 207.670863580441 1524.3026871879292 1526.3793958237338 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
30 3829.441144143989 1479.0187055033655 1517.3131169448054 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
35 -62.59855343678346 1436.048841346992 1435.422855812624 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
40 4086.532677517866 1397.493161365649 1438.3584881408274 Accuracy: 0.8489  test :  0.828  Prule Train :  0.9617316803157512  Prule test :  0.9725152610679786
45 -380.37950795932977 1361.6099705180613 1357.8061754384678 Accuracy: 0.8669  test :  0.84  Prule Train :  0.9584549584549584  Prule test :  0.9638162830477448
50 4373.188710793114 1328.9751455585665 1372.7070326664975 Accuracy: 0.8754  test :  0.842  Prule Train :  0.9565072520856893  Prule test :  0.9678738494039536
55 -727.3530887024082 1298.1286615281938 1290.8551306411696 Accuracy: 0.8797  test :  0.8407  Prule Train :  0.9543081032442735  Prule test :  0.9650520597555454
60 4681.451639025503 1269.814746909894 1316.6292633001488 Accuracy: 0.882  test :  0.8413  Prule Train :  0.9528859285253923  Prule test :  0.963508516700006
65 -1090.9411737624844 1244.3173128597973 1233.4079011221725 Accuracy: 0.8846  test :  0.842  Prule Train :  0.952039413577875  Prule test :  0.9620915924107414
70 5007.97358771092 1220.6879382227264 1270.7676740998356 Accuracy: 0.8866  test :  0.842  Prule Train :  0.9488105053163085  Prule test :  0.964840425531915
75 -1463.9101504776345 1196.8144013560166 1182.1752998512402 Accuracy: 0.8877  test :  0.8427  Prule Train :  0.9486994147544607  Prule test :  0.9633747298572427
80 5343.023705559346 1176.7814008168489 1230.2116378724422 Accuracy: 0.8891  test :  0.844  Prule Train :  0.94916929475753  Prule test :  0.9633298786807294
85 -1840.8153890195056 1157.7111460731821 1139.302992182987 Accuracy: 0.8909  test :  0.844  Prule Train :  0.9502242229514956  Prule test :  0.9633298786807294
90 5690.774161704315 1138.1842326242133 1195.0919742412566 Accuracy: 0.8914  test :  0.844  Prule Train :  0.9489470398561308  Prule test :  0.9660980679872828
95 -2218.5769425965173 1119.1608904775799 1096.9751210516147 Accuracy: 0.892  test :  0.842  Prule Train :  0.9488913053756324  Prule test :  0.9618106505258011
100 6037.017297909586 1101.5728899671874 1161.9430629462831 Accuracy: 0.8929  test :  0.8433  Prule Train :  0.9494194011117087  Prule test :  0.9618106505258011
105 -2593.77799488845 1084.1360135572231 1058.1982336083386 Accuracy: 0.8946  test :  0.842  Prule Train :  0.9480271217794322  Prule test :  0.9617633552732281
110 6385.6879430059 1069.1342203101772 1132.9910997402362 Accuracy: 0.8969  test :  0.8427  Prule Train :  0.9453487084579002  Prule test :  0.9631491814335642
115 -2965.2916197311997 1052.9800333305548 1023.3271171332426 Accuracy: 0.8983  test :  0.8413  Prule Train :  0.94336527669861  Prule test :  0.9659328495879965
120 6734.737312028688 1039.7252603725956 1107.0726334928827 Accuracy: 0.9003  test :  0.8427  Prule Train :  0.9437703385723188  Prule test :  0.9658495220474869
125 -3335.160495092711 1026.4840736400745 993.1324686891475 Accuracy: 0.9026  test :  0.8427  Prule Train :  0.9435324807533244  Prule test :  0.9658495220474869
130 7086.7714875464835 1013.1064247679085 1083.9741396433733 Accuracy: 0.9054  test :  0.8433  Prule Train :  0.9444681511929334  Prule test :  0.967251335577309
135 -3696.7805597798038 1000.5732863861606 963.6054807883625 Accuracy: 0.906  test :  0.8433  Prule Train :  0.9456457922792088  Prule test :  0.967251335577309
140 7414.371428206527 988.4246089287658 1062.568323210831 Accuracy: 0.9069  test :  0.8453  Prule Train :  0.9461774180875305  Prule test :  0.968657224146462
145 -4028.899037460962 977.066394002349 936.7774036277394 Accuracy: 0.908  test :  0.8467  Prule Train :  0.9448203264568036  Prule test :  0.9657657100445324
150 7630.588726734695 964.3113913590844 1040.6172786264315 Accuracy: 0.9094  test :  0.8473  Prule Train :  0.9452929215131968  Prule test :  0.9671714825482363
155 -4256.91399924608 950.8125580155851 908.2434180231243 Accuracy: 0.9106  test :  0.8467  Prule Train :  0.9439318769312508  Prule test :  0.9628741959426027
160 7534.517598425211 938.4087422556086 1013.7539182398606 Accuracy: 0.9114  test :  0.8467  Prule Train :  0.9444636867834361  Prule test :  0.9628741959426027
165 -4254.360995123327 925.7508156506084 883.2072056993752 Accuracy: 0.9134  test :  0.8467  Prule Train :  0.942386343516287  Prule test :  0.962827898045774
170 7250.999934721276 913.8730756048667 986.3830749520794 Accuracy: 0.9137  test :  0.8473  Prule Train :  0.9429782947370887  Prule test :  0.9642314372557533
175 -4115.099302409928 901.6673437180905 860.5163506939912 Accuracy: 0.9146  test :  0.8473  Prule Train :  0.9422641050548028  Prule test :  0.9642314372557533
180 7043.480773790137 891.0687265259402 961.5035342638416 Accuracy: 0.9163  test :  0.8487  Prule Train :  0.9395874565685887  Prule test :  0.9641869855567634
185 -3962.6427239428313 879.4269319902307 839.8005047508025 Accuracy: 0.9171  test :  0.8487  Prule Train :  0.9388702340244189  Prule test :  0.9641869855567634
190 6874.518313033351 869.1252366630936 937.870419793427 Accuracy: 0.9186  test :  0.8487  Prule Train :  0.9368427542231069  Prule test :  0.9641869855567634
195 -3820.816035511036 858.9180401701261 820.7098798150157 Accuracy: 0.92  test :  0.848  Prule Train :  0.9348127193117741  Prule test :  0.9656390743904333
Resultado | acc=0.8480 | bal_acc=0.6799 | f1=0.9096 | EOdds=0.0246 | EOp=0.0034 | p-rule=96.56 | score=0.6786 | tempo=0.12 min

FAGTB caucasian_1:  93%|█████████▎| 56/60 [05:00<00:22,  5.65s/modelo]

----------------------------------------------------------------------------------------------------
Treino 117/120 | config=caucasian_1 | lambda=0.01 | n_estimators=100 | learning_rate=0.1 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1810.1981427672456 1811.7482023689286 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2094.078574199139 1674.9273720963126 1695.868157838304 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2509.2970002395846 1559.8000935935884 1584.8930635959841 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 917.9300948543536 1464.2633090044408 1473.4426099529842 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3654.632208084064 1385.4820598922943 1422.0283819731349 Accuracy: 0.8631  test :  0.84  Prule Train :  0.9581730072160695  Prule test :  0.9611522830504423
25 -84.59610318250424 1317.9455087882022 1317.099547756377 Accuracy: 0.8766  test :  0.8393  Prule Train :  0.9539884706450423  Prule test :  0.9679118196612622
30 4026.3431627887308 1260.7564828270847 1301.019914454972 Accuracy: 0.8831  test :  0.8413  Prule Train :  0.9527801466825856  Prule test :  0.963508516700006
35 -504.6238403594569 1207.4666133009086 1202.420374897314 Accuracy: 0.8863  test :  0.8413  Prule Train :  0.9494455859758242  Prule test :  0.9662613981762918
40 4345.505704725522 1163.7802944151092 1207.2353514623644 Accuracy: 0.8891  test :  0.842  Prule Train :  0.9455201271715035  Prule test :  0.9647119875454073
45 -933.3675247962236 1124.642056225392 1115.3083809774298 Accuracy: 0.892  test :  0.844  Prule Train :  0.9452314556609034  Prule test :  0.963284898806435
50 4684.791589112523 1087.9257746895837 1134.773690580709 Accuracy: 0.896  test :  0.8447  Prule Train :  0.9472727560327807  Prule test :  0.9618578100674624
55 -1355.4243427981241 1053.2039362157802 1039.6496927877988 Accuracy: 0.898  test :  0.842  Prule Train :  0.9464589798335165  Prule test :  0.9617633552732281
60 5030.045374977535 1021.9353819184719 1072.235835668247 Accuracy: 0.8994  test :  0.8427  Prule Train :  0.9481604723240412  Prule test :  0.9603321598040716
65 -1766.1598797149281 991.565819336165 973.9042205390156 Accuracy: 0.9049  test :  0.844  Prule Train :  0.9457628299471387  Prule test :  0.9630580494404133
70 5385.529171651979 965.1805750068934 1019.0358667234133 Accuracy: 0.9097  test :  0.8453  Prule Train :  0.9434013974351686  Prule test :  0.9602330293819655
75 -2157.578897866916 938.193848025091 916.6180590464219 Accuracy: 0.9129  test :  0.8467  Prule Train :  0.9461847601382485  Prule test :  0.9601832492928299
80 5740.961434327216 913.7261907638825 971.1358051071546 Accuracy: 0.9143  test :  0.848  Prule Train :  0.9466629088795335  Prule test :  0.9629663891458526
85 -2530.1340439003734 890.2834707034003 864.9821302643966 Accuracy: 0.9177  test :  0.8467  Prule Train :  0.9463103268413003  Prule test :  0.9629203594478585
90 6088.739742594221 869.7322582822019 930.6196557081441 Accuracy: 0.92  test :  0.8487  Prule Train :  0.9448162139739087  Prule test :  0.9614284388916378
95 -2882.666174168951 849.6822800903626 820.855618348673 Accuracy: 0.9237  test :  0.8473  Prule Train :  0.9412750212750213  Prule test :  0.958536924789708
Resultado | acc=0.8480 | bal_acc=0.6799 | f1=0.9096 | EOdds=0.0246 | EOp=0.0102 | p-rule=95.99 | score=0.6783 | tempo=0.06 min

FAGTB caucasian_1:  95%|█████████▌| 57/60 [05:03<00:15,  5.05s/modelo]

----------------------------------------------------------------------------------------------------
Treino 118/120 | config=caucasian_1 | lambda=0.01 | n_estimators=200 | learning_rate=0.1 | max_depth=3
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1810.1981427672456 1811.7482023689286 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2094.078574199139 1674.9273720963126 1695.868157838304 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2509.2970002395846 1559.8000935935884 1584.8930635959841 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 917.9300948543536 1464.2633090044408 1473.4426099529842 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3654.632208084064 1385.4820598922943 1422.0283819731349 Accuracy: 0.8631  test :  0.84  Prule Train :  0.9581730072160695  Prule test :  0.9611522830504423
25 -84.59610318250424 1317.9455087882022 1317.099547756377 Accuracy: 0.8766  test :  0.8393  Prule Train :  0.9539884706450423  Prule test :  0.9679118196612622
30 4026.3431627887308 1260.7564828270847 1301.019914454972 Accuracy: 0.8831  test :  0.8413  Prule Train :  0.9527801466825856  Prule test :  0.963508516700006
35 -504.6238403594569 1207.4666133009086 1202.420374897314 Accuracy: 0.8863  test :  0.8413  Prule Train :  0.9494455859758242  Prule test :  0.9662613981762918
40 4345.505704725522 1163.7802944151092 1207.2353514623644 Accuracy: 0.8891  test :  0.842  Prule Train :  0.9455201271715035  Prule test :  0.9647119875454073
45 -933.3675247962236 1124.642056225392 1115.3083809774298 Accuracy: 0.892  test :  0.844  Prule Train :  0.9452314556609034  Prule test :  0.963284898806435
50 4684.791589112523 1087.9257746895837 1134.773690580709 Accuracy: 0.896  test :  0.8447  Prule Train :  0.9472727560327807  Prule test :  0.9618578100674624
55 -1355.4243427981241 1053.2039362157802 1039.6496927877988 Accuracy: 0.898  test :  0.842  Prule Train :  0.9464589798335165  Prule test :  0.9617633552732281
60 5030.045374977535 1021.9353819184719 1072.235835668247 Accuracy: 0.8994  test :  0.8427  Prule Train :  0.9481604723240412  Prule test :  0.9603321598040716
65 -1766.1598797149281 991.565819336165 973.9042205390156 Accuracy: 0.9049  test :  0.844  Prule Train :  0.9457628299471387  Prule test :  0.9630580494404133
70 5385.529171651979 965.1805750068934 1019.0358667234133 Accuracy: 0.9097  test :  0.8453  Prule Train :  0.9434013974351686  Prule test :  0.9602330293819655
75 -2157.578897866916 938.193848025091 916.6180590464219 Accuracy: 0.9129  test :  0.8467  Prule Train :  0.9461847601382485  Prule test :  0.9601832492928299
80 5740.961434327216 913.7261907638825 971.1358051071546 Accuracy: 0.9143  test :  0.848  Prule Train :  0.9466629088795335  Prule test :  0.9629663891458526
85 -2530.1340439003734 890.2834707034003 864.9821302643966 Accuracy: 0.9177  test :  0.8467  Prule Train :  0.9463103268413003  Prule test :  0.9629203594478585
90 6088.739742594221 869.7322582822019 930.6196557081441 Accuracy: 0.92  test :  0.8487  Prule Train :  0.9448162139739087  Prule test :  0.9614284388916378
95 -2882.666174168951 849.6822800903626 820.855618348673 Accuracy: 0.9237  test :  0.8473  Prule Train :  0.9412750212750213  Prule test :  0.958536924789708
100 6398.565931633924 831.3016655769648 895.287324893304 Accuracy: 0.9249  test :  0.8487  Prule Train :  0.9386346986346987  Prule test :  0.9613800365449535
105 -3186.119843088636 809.2759229074072 777.4147244765207 Accuracy: 0.9274  test :  0.8473  Prule Train :  0.9414989772132629  Prule test :  0.9613314930835556
110 6518.671571140694 793.8064711347864 858.9931868461933 Accuracy: 0.9294  test :  0.848  Prule Train :  0.9419127334728359  Prule test :  0.9599321750441328
115 -3293.1082167660206 778.0115622558789 745.0804800882187 Accuracy: 0.9326  test :  0.8473  Prule Train :  0.9422037098545443  Prule test :  0.9641869855567634
120 6300.15629756355 764.6966950278907 827.6982580035262 Accuracy: 0.9331  test :  0.8487  Prule Train :  0.9408691436932771  Prule test :  0.9613314930835556
125 -3178.325086954628 750.2190597970261 718.4358089274799 Accuracy: 0.9349  test :  0.8487  Prule Train :  0.9419529419529418  Prule test :  0.9613314930835556
130 6077.743939664823 737.7614221272036 798.5388615238519 Accuracy: 0.9351  test :  0.8487  Prule Train :  0.9400100435470209  Prule test :  0.9613314930835556
135 -3029.433661003828 723.666984935795 693.3726483257567 Accuracy: 0.936  test :  0.8487  Prule Train :  0.9392769392769392  Prule test :  0.9641424038820454
140 5901.008169733817 710.6230897170053 769.6331714143435 Accuracy: 0.9371  test :  0.8487  Prule Train :  0.9366009366009365  Prule test :  0.9641424038820454
145 -2894.1291247572644 696.154004754474 667.2127135069013 Accuracy: 0.9391  test :  0.848  Prule Train :  0.9382818601669473  Prule test :  0.9627348967230938
150 5743.13286185452 683.9355991377099 741.3669277562551 Accuracy: 0.9409  test :  0.8493  Prule Train :  0.936806782960629  Prule test :  0.9655540325846548
155 -2770.328944433939 672.2777608808505 644.5744714365111 Accuracy: 0.9423  test :  0.8493  Prule Train :  0.9360007845444739  Prule test :  0.9655113246396706
160 5599.293736897787 660.659337407176 716.6522747761541 Accuracy: 0.9431  test :  0.8493  Prule Train :  0.9352603355194029  Prule test :  0.9655113246396706
165 -2660.9023802823767 648.4951043733458 621.8860805705222 Accuracy: 0.946  test :  0.8487  Prule Train :  0.9349212624066425  Prule test :  0.9669291092573499
170 5464.169302787736 637.7011361670639 692.3428291949411 Accuracy: 0.9474  test :  0.848  Prule Train :  0.9341086153057526  Prule test :  0.9654255319148937
175 -2557.409680256205 627.3670985644153 601.7930017618532 Accuracy: 0.948  test :  0.8487  Prule Train :  0.9340399184149183  Prule test :  0.9668473662770657
180 5320.993123519473 617.9804027719872 671.190334007182 Accuracy: 0.9497  test :  0.8467  Prule Train :  0.931262006180573  Prule test :  0.9682343882585878
185 -2464.010440826145 607.6693062188475 583.0292018105861 Accuracy: 0.9514  test :  0.8467  Prule Train :  0.9284804721571345  Prule test :  0.9652524235175626
190 5204.769605694046 598.7609378180207 650.8086338749613 Accuracy: 0.9531  test :  0.8467  Prule Train :  0.9269781567431695  Prule test :  0.9652524235175626
195 -2375.515268157954 590.6985854951085 566.943432813529 Accuracy: 0.954  test :  0.8473  Prule Train :  0.926225527139962  Prule test :  0.9637810021402493
Resultado | acc=0.8467 | bal_acc=0.6889 | f1=0.9081 | EOdds=0.0098 | EOp=0.0058 | p-rule=96.52 | score=0.6882 | tempo=0.12 min

FAGTB caucasian_1:  97%|█████████▋| 58/60 [05:10<00:11,  5.65s/modelo]

----------------------------------------------------------------------------------------------------
Treino 119/120 | config=caucasian_1 | lambda=0.01 | n_estimators=100 | learning_rate=0.1 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1810.1981427672456 1811.7482023689286 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2094.078574199139 1674.9273720963126 1695.868157838304 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2509.2970002395846 1559.8000935935884 1584.8930635959841 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 917.9300948543536 1464.2633090044408 1473.4426099529842 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3654.632208084064 1385.4820598922943 1422.0283819731349 Accuracy: 0.8631  test :  0.84  Prule Train :  0.9581730072160695  Prule test :  0.9611522830504423
25 -84.59610318250424 1317.9455087882022 1317.099547756377 Accuracy: 0.8766  test :  0.8393  Prule Train :  0.9539884706450423  Prule test :  0.9679118196612622
30 4026.3431627887308 1260.7564828270847 1301.019914454972 Accuracy: 0.8831  test :  0.8413  Prule Train :  0.9527801466825856  Prule test :  0.963508516700006
35 -504.6238403594569 1207.4666133009086 1202.420374897314 Accuracy: 0.8863  test :  0.8413  Prule Train :  0.9494455859758242  Prule test :  0.9662613981762918
40 4345.505704725522 1163.7802944151092 1207.2353514623644 Accuracy: 0.8891  test :  0.842  Prule Train :  0.9455201271715035  Prule test :  0.9647119875454073
45 -933.3675247962236 1124.642056225392 1115.3083809774298 Accuracy: 0.892  test :  0.844  Prule Train :  0.9452314556609034  Prule test :  0.963284898806435
50 4684.791589112523 1087.9257746895837 1134.773690580709 Accuracy: 0.896  test :  0.8447  Prule Train :  0.9472727560327807  Prule test :  0.9618578100674624
55 -1355.4243427981241 1053.2039362157802 1039.6496927877988 Accuracy: 0.898  test :  0.842  Prule Train :  0.9464589798335165  Prule test :  0.9617633552732281
60 5030.045374977535 1021.9353819184719 1072.235835668247 Accuracy: 0.8994  test :  0.8427  Prule Train :  0.9481604723240412  Prule test :  0.9603321598040716
65 -1766.1598797149281 991.565819336165 973.9042205390156 Accuracy: 0.9049  test :  0.844  Prule Train :  0.9457628299471387  Prule test :  0.9630580494404133
70 5385.529171651979 965.1805750068934 1019.0358667234133 Accuracy: 0.9097  test :  0.8453  Prule Train :  0.9434013974351686  Prule test :  0.9602330293819655
75 -2157.578897866916 938.193848025091 916.6180590464219 Accuracy: 0.9129  test :  0.8467  Prule Train :  0.9461847601382485  Prule test :  0.9601832492928299
80 5740.961434327216 913.7261907638825 971.1358051071546 Accuracy: 0.9143  test :  0.848  Prule Train :  0.9466629088795335  Prule test :  0.9629663891458526
85 -2530.1340439003734 890.2834707034003 864.9821302643966 Accuracy: 0.9177  test :  0.8467  Prule Train :  0.9463103268413003  Prule test :  0.9629203594478585
90 6088.739742594221 869.7322582822019 930.6196557081441 Accuracy: 0.92  test :  0.8487  Prule Train :  0.9448162139739087  Prule test :  0.9614284388916378
95 -2882.666174168951 849.6822800903626 820.855618348673 Accuracy: 0.9237  test :  0.8473  Prule Train :  0.9412750212750213  Prule test :  0.958536924789708
Resultado | acc=0.8480 | bal_acc=0.6799 | f1=0.9096 | EOdds=0.0246 | EOp=0.0102 | p-rule=95.99 | score=0.6783 | tempo=0.06 min

FAGTB caucasian_1:  98%|█████████▊| 59/60 [05:14<00:05,  5.05s/modelo]

----------------------------------------------------------------------------------------------------
Treino 120/120 | config=caucasian_1 | lambda=0.01 | n_estimators=200 | learning_rate=0.1 | max_depth=5
----------------------------------------------------------------------------------------------------
0 155.0059601682837 1810.1981427672456 1811.7482023689286 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
5 2094.078574199139 1674.9273720963126 1695.868157838304 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
10 2509.2970002395846 1559.8000935935884 1584.8930635959841 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
15 917.9300948543536 1464.2633090044408 1473.4426099529842 Accuracy: 0.7811  test :  0.7813  Prule Train :  1.0  Prule test :  1.0
20 3654.632208084064 1385.4820598922943 1422.0283819731349 Accuracy: 0.8631  test :  0.84  Prule Train :  0.9581730072160695  Prule test :  0.9611522830504423
25 -84.59610318250424 1317.9455087882022 1317.099547756377 Accuracy: 0.8766  test :  0.8393  Prule Train :  0.9539884706450423  Prule test :  0.9679118196612622
30 4026.3431627887308 1260.7564828270847 1301.019914454972 Accuracy: 0.8831  test :  0.8413  Prule Train :  0.9527801466825856  Prule test :  0.963508516700006
35 -504.6238403594569 1207.4666133009086 1202.420374897314 Accuracy: 0.8863  test :  0.8413  Prule Train :  0.9494455859758242  Prule test :  0.9662613981762918
40 4345.505704725522 1163.7802944151092 1207.2353514623644 Accuracy: 0.8891  test :  0.842  Prule Train :  0.9455201271715035  Prule test :  0.9647119875454073
45 -933.3675247962236 1124.642056225392 1115.3083809774298 Accuracy: 0.892  test :  0.844  Prule Train :  0.9452314556609034  Prule test :  0.963284898806435
50 4684.791589112523 1087.9257746895837 1134.773690580709 Accuracy: 0.896  test :  0.8447  Prule Train :  0.9472727560327807  Prule test :  0.9618578100674624
55 -1355.4243427981241 1053.2039362157802 1039.6496927877988 Accuracy: 0.898  test :  0.842  Prule Train :  0.9464589798335165  Prule test :  0.9617633552732281
60 5030.045374977535 1021.9353819184719 1072.235835668247 Accuracy: 0.8994  test :  0.8427  Prule Train :  0.9481604723240412  Prule test :  0.9603321598040716
65 -1766.1598797149281 991.565819336165 973.9042205390156 Accuracy: 0.9049  test :  0.844  Prule Train :  0.9457628299471387  Prule test :  0.9630580494404133
70 5385.529171651979 965.1805750068934 1019.0358667234133 Accuracy: 0.9097  test :  0.8453  Prule Train :  0.9434013974351686  Prule test :  0.9602330293819655
75 -2157.578897866916 938.193848025091 916.6180590464219 Accuracy: 0.9129  test :  0.8467  Prule Train :  0.9461847601382485  Prule test :  0.9601832492928299
80 5740.961434327216 913.7261907638825 971.1358051071546 Accuracy: 0.9143  test :  0.848  Prule Train :  0.9466629088795335  Prule test :  0.9629663891458526
85 -2530.1340439003734 890.2834707034003 864.9821302643966 Accuracy: 0.9177  test :  0.8467  Prule Train :  0.9463103268413003  Prule test :  0.9629203594478585
90 6088.739742594221 869.7322582822019 930.6196557081441 Accuracy: 0.92  test :  0.8487  Prule Train :  0.9448162139739087  Prule test :  0.9614284388916378
95 -2882.666174168951 849.6822800903626 820.855618348673 Accuracy: 0.9237  test :  0.8473  Prule Train :  0.9412750212750213  Prule test :  0.958536924789708
100 6398.565931633924 831.3016655769648 895.287324893304 Accuracy: 0.9249  test :  0.8487  Prule Train :  0.9386346986346987  Prule test :  0.9613800365449535
105 -3186.119843088636 809.2759229074072 777.4147244765207 Accuracy: 0.9274  test :  0.8473  Prule Train :  0.9414989772132629  Prule test :  0.9613314930835556
110 6518.671571140694 793.8064711347864 858.9931868461933 Accuracy: 0.9294  test :  0.848  Prule Train :  0.9419127334728359  Prule test :  0.9599321750441328
115 -3293.1082167660206 778.0115622558789 745.0804800882187 Accuracy: 0.9326  test :  0.8473  Prule Train :  0.9422037098545443  Prule test :  0.9641869855567634
120 6300.15629756355 764.6966950278907 827.6982580035262 Accuracy: 0.9331  test :  0.8487  Prule Train :  0.9408691436932771  Prule test :  0.9613314930835556
125 -3178.325086954628 750.2190597970261 718.4358089274799 Accuracy: 0.9349  test :  0.8487  Prule Train :  0.9419529419529418  Prule test :  0.9613314930835556
130 6077.743939664823 737.7614221272036 798.5388615238519 Accuracy: 0.9351  test :  0.8487  Prule Train :  0.9400100435470209  Prule test :  0.9613314930835556
135 -3029.433661003828 723.666984935795 693.3726483257567 Accuracy: 0.936  test :  0.8487  Prule Train :  0.9392769392769392  Prule test :  0.9641424038820454
140 5901.008169733817 710.6230897170053 769.6331714143435 Accuracy: 0.9371  test :  0.8487  Prule Train :  0.9366009366009365  Prule test :  0.9641424038820454
145 -2894.1291247572644 696.154004754474 667.2127135069013 Accuracy: 0.9391  test :  0.848  Prule Train :  0.9382818601669473  Prule test :  0.9627348967230938
150 5743.13286185452 683.9355991377099 741.3669277562551 Accuracy: 0.9409  test :  0.8493  Prule Train :  0.936806782960629  Prule test :  0.9655540325846548
155 -2770.328944433939 672.2777608808505 644.5744714365111 Accuracy: 0.9423  test :  0.8493  Prule Train :  0.9360007845444739  Prule test :  0.9655113246396706
160 5599.293736897787 660.659337407176 716.6522747761541 Accuracy: 0.9431  test :  0.8493  Prule Train :  0.9352603355194029  Prule test :  0.9655113246396706
165 -2660.9023802823767 648.4951043733458 621.8860805705222 Accuracy: 0.946  test :  0.8487  Prule Train :  0.9349212624066425  Prule test :  0.9669291092573499
170 5464.169302787736 637.7011361670639 692.3428291949411 Accuracy: 0.9474  test :  0.848  Prule Train :  0.9341086153057526  Prule test :  0.9654255319148937
175 -2557.409680256205 627.3670985644153 601.7930017618532 Accuracy: 0.948  test :  0.8487  Prule Train :  0.9340399184149183  Prule test :  0.9668473662770657
180 5320.993123519473 617.9804027719872 671.190334007182 Accuracy: 0.9497  test :  0.8467  Prule Train :  0.931262006180573  Prule test :  0.9682343882585878
185 -2464.010440826145 607.6693062188475 583.0292018105861 Accuracy: 0.9514  test :  0.8467  Prule Train :  0.9284804721571345  Prule test :  0.9652524235175626
190 5204.769605694046 598.7609378180207 650.8086338749613 Accuracy: 0.9531  test :  0.8467  Prule Train :  0.9269781567431695  Prule test :  0.9652524235175626
195 -2375.515268157954 590.6985854951085 566.943432813529 Accuracy: 0.954  test :  0.8473  Prule Train :  0.926225527139962  Prule test :  0.9637810021402493
Resultado | acc=0.8467 | bal_acc=0.6889 | f1=0.9081 | EOdds=0.0098 | EOp=0.0058 | p-rule=96.52 | score=0.6882 | tempo=0.11 min

FAGTB caucasian_1: 100%|██████████| 60/60 [05:21<00:00,  5.36s/modelo]

Busca concluída.

In [8]:
# ============================================================
# RESULTADOS: MELHOR COMBINAÇÃO GLOBAL POR CONFIGURAÇÃO SENSÍVEL
# ============================================================

df_resultados = pd.read_csv(PASTA_SAIDA / "resultados_hiperparametros_fagtb.csv")

df_ok = df_resultados[df_resultados["status"] == "ok"].copy()

if df_ok.empty:
    raise RuntimeError("Nenhum teste foi concluído com status ok.")

# Melhor combinação global por config sensível
idx_melhores = (
    df_ok
    .sort_values(
        by=["config_sensivel", "score", "balanced_accuracy", "accuracy", "equalized_odds"],
        ascending=[True, False, False, False, True]
    )
    .groupby("config_sensivel")
    .head(1)
    .index
)

df_melhores = df_ok.loc[idx_melhores].copy()

df_melhores = df_melhores.sort_values("config_sensivel")
df_melhores.to_csv(PASTA_SAIDA / "melhores_combinacoes_fagtb.csv", index=False)

colunas_exibir = [
    "dataset",
    "config_sensivel",
    "cenario",
    "lambda_fagtb",
    "n_estimators",
    "learning_rate",
    "max_depth",
    "max_features",
    "min_samples_split",
    "min_impurity",
    "accuracy",
    "balanced_accuracy",
    "f1",
    "equalized_odds",
    "equal_opportunity",
    "p_rule",
    "score",
    "tempo_min"
]

print("Melhores combinações por configuração sensível:")
df_melhores[colunas_exibir]

Melhores combinações por configuração sensível:

,dataset,config_sensivel,cenario,lambda_fagtb,n_estimators,learning_rate,max_depth,max_features,min_samples_split,min_impurity,accuracy,balanced_accuracy,f1,equalized_odds,equal_opportunity,p_rule,score,tempo_min
57,hmda,african_american_0,aware,0.01,200,0.1,3,NaN,2,0,0.844667,0.68763,0.906763,0.014118,0.014118,96.146734,0.686501,0.114839
117,hmda,caucasian_1,aware,0.01,200,0.1,3,NaN,2,0,0.846667,0.68891,0.908074,0.009821,0.005833,96.520883,0.688244,0.115140

In [9]:
# ============================================================
# RESULTADOS: MELHOR VALOR MÉDIO PARA CADA HIPERPARÂMETRO
# ============================================================

resumos_por_config = []

for nome_config, df_config in df_ok.groupby("config_sensivel"):
    df_resumo_param = resumo_melhor_valor_por_hiperparametro(
        df_config,
        colunas_parametros=colunas_parametros
    )
    df_resumo_param["config_sensivel"] = nome_config
    resumos_por_config.append(df_resumo_param)

df_melhor_por_parametro = pd.concat(resumos_por_config, ignore_index=True)
df_melhor_por_parametro.to_csv(
    PASTA_SAIDA / "melhor_valor_medio_por_hiperparametro.csv",
    index=False
)

print("Melhor valor médio por hiperparâmetro e configuração sensível:")
df_melhor_por_parametro[[
    "config_sensivel",
    "hiperparametro",
    "melhor_valor",
    "score_medio",
    "balanced_accuracy_media",
    "accuracy_media",
    "equalized_odds_media",
    "tempo_min_medio",
    "n_testes"
]]

Melhor valor médio por hiperparâmetro e configuração sensível:

,config_sensivel,hiperparametro,melhor_valor,score_medio,balanced_accuracy_media,accuracy_media,equalized_odds_media,tempo_min_medio,n_testes
0,african_american_0,lambda_fagtb,0.01,0.667955,0.670229,0.843778,0.036297,0.087015,12.0
1,african_american_0,n_estimators,200.0,0.673706,0.675807,0.842889,0.030580,0.115840,30.0
2,african_american_0,learning_rate,0.1,0.678299,0.680703,0.842933,0.036074,0.087367,20.0
3,african_american_0,max_depth,3.0,0.667021,0.669526,0.842622,0.039500,0.092838,30.0
4,african_american_0,max_features,NaN,0.667021,0.669526,0.842622,0.039500,0.090184,60.0
5,african_american_0,min_samples_split,2.0,0.667021,0.669526,0.842622,0.039500,0.090184,60.0
6,african_american_0,min_impurity,0.0,0.667021,0.669526,0.842622,0.039500,0.090184,60.0
7,african_american_0,regression,False,0.667021,0.669526,0.842622,0.039500,0.090184,60.0
8,caucasian_1,lambda_fagtb,0.01,0.670404,0.671926,0.845000,0.026741,0.087092,12.0
9,caucasian_1,n_estimators,200.0,0.672739,0.674340,0.842311,0.027942,0.115469,30.0
10,caucasian_1,learning_rate,0.1,0.677033,0.678459,0.842000,0.023783,0.087247,20.0
11,caucasian_1,max_depth,3.0,0.667111,0.668845,0.842244,0.030796,0.087375,30.0
12,caucasian_1,max_features,NaN,0.667111,0.668845,0.842244,0.030796,0.087306,60.0
13,caucasian_1,min_samples_split,2.0,0.667111,0.668845,0.842244,0.030796,0.087306,60.0
14,caucasian_1,min_impurity,0.0,0.667111,0.668845,0.842244,0.030796,0.087306,60.0
15,caucasian_1,regression,False,0.667111,0.668845,0.842244,0.030796,0.087306,60.0

In [10]:
# ============================================================
# TOP 20 COMBINAÇÕES
# ============================================================

df_top20 = (
    df_ok
    .sort_values(
        by=["score", "balanced_accuracy", "accuracy", "equalized_odds"],
        ascending=[False, False, False, True]
    )
    .head(20)
)

df_top20.to_csv(PASTA_SAIDA / "top20_hiperparametros_fagtb.csv", index=False)

df_top20[colunas_exibir]

,dataset,config_sensivel,cenario,lambda_fagtb,n_estimators,learning_rate,max_depth,max_features,min_samples_split,min_impurity,accuracy,balanced_accuracy,f1,equalized_odds,equal_opportunity,p_rule,score,tempo_min
117,hmda,caucasian_1,aware,0.0100,200,0.10,3,NaN,2,0,0.846667,0.688910,0.908074,0.009821,0.005833,96.520883,0.688244,0.115140
119,hmda,caucasian_1,aware,0.0100,200,0.10,5,NaN,2,0,0.846667,0.688910,0.908074,0.009821,0.005833,96.520883,0.688244,0.114896
57,hmda,african_american_0,aware,0.0100,200,0.10,3,NaN,2,0,0.844667,0.687630,0.906763,0.014118,0.014118,96.146734,0.686501,0.114839
59,hmda,african_american_0,aware,0.0100,200,0.10,5,NaN,2,0,0.844667,0.687630,0.906763,0.014118,0.014118,96.146734,0.686501,0.114838
21,hmda,african_american_0,aware,0.0005,200,0.10,3,NaN,2,0,0.842667,0.687448,0.905373,0.036638,0.024036,94.625425,0.684895,0.114837
23,hmda,african_american_0,aware,0.0005,200,0.10,5,NaN,2,0,0.842667,0.687448,0.905373,0.036638,0.024036,94.625425,0.684895,0.115356
9,hmda,african_american_0,aware,0.0001,200,0.10,3,NaN,2,0,0.842000,0.684826,0.905086,0.030532,0.029935,94.345468,0.682401,0.118119
11,hmda,african_american_0,aware,0.0001,200,0.10,5,NaN,2,0,0.842000,0.684826,0.905086,0.030532,0.029935,94.345468,0.682401,0.116074
45,hmda,african_american_0,aware,0.0050,200,0.10,3,NaN,2,0,0.843333,0.684581,0.906038,0.034842,0.023693,94.765277,0.682128,0.115127
47,hmda,african_american_0,aware,0.0050,200,0.10,5,NaN,2,0,0.843333,0.684581,0.906038,0.034842,0.023693,94.765277,0.682128,0.114858
81,hmda,caucasian_1,aware,0.0005,200,0.10,3,NaN,2,0,0.840667,0.681777,0.904362,0.018918,0.013072,95.789532,0.680439,0.115169
83,hmda,caucasian_1,aware,0.0005,200,0.10,5,NaN,2,0,0.840667,0.681777,0.904362,0.018918,0.013072,95.789532,0.680439,0.114896
33,hmda,african_american_0,aware,0.0010,200,0.10,3,NaN,2,0,0.841333,0.682204,0.904800,0.039152,0.021471,94.858642,0.679602,0.115117
35,hmda,african_american_0,aware,0.0010,200,0.10,5,NaN,2,0,0.841333,0.682204,0.904800,0.039152,0.021471,94.858642,0.679602,0.115115
93,hmda,caucasian_1,aware,0.0010,200,0.10,3,NaN,2,0,0.840000,0.681350,0.903923,0.031403,0.014848,95.354191,0.679335,0.115619
95,hmda,caucasian_1,aware,0.0010,200,0.10,5,NaN,2,0,0.840000,0.681350,0.903923,0.031403,0.014848,95.354191,0.679335,0.115120
113,hmda,caucasian_1,aware,0.0100,200,0.05,3,NaN,2,0,0.848000,0.679883,0.909596,0.024628,0.003386,96.563907,0.678550,0.114902
115,hmda,caucasian_1,aware,0.0100,200,0.05,5,NaN,2,0,0.848000,0.679883,0.909596,0.024628,0.003386,96.563907,0.678550,0.115721
105,hmda,caucasian_1,aware,0.0050,200,0.10,3,NaN,2,0,0.839333,0.679826,0.903561,0.026112,0.001175,96.659922,0.678485,0.115424
107,hmda,caucasian_1,aware,0.0050,200,0.10,5,NaN,2,0,0.839333,0.679826,0.903561,0.026112,0.001175,96.659922,0.678485,0.115390

In [11]:
# ============================================================
# SUGESTÃO PARA ATUALIZAR O configs_datasets.json
# ============================================================

print("Sugestões de hiperparâmetros por configuração sensível:\n")

for _, row in df_melhores.iterrows():
    print("-" * 80)
    print(f"Configuração: {row['config_sensivel']}")
    print(f"lambda_fagtb: {row['lambda_fagtb']}")
    print(f"n_estimators: {int(row['n_estimators'])}")
    print(f"learning_rate: {row['learning_rate']}")
    print(f"max_depth: {int(row['max_depth'])}")
    print(f"max_features: {row['max_features']}")
    print(f"min_samples_split: {int(row['min_samples_split'])}")
    print(f"min_impurity: {row['min_impurity']}")
    print(f"balanced_accuracy: {row['balanced_accuracy']:.4f}")
    print(f"accuracy: {row['accuracy']:.4f}")
    print(f"equalized_odds: {row['equalized_odds']:.4f}")
    print(f"score: {row['score']:.4f}")

print("\nArquivos salvos em:")
print(PASTA_SAIDA)

Sugestões de hiperparâmetros por configuração sensível:

--------------------------------------------------------------------------------
Configuração: african_american_0
lambda_fagtb: 0.01
n_estimators: 200
learning_rate: 0.1
max_depth: 3
max_features: nan
min_samples_split: 2
min_impurity: 0
balanced_accuracy: 0.6876
accuracy: 0.8447
equalized_odds: 0.0141
score: 0.6865
--------------------------------------------------------------------------------
Configuração: caucasian_1
lambda_fagtb: 0.01
n_estimators: 200
learning_rate: 0.1
max_depth: 3
max_features: nan
min_samples_split: 2
min_impurity: 0
balanced_accuracy: 0.6889
accuracy: 0.8467
equalized_odds: 0.0098
score: 0.6882

Arquivos salvos em:
resultados\testes_hiperparametros_fagtb